In [4]:
import utils as ut

In [8]:
# score
names = ['FINAL_netscience_res.csv',
'FINAL_power_res.csv',
'FINAL_euroroad_res.csv',
'FINAL_yeast_res.csv',
'FINAL_crime_res.csv']
print("                             ROCAUC                      ")
all_data, all_res = ut.mix_dataset(names, 'ROCAUC')
display(ut.tex_table(all_data, all_res).T)
print("                             AP                      ")
all_data, all_res = ut.mix_dataset(names, 'AP')
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@100                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@100')
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50')
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@20                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@20')
display(ut.tex_table(all_data, all_res).T)

                             ROCAUC
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv \\
\midrule
baseline & 92.69$\pm$0.91 & 67.61$\pm$1.0 & 64.32$\pm$1.25 & 97.05$\pm$0.24 & \color{red}{53.34$\pm$2.52 $\bigstar$} \\
grace random & 90.16$\pm$0.97 & 66.42$\pm$0.96 & 62.79$\pm$2.3 & 96.6$\pm$0.27 & 43.18$\pm$2.55 \\
grace deg & \color{blue}{94.17$\pm$1.89 $\bigstar$} & \color{red}{74.12$\pm$3.67 $\bigstar$} & \color{blue}{68.43$\pm$6.66 $\bigstar$} & 97.75$\pm$0.64 & 47.49$\pm$4.77 \\
grace pr & 88.97$\pm$1.07 & 66.27$\pm$1.27 & 65.6$\pm$4.3 & 97.65$\pm$0.6 & 40.68$\pm$2.21 X \\
grace evc & 90.46$\pm$0.98 & 64.8$\pm$0.53 & 66.5$\pm$5.73 & 96.95$\pm$0.22 & 49.25$\pm$7.52 \\
grace scom & 91.7$\pm$1.28 & 67.56$\pm$2.16 & 62.73$\pm$3.11 & 97.07$\pm$0.37 & 46.54$\pm$5.69 \\
grace random+scom & 90.47$\pm$1.02 & 66.42$\pm$1.05 & 61.95$\pm$0.75 & 96.7$\pm$0.16 & 42.72$\pm$1.8 \\
grace random+deg & 93.47$\pm$2.05 & 67.5$\pm$2.31 & 64.3$\pm$2.49 & \color{blue}{97.82$\pm$0.64 $\bigstar$} & 42.94$\pm$2.27 \\
grace deg+scom & 93.2$\pm$1.58 & 68.84$\pm$1.59 & 63.72$\pm$3.22 & \color{violet}{97.77$\pm$0.67} & 42.96$\pm$2.04 \\
bgrl random & 90.03$\pm$1.09 & 60.74$\pm$1.12 & 52.04$\pm$2.67 & 96.04$\pm$0.25 & 48.56$\pm$2.36 \\
bgrl deg & \color{red}{94.36$\pm$2.52 $\bigstar$} & \color{violet}{69.37$\pm$6.0} & 65.33$\pm$8.35 & 97.65$\pm$0.87 & \color{blue}{52.09$\pm$6.96} \\
bgrl pr & 87.09$\pm$1.22 X & 55.52$\pm$2.32 X & 48.23$\pm$2.62 X & 95.81$\pm$0.25 X & 41.75$\pm$3.38 \\
bgrl evc & 88.93$\pm$0.98 & 56.23$\pm$1.31 X & 65.45$\pm$8.07 & 96.3$\pm$0.29 & 49.74$\pm$9.49 \\
bgrl scom & 90.2$\pm$1.26 & 60.16$\pm$3.2 & 52.62$\pm$3.33 X & 96.04$\pm$0.18 & 45.74$\pm$5.23 \\
bgrl random+scom & 89.78$\pm$0.82 & 60.45$\pm$1.31 & 53.27$\pm$2.82 & 95.74$\pm$0.24 X & 49.06$\pm$2.4 \\
bgrl random+deg & 91.58$\pm$1.16 & 62.33$\pm$1.98 & 61.98$\pm$3.71 & 96.84$\pm$0.56 & 45.03$\pm$5.07 \\
bgrl deg+scom & 91.06$\pm$1.37 & 61.09$\pm$1.58 & 59.14$\pm$3.5 & 96.71$\pm$0.46 & 40.49$\pm$3.58 X \\
csgcl random & 90.21$\pm$1.1 & 66.92$\pm$1.03 & 61.5$\pm$1.75 & 96.63$\pm$0.26 & 45.02$\pm$2.0 \\
csgcl deg & \color{violet}{94.17$\pm$1.95 $\bigstar$} & \color{blue}{73.24$\pm$3.13 $\bigstar$} & \color{red}{68.49$\pm$5.13 $\bigstar$} & \color{red}{97.86$\pm$0.66 $\bigstar$} & 47.77$\pm$5.35 \\
csgcl pr & 88.97$\pm$1.39 & 65.78$\pm$1.35 & 61.22$\pm$3.95 & 97.24$\pm$0.49 & 41.9$\pm$2.41 \\
csgcl evc & 89.99$\pm$0.99 & 65.46$\pm$0.91 & \color{violet}{67.11$\pm$6.32 $\bigstar$} & 96.9$\pm$0.19 & \color{violet}{49.97$\pm$7.42} \\
csgcl scom & 91.71$\pm$1.17 & 68.26$\pm$2.18 & 61.57$\pm$2.98 & 97.08$\pm$0.33 & 47.36$\pm$5.2 \\
csgcl random+scom & 89.58$\pm$1.49 & 66.51$\pm$1.36 & 61.96$\pm$2.59 & 96.64$\pm$0.24 & 42.94$\pm$3.44 \\
csgcl random+deg & 93.28$\pm$1.71 & 68.57$\pm$2.65 & 62.75$\pm$2.4 & 97.74$\pm$0.6 & 42.51$\pm$3.51 \\
csgcl deg+scom & 93.62$\pm$1.76 $\bigstar$ & 67.67$\pm$1.99 & 62.94$\pm$2.38 & 97.77$\pm$0.56 & 41.69$\pm$2.57 X \\
\bottomrule
\end{tabular}

}

,FINAL_netscience_res.csv,FINAL_power_res.csv,FINAL_euroroad_res.csv,FINAL_yeast_res.csv,FINAL_crime_res.csv
baseline,92.69$\pm$0.91,67.61$\pm$1.0,64.32$\pm$1.25,97.05$\pm$0.24,\color{red}{53.34$\pm$2.52 $\bigstar$}
grace random,90.16$\pm$0.97,66.42$\pm$0.96,62.79$\pm$2.3,96.6$\pm$0.27,43.18$\pm$2.55
grace deg,\color{blue}{94.17$\pm$1.89 $\bigstar$},\color{red}{74.12$\pm$3.67 $\bigstar$},\color{blue}{68.43$\pm$6.66 $\bigstar$},97.75$\pm$0.64,47.49$\pm$4.77
grace pr,88.97$\pm$1.07,66.27$\pm$1.27,65.6$\pm$4.3,97.65$\pm$0.6,40.68$\pm$2.21 X
grace evc,90.46$\pm$0.98,64.8$\pm$0.53,66.5$\pm$5.73,96.95$\pm$0.22,49.25$\pm$7.52
grace scom,91.7$\pm$1.28,67.56$\pm$2.16,62.73$\pm$3.11,97.07$\pm$0.37,46.54$\pm$5.69
grace random+scom,90.47$\pm$1.02,66.42$\pm$1.05,61.95$\pm$0.75,96.7$\pm$0.16,42.72$\pm$1.8
grace random+deg,93.47$\pm$2.05,67.5$\pm$2.31,64.3$\pm$2.49,\color{blue}{97.82$\pm$0.64 $\bigstar$},42.94$\pm$2.27
grace deg+scom,93.2$\pm$1.58,68.84$\pm$1.59,63.72$\pm$3.22,\color{violet}{97.77$\pm$0.67},42.96$\pm$2.04
bgrl random,90.03$\pm$1.09,60.74$\pm$1.12,52.04$\pm$2.67,96.04$\pm$0.25,48.56$\pm$2.36
bgrl deg,\color{red}{94.36$\pm$2.52 $\bigstar$},\color{violet}{69.37$\pm$6.0},65.33$\pm$8.35,97.65$\pm$0.87,\color{blue}{52.09$\pm$6.96}
bgrl pr,87.09$\pm$1.22 X,55.52$\pm$2.32 X,48.23$\pm$2.62 X,95.81$\pm$0.25 X,41.75$\pm$3.38
bgrl evc,88.93$\pm$0.98,56.23$\pm$1.31 X,65.45$\pm$8.07,96.3$\pm$0.29,49.74$\pm$9.49
bgrl scom,90.2$\pm$1.26,60.16$\pm$3.2,52.62$\pm$3.33 X,96.04$\pm$0.18,45.74$\pm$5.23
bgrl random+scom,89.78$\pm$0.82,60.45$\pm$1.31,53.27$\pm$2.82,95.74$\pm$0.24 X,49.06$\pm$2.4
bgrl random+deg,91.58$\pm$1.16,62.33$\pm$1.98,61.98$\pm$3.71,96.84$\pm$0.56,45.03$\pm$5.07
bgrl deg+scom,91.06$\pm$1.37,61.09$\pm$1.58,59.14$\pm$3.5,96.71$\pm$0.46,40.49$\pm$3.58 X
csgcl random,90.21$\pm$1.1,66.92$\pm$1.03,61.5$\pm$1.75,96.63$\pm$0.26,45.02$\pm$2.0
csgcl deg,\color{violet}{94.17$\pm$1.95 $\bigstar$},\color{blue}{73.24$\pm$3.13 $\bigstar$},\color{red}{68.49$\pm$5.13 $\bigstar$},\color{red}{97.86$\pm$0.66 $\bigstar$},47.77$\pm$5.35
csgcl pr,88.97$\pm$1.39,65.78$\pm$1.35,61.22$\pm$3.95,97.24$\pm$0.49,41.9$\pm$2.41
csgcl evc,89.99$\pm$0.99,65.46$\pm$0.91,\color{violet}{67.11$\pm$6.32 $\bigstar$},96.9$\pm$0.19,\color{violet}{49.97$\pm$7.42}
csgcl scom,91.71$\pm$1.17,68.26$\pm$2.18,61.57$\pm$2.98,97.08$\pm$0.33,47.36$\pm$5.2
csgcl random+scom,89.58$\pm$1.49,66.51$\pm$1.36,61.96$\pm$2.59,96.64$\pm$0.24,42.94$\pm$3.44
csgcl random+deg,93.28$\pm$1.71,68.57$\pm$2.65,62.75$\pm$2.4,97.74$\pm$0.6,42.51$\pm$3.51
csgcl deg+scom,93.62$\pm$1.76 $\bigstar$,67.67$\pm$1.99,62.94$\pm$2.38,97.77$\pm$0.56,41.69$\pm$2.57 X

                             AP
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv \\
\midrule
baseline & 94.93$\pm$0.59 & 73.85$\pm$0.66 & 66.62$\pm$1.44 & 98.01$\pm$0.13 & \color{red}{57.66$\pm$1.55 $\bigstar$} \\
grace random & 93.77$\pm$0.6 & 73.93$\pm$0.9 & 67.16$\pm$1.87 & 97.87$\pm$0.15 & 52.37$\pm$1.75 \\
grace deg & 95.4$\pm$0.96 & \color{red}{78.17$\pm$1.95 $\bigstar$} & \color{red}{70.25$\pm$4.52 $\bigstar$} & 98.31$\pm$0.34 & 54.96$\pm$2.94 \\
grace pr & 93.21$\pm$0.75 X & 73.93$\pm$0.89 & 68.79$\pm$2.9 & 98.41$\pm$0.31 $\bigstar$ & 50.84$\pm$1.48 X \\
grace evc & 93.93$\pm$0.6 & 73.29$\pm$0.74 & 68.53$\pm$3.95 & 97.98$\pm$0.16 & 55.34$\pm$4.33 \\
grace scom & 94.47$\pm$0.72 & 74.47$\pm$1.08 & 66.61$\pm$1.79 & 98.07$\pm$0.19 & 53.75$\pm$3.18 \\
grace random+scom & 93.93$\pm$0.59 & 74.0$\pm$0.85 & 66.35$\pm$1.12 & 97.9$\pm$0.09 & 51.64$\pm$1.54 \\
grace random+deg & 95.19$\pm$0.95 & 73.87$\pm$1.34 & 67.95$\pm$2.45 & \color{red}{98.46$\pm$0.32 $\bigstar$} & 52.7$\pm$1.5 \\
grace deg+scom & 95.13$\pm$0.84 & \color{violet}{75.03$\pm$1.09} & 67.88$\pm$2.67 & 98.39$\pm$0.37 & 52.24$\pm$1.46 \\
bgrl random & 94.02$\pm$0.6 & 69.73$\pm$0.8 & 58.79$\pm$3.18 X & 97.61$\pm$0.15 & 55.98$\pm$1.79 $\bigstar$ \\
bgrl deg & \color{red}{95.99$\pm$1.33 $\bigstar$} & 74.75$\pm$3.56 & 67.66$\pm$5.98 & 98.4$\pm$0.43 & \color{blue}{57.01$\pm$4.33 $\bigstar$} \\
bgrl pr & 92.53$\pm$0.65 X & 66.6$\pm$1.36 X & 56.04$\pm$1.79 X & 97.57$\pm$0.11 & 50.75$\pm$2.2 \\
bgrl evc & 93.42$\pm$0.58 & 67.3$\pm$0.91 X & 67.39$\pm$5.44 & 97.71$\pm$0.14 & 55.85$\pm$5.77 \\
bgrl scom & 93.97$\pm$0.71 & 69.29$\pm$1.89 & 58.72$\pm$2.67 X & 97.57$\pm$0.1 & 53.57$\pm$3.2 \\
bgrl random+scom & 93.86$\pm$0.53 & 69.61$\pm$0.97 & 59.78$\pm$2.37 & 97.43$\pm$0.13 X & \color{violet}{56.72$\pm$2.55 $\bigstar$} \\
bgrl random+deg & 94.59$\pm$0.7 & 70.77$\pm$1.15 & 65.49$\pm$2.77 & 98.02$\pm$0.28 & 53.14$\pm$3.64 \\
bgrl deg+scom & 94.28$\pm$0.74 & 69.91$\pm$1.22 & 63.41$\pm$2.77 & 97.97$\pm$0.23 & 50.39$\pm$2.3 X \\
csgcl random & 93.8$\pm$0.72 & 74.21$\pm$0.7 & 65.84$\pm$1.8 & 97.86$\pm$0.15 & 52.99$\pm$1.66 \\
csgcl deg & \color{blue}{95.61$\pm$1.01 $\bigstar$} & \color{blue}{77.78$\pm$1.71 $\bigstar$} & \color{blue}{70.08$\pm$3.43 $\bigstar$} & \color{violet}{98.42$\pm$0.31 $\bigstar$} & 54.45$\pm$3.35 \\
csgcl pr & 93.27$\pm$0.82 & 73.69$\pm$0.85 & 65.52$\pm$2.42 & 98.16$\pm$0.25 & 51.66$\pm$1.45 \\
csgcl evc & 93.71$\pm$0.61 & 73.49$\pm$0.71 & \color{violet}{69.09$\pm$4.22 $\bigstar$} & 97.98$\pm$0.08 & 56.23$\pm$4.95 \\
csgcl scom & 94.44$\pm$0.68 & 74.79$\pm$1.1 & 65.67$\pm$2.19 & 98.07$\pm$0.16 & 54.02$\pm$3.27 \\
csgcl random+scom & 93.49$\pm$0.86 & 73.87$\pm$1.03 & 66.58$\pm$1.73 & 97.86$\pm$0.13 & 51.36$\pm$2.2 X \\
csgcl random+deg & 95.15$\pm$1.01 & 74.58$\pm$1.43 & 66.81$\pm$2.55 & 98.41$\pm$0.32 $\bigstar$ & 51.92$\pm$1.81 \\
csgcl deg+scom & \color{violet}{95.47$\pm$1.04 $\bigstar$} & 74.39$\pm$0.79 & 67.51$\pm$2.19 & \color{blue}{98.43$\pm$0.3 $\bigstar$} & 51.33$\pm$1.83 X \\
\bottomrule
\end{tabular}

}

,FINAL_netscience_res.csv,FINAL_power_res.csv,FINAL_euroroad_res.csv,FINAL_yeast_res.csv,FINAL_crime_res.csv
baseline,94.93$\pm$0.59,73.85$\pm$0.66,66.62$\pm$1.44,98.01$\pm$0.13,\color{red}{57.66$\pm$1.55 $\bigstar$}
grace random,93.77$\pm$0.6,73.93$\pm$0.9,67.16$\pm$1.87,97.87$\pm$0.15,52.37$\pm$1.75
grace deg,95.4$\pm$0.96,\color{red}{78.17$\pm$1.95 $\bigstar$},\color{red}{70.25$\pm$4.52 $\bigstar$},98.31$\pm$0.34,54.96$\pm$2.94
grace pr,93.21$\pm$0.75 X,73.93$\pm$0.89,68.79$\pm$2.9,98.41$\pm$0.31 $\bigstar$,50.84$\pm$1.48 X
grace evc,93.93$\pm$0.6,73.29$\pm$0.74,68.53$\pm$3.95,97.98$\pm$0.16,55.34$\pm$4.33
grace scom,94.47$\pm$0.72,74.47$\pm$1.08,66.61$\pm$1.79,98.07$\pm$0.19,53.75$\pm$3.18
grace random+scom,93.93$\pm$0.59,74.0$\pm$0.85,66.35$\pm$1.12,97.9$\pm$0.09,51.64$\pm$1.54
grace random+deg,95.19$\pm$0.95,73.87$\pm$1.34,67.95$\pm$2.45,\color{red}{98.46$\pm$0.32 $\bigstar$},52.7$\pm$1.5
grace deg+scom,95.13$\pm$0.84,\color{violet}{75.03$\pm$1.09},67.88$\pm$2.67,98.39$\pm$0.37,52.24$\pm$1.46
bgrl random,94.02$\pm$0.6,69.73$\pm$0.8,58.79$\pm$3.18 X,97.61$\pm$0.15,55.98$\pm$1.79 $\bigstar$
bgrl deg,\color{red}{95.99$\pm$1.33 $\bigstar$},74.75$\pm$3.56,67.66$\pm$5.98,98.4$\pm$0.43,\color{blue}{57.01$\pm$4.33 $\bigstar$}
bgrl pr,92.53$\pm$0.65 X,66.6$\pm$1.36 X,56.04$\pm$1.79 X,97.57$\pm$0.11,50.75$\pm$2.2
bgrl evc,93.42$\pm$0.58,67.3$\pm$0.91 X,67.39$\pm$5.44,97.71$\pm$0.14,55.85$\pm$5.77
bgrl scom,93.97$\pm$0.71,69.29$\pm$1.89,58.72$\pm$2.67 X,97.57$\pm$0.1,53.57$\pm$3.2
bgrl random+scom,93.86$\pm$0.53,69.61$\pm$0.97,59.78$\pm$2.37,97.43$\pm$0.13 X,\color{violet}{56.72$\pm$2.55 $\bigstar$}
bgrl random+deg,94.59$\pm$0.7,70.77$\pm$1.15,65.49$\pm$2.77,98.02$\pm$0.28,53.14$\pm$3.64
bgrl deg+scom,94.28$\pm$0.74,69.91$\pm$1.22,63.41$\pm$2.77,97.97$\pm$0.23,50.39$\pm$2.3 X
csgcl random,93.8$\pm$0.72,74.21$\pm$0.7,65.84$\pm$1.8,97.86$\pm$0.15,52.99$\pm$1.66
csgcl deg,\color{blue}{95.61$\pm$1.01 $\bigstar$},\color{blue}{77.78$\pm$1.71 $\bigstar$},\color{blue}{70.08$\pm$3.43 $\bigstar$},\color{violet}{98.42$\pm$0.31 $\bigstar$},54.45$\pm$3.35
csgcl pr,93.27$\pm$0.82,73.69$\pm$0.85,65.52$\pm$2.42,98.16$\pm$0.25,51.66$\pm$1.45
csgcl evc,93.71$\pm$0.61,73.49$\pm$0.71,\color{violet}{69.09$\pm$4.22 $\bigstar$},97.98$\pm$0.08,56.23$\pm$4.95
csgcl scom,94.44$\pm$0.68,74.79$\pm$1.1,65.67$\pm$2.19,98.07$\pm$0.16,54.02$\pm$3.27
csgcl random+scom,93.49$\pm$0.86,73.87$\pm$1.03,66.58$\pm$1.73,97.86$\pm$0.13,51.36$\pm$2.2 X
csgcl random+deg,95.15$\pm$1.01,74.58$\pm$1.43,66.81$\pm$2.55,98.41$\pm$0.32 $\bigstar$,51.92$\pm$1.81
csgcl deg+scom,\color{violet}{95.47$\pm$1.04 $\bigstar$},74.39$\pm$0.79,67.51$\pm$2.19,\color{blue}{98.43$\pm$0.3 $\bigstar$},51.33$\pm$1.83 X

                             Hits@100
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv \\
\midrule
baseline & 87.55$\pm$1.47 & 36.84$\pm$1.22 & 55.09$\pm$2.31 & 94.55$\pm$0.29 & \color{red}{38.78$\pm$3.36 $\bigstar$} \\
grace random & 85.31$\pm$1.41 & 39.4$\pm$1.39 & 51.84$\pm$3.9 & 94.61$\pm$0.26 & 27.12$\pm$3.32 \\
grace deg & \color{blue}{91.26$\pm$3.25 $\bigstar$} & \color{red}{42.11$\pm$1.53 $\bigstar$} & \color{blue}{61.59$\pm$9.64 $\bigstar$} & 94.45$\pm$0.36 & 32.37$\pm$5.53 \\
grace pr & 84.73$\pm$1.5 X & 39.77$\pm$1.33 & 56.71$\pm$6.92 & 94.9$\pm$0.29 $\bigstar$ & 25.36$\pm$3.11 X \\
grace evc & 85.33$\pm$1.49 & 39.88$\pm$1.2 & 59.15$\pm$8.87 & 94.63$\pm$0.3 & 34.98$\pm$10.47 \\
grace scom & 85.82$\pm$1.64 & 39.39$\pm$0.97 & 51.48$\pm$4.92 & 94.66$\pm$0.3 & 29.83$\pm$6.19 \\
grace random+scom & 85.29$\pm$1.17 & 39.89$\pm$1.09 & 50.11$\pm$2.39 & 94.6$\pm$0.31 & 25.73$\pm$2.91 X \\
grace random+deg & 89.64$\pm$3.05 & 40.83$\pm$1.06 & 54.49$\pm$5.37 & \color{red}{94.94$\pm$0.52 $\bigstar$} & 27.53$\pm$1.42 \\
grace deg+scom & 89.22$\pm$2.16 & \color{violet}{41.18$\pm$1.42} & 54.77$\pm$5.11 & 94.84$\pm$0.45 & 27.36$\pm$3.17 \\
bgrl random & 86.31$\pm$1.26 & 33.03$\pm$0.87 & 40.21$\pm$3.37 X & 94.16$\pm$0.4 & 34.81$\pm$2.19 \\
bgrl deg & \color{violet}{89.89$\pm$2.88} & 36.43$\pm$2.34 & 58.34$\pm$11.86 & 94.7$\pm$0.51 & \color{blue}{38.2$\pm$6.85 $\bigstar$} \\
bgrl pr & 84.25$\pm$1.28 X & 30.64$\pm$1.65 X & 36.25$\pm$4.74 X & 94.32$\pm$0.35 & 28.78$\pm$3.25 \\
bgrl evc & 85.22$\pm$1.22 & 32.19$\pm$1.05 X & 58.06$\pm$10.85 & 94.24$\pm$0.4 & \color{violet}{37.56$\pm$9.88} \\
bgrl scom & 85.75$\pm$1.31 & 32.7$\pm$1.49 & 40.71$\pm$3.81 X & 94.11$\pm$0.42 & 32.34$\pm$5.07 \\
bgrl random+scom & 85.71$\pm$1.47 & 33.07$\pm$1.1 & 40.71$\pm$3.31 X & 93.84$\pm$0.51 X & 35.97$\pm$1.93 $\bigstar$ \\
bgrl random+deg & 86.5$\pm$1.54 & 33.91$\pm$0.99 & 51.8$\pm$4.39 & 94.59$\pm$0.51 & 29.39$\pm$6.35 \\
bgrl deg+scom & 85.6$\pm$1.42 & 33.08$\pm$1.79 & 47.53$\pm$3.86 & 94.63$\pm$0.39 & 25.56$\pm$4.88 \\
csgcl random & 85.22$\pm$1.84 & 39.42$\pm$1.11 & 49.96$\pm$4.15 & 94.45$\pm$0.24 & 30.03$\pm$3.27 \\
csgcl deg & \color{red}{91.3$\pm$2.89 $\bigstar$} & \color{blue}{41.97$\pm$1.95 $\bigstar$} & \color{red}{62.01$\pm$7.63 $\bigstar$} & 94.54$\pm$0.38 & 31.76$\pm$6.56 \\
csgcl pr & 84.58$\pm$1.7 X & 39.21$\pm$0.71 & 50.49$\pm$5.52 & 94.71$\pm$0.22 & 26.78$\pm$2.88 \\
csgcl evc & 85.0$\pm$1.37 & 39.08$\pm$1.12 & \color{violet}{59.93$\pm$10.46} & 94.6$\pm$0.26 & 35.59$\pm$10.48 \\
csgcl scom & 85.73$\pm$1.32 & 39.19$\pm$0.78 & 50.46$\pm$4.19 & 94.65$\pm$0.27 & 31.08$\pm$6.53 \\
csgcl random+scom & 84.53$\pm$1.93 X & 39.0$\pm$1.79 & 50.35$\pm$3.58 & 94.57$\pm$0.34 & 26.14$\pm$2.5 X \\
csgcl random+deg & 88.56$\pm$2.36 & 40.33$\pm$0.64 & 50.92$\pm$5.99 & \color{blue}{94.93$\pm$0.5 $\bigstar$} & 27.08$\pm$3.08 \\
csgcl deg+scom & 89.29$\pm$2.93 & 40.35$\pm$1.19 & 53.57$\pm$3.64 & \color{violet}{94.91$\pm$0.4 $\bigstar$} & 26.07$\pm$2.44 X \\
\bottomrule
\end{tabular}

}

,FINAL_netscience_res.csv,FINAL_power_res.csv,FINAL_euroroad_res.csv,FINAL_yeast_res.csv,FINAL_crime_res.csv
baseline,87.55$\pm$1.47,36.84$\pm$1.22,55.09$\pm$2.31,94.55$\pm$0.29,\color{red}{38.78$\pm$3.36 $\bigstar$}
grace random,85.31$\pm$1.41,39.4$\pm$1.39,51.84$\pm$3.9,94.61$\pm$0.26,27.12$\pm$3.32
grace deg,\color{blue}{91.26$\pm$3.25 $\bigstar$},\color{red}{42.11$\pm$1.53 $\bigstar$},\color{blue}{61.59$\pm$9.64 $\bigstar$},94.45$\pm$0.36,32.37$\pm$5.53
grace pr,84.73$\pm$1.5 X,39.77$\pm$1.33,56.71$\pm$6.92,94.9$\pm$0.29 $\bigstar$,25.36$\pm$3.11 X
grace evc,85.33$\pm$1.49,39.88$\pm$1.2,59.15$\pm$8.87,94.63$\pm$0.3,34.98$\pm$10.47
grace scom,85.82$\pm$1.64,39.39$\pm$0.97,51.48$\pm$4.92,94.66$\pm$0.3,29.83$\pm$6.19
grace random+scom,85.29$\pm$1.17,39.89$\pm$1.09,50.11$\pm$2.39,94.6$\pm$0.31,25.73$\pm$2.91 X
grace random+deg,89.64$\pm$3.05,40.83$\pm$1.06,54.49$\pm$5.37,\color{red}{94.94$\pm$0.52 $\bigstar$},27.53$\pm$1.42
grace deg+scom,89.22$\pm$2.16,\color{violet}{41.18$\pm$1.42},54.77$\pm$5.11,94.84$\pm$0.45,27.36$\pm$3.17
bgrl random,86.31$\pm$1.26,33.03$\pm$0.87,40.21$\pm$3.37 X,94.16$\pm$0.4,34.81$\pm$2.19
bgrl deg,\color{violet}{89.89$\pm$2.88},36.43$\pm$2.34,58.34$\pm$11.86,94.7$\pm$0.51,\color{blue}{38.2$\pm$6.85 $\bigstar$}
bgrl pr,84.25$\pm$1.28 X,30.64$\pm$1.65 X,36.25$\pm$4.74 X,94.32$\pm$0.35,28.78$\pm$3.25
bgrl evc,85.22$\pm$1.22,32.19$\pm$1.05 X,58.06$\pm$10.85,94.24$\pm$0.4,\color{violet}{37.56$\pm$9.88}
bgrl scom,85.75$\pm$1.31,32.7$\pm$1.49,40.71$\pm$3.81 X,94.11$\pm$0.42,32.34$\pm$5.07
bgrl random+scom,85.71$\pm$1.47,33.07$\pm$1.1,40.71$\pm$3.31 X,93.84$\pm$0.51 X,35.97$\pm$1.93 $\bigstar$
bgrl random+deg,86.5$\pm$1.54,33.91$\pm$0.99,51.8$\pm$4.39,94.59$\pm$0.51,29.39$\pm$6.35
bgrl deg+scom,85.6$\pm$1.42,33.08$\pm$1.79,47.53$\pm$3.86,94.63$\pm$0.39,25.56$\pm$4.88
csgcl random,85.22$\pm$1.84,39.42$\pm$1.11,49.96$\pm$4.15,94.45$\pm$0.24,30.03$\pm$3.27
csgcl deg,\color{red}{91.3$\pm$2.89 $\bigstar$},\color{blue}{41.97$\pm$1.95 $\bigstar$},\color{red}{62.01$\pm$7.63 $\bigstar$},94.54$\pm$0.38,31.76$\pm$6.56
csgcl pr,84.58$\pm$1.7 X,39.21$\pm$0.71,50.49$\pm$5.52,94.71$\pm$0.22,26.78$\pm$2.88
csgcl evc,85.0$\pm$1.37,39.08$\pm$1.12,\color{violet}{59.93$\pm$10.46},94.6$\pm$0.26,35.59$\pm$10.48
csgcl scom,85.73$\pm$1.32,39.19$\pm$0.78,50.46$\pm$4.19,94.65$\pm$0.27,31.08$\pm$6.53
csgcl random+scom,84.53$\pm$1.93 X,39.0$\pm$1.79,50.35$\pm$3.58,94.57$\pm$0.34,26.14$\pm$2.5 X
csgcl random+deg,88.56$\pm$2.36,40.33$\pm$0.64,50.92$\pm$5.99,\color{blue}{94.93$\pm$0.5 $\bigstar$},27.08$\pm$3.08
csgcl deg+scom,89.29$\pm$2.93,40.35$\pm$1.19,53.57$\pm$3.64,\color{violet}{94.91$\pm$0.4 $\bigstar$},26.07$\pm$2.44 X

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv \\
\midrule
baseline & 85.18$\pm$1.85 & 32.24$\pm$0.75 & 36.71$\pm$3.26 & 93.98$\pm$0.55 & 23.02$\pm$2.9 \\
grace random & 84.34$\pm$1.29 & 36.05$\pm$1.17 & 37.42$\pm$2.96 & 94.28$\pm$0.28 & 18.34$\pm$2.03 \\
grace deg & \color{violet}{86.28$\pm$2.0} & 36.46$\pm$1.26 $\bigstar$ & \color{red}{43.46$\pm$7.72 $\bigstar$} & 93.66$\pm$0.56 & 21.05$\pm$3.22 \\
grace pr & 84.0$\pm$1.65 & 36.44$\pm$0.93 $\bigstar$ & 39.65$\pm$4.48 & 94.32$\pm$0.3 & 17.12$\pm$1.93 X \\
grace evc & 84.32$\pm$1.58 & \color{violet}{36.57$\pm$1.3 $\bigstar$} & 42.08$\pm$7.26 $\bigstar$ & 94.24$\pm$0.3 & 21.63$\pm$5.49 \\
grace scom & 84.32$\pm$1.3 & 36.34$\pm$1.11 $\bigstar$ & 36.22$\pm$3.33 & \color{red}{94.37$\pm$0.24 $\bigstar$} & 18.85$\pm$3.06 \\
grace random+scom & 84.11$\pm$1.34 & 36.4$\pm$0.94 $\bigstar$ & 34.88$\pm$1.91 & 94.26$\pm$0.33 & 16.95$\pm$2.03 X \\
grace random+deg & \color{blue}{86.93$\pm$2.53 $\bigstar$} & 36.27$\pm$1.03 $\bigstar$ & 38.37$\pm$3.28 & 94.2$\pm$0.48 & 18.27$\pm$2.03 \\
grace deg+scom & 86.04$\pm$2.0 $\bigstar$ & \color{blue}{36.8$\pm$1.64 $\bigstar$} & 38.94$\pm$5.06 & 94.02$\pm$0.49 & 17.59$\pm$2.47 \\
bgrl random & 85.18$\pm$1.28 & 29.6$\pm$0.96 & 27.31$\pm$3.89 & 93.78$\pm$0.54 & \color{blue}{23.73$\pm$2.21 $\bigstar$} \\
bgrl deg & \color{red}{86.95$\pm$2.33 $\bigstar$} & 31.79$\pm$1.73 & 38.94$\pm$9.26 & 94.26$\pm$0.48 & 22.85$\pm$3.54 \\
bgrl pr & 83.58$\pm$1.23 X & 27.75$\pm$1.17 X & 23.39$\pm$2.68 X & 94.0$\pm$0.38 & 17.86$\pm$2.27 \\
bgrl evc & 84.25$\pm$1.55 & 29.49$\pm$1.11 & 38.27$\pm$8.41 & 93.69$\pm$0.44 & 22.1$\pm$6.04 \\
bgrl scom & 84.69$\pm$1.39 & 29.92$\pm$1.16 & 28.13$\pm$2.69 & 93.46$\pm$0.56 X & 20.51$\pm$3.5 \\
bgrl random+scom & 84.84$\pm$1.56 & 29.77$\pm$1.38 & 28.37$\pm$2.86 & 93.33$\pm$0.65 X & \color{red}{24.95$\pm$3.63 $\bigstar$} \\
bgrl random+deg & 84.89$\pm$1.64 & 30.33$\pm$0.85 & 34.88$\pm$3.01 & \color{violet}{94.36$\pm$0.6 $\bigstar$} & 18.78$\pm$4.59 \\
bgrl deg+scom & 84.43$\pm$1.56 & 29.86$\pm$1.42 & 32.08$\pm$3.74 & \color{blue}{94.37$\pm$0.5 $\bigstar$} & 17.12$\pm$3.17 \\
csgcl random & 84.2$\pm$1.8 & 36.19$\pm$0.87 $\bigstar$ & 34.73$\pm$2.9 & 94.21$\pm$0.27 & 18.47$\pm$2.91 \\
csgcl deg & 86.11$\pm$2.27 & \color{red}{36.84$\pm$1.63 $\bigstar$} & \color{blue}{43.36$\pm$7.14 $\bigstar$} & 93.93$\pm$0.59 & 19.9$\pm$4.79 \\
csgcl pr & 83.94$\pm$1.82 & 35.58$\pm$0.9 & 35.19$\pm$4.83 & 94.31$\pm$0.21 & 18.07$\pm$1.56 \\
csgcl evc & 84.09$\pm$1.56 & 36.13$\pm$1.17 & \color{violet}{42.26$\pm$6.19 $\bigstar$} & 94.26$\pm$0.31 & \color{violet}{23.39$\pm$7.61} \\
csgcl scom & 84.05$\pm$1.53 & 35.93$\pm$0.8 & 34.1$\pm$2.38 & 94.29$\pm$0.32 & 18.61$\pm$3.45 \\
csgcl random+scom & 83.78$\pm$1.81 & 36.12$\pm$1.42 & 35.9$\pm$2.9 & 94.26$\pm$0.31 & 16.58$\pm$1.87 X \\
csgcl random+deg & 86.26$\pm$2.19 & 36.18$\pm$0.91 $\bigstar$ & 37.03$\pm$3.94 & 94.16$\pm$0.37 & 18.03$\pm$2.27 \\
csgcl deg+scom & 86.26$\pm$2.22 & 36.2$\pm$0.89 $\bigstar$ & 38.02$\pm$3.79 & 94.16$\pm$0.47 & 17.19$\pm$2.12 X \\
\bottomrule
\end{tabular}

}

,FINAL_netscience_res.csv,FINAL_power_res.csv,FINAL_euroroad_res.csv,FINAL_yeast_res.csv,FINAL_crime_res.csv
baseline,85.18$\pm$1.85,32.24$\pm$0.75,36.71$\pm$3.26,93.98$\pm$0.55,23.02$\pm$2.9
grace random,84.34$\pm$1.29,36.05$\pm$1.17,37.42$\pm$2.96,94.28$\pm$0.28,18.34$\pm$2.03
grace deg,\color{violet}{86.28$\pm$2.0},36.46$\pm$1.26 $\bigstar$,\color{red}{43.46$\pm$7.72 $\bigstar$},93.66$\pm$0.56,21.05$\pm$3.22
grace pr,84.0$\pm$1.65,36.44$\pm$0.93 $\bigstar$,39.65$\pm$4.48,94.32$\pm$0.3,17.12$\pm$1.93 X
grace evc,84.32$\pm$1.58,\color{violet}{36.57$\pm$1.3 $\bigstar$},42.08$\pm$7.26 $\bigstar$,94.24$\pm$0.3,21.63$\pm$5.49
grace scom,84.32$\pm$1.3,36.34$\pm$1.11 $\bigstar$,36.22$\pm$3.33,\color{red}{94.37$\pm$0.24 $\bigstar$},18.85$\pm$3.06
grace random+scom,84.11$\pm$1.34,36.4$\pm$0.94 $\bigstar$,34.88$\pm$1.91,94.26$\pm$0.33,16.95$\pm$2.03 X
grace random+deg,\color{blue}{86.93$\pm$2.53 $\bigstar$},36.27$\pm$1.03 $\bigstar$,38.37$\pm$3.28,94.2$\pm$0.48,18.27$\pm$2.03
grace deg+scom,86.04$\pm$2.0 $\bigstar$,\color{blue}{36.8$\pm$1.64 $\bigstar$},38.94$\pm$5.06,94.02$\pm$0.49,17.59$\pm$2.47
bgrl random,85.18$\pm$1.28,29.6$\pm$0.96,27.31$\pm$3.89,93.78$\pm$0.54,\color{blue}{23.73$\pm$2.21 $\bigstar$}
bgrl deg,\color{red}{86.95$\pm$2.33 $\bigstar$},31.79$\pm$1.73,38.94$\pm$9.26,94.26$\pm$0.48,22.85$\pm$3.54
bgrl pr,83.58$\pm$1.23 X,27.75$\pm$1.17 X,23.39$\pm$2.68 X,94.0$\pm$0.38,17.86$\pm$2.27
bgrl evc,84.25$\pm$1.55,29.49$\pm$1.11,38.27$\pm$8.41,93.69$\pm$0.44,22.1$\pm$6.04
bgrl scom,84.69$\pm$1.39,29.92$\pm$1.16,28.13$\pm$2.69,93.46$\pm$0.56 X,20.51$\pm$3.5
bgrl random+scom,84.84$\pm$1.56,29.77$\pm$1.38,28.37$\pm$2.86,93.33$\pm$0.65 X,\color{red}{24.95$\pm$3.63 $\bigstar$}
bgrl random+deg,84.89$\pm$1.64,30.33$\pm$0.85,34.88$\pm$3.01,\color{violet}{94.36$\pm$0.6 $\bigstar$},18.78$\pm$4.59
bgrl deg+scom,84.43$\pm$1.56,29.86$\pm$1.42,32.08$\pm$3.74,\color{blue}{94.37$\pm$0.5 $\bigstar$},17.12$\pm$3.17
csgcl random,84.2$\pm$1.8,36.19$\pm$0.87 $\bigstar$,34.73$\pm$2.9,94.21$\pm$0.27,18.47$\pm$2.91
csgcl deg,86.11$\pm$2.27,\color{red}{36.84$\pm$1.63 $\bigstar$},\color{blue}{43.36$\pm$7.14 $\bigstar$},93.93$\pm$0.59,19.9$\pm$4.79
csgcl pr,83.94$\pm$1.82,35.58$\pm$0.9,35.19$\pm$4.83,94.31$\pm$0.21,18.07$\pm$1.56
csgcl evc,84.09$\pm$1.56,36.13$\pm$1.17,\color{violet}{42.26$\pm$6.19 $\bigstar$},94.26$\pm$0.31,\color{violet}{23.39$\pm$7.61}
csgcl scom,84.05$\pm$1.53,35.93$\pm$0.8,34.1$\pm$2.38,94.29$\pm$0.32,18.61$\pm$3.45
csgcl random+scom,83.78$\pm$1.81,36.12$\pm$1.42,35.9$\pm$2.9,94.26$\pm$0.31,16.58$\pm$1.87 X
csgcl random+deg,86.26$\pm$2.19,36.18$\pm$0.91 $\bigstar$,37.03$\pm$3.94,94.16$\pm$0.37,18.03$\pm$2.27
csgcl deg+scom,86.26$\pm$2.22,36.2$\pm$0.89 $\bigstar$,38.02$\pm$3.79,94.16$\pm$0.47,17.19$\pm$2.12 X

                             Hits@20
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv \\
\midrule
baseline & 83.18$\pm$1.69 & 27.37$\pm$1.92 & 23.64$\pm$1.54 & 91.53$\pm$1.3 & \color{violet}{14.64$\pm$2.25} \\
grace random & 83.56$\pm$1.23 & \color{violet}{32.88$\pm$1.33} & 25.27$\pm$2.58 & 92.7$\pm$1.1 & 13.32$\pm$1.73 \\
grace deg & 82.46$\pm$1.48 X & 30.93$\pm$2.51 & \color{blue}{26.57$\pm$6.03} & 89.69$\pm$2.5 X & 13.49$\pm$1.96 \\
grace pr & 83.19$\pm$1.56 & 32.75$\pm$1.22 & \color{violet}{26.4$\pm$3.35} & 92.7$\pm$1.27 & 12.31$\pm$1.55 \\
grace evc & 83.54$\pm$1.4 & 32.72$\pm$1.75 & 25.97$\pm$4.91 & 92.36$\pm$1.95 & 12.64$\pm$2.07 \\
grace scom & 83.54$\pm$1.52 & \color{blue}{32.92$\pm$1.4 $\bigstar$} & 24.63$\pm$1.91 & 92.47$\pm$1.91 & 12.31$\pm$1.06 \\
grace random+scom & 83.43$\pm$1.64 & \color{red}{33.06$\pm$1.1 $\bigstar$} & 25.97$\pm$1.92 & 92.56$\pm$1.15 & 12.14$\pm$1.58 X \\
grace random+deg & \color{red}{84.74$\pm$1.79 $\bigstar$} & 31.33$\pm$2.56 & 25.69$\pm$2.94 & 91.82$\pm$1.29 & 13.19$\pm$1.07 \\
grace deg+scom & 83.65$\pm$1.88 & 32.27$\pm$2.17 & \color{red}{27.56$\pm$3.27 $\bigstar$} & 91.68$\pm$1.37 & 12.88$\pm$1.7 \\
bgrl random & \color{blue}{84.38$\pm$1.45 $\bigstar$} & 26.91$\pm$1.23 & 17.35$\pm$3.12 X & 92.89$\pm$0.79 & \color{blue}{15.29$\pm$3.03} \\
bgrl deg & \color{violet}{84.34$\pm$1.81} & 28.29$\pm$1.29 & 23.0$\pm$4.81 & \color{violet}{92.99$\pm$0.91} & 14.0$\pm$2.84 \\
bgrl pr & 82.34$\pm$1.48 X & 25.27$\pm$0.98 X & 15.94$\pm$1.23 X & 92.98$\pm$0.73 & 11.15$\pm$2.11 X \\
bgrl evc & 83.69$\pm$1.67 & 27.03$\pm$1.01 & 22.51$\pm$4.61 & 92.51$\pm$1.13 & 13.59$\pm$2.93 \\
bgrl scom & 83.83$\pm$1.45 & 27.25$\pm$1.07 & 16.89$\pm$2.62 X & 91.96$\pm$0.82 & 13.69$\pm$1.76 \\
bgrl random+scom & 84.12$\pm$1.7 & 26.99$\pm$1.26 & 18.76$\pm$2.43 & 92.11$\pm$1.01 & \color{red}{16.1$\pm$3.42 $\bigstar$} \\
bgrl random+deg & 83.96$\pm$1.77 & 27.68$\pm$0.84 & 23.22$\pm$2.39 & \color{blue}{93.22$\pm$0.77} & 12.71$\pm$2.34 \\
bgrl deg+scom & 83.47$\pm$1.68 & 27.26$\pm$1.04 & 20.57$\pm$2.77 & \color{red}{93.38$\pm$0.83 $\bigstar$} & 11.69$\pm$1.77 X \\
csgcl random & 83.34$\pm$1.74 & 32.58$\pm$0.88 & 24.06$\pm$2.47 & 92.9$\pm$0.95 & 12.61$\pm$1.43 \\
csgcl deg & 82.85$\pm$1.59 & 32.04$\pm$1.78 & 25.87$\pm$2.12 & 90.88$\pm$1.78 & 13.19$\pm$1.96 \\
csgcl pr & 83.36$\pm$1.82 & 32.26$\pm$1.26 & 22.76$\pm$1.88 & 92.94$\pm$0.85 & 12.95$\pm$1.87 \\
csgcl evc & 83.18$\pm$1.71 & 32.33$\pm$1.54 & 26.01$\pm$4.98 & 92.76$\pm$1.24 & 14.03$\pm$3.14 \\
csgcl scom & 83.16$\pm$1.48 & 32.4$\pm$1.34 & 23.32$\pm$2.53 & 92.97$\pm$1.1 & 12.98$\pm$1.71 \\
csgcl random+scom & 83.19$\pm$1.71 & 32.15$\pm$1.16 & 26.18$\pm$2.09 $\bigstar$ & 92.84$\pm$1.01 & 11.73$\pm$1.7 X \\
csgcl random+deg & 83.98$\pm$1.96 & 31.93$\pm$1.5 & 25.94$\pm$2.06 $\bigstar$ & 92.08$\pm$0.89 & 12.41$\pm$1.57 \\
csgcl deg+scom & 83.98$\pm$2.11 & 31.47$\pm$1.19 & 25.9$\pm$3.31 & 92.02$\pm$1.04 & 12.51$\pm$1.92 \\
\bottomrule
\end{tabular}

}

,FINAL_netscience_res.csv,FINAL_power_res.csv,FINAL_euroroad_res.csv,FINAL_yeast_res.csv,FINAL_crime_res.csv
baseline,83.18$\pm$1.69,27.37$\pm$1.92,23.64$\pm$1.54,91.53$\pm$1.3,\color{violet}{14.64$\pm$2.25}
grace random,83.56$\pm$1.23,\color{violet}{32.88$\pm$1.33},25.27$\pm$2.58,92.7$\pm$1.1,13.32$\pm$1.73
grace deg,82.46$\pm$1.48 X,30.93$\pm$2.51,\color{blue}{26.57$\pm$6.03},89.69$\pm$2.5 X,13.49$\pm$1.96
grace pr,83.19$\pm$1.56,32.75$\pm$1.22,\color{violet}{26.4$\pm$3.35},92.7$\pm$1.27,12.31$\pm$1.55
grace evc,83.54$\pm$1.4,32.72$\pm$1.75,25.97$\pm$4.91,92.36$\pm$1.95,12.64$\pm$2.07
grace scom,83.54$\pm$1.52,\color{blue}{32.92$\pm$1.4 $\bigstar$},24.63$\pm$1.91,92.47$\pm$1.91,12.31$\pm$1.06
grace random+scom,83.43$\pm$1.64,\color{red}{33.06$\pm$1.1 $\bigstar$},25.97$\pm$1.92,92.56$\pm$1.15,12.14$\pm$1.58 X
grace random+deg,\color{red}{84.74$\pm$1.79 $\bigstar$},31.33$\pm$2.56,25.69$\pm$2.94,91.82$\pm$1.29,13.19$\pm$1.07
grace deg+scom,83.65$\pm$1.88,32.27$\pm$2.17,\color{red}{27.56$\pm$3.27 $\bigstar$},91.68$\pm$1.37,12.88$\pm$1.7
bgrl random,\color{blue}{84.38$\pm$1.45 $\bigstar$},26.91$\pm$1.23,17.35$\pm$3.12 X,92.89$\pm$0.79,\color{blue}{15.29$\pm$3.03}
bgrl deg,\color{violet}{84.34$\pm$1.81},28.29$\pm$1.29,23.0$\pm$4.81,\color{violet}{92.99$\pm$0.91},14.0$\pm$2.84
bgrl pr,82.34$\pm$1.48 X,25.27$\pm$0.98 X,15.94$\pm$1.23 X,92.98$\pm$0.73,11.15$\pm$2.11 X
bgrl evc,83.69$\pm$1.67,27.03$\pm$1.01,22.51$\pm$4.61,92.51$\pm$1.13,13.59$\pm$2.93
bgrl scom,83.83$\pm$1.45,27.25$\pm$1.07,16.89$\pm$2.62 X,91.96$\pm$0.82,13.69$\pm$1.76
bgrl random+scom,84.12$\pm$1.7,26.99$\pm$1.26,18.76$\pm$2.43,92.11$\pm$1.01,\color{red}{16.1$\pm$3.42 $\bigstar$}
bgrl random+deg,83.96$\pm$1.77,27.68$\pm$0.84,23.22$\pm$2.39,\color{blue}{93.22$\pm$0.77},12.71$\pm$2.34
bgrl deg+scom,83.47$\pm$1.68,27.26$\pm$1.04,20.57$\pm$2.77,\color{red}{93.38$\pm$0.83 $\bigstar$},11.69$\pm$1.77 X
csgcl random,83.34$\pm$1.74,32.58$\pm$0.88,24.06$\pm$2.47,92.9$\pm$0.95,12.61$\pm$1.43
csgcl deg,82.85$\pm$1.59,32.04$\pm$1.78,25.87$\pm$2.12,90.88$\pm$1.78,13.19$\pm$1.96
csgcl pr,83.36$\pm$1.82,32.26$\pm$1.26,22.76$\pm$1.88,92.94$\pm$0.85,12.95$\pm$1.87
csgcl evc,83.18$\pm$1.71,32.33$\pm$1.54,26.01$\pm$4.98,92.76$\pm$1.24,14.03$\pm$3.14
csgcl scom,83.16$\pm$1.48,32.4$\pm$1.34,23.32$\pm$2.53,92.97$\pm$1.1,12.98$\pm$1.71
csgcl random+scom,83.19$\pm$1.71,32.15$\pm$1.16,26.18$\pm$2.09 $\bigstar$,92.84$\pm$1.01,11.73$\pm$1.7 X
csgcl random+deg,83.98$\pm$1.96,31.93$\pm$1.5,25.94$\pm$2.06 $\bigstar$,92.08$\pm$0.89,12.41$\pm$1.57
csgcl deg+scom,83.98$\pm$2.11,31.47$\pm$1.19,25.9$\pm$3.31,92.02$\pm$1.04,12.51$\pm$1.92

In [6]:
# score
names = ['FINAL_cora_res.csv',
'FINAL_citeseer_res.csv',
'FINAL_photo_res.csv']
print("                             ROCAUC                      ")
all_data, all_res = ut.mix_dataset(names, 'ROCAUC')
display(ut.tex_table(all_data, all_res).T)
print("                             AP                      ")
all_data, all_res = ut.mix_dataset(names, 'AP')
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@100                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@100')
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50')
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@20                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@20')
display(ut.tex_table(all_data, all_res).T)

                             ROCAUC
\resizebox{\textwidth}{!}{
\begin{tabular}{llll}
\toprule
 & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_photo_res.csv \\
\midrule
baseline & 90.61$\pm$0.77 & 91.54$\pm$0.44 & 76.85$\pm$22.69 X \\
grace random & 91.73$\pm$0.78 & 93.38$\pm$0.6 & 97.94$\pm$0.16 \\
grace deg & 93.43$\pm$0.5 & \color{blue}{94.48$\pm$0.66 $\bigstar$} & 97.9$\pm$0.27 \\
grace pr & 93.39$\pm$0.47 & 94.08$\pm$0.46 & 98.05$\pm$0.19 \\
grace evc & 93.41$\pm$0.4 & 94.04$\pm$0.42 & 97.82$\pm$0.48 \\
grace scom & 91.7$\pm$0.9 & 94.2$\pm$0.48 $\bigstar$ & 97.98$\pm$0.28 \\
grace random+scom & 91.57$\pm$0.84 & 93.82$\pm$0.53 & 97.83$\pm$0.43 \\
grace random+deg & \color{violet}{93.8$\pm$0.52 $\bigstar$} & 94.16$\pm$0.9 & 97.99$\pm$0.22 \\
grace deg+scom & 93.62$\pm$0.58 & \color{violet}{94.48$\pm$0.7 $\bigstar$} & 97.86$\pm$0.17 X \\
bgrl random & 89.62$\pm$0.79 X & 90.02$\pm$0.66 & 96.3$\pm$7.37 \\
bgrl deg & 92.18$\pm$0.68 & 90.97$\pm$2.79 & 97.23$\pm$4.85 \\
bgrl pr & 92.22$\pm$0.68 & 89.23$\pm$0.77 X & 97.83$\pm$2.07 \\
bgrl evc & 92.1$\pm$0.83 & 90.09$\pm$0.45 & \color{red}{98.85$\pm$0.11 $\bigstar$} \\
bgrl scom & 89.59$\pm$0.88 X & 90.24$\pm$0.4 & \color{violet}{98.66$\pm$0.33} \\
bgrl random+scom & 89.38$\pm$1.0 X & 89.98$\pm$0.45 & 97.52$\pm$3.75 \\
bgrl random+deg & 91.73$\pm$0.83 & 90.87$\pm$2.43 & 98.26$\pm$1.72 \\
bgrl deg+scom & 91.46$\pm$1.06 & 91.05$\pm$1.91 & \color{blue}{98.75$\pm$0.28} \\
csgcl random & 91.67$\pm$0.98 & 93.39$\pm$0.56 & 97.82$\pm$0.17 X \\
csgcl deg & \color{blue}{93.81$\pm$0.61 $\bigstar$} & \color{red}{94.55$\pm$0.67 $\bigstar$} & 98.04$\pm$0.17 \\
csgcl pr & 93.79$\pm$0.49 $\bigstar$ & 93.98$\pm$0.32 & 98.04$\pm$0.18 \\
csgcl evc & 93.59$\pm$0.4 & 93.6$\pm$0.48 & 97.88$\pm$0.21 X \\
csgcl scom & 91.72$\pm$1.09 & 94.0$\pm$0.38 & 97.84$\pm$0.27 X \\
csgcl random+scom & 91.49$\pm$0.8 & 93.48$\pm$0.51 & 97.73$\pm$0.46 X \\
csgcl random+deg & \color{red}{93.88$\pm$0.71 $\bigstar$} & 94.12$\pm$0.96 & 97.97$\pm$0.21 \\
csgcl deg+scom & 93.52$\pm$0.62 & 94.31$\pm$0.88 & 97.95$\pm$0.25 \\
\bottomrule
\end{tabular}

}

,FINAL_cora_res.csv,FINAL_citeseer_res.csv,FINAL_photo_res.csv
baseline,90.61$\pm$0.77,91.54$\pm$0.44,76.85$\pm$22.69 X
grace random,91.73$\pm$0.78,93.38$\pm$0.6,97.94$\pm$0.16
grace deg,93.43$\pm$0.5,\color{blue}{94.48$\pm$0.66 $\bigstar$},97.9$\pm$0.27
grace pr,93.39$\pm$0.47,94.08$\pm$0.46,98.05$\pm$0.19
grace evc,93.41$\pm$0.4,94.04$\pm$0.42,97.82$\pm$0.48
grace scom,91.7$\pm$0.9,94.2$\pm$0.48 $\bigstar$,97.98$\pm$0.28
grace random+scom,91.57$\pm$0.84,93.82$\pm$0.53,97.83$\pm$0.43
grace random+deg,\color{violet}{93.8$\pm$0.52 $\bigstar$},94.16$\pm$0.9,97.99$\pm$0.22
grace deg+scom,93.62$\pm$0.58,\color{violet}{94.48$\pm$0.7 $\bigstar$},97.86$\pm$0.17 X
bgrl random,89.62$\pm$0.79 X,90.02$\pm$0.66,96.3$\pm$7.37
bgrl deg,92.18$\pm$0.68,90.97$\pm$2.79,97.23$\pm$4.85
bgrl pr,92.22$\pm$0.68,89.23$\pm$0.77 X,97.83$\pm$2.07
bgrl evc,92.1$\pm$0.83,90.09$\pm$0.45,\color{red}{98.85$\pm$0.11 $\bigstar$}
bgrl scom,89.59$\pm$0.88 X,90.24$\pm$0.4,\color{violet}{98.66$\pm$0.33}
bgrl random+scom,89.38$\pm$1.0 X,89.98$\pm$0.45,97.52$\pm$3.75
bgrl random+deg,91.73$\pm$0.83,90.87$\pm$2.43,98.26$\pm$1.72
bgrl deg+scom,91.46$\pm$1.06,91.05$\pm$1.91,\color{blue}{98.75$\pm$0.28}
csgcl random,91.67$\pm$0.98,93.39$\pm$0.56,97.82$\pm$0.17 X
csgcl deg,\color{blue}{93.81$\pm$0.61 $\bigstar$},\color{red}{94.55$\pm$0.67 $\bigstar$},98.04$\pm$0.17
csgcl pr,93.79$\pm$0.49 $\bigstar$,93.98$\pm$0.32,98.04$\pm$0.18
csgcl evc,93.59$\pm$0.4,93.6$\pm$0.48,97.88$\pm$0.21 X
csgcl scom,91.72$\pm$1.09,94.0$\pm$0.38,97.84$\pm$0.27 X
csgcl random+scom,91.49$\pm$0.8,93.48$\pm$0.51,97.73$\pm$0.46 X
csgcl random+deg,\color{red}{93.88$\pm$0.71 $\bigstar$},94.12$\pm$0.96,97.97$\pm$0.21
csgcl deg+scom,93.52$\pm$0.62,94.31$\pm$0.88,97.95$\pm$0.25

                             AP
\resizebox{\textwidth}{!}{
\begin{tabular}{llll}
\toprule
 & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_photo_res.csv \\
\midrule
baseline & 92.5$\pm$0.52 X & 93.19$\pm$0.37 & 76.77$\pm$22.55 X \\
grace random & 93.49$\pm$0.57 & 94.66$\pm$0.5 & 97.38$\pm$0.37 \\
grace deg & 93.78$\pm$0.5 & 95.16$\pm$0.4 & 97.32$\pm$0.52 \\
grace pr & 93.66$\pm$0.48 & 95.03$\pm$0.38 & 97.51$\pm$0.35 \\
grace evc & 93.7$\pm$0.42 & 95.02$\pm$0.42 & 97.09$\pm$0.81 \\
grace scom & 93.5$\pm$0.65 & 95.16$\pm$0.4 $\bigstar$ & 97.54$\pm$0.38 \\
grace random+scom & 93.34$\pm$0.62 & 94.96$\pm$0.43 & 97.17$\pm$0.86 \\
grace random+deg & \color{blue}{94.26$\pm$0.49} & 95.11$\pm$0.56 & 97.51$\pm$0.36 \\
grace deg+scom & 94.14$\pm$0.46 & \color{blue}{95.25$\pm$0.52 $\bigstar$} & 97.0$\pm$0.58 X \\
bgrl random & 92.26$\pm$0.62 X & 92.59$\pm$0.56 & 96.13$\pm$7.34 \\
bgrl deg & 93.98$\pm$0.49 & 93.24$\pm$2.01 & 97.14$\pm$4.69 \\
bgrl pr & 94.02$\pm$0.45 & 91.95$\pm$0.61 X & 97.56$\pm$2.32 \\
bgrl evc & 93.93$\pm$0.6 & 92.53$\pm$0.4 & \color{red}{98.69$\pm$0.15 $\bigstar$} \\
bgrl scom & 92.3$\pm$0.61 X & 92.69$\pm$0.41 & \color{violet}{98.46$\pm$0.4} \\
bgrl random+scom & 92.1$\pm$0.75 X & 92.57$\pm$0.34 & 97.43$\pm$3.48 \\
bgrl random+deg & 93.8$\pm$0.59 & 93.23$\pm$1.76 & 98.03$\pm$1.9 \\
bgrl deg+scom & 93.64$\pm$0.69 & 93.34$\pm$1.39 & \color{blue}{98.6$\pm$0.3 $\bigstar$} \\
csgcl random & 93.44$\pm$0.75 & 94.62$\pm$0.47 & 97.24$\pm$0.3 X \\
csgcl deg & \color{violet}{94.26$\pm$0.47} & \color{red}{95.31$\pm$0.52 $\bigstar$} & 97.55$\pm$0.26 \\
csgcl pr & 94.22$\pm$0.35 & 95.0$\pm$0.28 & 97.48$\pm$0.28 \\
csgcl evc & 93.99$\pm$0.35 & 94.73$\pm$0.39 & 97.23$\pm$0.39 X \\
csgcl scom & 93.48$\pm$0.82 & 95.01$\pm$0.33 & 97.23$\pm$0.6 \\
csgcl random+scom & 93.4$\pm$0.6 & 94.65$\pm$0.53 & 96.88$\pm$1.04 X \\
csgcl random+deg & \color{red}{94.55$\pm$0.57 $\bigstar$} & 95.12$\pm$0.71 & 97.36$\pm$0.37 \\
csgcl deg+scom & 94.21$\pm$0.47 & \color{violet}{95.22$\pm$0.65} & 97.26$\pm$0.48 \\
\bottomrule
\end{tabular}

}

,FINAL_cora_res.csv,FINAL_citeseer_res.csv,FINAL_photo_res.csv
baseline,92.5$\pm$0.52 X,93.19$\pm$0.37,76.77$\pm$22.55 X
grace random,93.49$\pm$0.57,94.66$\pm$0.5,97.38$\pm$0.37
grace deg,93.78$\pm$0.5,95.16$\pm$0.4,97.32$\pm$0.52
grace pr,93.66$\pm$0.48,95.03$\pm$0.38,97.51$\pm$0.35
grace evc,93.7$\pm$0.42,95.02$\pm$0.42,97.09$\pm$0.81
grace scom,93.5$\pm$0.65,95.16$\pm$0.4 $\bigstar$,97.54$\pm$0.38
grace random+scom,93.34$\pm$0.62,94.96$\pm$0.43,97.17$\pm$0.86
grace random+deg,\color{blue}{94.26$\pm$0.49},95.11$\pm$0.56,97.51$\pm$0.36
grace deg+scom,94.14$\pm$0.46,\color{blue}{95.25$\pm$0.52 $\bigstar$},97.0$\pm$0.58 X
bgrl random,92.26$\pm$0.62 X,92.59$\pm$0.56,96.13$\pm$7.34
bgrl deg,93.98$\pm$0.49,93.24$\pm$2.01,97.14$\pm$4.69
bgrl pr,94.02$\pm$0.45,91.95$\pm$0.61 X,97.56$\pm$2.32
bgrl evc,93.93$\pm$0.6,92.53$\pm$0.4,\color{red}{98.69$\pm$0.15 $\bigstar$}
bgrl scom,92.3$\pm$0.61 X,92.69$\pm$0.41,\color{violet}{98.46$\pm$0.4}
bgrl random+scom,92.1$\pm$0.75 X,92.57$\pm$0.34,97.43$\pm$3.48
bgrl random+deg,93.8$\pm$0.59,93.23$\pm$1.76,98.03$\pm$1.9
bgrl deg+scom,93.64$\pm$0.69,93.34$\pm$1.39,\color{blue}{98.6$\pm$0.3 $\bigstar$}
csgcl random,93.44$\pm$0.75,94.62$\pm$0.47,97.24$\pm$0.3 X
csgcl deg,\color{violet}{94.26$\pm$0.47},\color{red}{95.31$\pm$0.52 $\bigstar$},97.55$\pm$0.26
csgcl pr,94.22$\pm$0.35,95.0$\pm$0.28,97.48$\pm$0.28
csgcl evc,93.99$\pm$0.35,94.73$\pm$0.39,97.23$\pm$0.39 X
csgcl scom,93.48$\pm$0.82,95.01$\pm$0.33,97.23$\pm$0.6
csgcl random+scom,93.4$\pm$0.6,94.65$\pm$0.53,96.88$\pm$1.04 X
csgcl random+deg,\color{red}{94.55$\pm$0.57 $\bigstar$},95.12$\pm$0.71,97.36$\pm$0.37
csgcl deg+scom,94.21$\pm$0.47,\color{violet}{95.22$\pm$0.65},97.26$\pm$0.48

                             Hits@100
\resizebox{\textwidth}{!}{
\begin{tabular}{llll}
\toprule
 & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_photo_res.csv \\
\midrule
baseline & 77.84$\pm$1.7 X & 80.03$\pm$1.13 & 24.09$\pm$24.24 X \\
grace random & 81.79$\pm$1.1 & 83.62$\pm$1.62 & 37.07$\pm$4.65 \\
grace deg & 84.4$\pm$1.15 & \color{violet}{85.82$\pm$2.4} & 36.09$\pm$5.48 \\
grace pr & 84.22$\pm$1.18 & 84.93$\pm$0.9 & 37.97$\pm$3.92 \\
grace evc & 83.82$\pm$1.07 & 84.63$\pm$1.55 & 33.56$\pm$9.93 \\
grace scom & 81.61$\pm$1.52 & 84.66$\pm$1.05 & 39.79$\pm$5.25 \\
grace random+scom & 81.31$\pm$1.51 & 84.46$\pm$1.54 & 34.47$\pm$10.61 \\
grace random+deg & \color{violet}{84.64$\pm$1.14 $\bigstar$} & 85.26$\pm$2.41 & 38.47$\pm$5.35 \\
grace deg+scom & 84.21$\pm$1.28 & \color{blue}{85.96$\pm$2.03} & 30.63$\pm$8.85 X \\
bgrl random & 78.39$\pm$1.14 X & 78.4$\pm$1.49 & 49.05$\pm$14.99 \\
bgrl deg & 82.98$\pm$1.31 & 80.31$\pm$5.48 & 52.02$\pm$13.75 $\bigstar$ \\
bgrl pr & 82.93$\pm$1.33 & 76.33$\pm$1.62 X & 48.54$\pm$14.03 \\
bgrl evc & 82.7$\pm$1.52 & 78.09$\pm$1.04 & \color{red}{55.9$\pm$3.58 $\bigstar$} \\
bgrl scom & 78.64$\pm$1.06 X & 79.05$\pm$1.41 & \color{violet}{52.46$\pm$5.08} \\
bgrl random+scom & 78.11$\pm$1.57 X & 78.27$\pm$0.58 & 49.34$\pm$11.9 \\
bgrl random+deg & 82.38$\pm$1.59 & 80.34$\pm$4.75 & 51.59$\pm$10.71 \\
bgrl deg+scom & 82.53$\pm$1.31 & 80.43$\pm$3.8 & \color{blue}{54.62$\pm$4.1 $\bigstar$} \\
csgcl random & 81.51$\pm$1.98 & 83.73$\pm$1.14 & 34.56$\pm$4.45 X \\
csgcl deg & 84.62$\pm$1.54 $\bigstar$ & \color{red}{86.48$\pm$2.1 $\bigstar$} & 38.17$\pm$4.58 \\
csgcl pr & \color{blue}{84.75$\pm$1.26 $\bigstar$} & 84.27$\pm$1.1 & 37.85$\pm$3.32 \\
csgcl evc & 84.41$\pm$0.75 & 83.46$\pm$1.15 & 34.85$\pm$5.83 X \\
csgcl scom & 81.42$\pm$2.33 & 84.59$\pm$0.82 & 34.14$\pm$8.36 \\
csgcl random+scom & 81.53$\pm$1.63 & 83.58$\pm$1.24 & 30.95$\pm$12.95 X \\
csgcl random+deg & \color{red}{84.78$\pm$1.54 $\bigstar$} & 85.7$\pm$2.86 & 36.93$\pm$5.87 \\
csgcl deg+scom & 83.75$\pm$1.69 & 85.4$\pm$2.66 & 34.44$\pm$6.57 \\
\bottomrule
\end{tabular}

}

,FINAL_cora_res.csv,FINAL_citeseer_res.csv,FINAL_photo_res.csv
baseline,77.84$\pm$1.7 X,80.03$\pm$1.13,24.09$\pm$24.24 X
grace random,81.79$\pm$1.1,83.62$\pm$1.62,37.07$\pm$4.65
grace deg,84.4$\pm$1.15,\color{violet}{85.82$\pm$2.4},36.09$\pm$5.48
grace pr,84.22$\pm$1.18,84.93$\pm$0.9,37.97$\pm$3.92
grace evc,83.82$\pm$1.07,84.63$\pm$1.55,33.56$\pm$9.93
grace scom,81.61$\pm$1.52,84.66$\pm$1.05,39.79$\pm$5.25
grace random+scom,81.31$\pm$1.51,84.46$\pm$1.54,34.47$\pm$10.61
grace random+deg,\color{violet}{84.64$\pm$1.14 $\bigstar$},85.26$\pm$2.41,38.47$\pm$5.35
grace deg+scom,84.21$\pm$1.28,\color{blue}{85.96$\pm$2.03},30.63$\pm$8.85 X
bgrl random,78.39$\pm$1.14 X,78.4$\pm$1.49,49.05$\pm$14.99
bgrl deg,82.98$\pm$1.31,80.31$\pm$5.48,52.02$\pm$13.75 $\bigstar$
bgrl pr,82.93$\pm$1.33,76.33$\pm$1.62 X,48.54$\pm$14.03
bgrl evc,82.7$\pm$1.52,78.09$\pm$1.04,\color{red}{55.9$\pm$3.58 $\bigstar$}
bgrl scom,78.64$\pm$1.06 X,79.05$\pm$1.41,\color{violet}{52.46$\pm$5.08}
bgrl random+scom,78.11$\pm$1.57 X,78.27$\pm$0.58,49.34$\pm$11.9
bgrl random+deg,82.38$\pm$1.59,80.34$\pm$4.75,51.59$\pm$10.71
bgrl deg+scom,82.53$\pm$1.31,80.43$\pm$3.8,\color{blue}{54.62$\pm$4.1 $\bigstar$}
csgcl random,81.51$\pm$1.98,83.73$\pm$1.14,34.56$\pm$4.45 X
csgcl deg,84.62$\pm$1.54 $\bigstar$,\color{red}{86.48$\pm$2.1 $\bigstar$},38.17$\pm$4.58
csgcl pr,\color{blue}{84.75$\pm$1.26 $\bigstar$},84.27$\pm$1.1,37.85$\pm$3.32
csgcl evc,84.41$\pm$0.75,83.46$\pm$1.15,34.85$\pm$5.83 X
csgcl scom,81.42$\pm$2.33,84.59$\pm$0.82,34.14$\pm$8.36
csgcl random+scom,81.53$\pm$1.63,83.58$\pm$1.24,30.95$\pm$12.95 X
csgcl random+deg,\color{red}{84.78$\pm$1.54 $\bigstar$},85.7$\pm$2.86,36.93$\pm$5.87
csgcl deg+scom,83.75$\pm$1.69,85.4$\pm$2.66,34.44$\pm$6.57

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{llll}
\toprule
 & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_photo_res.csv \\
\midrule
baseline & 71.55$\pm$1.75 X & 73.69$\pm$1.6 & 16.41$\pm$16.66 X \\
grace random & 75.85$\pm$1.75 & 77.99$\pm$1.21 & 22.54$\pm$7.0 \\
grace deg & 73.9$\pm$2.04 & 79.16$\pm$2.24 & 21.3$\pm$8.02 \\
grace pr & 73.73$\pm$1.97 & 78.67$\pm$1.27 & 23.74$\pm$5.38 \\
grace evc & 73.55$\pm$2.85 & 78.31$\pm$1.82 & 18.94$\pm$8.59 \\
grace scom & 76.3$\pm$2.02 & 78.6$\pm$1.31 & 25.96$\pm$4.65 \\
grace random+scom & 75.37$\pm$1.78 & 78.44$\pm$1.54 & 21.08$\pm$9.43 \\
grace random+deg & 77.02$\pm$1.56 & \color{blue}{79.65$\pm$2.56} & 24.58$\pm$5.23 \\
grace deg+scom & 76.62$\pm$1.79 & 79.15$\pm$2.62 & 15.63$\pm$9.45 X \\
bgrl random & 73.58$\pm$1.44 & 74.08$\pm$1.06 & 35.99$\pm$11.71 \\
bgrl deg & \color{violet}{77.49$\pm$1.21} & 76.19$\pm$5.97 & \color{violet}{39.23$\pm$10.85 $\bigstar$} \\
bgrl pr & 77.46$\pm$1.43 & 71.93$\pm$1.4 X & 35.51$\pm$10.72 \\
bgrl evc & 77.0$\pm$1.73 & 73.31$\pm$1.27 & \color{blue}{41.13$\pm$3.45 $\bigstar$} \\
bgrl scom & 73.79$\pm$1.91 & 74.79$\pm$1.18 & 38.38$\pm$4.96 \\
bgrl random+scom & 73.31$\pm$1.8 & 74.53$\pm$0.64 & 36.14$\pm$9.57 \\
bgrl random+deg & \color{blue}{77.88$\pm$1.69 $\bigstar$} & 76.51$\pm$5.06 & 38.49$\pm$8.2 \\
bgrl deg+scom & 77.49$\pm$1.84 & 76.74$\pm$3.92 & \color{red}{41.42$\pm$2.87 $\bigstar$} \\
csgcl random & 75.86$\pm$2.17 & 78.14$\pm$1.51 & 20.85$\pm$4.43 \\
csgcl deg & 76.68$\pm$1.78 & \color{red}{80.3$\pm$2.33 $\bigstar$} & 23.56$\pm$4.03 \\
csgcl pr & 77.33$\pm$1.32 & 77.7$\pm$1.67 & 23.06$\pm$4.14 \\
csgcl evc & 75.61$\pm$1.32 & 77.95$\pm$1.62 & 20.02$\pm$5.57 X \\
csgcl scom & 75.8$\pm$2.6 & 78.43$\pm$1.35 & 20.42$\pm$7.54 \\
csgcl random+scom & 75.91$\pm$1.66 & 77.98$\pm$1.7 & 18.05$\pm$11.29 \\
csgcl random+deg & \color{red}{78.21$\pm$2.16 $\bigstar$} & \color{violet}{79.62$\pm$2.5} & 21.42$\pm$6.49 \\
csgcl deg+scom & 76.77$\pm$1.72 & 79.2$\pm$2.91 & 17.94$\pm$9.75 X \\
\bottomrule
\end{tabular}

}

,FINAL_cora_res.csv,FINAL_citeseer_res.csv,FINAL_photo_res.csv
baseline,71.55$\pm$1.75 X,73.69$\pm$1.6,16.41$\pm$16.66 X
grace random,75.85$\pm$1.75,77.99$\pm$1.21,22.54$\pm$7.0
grace deg,73.9$\pm$2.04,79.16$\pm$2.24,21.3$\pm$8.02
grace pr,73.73$\pm$1.97,78.67$\pm$1.27,23.74$\pm$5.38
grace evc,73.55$\pm$2.85,78.31$\pm$1.82,18.94$\pm$8.59
grace scom,76.3$\pm$2.02,78.6$\pm$1.31,25.96$\pm$4.65
grace random+scom,75.37$\pm$1.78,78.44$\pm$1.54,21.08$\pm$9.43
grace random+deg,77.02$\pm$1.56,\color{blue}{79.65$\pm$2.56},24.58$\pm$5.23
grace deg+scom,76.62$\pm$1.79,79.15$\pm$2.62,15.63$\pm$9.45 X
bgrl random,73.58$\pm$1.44,74.08$\pm$1.06,35.99$\pm$11.71
bgrl deg,\color{violet}{77.49$\pm$1.21},76.19$\pm$5.97,\color{violet}{39.23$\pm$10.85 $\bigstar$}
bgrl pr,77.46$\pm$1.43,71.93$\pm$1.4 X,35.51$\pm$10.72
bgrl evc,77.0$\pm$1.73,73.31$\pm$1.27,\color{blue}{41.13$\pm$3.45 $\bigstar$}
bgrl scom,73.79$\pm$1.91,74.79$\pm$1.18,38.38$\pm$4.96
bgrl random+scom,73.31$\pm$1.8,74.53$\pm$0.64,36.14$\pm$9.57
bgrl random+deg,\color{blue}{77.88$\pm$1.69 $\bigstar$},76.51$\pm$5.06,38.49$\pm$8.2
bgrl deg+scom,77.49$\pm$1.84,76.74$\pm$3.92,\color{red}{41.42$\pm$2.87 $\bigstar$}
csgcl random,75.86$\pm$2.17,78.14$\pm$1.51,20.85$\pm$4.43
csgcl deg,76.68$\pm$1.78,\color{red}{80.3$\pm$2.33 $\bigstar$},23.56$\pm$4.03
csgcl pr,77.33$\pm$1.32,77.7$\pm$1.67,23.06$\pm$4.14
csgcl evc,75.61$\pm$1.32,77.95$\pm$1.62,20.02$\pm$5.57 X
csgcl scom,75.8$\pm$2.6,78.43$\pm$1.35,20.42$\pm$7.54
csgcl random+scom,75.91$\pm$1.66,77.98$\pm$1.7,18.05$\pm$11.29
csgcl random+deg,\color{red}{78.21$\pm$2.16 $\bigstar$},\color{violet}{79.62$\pm$2.5},21.42$\pm$6.49
csgcl deg+scom,76.77$\pm$1.72,79.2$\pm$2.91,17.94$\pm$9.75 X

                             Hits@20
\resizebox{\textwidth}{!}{
\begin{tabular}{llll}
\toprule
 & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_photo_res.csv \\
\midrule
baseline & 61.48$\pm$2.88 & 64.11$\pm$2.78 X & 10.12$\pm$10.85 \\
grace random & 66.7$\pm$2.83 & 70.76$\pm$1.82 & 9.82$\pm$6.0 \\
grace deg & 54.14$\pm$5.76 X & 69.44$\pm$2.37 & 9.94$\pm$6.55 \\
grace pr & 53.7$\pm$4.41 X & 69.86$\pm$1.89 & 9.32$\pm$6.93 \\
grace evc & 53.33$\pm$4.7 X & 70.24$\pm$2.51 & 7.07$\pm$6.17 \\
grace scom & 66.33$\pm$3.98 & 70.98$\pm$1.8 $\bigstar$ & 12.37$\pm$3.72 \\
grace random+scom & 66.39$\pm$2.51 & 70.74$\pm$2.07 & 9.13$\pm$5.56 \\
grace random+deg & 59.93$\pm$4.64 & 71.01$\pm$2.06 $\bigstar$ & 12.09$\pm$4.1 \\
grace deg+scom & 59.45$\pm$5.58 & 69.95$\pm$2.44 & 5.06$\pm$5.51 X \\
bgrl random & 65.92$\pm$2.07 & 69.34$\pm$1.69 & 20.96$\pm$7.72 \\
bgrl deg & 68.39$\pm$2.1 & \color{violet}{71.55$\pm$5.48} & 22.85$\pm$7.08 $\bigstar$ \\
bgrl pr & \color{violet}{68.64$\pm$1.61} & 68.13$\pm$1.62 & 21.7$\pm$7.32 \\
bgrl evc & 68.58$\pm$2.88 & 68.26$\pm$1.34 & \color{blue}{24.78$\pm$3.47 $\bigstar$} \\
bgrl scom & 66.73$\pm$2.01 & 68.86$\pm$2.19 & \color{violet}{22.98$\pm$5.21 $\bigstar$} \\
bgrl random+scom & 65.3$\pm$3.37 & 69.42$\pm$1.32 & 21.0$\pm$6.17 \\
bgrl random+deg & \color{red}{69.69$\pm$2.47 $\bigstar$} & \color{red}{71.84$\pm$5.03} & 22.66$\pm$4.68 \\
bgrl deg+scom & \color{blue}{68.71$\pm$2.76} & 71.29$\pm$3.68 & \color{red}{25.07$\pm$2.53 $\bigstar$} \\
csgcl random & 67.57$\pm$2.37 & 70.25$\pm$2.46 & 8.34$\pm$3.25 \\
csgcl deg & 59.18$\pm$4.75 & 71.09$\pm$2.62 & 10.29$\pm$3.93 \\
csgcl pr & 57.65$\pm$2.99 & 71.3$\pm$1.83 $\bigstar$ & 8.62$\pm$3.75 \\
csgcl evc & 56.18$\pm$4.74 X & 69.47$\pm$1.6 & 7.66$\pm$4.69 \\
csgcl scom & 66.77$\pm$2.86 & 70.03$\pm$2.17 & 9.66$\pm$4.87 \\
csgcl random+scom & 66.75$\pm$1.79 & 70.3$\pm$2.37 & 6.97$\pm$5.81 \\
csgcl random+deg & 64.03$\pm$3.25 & \color{blue}{71.71$\pm$2.66 $\bigstar$} & 6.91$\pm$4.99 X \\
csgcl deg+scom & 63.26$\pm$2.97 & 71.19$\pm$2.3 & 6.91$\pm$6.16 X \\
\bottomrule
\end{tabular}

}

,FINAL_cora_res.csv,FINAL_citeseer_res.csv,FINAL_photo_res.csv
baseline,61.48$\pm$2.88,64.11$\pm$2.78 X,10.12$\pm$10.85
grace random,66.7$\pm$2.83,70.76$\pm$1.82,9.82$\pm$6.0
grace deg,54.14$\pm$5.76 X,69.44$\pm$2.37,9.94$\pm$6.55
grace pr,53.7$\pm$4.41 X,69.86$\pm$1.89,9.32$\pm$6.93
grace evc,53.33$\pm$4.7 X,70.24$\pm$2.51,7.07$\pm$6.17
grace scom,66.33$\pm$3.98,70.98$\pm$1.8 $\bigstar$,12.37$\pm$3.72
grace random+scom,66.39$\pm$2.51,70.74$\pm$2.07,9.13$\pm$5.56
grace random+deg,59.93$\pm$4.64,71.01$\pm$2.06 $\bigstar$,12.09$\pm$4.1
grace deg+scom,59.45$\pm$5.58,69.95$\pm$2.44,5.06$\pm$5.51 X
bgrl random,65.92$\pm$2.07,69.34$\pm$1.69,20.96$\pm$7.72
bgrl deg,68.39$\pm$2.1,\color{violet}{71.55$\pm$5.48},22.85$\pm$7.08 $\bigstar$
bgrl pr,\color{violet}{68.64$\pm$1.61},68.13$\pm$1.62,21.7$\pm$7.32
bgrl evc,68.58$\pm$2.88,68.26$\pm$1.34,\color{blue}{24.78$\pm$3.47 $\bigstar$}
bgrl scom,66.73$\pm$2.01,68.86$\pm$2.19,\color{violet}{22.98$\pm$5.21 $\bigstar$}
bgrl random+scom,65.3$\pm$3.37,69.42$\pm$1.32,21.0$\pm$6.17
bgrl random+deg,\color{red}{69.69$\pm$2.47 $\bigstar$},\color{red}{71.84$\pm$5.03},22.66$\pm$4.68
bgrl deg+scom,\color{blue}{68.71$\pm$2.76},71.29$\pm$3.68,\color{red}{25.07$\pm$2.53 $\bigstar$}
csgcl random,67.57$\pm$2.37,70.25$\pm$2.46,8.34$\pm$3.25
csgcl deg,59.18$\pm$4.75,71.09$\pm$2.62,10.29$\pm$3.93
csgcl pr,57.65$\pm$2.99,71.3$\pm$1.83 $\bigstar$,8.62$\pm$3.75
csgcl evc,56.18$\pm$4.74 X,69.47$\pm$1.6,7.66$\pm$4.69
csgcl scom,66.77$\pm$2.86,70.03$\pm$2.17,9.66$\pm$4.87
csgcl random+scom,66.75$\pm$1.79,70.3$\pm$2.37,6.97$\pm$5.81
csgcl random+deg,64.03$\pm$3.25,\color{blue}{71.71$\pm$2.66 $\bigstar$},6.91$\pm$4.99 X
csgcl deg+scom,63.26$\pm$2.97,71.19$\pm$2.3,6.91$\pm$6.16 X

In [9]:
# score
names = ['FINAL_struct_cora_res.csv',
'FINAL_struct_citeseer_res.csv']
print("                             ROCAUC                      ")
all_data, all_res = ut.mix_dataset(names, 'ROCAUC')
display(ut.tex_table(all_data, all_res).T)
print("                             AP                      ")
all_data, all_res = ut.mix_dataset(names, 'AP')
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@100                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@100')
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50')
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@20                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@20')
display(ut.tex_table(all_data, all_res).T)

                             ROCAUC
\resizebox{\textwidth}{!}{
\begin{tabular}{lll}
\toprule
 & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv \\
\midrule
baseline & \color{violet}{82.59$\pm$0.72} & \color{violet}{78.28$\pm$1.18 $\bigstar$} \\
grace random & 78.14$\pm$0.73 & 74.3$\pm$1.75 \\
grace deg & \color{red}{83.5$\pm$1.03 $\bigstar$} & \color{red}{78.6$\pm$2.08 $\bigstar$} \\
grace pr & 78.34$\pm$1.28 & 71.8$\pm$2.17 \\
grace evc & 77.62$\pm$0.93 & 73.87$\pm$1.81 \\
grace scom & 80.97$\pm$1.31 & 76.7$\pm$1.83 \\
grace random+scom & 78.57$\pm$0.93 & 73.96$\pm$1.76 \\
grace random+deg & 81.72$\pm$1.39 & 76.59$\pm$1.65 \\
grace deg+scom & 80.93$\pm$1.21 & 77.06$\pm$1.43 \\
bgrl random & 76.49$\pm$1.13 & 70.36$\pm$1.36 \\
bgrl deg & 80.3$\pm$0.8 & 77.59$\pm$3.15 \\
bgrl pr & 73.97$\pm$0.82 X & 67.46$\pm$2.1 X \\
bgrl evc & 73.96$\pm$0.46 X & 70.49$\pm$1.78 \\
bgrl scom & 77.74$\pm$0.8 & 72.4$\pm$1.31 \\
bgrl random+scom & 76.23$\pm$0.99 & 69.96$\pm$1.57 \\
bgrl random+deg & 79.47$\pm$0.95 & 71.26$\pm$1.25 \\
bgrl deg+scom & 79.14$\pm$0.99 & 69.64$\pm$1.56 X \\
csgcl random & 77.98$\pm$1.23 & 74.25$\pm$1.72 \\
csgcl deg & \color{blue}{83.47$\pm$1.26 $\bigstar$} & \color{blue}{78.51$\pm$2.07 $\bigstar$} \\
csgcl pr & 77.56$\pm$1.18 & 71.79$\pm$2.25 \\
csgcl evc & 77.36$\pm$0.91 & 73.45$\pm$1.8 \\
csgcl scom & 80.5$\pm$1.02 & 76.41$\pm$1.25 \\
csgcl random+scom & 77.8$\pm$0.98 & 74.36$\pm$1.64 \\
csgcl random+deg & 81.37$\pm$1.44 & 76.96$\pm$1.24 \\
csgcl deg+scom & 81.48$\pm$1.47 & 76.86$\pm$1.41 \\
\bottomrule
\end{tabular}

}

,FINAL_struct_cora_res.csv,FINAL_struct_citeseer_res.csv
baseline,\color{violet}{82.59$\pm$0.72},\color{violet}{78.28$\pm$1.18 $\bigstar$}
grace random,78.14$\pm$0.73,74.3$\pm$1.75
grace deg,\color{red}{83.5$\pm$1.03 $\bigstar$},\color{red}{78.6$\pm$2.08 $\bigstar$}
grace pr,78.34$\pm$1.28,71.8$\pm$2.17
grace evc,77.62$\pm$0.93,73.87$\pm$1.81
grace scom,80.97$\pm$1.31,76.7$\pm$1.83
grace random+scom,78.57$\pm$0.93,73.96$\pm$1.76
grace random+deg,81.72$\pm$1.39,76.59$\pm$1.65
grace deg+scom,80.93$\pm$1.21,77.06$\pm$1.43
bgrl random,76.49$\pm$1.13,70.36$\pm$1.36
bgrl deg,80.3$\pm$0.8,77.59$\pm$3.15
bgrl pr,73.97$\pm$0.82 X,67.46$\pm$2.1 X
bgrl evc,73.96$\pm$0.46 X,70.49$\pm$1.78
bgrl scom,77.74$\pm$0.8,72.4$\pm$1.31
bgrl random+scom,76.23$\pm$0.99,69.96$\pm$1.57
bgrl random+deg,79.47$\pm$0.95,71.26$\pm$1.25
bgrl deg+scom,79.14$\pm$0.99,69.64$\pm$1.56 X
csgcl random,77.98$\pm$1.23,74.25$\pm$1.72
csgcl deg,\color{blue}{83.47$\pm$1.26 $\bigstar$},\color{blue}{78.51$\pm$2.07 $\bigstar$}
csgcl pr,77.56$\pm$1.18,71.79$\pm$2.25
csgcl evc,77.36$\pm$0.91,73.45$\pm$1.8
csgcl scom,80.5$\pm$1.02,76.41$\pm$1.25
csgcl random+scom,77.8$\pm$0.98,74.36$\pm$1.64
csgcl random+deg,81.37$\pm$1.44,76.96$\pm$1.24
csgcl deg+scom,81.48$\pm$1.47,76.86$\pm$1.41

                             AP
\resizebox{\textwidth}{!}{
\begin{tabular}{lll}
\toprule
 & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv \\
\midrule
baseline & 85.89$\pm$0.57 & \color{violet}{83.25$\pm$1.07 $\bigstar$} \\
grace random & 84.92$\pm$0.61 & 81.59$\pm$1.26 \\
grace deg & \color{blue}{87.67$\pm$0.69 $\bigstar$} & \color{blue}{83.26$\pm$1.23 $\bigstar$} \\
grace pr & 84.91$\pm$0.89 & 80.46$\pm$1.4 \\
grace evc & 84.59$\pm$0.69 & 81.22$\pm$1.32 \\
grace scom & 86.17$\pm$0.95 & 82.81$\pm$1.19 \\
grace random+scom & 85.25$\pm$0.71 & 81.33$\pm$1.13 \\
grace random+deg & \color{violet}{87.06$\pm$0.87} & 82.09$\pm$0.92 \\
grace deg+scom & 86.61$\pm$0.82 & 82.03$\pm$0.95 \\
bgrl random & 82.67$\pm$0.71 & 79.22$\pm$0.93 \\
bgrl deg & 86.24$\pm$0.55 & \color{red}{83.54$\pm$1.87 $\bigstar$} \\
bgrl pr & 81.35$\pm$0.59 X & 77.88$\pm$1.27 X \\
bgrl evc & 81.38$\pm$0.56 X & 79.33$\pm$1.09 \\
bgrl scom & 83.34$\pm$0.67 & 80.0$\pm$0.89 \\
bgrl random+scom & 82.55$\pm$0.7 & 79.06$\pm$1.04 \\
bgrl random+deg & 85.87$\pm$0.53 & 80.12$\pm$0.93 \\
bgrl deg+scom & 85.64$\pm$0.67 & 79.12$\pm$0.96 \\
csgcl random & 84.72$\pm$0.8 & 81.58$\pm$1.28 \\
csgcl deg & \color{red}{87.71$\pm$0.88 $\bigstar$} & 83.19$\pm$1.21 $\bigstar$ \\
csgcl pr & 84.42$\pm$0.9 & 80.44$\pm$1.45 \\
csgcl evc & 84.41$\pm$0.74 & 81.01$\pm$1.32 \\
csgcl scom & 85.87$\pm$0.77 & 82.52$\pm$1.0 \\
csgcl random+scom & 84.7$\pm$0.73 & 81.45$\pm$1.18 \\
csgcl random+deg & 86.91$\pm$0.85 & 82.58$\pm$0.94 \\
csgcl deg+scom & 86.92$\pm$0.92 & 82.31$\pm$1.07 \\
\bottomrule
\end{tabular}

}

,FINAL_struct_cora_res.csv,FINAL_struct_citeseer_res.csv
baseline,85.89$\pm$0.57,\color{violet}{83.25$\pm$1.07 $\bigstar$}
grace random,84.92$\pm$0.61,81.59$\pm$1.26
grace deg,\color{blue}{87.67$\pm$0.69 $\bigstar$},\color{blue}{83.26$\pm$1.23 $\bigstar$}
grace pr,84.91$\pm$0.89,80.46$\pm$1.4
grace evc,84.59$\pm$0.69,81.22$\pm$1.32
grace scom,86.17$\pm$0.95,82.81$\pm$1.19
grace random+scom,85.25$\pm$0.71,81.33$\pm$1.13
grace random+deg,\color{violet}{87.06$\pm$0.87},82.09$\pm$0.92
grace deg+scom,86.61$\pm$0.82,82.03$\pm$0.95
bgrl random,82.67$\pm$0.71,79.22$\pm$0.93
bgrl deg,86.24$\pm$0.55,\color{red}{83.54$\pm$1.87 $\bigstar$}
bgrl pr,81.35$\pm$0.59 X,77.88$\pm$1.27 X
bgrl evc,81.38$\pm$0.56 X,79.33$\pm$1.09
bgrl scom,83.34$\pm$0.67,80.0$\pm$0.89
bgrl random+scom,82.55$\pm$0.7,79.06$\pm$1.04
bgrl random+deg,85.87$\pm$0.53,80.12$\pm$0.93
bgrl deg+scom,85.64$\pm$0.67,79.12$\pm$0.96
csgcl random,84.72$\pm$0.8,81.58$\pm$1.28
csgcl deg,\color{red}{87.71$\pm$0.88 $\bigstar$},83.19$\pm$1.21 $\bigstar$
csgcl pr,84.42$\pm$0.9,80.44$\pm$1.45
csgcl evc,84.41$\pm$0.74,81.01$\pm$1.32
csgcl scom,85.87$\pm$0.77,82.52$\pm$1.0
csgcl random+scom,84.7$\pm$0.73,81.45$\pm$1.18
csgcl random+deg,86.91$\pm$0.85,82.58$\pm$0.94
csgcl deg+scom,86.92$\pm$0.92,82.31$\pm$1.07

                             Hits@100
\resizebox{\textwidth}{!}{
\begin{tabular}{lll}
\toprule
 & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv \\
\midrule
baseline & 63.54$\pm$1.6 & 56.46$\pm$2.51 \\
grace random & 64.0$\pm$1.45 & 56.03$\pm$2.15 \\
grace deg & 67.75$\pm$1.38 $\bigstar$ & 57.79$\pm$3.13 \\
grace pr & 64.4$\pm$1.29 & 56.1$\pm$2.05 \\
grace evc & 64.14$\pm$1.5 & 55.62$\pm$1.62 \\
grace scom & 64.73$\pm$1.52 & 57.0$\pm$1.76 \\
grace random+scom & 65.02$\pm$1.7 & 55.64$\pm$1.86 \\
grace random+deg & \color{red}{68.42$\pm$2.06 $\bigstar$} & 59.03$\pm$2.54 \\
grace deg+scom & \color{violet}{67.83$\pm$1.82 $\bigstar$} & \color{red}{59.82$\pm$2.46 $\bigstar$} \\
bgrl random & 56.63$\pm$1.18 X & 52.69$\pm$1.77 X \\
bgrl deg & 65.8$\pm$1.21 & 57.76$\pm$2.57 \\
bgrl pr & 55.54$\pm$1.32 X & 52.19$\pm$1.75 X \\
bgrl evc & 55.36$\pm$1.18 X & 53.31$\pm$1.76 \\
bgrl scom & 57.3$\pm$1.66 & 52.84$\pm$1.4 X \\
bgrl random+scom & 56.42$\pm$1.64 X & 52.91$\pm$1.68 X \\
bgrl random+deg & 65.61$\pm$1.13 & 54.88$\pm$1.73 \\
bgrl deg+scom & 64.87$\pm$1.43 & 53.55$\pm$1.77 \\
csgcl random & 63.5$\pm$1.29 & 56.22$\pm$2.35 \\
csgcl deg & \color{blue}{68.01$\pm$2.1 $\bigstar$} & 57.7$\pm$2.82 \\
csgcl pr & 62.85$\pm$1.5 & 55.75$\pm$2.0 \\
csgcl evc & 63.32$\pm$1.61 & 55.54$\pm$1.89 \\
csgcl scom & 64.32$\pm$1.62 & 56.56$\pm$2.16 \\
csgcl random+scom & 63.87$\pm$1.71 & 55.56$\pm$1.68 \\
csgcl random+deg & 67.76$\pm$2.1 $\bigstar$ & \color{violet}{59.14$\pm$1.8} \\
csgcl deg+scom & 67.43$\pm$1.82 & \color{blue}{59.54$\pm$2.03 $\bigstar$} \\
\bottomrule
\end{tabular}

}

,FINAL_struct_cora_res.csv,FINAL_struct_citeseer_res.csv
baseline,63.54$\pm$1.6,56.46$\pm$2.51
grace random,64.0$\pm$1.45,56.03$\pm$2.15
grace deg,67.75$\pm$1.38 $\bigstar$,57.79$\pm$3.13
grace pr,64.4$\pm$1.29,56.1$\pm$2.05
grace evc,64.14$\pm$1.5,55.62$\pm$1.62
grace scom,64.73$\pm$1.52,57.0$\pm$1.76
grace random+scom,65.02$\pm$1.7,55.64$\pm$1.86
grace random+deg,\color{red}{68.42$\pm$2.06 $\bigstar$},59.03$\pm$2.54
grace deg+scom,\color{violet}{67.83$\pm$1.82 $\bigstar$},\color{red}{59.82$\pm$2.46 $\bigstar$}
bgrl random,56.63$\pm$1.18 X,52.69$\pm$1.77 X
bgrl deg,65.8$\pm$1.21,57.76$\pm$2.57
bgrl pr,55.54$\pm$1.32 X,52.19$\pm$1.75 X
bgrl evc,55.36$\pm$1.18 X,53.31$\pm$1.76
bgrl scom,57.3$\pm$1.66,52.84$\pm$1.4 X
bgrl random+scom,56.42$\pm$1.64 X,52.91$\pm$1.68 X
bgrl random+deg,65.61$\pm$1.13,54.88$\pm$1.73
bgrl deg+scom,64.87$\pm$1.43,53.55$\pm$1.77
csgcl random,63.5$\pm$1.29,56.22$\pm$2.35
csgcl deg,\color{blue}{68.01$\pm$2.1 $\bigstar$},57.7$\pm$2.82
csgcl pr,62.85$\pm$1.5,55.75$\pm$2.0
csgcl evc,63.32$\pm$1.61,55.54$\pm$1.89
csgcl scom,64.32$\pm$1.62,56.56$\pm$2.16
csgcl random+scom,63.87$\pm$1.71,55.56$\pm$1.68
csgcl random+deg,67.76$\pm$2.1 $\bigstar$,\color{violet}{59.14$\pm$1.8}
csgcl deg+scom,67.43$\pm$1.82,\color{blue}{59.54$\pm$2.03 $\bigstar$}

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{lll}
\toprule
 & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv \\
\midrule
baseline & 56.27$\pm$2.29 & 53.07$\pm$2.68 \\
grace random & 60.67$\pm$1.42 & 53.31$\pm$2.03 \\
grace deg & 62.02$\pm$1.7 & 52.53$\pm$2.22 \\
grace pr & 60.52$\pm$1.31 & 53.04$\pm$1.87 \\
grace evc & 59.93$\pm$0.93 & 52.75$\pm$1.78 \\
grace scom & 60.77$\pm$1.77 & 53.95$\pm$1.92 \\
grace random+scom & 61.76$\pm$1.5 & 52.79$\pm$1.71 \\
grace random+deg & 62.13$\pm$1.97 & 54.0$\pm$2.52 \\
grace deg+scom & \color{blue}{62.29$\pm$1.62 $\bigstar$} & \color{red}{54.75$\pm$2.17 $\bigstar$} \\
bgrl random & 50.93$\pm$1.72 X & 49.63$\pm$1.87 X \\
bgrl deg & 62.03$\pm$1.35 & 52.49$\pm$1.95 \\
bgrl pr & 50.03$\pm$1.36 X & 49.29$\pm$1.51 X \\
bgrl evc & 50.55$\pm$1.41 X & 50.13$\pm$1.61 \\
bgrl scom & 51.88$\pm$1.51 & 49.34$\pm$1.86 X \\
bgrl random+scom & 51.48$\pm$1.8 X & 49.91$\pm$1.78 X \\
bgrl random+deg & 61.72$\pm$1.32 & 52.09$\pm$1.63 \\
bgrl deg+scom & 60.79$\pm$1.06 & 51.14$\pm$1.57 \\
csgcl random & 60.12$\pm$1.03 & 53.41$\pm$2.27 \\
csgcl deg & 61.5$\pm$2.17 & 52.43$\pm$2.06 \\
csgcl pr & 59.4$\pm$1.5 & 52.86$\pm$1.7 \\
csgcl evc & 59.18$\pm$1.51 & 52.56$\pm$1.91 \\
csgcl scom & 60.26$\pm$1.53 & 53.12$\pm$1.72 \\
csgcl random+scom & 60.77$\pm$1.58 & 52.71$\pm$1.8 \\
csgcl random+deg & \color{red}{62.48$\pm$1.83 $\bigstar$} & \color{violet}{54.19$\pm$1.97} \\
csgcl deg+scom & \color{violet}{62.29$\pm$1.55 $\bigstar$} & \color{blue}{54.69$\pm$1.94 $\bigstar$} \\
\bottomrule
\end{tabular}

}

,FINAL_struct_cora_res.csv,FINAL_struct_citeseer_res.csv
baseline,56.27$\pm$2.29,53.07$\pm$2.68
grace random,60.67$\pm$1.42,53.31$\pm$2.03
grace deg,62.02$\pm$1.7,52.53$\pm$2.22
grace pr,60.52$\pm$1.31,53.04$\pm$1.87
grace evc,59.93$\pm$0.93,52.75$\pm$1.78
grace scom,60.77$\pm$1.77,53.95$\pm$1.92
grace random+scom,61.76$\pm$1.5,52.79$\pm$1.71
grace random+deg,62.13$\pm$1.97,54.0$\pm$2.52
grace deg+scom,\color{blue}{62.29$\pm$1.62 $\bigstar$},\color{red}{54.75$\pm$2.17 $\bigstar$}
bgrl random,50.93$\pm$1.72 X,49.63$\pm$1.87 X
bgrl deg,62.03$\pm$1.35,52.49$\pm$1.95
bgrl pr,50.03$\pm$1.36 X,49.29$\pm$1.51 X
bgrl evc,50.55$\pm$1.41 X,50.13$\pm$1.61
bgrl scom,51.88$\pm$1.51,49.34$\pm$1.86 X
bgrl random+scom,51.48$\pm$1.8 X,49.91$\pm$1.78 X
bgrl random+deg,61.72$\pm$1.32,52.09$\pm$1.63
bgrl deg+scom,60.79$\pm$1.06,51.14$\pm$1.57
csgcl random,60.12$\pm$1.03,53.41$\pm$2.27
csgcl deg,61.5$\pm$2.17,52.43$\pm$2.06
csgcl pr,59.4$\pm$1.5,52.86$\pm$1.7
csgcl evc,59.18$\pm$1.51,52.56$\pm$1.91
csgcl scom,60.26$\pm$1.53,53.12$\pm$1.72
csgcl random+scom,60.77$\pm$1.58,52.71$\pm$1.8
csgcl random+deg,\color{red}{62.48$\pm$1.83 $\bigstar$},\color{violet}{54.19$\pm$1.97}
csgcl deg+scom,\color{violet}{62.29$\pm$1.55 $\bigstar$},\color{blue}{54.69$\pm$1.94 $\bigstar$}

                             Hits@20
\resizebox{\textwidth}{!}{
\begin{tabular}{lll}
\toprule
 & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv \\
\midrule
baseline & 44.52$\pm$2.66 X & 48.87$\pm$2.77 \\
grace random & 55.2$\pm$2.0 & \color{blue}{50.54$\pm$2.4} \\
grace deg & 52.64$\pm$2.9 & 48.85$\pm$2.64 \\
grace pr & 54.18$\pm$2.78 & 50.25$\pm$1.92 \\
grace evc & 53.32$\pm$1.9 & 49.79$\pm$2.11 \\
grace scom & 55.17$\pm$1.82 & \color{red}{51.14$\pm$2.17 $\bigstar$} \\
grace random+scom & 55.18$\pm$2.48 & 50.25$\pm$2.09 \\
grace random+deg & 54.75$\pm$3.01 & 49.01$\pm$2.62 \\
grace deg+scom & 54.36$\pm$2.81 & 49.64$\pm$2.3 \\
bgrl random & 45.83$\pm$2.07 X & 46.87$\pm$1.74 \\
bgrl deg & 55.36$\pm$2.2 & 49.74$\pm$1.96 \\
bgrl pr & 44.72$\pm$1.53 X & 46.09$\pm$1.57 X \\
bgrl evc & 45.19$\pm$1.95 X & 46.7$\pm$1.62 \\
bgrl scom & 45.85$\pm$1.8 X & 46.2$\pm$2.05 X \\
bgrl random+scom & 45.42$\pm$1.79 X & 46.81$\pm$1.95 \\
bgrl random+deg & \color{red}{56.82$\pm$1.75 $\bigstar$} & 49.66$\pm$1.8 \\
bgrl deg+scom & \color{violet}{55.37$\pm$1.48} & 48.69$\pm$1.75 \\
csgcl random & 54.67$\pm$1.57 & \color{violet}{50.35$\pm$2.24} \\
csgcl deg & 53.45$\pm$2.92 & 48.34$\pm$2.17 \\
csgcl pr & 53.49$\pm$2.04 & 49.82$\pm$1.7 \\
csgcl evc & 53.91$\pm$2.06 & 50.19$\pm$2.06 \\
csgcl scom & 54.19$\pm$2.57 & 50.13$\pm$2.02 \\
csgcl random+scom & 55.06$\pm$1.78 & 49.62$\pm$1.81 \\
csgcl random+deg & 54.83$\pm$2.53 & 49.7$\pm$2.59 \\
csgcl deg+scom & \color{blue}{55.38$\pm$2.58} & 49.38$\pm$2.51 \\
\bottomrule
\end{tabular}

}

,FINAL_struct_cora_res.csv,FINAL_struct_citeseer_res.csv
baseline,44.52$\pm$2.66 X,48.87$\pm$2.77
grace random,55.2$\pm$2.0,\color{blue}{50.54$\pm$2.4}
grace deg,52.64$\pm$2.9,48.85$\pm$2.64
grace pr,54.18$\pm$2.78,50.25$\pm$1.92
grace evc,53.32$\pm$1.9,49.79$\pm$2.11
grace scom,55.17$\pm$1.82,\color{red}{51.14$\pm$2.17 $\bigstar$}
grace random+scom,55.18$\pm$2.48,50.25$\pm$2.09
grace random+deg,54.75$\pm$3.01,49.01$\pm$2.62
grace deg+scom,54.36$\pm$2.81,49.64$\pm$2.3
bgrl random,45.83$\pm$2.07 X,46.87$\pm$1.74
bgrl deg,55.36$\pm$2.2,49.74$\pm$1.96
bgrl pr,44.72$\pm$1.53 X,46.09$\pm$1.57 X
bgrl evc,45.19$\pm$1.95 X,46.7$\pm$1.62
bgrl scom,45.85$\pm$1.8 X,46.2$\pm$2.05 X
bgrl random+scom,45.42$\pm$1.79 X,46.81$\pm$1.95
bgrl random+deg,\color{red}{56.82$\pm$1.75 $\bigstar$},49.66$\pm$1.8
bgrl deg+scom,\color{violet}{55.37$\pm$1.48},48.69$\pm$1.75
csgcl random,54.67$\pm$1.57,\color{violet}{50.35$\pm$2.24}
csgcl deg,53.45$\pm$2.92,48.34$\pm$2.17
csgcl pr,53.49$\pm$2.04,49.82$\pm$1.7
csgcl evc,53.91$\pm$2.06,50.19$\pm$2.06
csgcl scom,54.19$\pm$2.57,50.13$\pm$2.02
csgcl random+scom,55.06$\pm$1.78,49.62$\pm$1.81
csgcl random+deg,54.83$\pm$2.53,49.7$\pm$2.59
csgcl deg+scom,\color{blue}{55.38$\pm$2.58},49.38$\pm$2.51