In [2]:
import utils as ut

CSGCL ~ GRACE

In [9]:
names = ['netscience', 'power', 'euroroad', 'yeast', 'crime']
datasets = [
'FINAL_netscience_res.csv',
'FINAL_power_res.csv',
'FINAL_euroroad_res.csv',
'FINAL_yeast_res.csv',
'FINAL_crime_res.csv']
data, res = ut.mix_dataset(datasets, 'Hits@50', ['grace', 'csgcl'], ['\+'])

data.index = names
res.index = names
big_tab = ut.tex_table(data).T
big_tab = big_tab.reindex(['grace random', 'csgcl random', 'grace deg', 'csgcl deg', 'grace pr', 'csgcl pr', 'grace evc', 'csgcl evc', 'grace scom', 'csgcl scom'])
print(big_tab.to_latex(
        index=True, formatters={"name": str.upper}, float_format="{:.1f}".format
    ))

\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & netscience & power & euroroad & yeast & crime \\
\midrule
grace random & \color{violet}{84.34$\pm$1.29} & 36.05$\pm$1.17 & 37.42$\pm$2.96 & 94.28$\pm$0.28 & 18.34$\pm$2.03 \\
grace deg & \color{red}{86.28$\pm$2.0} & \color{violet}{36.46$\pm$1.26} & \color{red}{43.46$\pm$7.72} & 93.66$\pm$0.56 & \color{violet}{21.05$\pm$3.22} \\
grace pr & 84.0$\pm$1.65 & 36.44$\pm$0.93 & 39.65$\pm$4.48 & \color{blue}{94.32$\pm$0.3} & 17.12$\pm$1.93 \\
grace evc & 84.32$\pm$1.58 & \color{blue}{36.57$\pm$1.3} & 42.08$\pm$7.26 & 94.24$\pm$0.3 & \color{blue}{21.63$\pm$5.49} \\
grace scom & 84.32$\pm$1.3 & 36.34$\pm$1.11 & 36.22$\pm$3.33 & \color{red}{94.37$\pm$0.24} & 18.85$\pm$3.06 \\
csgcl random & 84.2$\pm$1.8 & 36.19$\pm$0.87 & 34.73$\pm$2.9 & 94.21$\pm$0.27 & 18.47$\pm$2.91 \\
csgcl deg & \color{blue}{86.11$\pm$2.27} & \color{red}{36.84$\pm$1.63} & \color{blue}{43.36$\pm$7.14} & 93.93$\pm$0.59 & 19.9$\pm$4.79 \\
csgcl pr & 83.94$\pm$1.82 & 35.58$\pm$0.9 & 35.19$\pm$4.83 & \color{violet}{94.31$\pm$0.21} & 18.07$\pm$1.56 \\
csgcl evc & 84.09$\pm$1.56 & 36.13$\pm$1.17 & \color{violet}{42.26$\pm$6.19} & 94.26$\pm$0.31 & \color{red}{23.39$\pm$7.61} \\
csgcl scom & 84.05$\pm$1.53 & 35.93$\pm$0.8 & 34.1$\pm$2.38 & 94.29$\pm$0.32 & 18.61$\pm$3.45 \\
\bottomrule
\end{tabular}

}
\begin{tabular}{llllll}
\toprule
 & netscience & power & euroroad & yeast & crime \\
\midrule
grace random & \color{violet}{84.34$\pm$1.29} & 36.05$\pm$1.17 & 37.42$\pm$2.96 & 94.28$\pm$0.28 & 18.34$\pm$2.03 \\
csgcl random & 84.2$\pm$1.8 & 36.19$\pm$0.87 & 34.73$\pm$2.9 & 94.21$\pm$0.27 & 18.47$\pm$2.91 \\
grace deg & \color{red}{86.28$\pm$2.0} & \color{violet}{36.46$\pm$1.26} & \color{red}{43.46$\pm$7.72} & 93.66$\pm$0.56 & \color{violet}{21.05$\pm$3.22} \\
csgcl deg & \color{blue}{86.11$\pm$2.27} & \color{red}{36.84$\pm$1.63} & \color{blue}{43.36$\pm$7.14} & 93.93$\pm$0.59 & 19.9$\pm$4.79 \\
grace pr & 84.0$\pm$1.65 & 36.44$\pm$0.93 & 39.65$\pm$4.48 & \color{blue}{94.32$\pm$0.3} & 17.12$\pm$1.93 \\
csgcl pr & 83.94$\pm$1.82 & 35.58$\pm$0.9 & 35.19$\pm$4.83 & \color{violet}{94.31$\pm$0.21} & 18.07$\pm$1.56 \\
grace evc & 84.32$\pm$1.58 & \color{blue}{36.57$\pm$1.3} & 42.08$\pm$7.26 & 94.24$\pm$0.3 & \color{blue}{21.63$\pm$5.49} \\
csgcl evc & 84.09$\pm$1.56 & 36.13$\pm$1.17 & \color{violet}{42.26$\pm$6.19} & 94.26$\pm$0.31 & \color{red}{23.39$\pm$7.61} \\
grace scom & 84.32$\pm$1.3 & 36.34$\pm$1.11 & 36.22$\pm$3.33 & \color{red}{94.37$\pm$0.24} & 18.85$\pm$3.06 \\
csgcl scom & 84.05$\pm$1.53 & 35.93$\pm$0.8 & 34.1$\pm$2.38 & 94.29$\pm$0.32 & 18.61$\pm$3.45 \\
\bottomrule
\end{tabular}

bgrl avec augmentation cool

In [17]:
names = ['netscience', 'power', 'euroroad', 'yeast', 'crime']
datasets = [
'FINAL_netscience_res.csv',
'FINAL_power_res.csv',
'FINAL_euroroad_res.csv',
'FINAL_yeast_res.csv',
'FINAL_crime_res.csv']
data, res = ut.mix_dataset(datasets, 'Hits@50', ['bgrl'], ['\+'])

data.index = names
res.index = names
big_tab = ut.tex_table(data).T

\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & netscience & power & euroroad & yeast & crime \\
\midrule
bgrl random & \color{blue}{85.18$\pm$1.28} & \color{violet}{29.6$\pm$0.96} & 27.31$\pm$3.89 & \color{violet}{93.78$\pm$0.54} & \color{red}{23.73$\pm$2.21} \\
bgrl deg & \color{red}{86.95$\pm$2.33} & \color{red}{31.79$\pm$1.73} & \color{red}{38.94$\pm$9.26} & \color{red}{94.26$\pm$0.48} & \color{blue}{22.85$\pm$3.54} \\
bgrl pr & 83.58$\pm$1.23 & 27.75$\pm$1.17 & 23.39$\pm$2.68 & \color{blue}{94.0$\pm$0.38} & 17.86$\pm$2.27 \\
bgrl evc & 84.25$\pm$1.55 & 29.49$\pm$1.11 & \color{blue}{38.27$\pm$8.41} & 93.69$\pm$0.44 & \color{violet}{22.1$\pm$6.04} \\
bgrl scom & \color{violet}{84.69$\pm$1.39} & \color{blue}{29.92$\pm$1.16} & \color{violet}{28.13$\pm$2.69} & 93.46$\pm$0.56 & 20.51$\pm$3.5 \\
\bottomrule
\end{tabular}

}

sbm

In [13]:
names = ['cora', 'citeseer', 'netscience', 'power', 'euroroad', 'yeast', 'crime']
datasets = ['FINAL_SBM_cora_res.csv',
'FINAL_SBM_citeseer_res.csv',
'FINAL_SBM_netscience_res.csv',
'FINAL_SBM_power_res.csv',
'FINAL_SBM_euroroad_res.csv',
'FINAL_SBM_yeast_res.csv',
'FINAL_SBM_crime_res.csv']
data, res = ut.mix_dataset(datasets, 'Hits@50')

data.index = names
res.index = names
big_tab = ut.tex_table(data).T

\resizebox{\textwidth}{!}{
\begin{tabular}{llllllll}
\toprule
 & cora & citeseer & netscience & power & euroroad & yeast & crime \\
\midrule
louvain prob pred & 52.83$\pm$1.21 & 50.24$\pm$1.59 & 80.62$\pm$1.44 & 33.69$\pm$1.47 & 33.43$\pm$4.01 & 89.99$\pm$1.05 & 23.36$\pm$2.73 \\
grace sbm & 76.28$\pm$1.69 & 65.65$\pm$3.18 & 91.42$\pm$1.03 & \color{violet}{59.59$\pm$2.6} & 69.68$\pm$2.71 & 92.08$\pm$0.61 & 31.53$\pm$4.0 \\
grace sbm+random & \color{blue}{77.75$\pm$1.66} & 67.64$\pm$1.87 & \color{red}{92.43$\pm$0.97} & \color{blue}{63.01$\pm$2.91} & \color{red}{75.37$\pm$2.89} & 93.56$\pm$0.68 & 33.69$\pm$4.59 \\
grace sbm+deg & \color{violet}{77.68$\pm$2.05} & 73.64$\pm$7.46 & \color{violet}{92.23$\pm$0.88} & 54.41$\pm$5.27 & \color{violet}{74.06$\pm$4.63} & \color{blue}{94.98$\pm$0.54} & 32.37$\pm$3.48 \\
grace sbm+scom & 77.18$\pm$1.94 & 69.08$\pm$1.83 & \color{blue}{92.43$\pm$1.34} & \color{red}{63.57$\pm$2.25} & \color{blue}{75.34$\pm$2.55} & 94.25$\pm$0.62 & \color{violet}{36.07$\pm$4.89} \\
grace sbm2 & 58.88$\pm$2.29 & NaN & 90.91$\pm$0.98 & NaN & 68.41$\pm$4.9 & 93.12$\pm$0.97 & \color{blue}{38.2$\pm$4.14} \\
bgrl sbm & 72.79$\pm$1.71 & 73.53$\pm$1.85 & 88.52$\pm$2.02 & 44.94$\pm$3.18 & 47.84$\pm$4.25 & 93.75$\pm$0.59 & 26.92$\pm$2.38 \\
bgrl sbm+random & 75.75$\pm$1.95 & \color{blue}{75.25$\pm$2.42} & 89.36$\pm$1.35 & 50.46$\pm$2.31 & 59.51$\pm$4.25 & 93.91$\pm$0.48 & 26.64$\pm$3.0 \\
bgrl sbm+deg & \color{red}{79.28$\pm$1.72} & \color{red}{78.55$\pm$3.62} & 88.39$\pm$1.72 & 41.66$\pm$4.16 & 55.12$\pm$4.05 & \color{red}{95.09$\pm$0.58} & 22.37$\pm$4.35 \\
bgrl sbm+scom & 76.83$\pm$1.51 & \color{violet}{74.91$\pm$1.62} & 89.62$\pm$1.57 & 49.86$\pm$2.3 & 55.37$\pm$2.63 & 94.43$\pm$0.55 & 27.42$\pm$3.11 \\
bgrl sbm2 & 76.92$\pm$2.18 & NaN & 92.19$\pm$1.38 & NaN & 69.93$\pm$4.08 & \color{violet}{94.62$\pm$0.48} & \color{red}{40.64$\pm$3.76} \\
\bottomrule
\end{tabular}

}

reconstruction

In [ ]:
names = ['cora', 'citeseer', 'netscience', 'power', 'euroroad', 'yeast', 'crime']
datasets = [
'R_FINAL_cora_res.csv',
'R_FINAL_citeseer_res.csv',
'R_FINAL_netscience_res.csv',
'R_FINAL_power_res.csv',
'R_FINAL_euroroad_res.csv',
'R_FINAL_yeast_res.csv',
'R_FINAL_crime_res.csv']
data, res = ut.mix_dataset(datasets, 'Hits@50', filtre2=['\+'])

data.index = names
res.index = names
big_tab = ut.tex_table(data).T

\resizebox{\textwidth}{!}{
\begin{tabular}{llllllll}
\toprule
 & cora & citeseer & netscience & power & euroroad & yeast & crime \\
\midrule
grace rjc & 74.45$\pm$2.23 & \color{violet}{78.19$\pm$1.31} & 83.5$\pm$1.63 & 35.43$\pm$1.18 & 33.18$\pm$2.71 & 94.2$\pm$0.31 & 15.76$\pm$2.06 \\
grace raa & \color{violet}{76.1$\pm$1.72} & \color{red}{79.25$\pm$1.41} & 83.83$\pm$1.23 & 35.18$\pm$1.0 & 34.17$\pm$2.92 & 94.25$\pm$0.29 & 16.51$\pm$2.51 \\
grace rra & 75.59$\pm$1.92 & \color{blue}{78.74$\pm$1.42} & 83.8$\pm$1.62 & 35.82$\pm$0.63 & 35.12$\pm$4.68 & 94.18$\pm$0.3 & 17.05$\pm$2.75 \\
grace raa+scom & 74.75$\pm$1.77 & 77.46$\pm$0.77 & 83.81$\pm$1.63 & \color{violet}{36.48$\pm$0.8} & 36.93$\pm$2.17 & 94.22$\pm$0.29 & 17.19$\pm$1.79 \\
grace raa+deg & \color{blue}{76.43$\pm$1.64} & 78.11$\pm$2.67 & \color{violet}{86.48$\pm$2.27} & 35.97$\pm$0.93 & \color{violet}{38.69$\pm$4.89} & 93.94$\pm$0.64 & 17.8$\pm$3.0 \\
grace sbm+raa & 76.09$\pm$2.31 & 68.7$\pm$1.85 & \color{red}{92.14$\pm$1.04} & \color{red}{61.02$\pm$4.08} & \color{red}{73.99$\pm$3.01} & \color{red}{94.79$\pm$0.45} & \color{red}{33.76$\pm$3.07} \\
bgrl rjc & 73.0$\pm$1.49 & 73.46$\pm$1.47 & 84.31$\pm$1.38 & 28.97$\pm$0.83 & 23.71$\pm$3.5 & 93.61$\pm$0.62 & 19.39$\pm$2.19 \\
bgrl raa & 71.72$\pm$1.14 & 71.08$\pm$1.22 & 84.18$\pm$1.39 & 29.1$\pm$0.74 & 24.35$\pm$1.04 & 94.08$\pm$0.48 & 17.32$\pm$1.84 \\
bgrl rra & 72.25$\pm$1.29 & 72.05$\pm$1.01 & 84.38$\pm$1.58 & 29.08$\pm$1.0 & 25.02$\pm$1.76 & 93.45$\pm$0.47 & 17.46$\pm$3.44 \\
bgrl raa+scom & 70.89$\pm$1.24 & 70.81$\pm$2.06 & 84.23$\pm$1.63 & 30.87$\pm$0.71 & 26.33$\pm$2.5 & 93.73$\pm$0.61 & \color{violet}{20.47$\pm$3.03} \\
bgrl raa+deg & \color{red}{78.12$\pm$1.45} & 73.84$\pm$5.96 & 85.02$\pm$2.23 & 32.38$\pm$1.92 & 33.92$\pm$4.61 & \color{violet}{94.29$\pm$0.6} & 18.14$\pm$3.21 \\
bgrl sbm+raa & 74.66$\pm$1.37 & 76.37$\pm$1.23 & \color{blue}{88.74$\pm$1.22} & \color{blue}{48.6$\pm$1.43} & \color{blue}{42.51$\pm$4.53} & \color{blue}{94.61$\pm$0.45} & \color{blue}{23.93$\pm$2.14} \\
\bottomrule
\end{tabular}

}

Res 1 globale

In [24]:
names = ['cora', 'netscience', 'power', 'euroroad', 'yeast', 'crime']
datasets = [
'FINAL_cora_res.csv',
'FINAL_netscience_res.csv',
'FINAL_power_res.csv',
'FINAL_euroroad_res.csv',
'FINAL_yeast_res.csv',
'FINAL_crime_res.csv']
data, res = ut.mix_dataset(datasets, 'Hits@50', filtre2=['evc', 'pr', 'csgcl'])

datasets_sbm = [
'FINAL_SBM_cora_res.csv',
'FINAL_SBM_netscience_res.csv',
'FINAL_SBM_power_res.csv',
'FINAL_SBM_euroroad_res.csv',
'FINAL_SBM_yeast_res.csv',
'FINAL_SBM_crime_res.csv']
data_sbm, res_sbm = ut.mix_dataset(datasets_sbm, 'Hits@50', filtre=['sbm\+'])

datasets_r = [
'R_FINAL_cora_res.csv',
'R_FINAL_netscience_res.csv',
'R_FINAL_power_res.csv',
'R_FINAL_euroroad_res.csv',
'R_FINAL_yeast_res.csv',
'R_FINAL_crime_res.csv']
data_r, res_r = ut.mix_dataset(datasets_r, 'Hits@50', filtre2=['rjc', 'rra'])

datasets_A = [
'A2_FINAL_cora_res.csv',
'A2_FINAL_netscience_res.csv',
'A2_FINAL_power_res.csv',
'A2_FINAL_euroroad_res.csv',
'A2_FINAL_yeast_res.csv',
'A2_FINAL_crime_res.csv']
data_a, res_a = ut.mix_dataset(datasets_A, 'Hits@50')

datasets_L = [
'L_FINAL_cora_res.csv',
'L_FINAL_netscience_res.csv',
'L_FINAL_power_res.csv',
'L_FINAL_euroroad_res.csv',
'L_FINAL_yeast_res.csv',
'L_FINAL_crime_res.csv'
]
data_l, res_l = ut.mix_dataset(datasets_L, 'Hits@50')

for df in [data, res, data_sbm, res_sbm, data_r, res_r, data_a, res_a, data_l, res_l]:
	df.index = names

for df in [data_sbm, data_r, data_a, data_l]:
	data = data.join(df)
	
for df in [res_sbm, res_r, res_a, res_l]:
	res = res.join(df)
big_tab = ut.tex_table(data, res).T
big_tab

\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & cora & netscience & power & euroroad & yeast & crime \\
\midrule
baseline & 71.55$\pm$1.75 & 85.18$\pm$1.85 & 32.24$\pm$0.75 & 36.71$\pm$3.26 & 93.98$\pm$0.55 & 23.02$\pm$2.9 \\
grace random & 75.85$\pm$1.75 & 84.34$\pm$1.29 & 36.05$\pm$1.17 & 37.42$\pm$2.96 & 94.28$\pm$0.28 & 18.34$\pm$2.03 \\
grace deg & 73.9$\pm$2.04 & 86.28$\pm$2.0 & 36.46$\pm$1.26 & 43.46$\pm$7.72 & 93.66$\pm$0.56 & 21.05$\pm$3.22 \\
grace scom & 76.3$\pm$2.02 & 84.32$\pm$1.3 & 36.34$\pm$1.11 & 36.22$\pm$3.33 & 94.37$\pm$0.24 & 18.85$\pm$3.06 \\
grace random+scom & 75.37$\pm$1.78 & 84.11$\pm$1.34 & 36.4$\pm$0.94 & 34.88$\pm$1.91 & 94.26$\pm$0.33 & 16.95$\pm$2.03 X \\
grace random+deg & 77.02$\pm$1.56 & 86.93$\pm$2.53 & 36.27$\pm$1.03 & 38.37$\pm$3.28 & 94.2$\pm$0.48 & 18.27$\pm$2.03 \\
grace deg+scom & 76.62$\pm$1.79 & 86.04$\pm$2.0 & 36.8$\pm$1.64 & 38.94$\pm$5.06 & 94.02$\pm$0.49 & 17.59$\pm$2.47 \\
bgrl random & 73.58$\pm$1.44 & 85.18$\pm$1.28 & 29.6$\pm$0.96 & 27.31$\pm$3.89 & 93.78$\pm$0.54 & 23.73$\pm$2.21 \\
bgrl deg & 77.49$\pm$1.21 & 86.95$\pm$2.33 & 31.79$\pm$1.73 & 38.94$\pm$9.26 & 94.26$\pm$0.48 & 22.85$\pm$3.54 \\
bgrl scom & 73.79$\pm$1.91 & 84.69$\pm$1.39 & 29.92$\pm$1.16 & 28.13$\pm$2.69 & 93.46$\pm$0.56 & 20.51$\pm$3.5 \\
bgrl random+scom & 73.31$\pm$1.8 & 84.84$\pm$1.56 & 29.77$\pm$1.38 & 28.37$\pm$2.86 & 93.33$\pm$0.65 & 24.95$\pm$3.63 \\
bgrl random+deg & 77.88$\pm$1.69 & 84.89$\pm$1.64 & 30.33$\pm$0.85 & 34.88$\pm$3.01 & 94.36$\pm$0.6 & 18.78$\pm$4.59 \\
bgrl deg+scom & 77.49$\pm$1.84 & 84.43$\pm$1.56 & 29.86$\pm$1.42 & 32.08$\pm$3.74 & 94.37$\pm$0.5 & 17.12$\pm$3.17 \\
grace sbm+random & 77.75$\pm$1.66 & \color{blue}{92.43$\pm$0.97 $\bigstar$} & \color{blue}{63.01$\pm$2.91 $\bigstar$} & \color{blue}{75.37$\pm$2.89 $\bigstar$} & 93.56$\pm$0.68 & 33.69$\pm$4.59 \\
grace sbm+deg & 77.68$\pm$2.05 & 92.23$\pm$0.88 & 54.41$\pm$5.27 & 74.06$\pm$4.63 & \color{violet}{94.98$\pm$0.54} & 32.37$\pm$3.48 \\
grace sbm+scom & 77.18$\pm$1.94 & \color{violet}{92.43$\pm$1.34 $\bigstar$} & \color{red}{63.57$\pm$2.25 $\bigstar$} & \color{violet}{75.34$\pm$2.55 $\bigstar$} & 94.25$\pm$0.62 & \color{red}{36.07$\pm$4.89 $\bigstar$} \\
bgrl sbm+random & 75.75$\pm$1.95 & 89.36$\pm$1.35 & 50.46$\pm$2.31 & 59.51$\pm$4.25 & 93.91$\pm$0.48 & 26.64$\pm$3.0 \\
bgrl sbm+deg & \color{red}{79.28$\pm$1.72 $\bigstar$} & 88.39$\pm$1.72 & 41.66$\pm$4.16 & 55.12$\pm$4.05 & \color{blue}{95.09$\pm$0.58 $\bigstar$} & 22.37$\pm$4.35 \\
bgrl sbm+scom & 76.83$\pm$1.51 & 89.62$\pm$1.57 & 49.86$\pm$2.3 & 55.37$\pm$2.63 & 94.43$\pm$0.55 & 27.42$\pm$3.11 \\
grace raa & 76.1$\pm$1.72 & 83.83$\pm$1.23 & 35.18$\pm$1.0 & 34.17$\pm$2.92 & 94.25$\pm$0.29 & 16.51$\pm$2.51 X \\
grace raa+scom & 74.75$\pm$1.77 & 83.81$\pm$1.63 X & 36.48$\pm$0.8 & 36.93$\pm$2.17 & 94.22$\pm$0.29 & 17.19$\pm$1.79 \\
grace raa+deg & 76.43$\pm$1.64 & 86.48$\pm$2.27 & 35.97$\pm$0.93 & 38.69$\pm$4.89 & 93.94$\pm$0.64 & 17.8$\pm$3.0 \\
grace sbm+raa & 76.09$\pm$2.31 & 92.14$\pm$1.04 & 61.02$\pm$4.08 & 73.99$\pm$3.01 & 94.79$\pm$0.45 & \color{violet}{33.76$\pm$3.07} \\
bgrl raa & 71.72$\pm$1.14 & 84.18$\pm$1.39 & 29.1$\pm$0.74 & 24.35$\pm$1.04 X & 94.08$\pm$0.48 & 17.32$\pm$1.84 \\
bgrl raa+scom & 70.89$\pm$1.24 & 84.23$\pm$1.63 & 30.87$\pm$0.71 & 26.33$\pm$2.5 & 93.73$\pm$0.61 & 20.47$\pm$3.03 \\
bgrl raa+deg & \color{violet}{78.12$\pm$1.45} & 85.02$\pm$2.23 & 32.38$\pm$1.92 & 33.92$\pm$4.61 & 94.29$\pm$0.6 & 18.14$\pm$3.21 \\
bgrl sbm+raa & 74.66$\pm$1.37 & 88.74$\pm$1.22 & 48.6$\pm$1.43 & 42.51$\pm$4.53 & 94.61$\pm$0.45 & 23.93$\pm$2.14 \\
a2grace random & 75.53$\pm$1.79 & 84.01$\pm$1.6 & 36.67$\pm$0.99 & 36.04$\pm$2.05 & 94.23$\pm$0.3 & 17.8$\pm$2.01 \\
a2grace deg & 73.84$\pm$2.33 & 87.96$\pm$2.63 & 36.24$\pm$1.19 & 42.97$\pm$6.99 & 93.91$\pm$0.44 & 22.68$\pm$5.33 \\
a2grace raa & 75.19$\pm$1.11 & 83.87$\pm$1.57 & 35.7$\pm$1.06 & 33.57$\pm$3.04 & 94.13$\pm$0.34 & 16.95$\pm$2.96 X \\
a2grace sbm+random & 77.52$\pm$2.0 & \color{red}{92.7$\pm$0.87 $\bigstar$} & \color{violet}{62.69$\pm$2.55 $\bigstar$} & \color{red}{76.64$\pm$4.48 $\bigstar$} & 94.9$\pm$0.44 & \color{blue}{35.8$\pm$3.2 $\bigstar$} \\
a2grace sbm+deg & 76.87$\pm$1.92 & 92.01$\pm$1.7 & 53.47$\pm$5.73 & 71.27$\pm$4.59 & 94.87$\pm$0.66 & 30.95$\pm$4.56 \\
a2grace sbm+raa & 76.73$\pm$1.63 & 92.37$\pm$0.73 $\bigstar$ & 60.2$\pm$2.33 & 71.87$\pm$3.12 & \color{red}{95.23$\pm$0.63 $\bigstar$} & 30.92$\pm$2.99 \\
a2bgrl random & 70.78$\pm$1.72 & 85.95$\pm$2.05 & 30.73$\pm$1.15 & 26.93$\pm$3.2 & 94.31$\pm$0.42 & 31.86$\pm$5.01 \\
a2bgrl deg & 76.55$\pm$1.51 & 86.02$\pm$1.44 & 31.99$\pm$2.37 & 29.61$\pm$4.0 & 94.58$\pm$0.45 & 23.02$\pm$4.77 \\
a2bgrl raa & 69.02$\pm$0.91 & 86.41$\pm$1.48 & 35.78$\pm$0.91 & 26.15$\pm$3.69 & 94.28$\pm$0.38 & 28.92$\pm$4.4 \\
a2bgrl sbm+random & 74.54$\pm$1.77 & 87.01$\pm$1.45 & 28.02$\pm$6.4 & 32.76$\pm$4.86 & 94.54$\pm$0.36 & 28.44$\pm$4.12 \\
a2bgrl sbm+deg & 76.46$\pm$1.52 & 88.56$\pm$1.26 & 32.69$\pm$2.14 & 36.68$\pm$3.77 & 94.52$\pm$0.39 & 28.78$\pm$2.0 \\
a2bgrl sbm+raa & 73.91$\pm$0.92 & 85.46$\pm$1.74 & 37.0$\pm$1.33 & 26.25$\pm$2.84 & 94.46$\pm$0.36 & 28.37$\pm$2.5 \\
lgrace random & 73.27$\pm$1.36 & 84.71$\pm$1.61 & 33.04$\pm$2.63 & 32.19$\pm$2.64 & 94.01$\pm$0.34 & 18.2$\pm$1.77 \\
lgrace deg & 74.21$\pm$1.84 & 85.04$\pm$1.61 & 34.44$\pm$2.35 & 37.6$\pm$4.6 & 94.0$\pm$0.41 & 19.73$\pm$2.94 \\
lgrace raa & 73.46$\pm$1.19 & 85.09$\pm$1.19 & 35.51$\pm$0.82 & 38.48$\pm$4.51 & 93.81$\pm$0.47 & 18.47$\pm$2.24 \\
lgrace sbm+random & 53.68$\pm$3.8 X & 82.99$\pm$2.2 X & 11.29$\pm$2.06 X & 24.35$\pm$3.65 X & 92.99$\pm$0.83 & 28.14$\pm$7.05 \\
lgrace sbm+deg & 53.31$\pm$5.71 X & 82.52$\pm$2.6 X & 12.38$\pm$3.17 X & 24.06$\pm$3.84 X & 92.68$\pm$0.58 X & 28.14$\pm$7.05 \\
lgrace sbm+raa & 61.68$\pm$3.16 & 83.47$\pm$1.26 X & 17.43$\pm$5.19 & 29.15$\pm$5.25 & 93.13$\pm$0.83 & 24.1$\pm$1.9 \\
lbgrl random & \color{blue}{78.29$\pm$1.43} & 84.25$\pm$1.72 & 29.63$\pm$0.95 & 26.25$\pm$5.64 & 94.22$\pm$0.32 & 19.42$\pm$3.94 \\
lbgrl deg & 72.64$\pm$2.23 & 82.1$\pm$4.49 & 26.43$\pm$3.69 & 43.11$\pm$8.41 & 91.03$\pm$2.83 X & 27.59$\pm$4.74 \\
lbgrl raa & 77.23$\pm$1.65 & 84.14$\pm$1.94 & 32.49$\pm$1.12 & 38.3$\pm$6.45 & 94.08$\pm$0.37 & 25.02$\pm$5.46 \\
lbgrl sbm+random & 67.0$\pm$2.05 & 88.56$\pm$1.85 & 24.97$\pm$2.4 & 35.55$\pm$2.94 & 93.73$\pm$0.51 & 28.24$\pm$7.84 \\
lbgrl sbm+deg & 62.23$\pm$3.06 & 87.5$\pm$1.54 & 16.88$\pm$7.69 & 32.05$\pm$7.02 & 92.81$\pm$1.43 & 27.32$\pm$5.37 \\
lbgrl sbm+raa & 70.35$\pm$2.33 & 88.54$\pm$1.89 & 31.52$\pm$4.24 & 37.53$\pm$2.77 & 94.09$\pm$0.63 & 32.34$\pm$4.09 \\
\bottomrule
\end{tabular}

}

,cora,netscience,power,euroroad,yeast,crime
baseline,71.55$\pm$1.75,85.18$\pm$1.85,32.24$\pm$0.75,36.71$\pm$3.26,93.98$\pm$0.55,23.02$\pm$2.9
grace random,75.85$\pm$1.75,84.34$\pm$1.29,36.05$\pm$1.17,37.42$\pm$2.96,94.28$\pm$0.28,18.34$\pm$2.03
grace deg,73.9$\pm$2.04,86.28$\pm$2.0,36.46$\pm$1.26,43.46$\pm$7.72,93.66$\pm$0.56,21.05$\pm$3.22
grace scom,76.3$\pm$2.02,84.32$\pm$1.3,36.34$\pm$1.11,36.22$\pm$3.33,94.37$\pm$0.24,18.85$\pm$3.06
grace random+scom,75.37$\pm$1.78,84.11$\pm$1.34,36.4$\pm$0.94,34.88$\pm$1.91,94.26$\pm$0.33,16.95$\pm$2.03 X
grace random+deg,77.02$\pm$1.56,86.93$\pm$2.53,36.27$\pm$1.03,38.37$\pm$3.28,94.2$\pm$0.48,18.27$\pm$2.03
grace deg+scom,76.62$\pm$1.79,86.04$\pm$2.0,36.8$\pm$1.64,38.94$\pm$5.06,94.02$\pm$0.49,17.59$\pm$2.47
bgrl random,73.58$\pm$1.44,85.18$\pm$1.28,29.6$\pm$0.96,27.31$\pm$3.89,93.78$\pm$0.54,23.73$\pm$2.21
bgrl deg,77.49$\pm$1.21,86.95$\pm$2.33,31.79$\pm$1.73,38.94$\pm$9.26,94.26$\pm$0.48,22.85$\pm$3.54
bgrl scom,73.79$\pm$1.91,84.69$\pm$1.39,29.92$\pm$1.16,28.13$\pm$2.69,93.46$\pm$0.56,20.51$\pm$3.5
bgrl random+scom,73.31$\pm$1.8,84.84$\pm$1.56,29.77$\pm$1.38,28.37$\pm$2.86,93.33$\pm$0.65,24.95$\pm$3.63
bgrl random+deg,77.88$\pm$1.69,84.89$\pm$1.64,30.33$\pm$0.85,34.88$\pm$3.01,94.36$\pm$0.6,18.78$\pm$4.59
bgrl deg+scom,77.49$\pm$1.84,84.43$\pm$1.56,29.86$\pm$1.42,32.08$\pm$3.74,94.37$\pm$0.5,17.12$\pm$3.17
grace sbm+random,77.75$\pm$1.66,\color{blue}{92.43$\pm$0.97 $\bigstar$},\color{blue}{63.01$\pm$2.91 $\bigstar$},\color{blue}{75.37$\pm$2.89 $\bigstar$},93.56$\pm$0.68,33.69$\pm$4.59
grace sbm+deg,77.68$\pm$2.05,92.23$\pm$0.88,54.41$\pm$5.27,74.06$\pm$4.63,\color{violet}{94.98$\pm$0.54},32.37$\pm$3.48
grace sbm+scom,77.18$\pm$1.94,\color{violet}{92.43$\pm$1.34 $\bigstar$},\color{red}{63.57$\pm$2.25 $\bigstar$},\color{violet}{75.34$\pm$2.55 $\bigstar$},94.25$\pm$0.62,\color{red}{36.07$\pm$4.89 $\bigstar$}
bgrl sbm+random,75.75$\pm$1.95,89.36$\pm$1.35,50.46$\pm$2.31,59.51$\pm$4.25,93.91$\pm$0.48,26.64$\pm$3.0
bgrl sbm+deg,\color{red}{79.28$\pm$1.72 $\bigstar$},88.39$\pm$1.72,41.66$\pm$4.16,55.12$\pm$4.05,\color{blue}{95.09$\pm$0.58 $\bigstar$},22.37$\pm$4.35
bgrl sbm+scom,76.83$\pm$1.51,89.62$\pm$1.57,49.86$\pm$2.3,55.37$\pm$2.63,94.43$\pm$0.55,27.42$\pm$3.11
grace raa,76.1$\pm$1.72,83.83$\pm$1.23,35.18$\pm$1.0,34.17$\pm$2.92,94.25$\pm$0.29,16.51$\pm$2.51 X
grace raa+scom,74.75$\pm$1.77,83.81$\pm$1.63 X,36.48$\pm$0.8,36.93$\pm$2.17,94.22$\pm$0.29,17.19$\pm$1.79
grace raa+deg,76.43$\pm$1.64,86.48$\pm$2.27,35.97$\pm$0.93,38.69$\pm$4.89,93.94$\pm$0.64,17.8$\pm$3.0
grace sbm+raa,76.09$\pm$2.31,92.14$\pm$1.04,61.02$\pm$4.08,73.99$\pm$3.01,94.79$\pm$0.45,\color{violet}{33.76$\pm$3.07}
bgrl raa,71.72$\pm$1.14,84.18$\pm$1.39,29.1$\pm$0.74,24.35$\pm$1.04 X,94.08$\pm$0.48,17.32$\pm$1.84
bgrl raa+scom,70.89$\pm$1.24,84.23$\pm$1.63,30.87$\pm$0.71,26.33$\pm$2.5,93.73$\pm$0.61,20.47$\pm$3.03
bgrl raa+deg,\color{violet}{78.12$\pm$1.45},85.02$\pm$2.23,32.38$\pm$1.92,33.92$\pm$4.61,94.29$\pm$0.6,18.14$\pm$3.21
bgrl sbm+raa,74.66$\pm$1.37,88.74$\pm$1.22,48.6$\pm$1.43,42.51$\pm$4.53,94.61$\pm$0.45,23.93$\pm$2.14
a2grace random,75.53$\pm$1.79,84.01$\pm$1.6,36.67$\pm$0.99,36.04$\pm$2.05,94.23$\pm$0.3,17.8$\pm$2.01
a2grace deg,73.84$\pm$2.33,87.96$\pm$2.63,36.24$\pm$1.19,42.97$\pm$6.99,93.91$\pm$0.44,22.68$\pm$5.33
a2grace raa,75.19$\pm$1.11,83.87$\pm$1.57,35.7$\pm$1.06,33.57$\pm$3.04,94.13$\pm$0.34,16.95$\pm$2.96 X
a2grace sbm+random,77.52$\pm$2.0,\color{red}{92.7$\pm$0.87 $\bigstar$},\color{violet}{62.69$\pm$2.55 $\bigstar$},\color{red}{76.64$\pm$4.48 $\bigstar$},94.9$\pm$0.44,\color{blue}{35.8$\pm$3.2 $\bigstar$}
a2grace sbm+deg,76.87$\pm$1.92,92.01$\pm$1.7,53.47$\pm$5.73,71.27$\pm$4.59,94.87$\pm$0.66,30.95$\pm$4.56
a2grace sbm+raa,76.73$\pm$1.63,92.37$\pm$0.73 $\bigstar$,60.2$\pm$2.33,71.87$\pm$3.12,\color{red}{95.23$\pm$0.63 $\bigstar$},30.92$\pm$2.99
a2bgrl random,70.78$\pm$1.72,85.95$\pm$2.05,30.73$\pm$1.15,26.93$\pm$3.2,94.31$\pm$0.42,31.86$\pm$5.01
a2bgrl deg,76.55$\pm$1.51,86.02$\pm$1.44,31.99$\pm$2.37,29.61$\pm$4.0,94.58$\pm$0.45,23.02$\pm$4.77
a2bgrl raa,69.02$\pm$0.91,86.41$\pm$1.48,35.78$\pm$0.91,26.15$\pm$3.69,94.28$\pm$0.38,28.92$\pm$4.4
a2bgrl sbm+random,74.54$\pm$1.77,87.01$\pm$1.45,28.02$\pm$6.4,32.76$\pm$4.86,94.54$\pm$0.36,28.44$\pm$4.12
a2bgrl sbm+deg,76.46$\pm$1.52,88.56$\pm$1.26,32.69$\pm$2.14,36.68$\pm$3.77,94.52$\pm$0.39,28.78$\pm$2.0
a2bgrl sbm+raa,73.91$\pm$0.92,85.46$\pm$1.74,37.0$\pm$1.33,26.25$\pm$2.84,94.46$\pm$0.36,28.37$\pm$2.5
lgrace random,73.27$\pm$1.36,84.71$\pm$1.61,33.04$\pm$2.63,32.19$\pm$2.64,94.01$\pm$0.34,18.2$\pm$1.77
lgrace deg,74.21$\pm$1.84,85.04$\pm$1.61,34.44$\pm$2.35,37.6$\pm$4.6,94.0$\pm$0.41,19.73$\pm$2.94
lgrace raa,73.46$\pm$1.19,85.09$\pm$1.19,35.51$\pm$0.82,38.48$\pm$4.51,93.81$\pm$0.47,18.47$\pm$2.24
lgrace sbm+random,53.68$\pm$3.8 X,82.99$\pm$2.2 X,11.29$\pm$2.06 X,24.35$\pm$3.65 X,92.99$\pm$0.83,28.14$\pm$7.05
lgrace sbm+deg,53.31$\pm$5.71 X,82.52$\pm$2.6 X,12.38$\pm$3.17 X,24.06$\pm$3.84 X,92.68$\pm$0.58 X,28.14$\pm$7.05
lgrace sbm+raa,61.68$\pm$3.16,83.47$\pm$1.26 X,17.43$\pm$5.19,29.15$\pm$5.25,93.13$\pm$0.83,24.1$\pm$1.9
lbgrl random,\color{blue}{78.29$\pm$1.43},84.25$\pm$1.72,29.63$\pm$0.95,26.25$\pm$5.64,94.22$\pm$0.32,19.42$\pm$3.94
lbgrl deg,72.64$\pm$2.23,82.1$\pm$4.49,26.43$\pm$3.69,43.11$\pm$8.41,91.03$\pm$2.83 X,27.59$\pm$4.74
lbgrl raa,77.23$\pm$1.65,84.14$\pm$1.94,32.49$\pm$1.12,38.3$\pm$6.45,94.08$\pm$0.37,25.02$\pm$5.46
lbgrl sbm+random,67.0$\pm$2.05,88.56$\pm$1.85,24.97$\pm$2.4,35.55$\pm$2.94,93.73$\pm$0.51,28.24$\pm$7.84
lbgrl sbm+deg,62.23$\pm$3.06,87.5$\pm$1.54,16.88$\pm$7.69,32.05$\pm$7.02,92.81$\pm$1.43,27.32$\pm$5.37
lbgrl sbm+raa,70.35$\pm$2.33,88.54$\pm$1.89,31.52$\pm$4.24,37.53$\pm$2.77,94.09$\pm$0.63,32.34$\pm$4.09

In [40]:
names = ['cora', 'citeseer', 'pubmed']
datasets = [
'FINAL_cora_res.csv',
'FINAL_citeseer_res.csv',
'FINAL_pubmed_res.csv',
]
data, res = ut.mix_dataset(datasets, 'Hits@100', filtre2=['csgcl', 'pr', 'evc'])
data.index = names
res.index = names

datasets_L = [
'L_FINAL_cora_res.csv',
'L_FINAL_citeseer_res.csv',
'L_FINAL_pubmed_res.csv',
]
data_l, res_l = ut.mix_dataset(datasets_L, 'Hits@100', filtre2=['csgcl', 'pr', 'evc'])
data_l.index = names
res_l.index = names

datasets_A = [
'A2_FINAL_cora_res.csv',
'A2_FINAL_citeseer_res.csv',
'A2_FINAL_pubmed_res.csv',
]
data_a, res_a = ut.mix_dataset(datasets_A, 'Hits@100', filtre2=['csgcl', 'pr', 'evc'])
data_a.index = names
res_a.index = names

for df in [data_a, data_l]:
	data = data.join(df)
	
for df in [res_a, res_l]:
	res = res.join(df)

big_tab = ut.tex_table(data, res).T
big_tab

\resizebox{\textwidth}{!}{
\begin{tabular}{llll}
\toprule
 & cora & citeseer & pubmed \\
\midrule
baseline & 77.84$\pm$1.7 & 0.0$\pm$0.0 X & 77.46$\pm$2.27 \\
grace random & 81.79$\pm$1.1 & 83.62$\pm$1.62 & 77.59$\pm$1.87 \\
grace deg & 84.4$\pm$1.15 $\bigstar$ & \color{blue}{85.82$\pm$2.4 $\bigstar$} & \color{violet}{77.86$\pm$1.6} \\
grace scom & 81.61$\pm$1.52 & 84.66$\pm$1.05 & \color{blue}{78.47$\pm$1.57 $\bigstar$} \\
grace random+scom & 81.31$\pm$1.51 & 84.46$\pm$1.54 & 77.62$\pm$1.96 \\
grace random+deg & \color{blue}{84.64$\pm$1.14 $\bigstar$} & \color{violet}{85.26$\pm$2.41 $\bigstar$} & 77.54$\pm$1.38 \\
grace deg+scom & 84.21$\pm$1.28 & \color{red}{85.96$\pm$2.03 $\bigstar$} & \color{red}{78.85$\pm$1.19 $\bigstar$} \\
bgrl random & 78.39$\pm$1.14 & 78.4$\pm$1.49 & 71.03$\pm$1.43 \\
bgrl deg & 82.98$\pm$1.31 & 80.31$\pm$5.48 & 72.44$\pm$1.97 \\
bgrl scom & 78.64$\pm$1.06 & 79.05$\pm$1.41 & 72.95$\pm$1.87 \\
bgrl random+scom & 78.11$\pm$1.57 & 78.27$\pm$0.58 & 73.33$\pm$1.76 \\
bgrl random+deg & 82.38$\pm$1.59 & 80.34$\pm$4.75 & 73.79$\pm$2.18 \\
bgrl deg+scom & 82.53$\pm$1.31 & 80.43$\pm$3.8 & 72.8$\pm$1.8 \\
a2grace random & 81.48$\pm$1.72 & NaN & NaN \\
a2grace deg & 84.45$\pm$1.89 & NaN & NaN \\
a2grace raa & 81.29$\pm$1.7 & NaN & NaN \\
a2grace sbm+random & 82.83$\pm$1.89 & NaN & NaN \\
a2grace sbm+deg & \color{red}{84.82$\pm$1.79 $\bigstar$} & NaN & NaN \\
a2grace sbm+raa & 82.09$\pm$1.49 & NaN & NaN \\
a2bgrl random & 75.58$\pm$1.45 & 74.2$\pm$1.36 & 62.16$\pm$1.8 X \\
a2bgrl deg & 81.51$\pm$1.45 & 76.44$\pm$3.64 & 65.08$\pm$2.89 \\
a2bgrl raa & 73.55$\pm$1.16 & 72.8$\pm$0.9 & NaN \\
a2bgrl sbm+random & 80.81$\pm$1.15 & 77.79$\pm$1.22 & NaN \\
a2bgrl sbm+deg & 82.12$\pm$1.29 & 78.11$\pm$2.55 & NaN \\
a2bgrl sbm+raa & 79.01$\pm$1.26 & 76.12$\pm$1.19 & NaN \\
a2bgrl scom & NaN & NaN & 63.6$\pm$3.15 X \\
a2bgrl random+scom & NaN & NaN & 63.75$\pm$1.66 \\
a2bgrl random+deg & NaN & NaN & 65.68$\pm$1.69 \\
a2bgrl deg+scom & NaN & NaN & 64.56$\pm$2.01 \\
lgrace random & 79.28$\pm$1.76 & NaN & NaN \\
lgrace deg & 80.7$\pm$1.36 & NaN & NaN \\
lgrace raa & 79.26$\pm$1.74 & NaN & NaN \\
lgrace sbm+random & 66.0$\pm$2.74 X & NaN & NaN \\
lgrace sbm+deg & 66.28$\pm$5.23 X & NaN & NaN \\
lgrace sbm+raa & 72.38$\pm$2.04 & NaN & NaN \\
lbgrl random & \color{violet}{84.64$\pm$1.19 $\bigstar$} & 82.98$\pm$1.45 & 72.47$\pm$2.51 \\
lbgrl deg & 80.48$\pm$1.32 & 85.01$\pm$2.89 & 72.64$\pm$3.8 \\
lbgrl raa & 84.06$\pm$1.18 & 82.92$\pm$1.74 & NaN \\
lbgrl sbm+random & 76.07$\pm$1.64 & 72.37$\pm$3.27 & NaN \\
lbgrl sbm+deg & 74.46$\pm$1.91 & 72.11$\pm$3.06 & NaN \\
lbgrl sbm+raa & 79.56$\pm$1.16 & 75.82$\pm$2.68 & NaN \\
lbgrl scom & NaN & NaN & 71.21$\pm$3.43 \\
lbgrl random+scom & NaN & NaN & 71.48$\pm$4.54 \\
lbgrl random+deg & NaN & NaN & 72.36$\pm$4.5 \\
lbgrl deg+scom & NaN & NaN & 73.18$\pm$3.05 \\
\bottomrule
\end{tabular}

}

,cora,citeseer,pubmed
baseline,77.84$\pm$1.7,0.0$\pm$0.0 X,77.46$\pm$2.27
grace random,81.79$\pm$1.1,83.62$\pm$1.62,77.59$\pm$1.87
grace deg,84.4$\pm$1.15 $\bigstar$,\color{blue}{85.82$\pm$2.4 $\bigstar$},\color{violet}{77.86$\pm$1.6}
grace scom,81.61$\pm$1.52,84.66$\pm$1.05,\color{blue}{78.47$\pm$1.57 $\bigstar$}
grace random+scom,81.31$\pm$1.51,84.46$\pm$1.54,77.62$\pm$1.96
grace random+deg,\color{blue}{84.64$\pm$1.14 $\bigstar$},\color{violet}{85.26$\pm$2.41 $\bigstar$},77.54$\pm$1.38
grace deg+scom,84.21$\pm$1.28,\color{red}{85.96$\pm$2.03 $\bigstar$},\color{red}{78.85$\pm$1.19 $\bigstar$}
bgrl random,78.39$\pm$1.14,78.4$\pm$1.49,71.03$\pm$1.43
bgrl deg,82.98$\pm$1.31,80.31$\pm$5.48,72.44$\pm$1.97
bgrl scom,78.64$\pm$1.06,79.05$\pm$1.41,72.95$\pm$1.87
bgrl random+scom,78.11$\pm$1.57,78.27$\pm$0.58,73.33$\pm$1.76
bgrl random+deg,82.38$\pm$1.59,80.34$\pm$4.75,73.79$\pm$2.18
bgrl deg+scom,82.53$\pm$1.31,80.43$\pm$3.8,72.8$\pm$1.8
a2grace random,81.48$\pm$1.72,NaN,NaN
a2grace deg,84.45$\pm$1.89,NaN,NaN
a2grace raa,81.29$\pm$1.7,NaN,NaN
a2grace sbm+random,82.83$\pm$1.89,NaN,NaN
a2grace sbm+deg,\color{red}{84.82$\pm$1.79 $\bigstar$},NaN,NaN
a2grace sbm+raa,82.09$\pm$1.49,NaN,NaN
a2bgrl random,75.58$\pm$1.45,74.2$\pm$1.36,62.16$\pm$1.8 X
a2bgrl deg,81.51$\pm$1.45,76.44$\pm$3.64,65.08$\pm$2.89
a2bgrl raa,73.55$\pm$1.16,72.8$\pm$0.9,NaN
a2bgrl sbm+random,80.81$\pm$1.15,77.79$\pm$1.22,NaN
a2bgrl sbm+deg,82.12$\pm$1.29,78.11$\pm$2.55,NaN
a2bgrl sbm+raa,79.01$\pm$1.26,76.12$\pm$1.19,NaN
a2bgrl scom,NaN,NaN,63.6$\pm$3.15 X
a2bgrl random+scom,NaN,NaN,63.75$\pm$1.66
a2bgrl random+deg,NaN,NaN,65.68$\pm$1.69
a2bgrl deg+scom,NaN,NaN,64.56$\pm$2.01
lgrace random,79.28$\pm$1.76,NaN,NaN
lgrace deg,80.7$\pm$1.36,NaN,NaN
lgrace raa,79.26$\pm$1.74,NaN,NaN
lgrace sbm+random,66.0$\pm$2.74 X,NaN,NaN
lgrace sbm+deg,66.28$\pm$5.23 X,NaN,NaN
lgrace sbm+raa,72.38$\pm$2.04,NaN,NaN
lbgrl random,\color{violet}{84.64$\pm$1.19 $\bigstar$},82.98$\pm$1.45,72.47$\pm$2.51
lbgrl deg,80.48$\pm$1.32,85.01$\pm$2.89,72.64$\pm$3.8
lbgrl raa,84.06$\pm$1.18,82.92$\pm$1.74,NaN
lbgrl sbm+random,76.07$\pm$1.64,72.37$\pm$3.27,NaN
lbgrl sbm+deg,74.46$\pm$1.91,72.11$\pm$3.06,NaN
lbgrl sbm+raa,79.56$\pm$1.16,75.82$\pm$2.68,NaN
lbgrl scom,NaN,NaN,71.21$\pm$3.43
lbgrl random+scom,NaN,NaN,71.48$\pm$4.54
lbgrl random+deg,NaN,NaN,72.36$\pm$4.5
lbgrl deg+scom,NaN,NaN,73.18$\pm$3.05

In [ ]:
names = ['struct_cora', 'struct_citeseer', 'struct_pubmed', 'struct_computers', 'struct_photo', 'csstruct_']
datasets = [
'FINAL_struct_cora_res.csv',
'FINAL_struct_citeseer_res.csv',
'FINAL_struct_pubmed_res.csv',
'FINAL_struct_computers_res.csv',
'FINAL_struct_photo_res.csv',
'FINAL_struct_cs_res.csv']