In [2]:
import utils as ut

In [3]:
# BGRL
names = ['FINAL_netscience_res.csv',
'FINAL_power_res.csv',
'FINAL_euroroad_res.csv',
'FINAL_yeast_res.csv',
'FINAL_crime_res.csv',
'FINAL_cora_res.csv',
'FINAL_citeseer_res.csv',
'FINAL_pubmed_res.csv',
'FINAL_computers_res.csv',
'FINAL_photo_res.csv',
'FINAL_cs_res.csv',
'FINAL_struct_cora_res.csv',
'FINAL_struct_citeseer_res.csv',
'FINAL_struct_pubmed_res.csv',
'FINAL_struct_computers_res.csv',
'FINAL_struct_photo_res.csv',
'FINAL_struct_cs_res.csv']

all_data, all_res = ut.mix_dataset(names, 'Hits@50', ['bgrl'])
res = ut.tex_table(all_data, all_res)
print(res.to_latex(
        index=True, formatters={"name": str.upper}, float_format="{:.1f}".format
    ))

\resizebox{\textwidth}{!}{
\begin{tabular}{llllllllllllllllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_pubmed_res.csv & FINAL_computers_res.csv & FINAL_photo_res.csv & FINAL_cs_res.csv & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv & FINAL_struct_pubmed_res.csv & FINAL_struct_computers_res.csv & FINAL_struct_photo_res.csv & FINAL_struct_cs_res.csv \\
\midrule
bgrl random & \color{blue}{85.18$\pm$1.28 $\bigstar$} & 29.6$\pm$0.96 & 27.31$\pm$3.89 X & 93.78$\pm$0.54 & \color{blue}{23.73$\pm$2.21 $\bigstar$} & 73.58$\pm$1.44 X & 74.08$\pm$1.06 $\bigstar$ & 61.81$\pm$1.76 X & 18.71$\pm$7.7 X & 35.99$\pm$11.71 X & \color{red}{64.42$\pm$4.93 $\bigstar$} & 50.93$\pm$1.72 X & 49.63$\pm$1.87 X & 38.29$\pm$0.88 & 30.52$\pm$3.62 $\bigstar$ & \color{blue}{46.35$\pm$3.91 $\bigstar$} & \color{violet}{65.79$\pm$0.96 $\bigstar$} \\
bgrl deg & \color{red}{86.95$\pm$2.33 $\bigstar$} & \color{red}{31.79$\pm$1.73 $\bigstar$} & \color{red}{38.94$\pm$9.26 $\bigstar$} & \color{violet}{94.26$\pm$0.48 $\bigstar$} & \color{violet}{22.85$\pm$3.54 $\bigstar$} & \color{blue}{77.49$\pm$1.21 $\bigstar$} & \color{violet}{76.19$\pm$5.97} & 61.91$\pm$2.07 X & 21.22$\pm$5.95 $\bigstar$ & \color{violet}{39.23$\pm$10.85 $\bigstar$} & 51.73$\pm$14.51 X & \color{red}{62.03$\pm$1.35 $\bigstar$} & \color{red}{52.49$\pm$1.95 $\bigstar$} & \color{blue}{44.51$\pm$6.33 $\bigstar$} & \color{blue}{31.39$\pm$4.16 $\bigstar$} & \color{red}{47.78$\pm$2.91 $\bigstar$} & 63.34$\pm$2.88 \\
bgrl pr & 83.58$\pm$1.23 X & 27.75$\pm$1.17 X & 23.39$\pm$2.68 X & 94.0$\pm$0.38 $\bigstar$ & 17.86$\pm$2.27 X & 77.46$\pm$1.43 $\bigstar$ & 71.93$\pm$1.4 X & 62.32$\pm$2.03 $\bigstar$ & \color{blue}{22.47$\pm$5.24 $\bigstar$} & 35.51$\pm$10.72 X & \color{violet}{62.37$\pm$10.33 $\bigstar$} & 50.03$\pm$1.36 X & 49.29$\pm$1.51 X & 35.37$\pm$1.12 X & \color{red}{31.72$\pm$1.92 $\bigstar$} & 45.63$\pm$4.02 $\bigstar$ & \color{red}{66.57$\pm$1.2 $\bigstar$} \\
bgrl evc & 84.25$\pm$1.55 & 29.49$\pm$1.11 & \color{blue}{38.27$\pm$8.41 $\bigstar$} & 93.69$\pm$0.44 X & 22.1$\pm$6.04 & 77.0$\pm$1.73 & 73.31$\pm$1.27 & 62.08$\pm$2.65 $\bigstar$ & 20.88$\pm$7.76 $\bigstar$ & \color{blue}{41.13$\pm$3.45 $\bigstar$} & \color{blue}{62.42$\pm$11.47 $\bigstar$} & 50.55$\pm$1.41 X & 50.13$\pm$1.61 X & \color{red}{48.28$\pm$1.45 $\bigstar$} & \color{violet}{30.61$\pm$2.54 $\bigstar$} & 43.71$\pm$2.5 X & 54.05$\pm$11.79 X \\
bgrl scom & 84.69$\pm$1.39 & \color{violet}{29.92$\pm$1.16} & 28.13$\pm$2.69 X & 93.46$\pm$0.56 X & 20.51$\pm$3.5 & 73.79$\pm$1.91 X & 74.79$\pm$1.18 $\bigstar$ & \color{blue}{62.99$\pm$2.6 $\bigstar$} & 16.13$\pm$9.73 $\bigstar$ & 38.38$\pm$4.96 X & 58.24$\pm$8.68 X & 51.88$\pm$1.51 & 49.34$\pm$1.86 X & 36.65$\pm$1.17 X & 28.24$\pm$2.71 X & 44.4$\pm$4.1 $\bigstar$ & 65.34$\pm$1.58 \\
bgrl random+scom & 84.84$\pm$1.56 & 29.77$\pm$1.38 & 28.37$\pm$2.86 & 93.33$\pm$0.65 X & \color{red}{24.95$\pm$3.63 $\bigstar$} & 73.31$\pm$1.8 X & 74.53$\pm$0.64 $\bigstar$ & \color{violet}{62.7$\pm$2.43 $\bigstar$} & \color{red}{22.93$\pm$3.07 $\bigstar$} & 36.14$\pm$9.57 X & 60.88$\pm$12.16 $\bigstar$ & 51.48$\pm$1.8 X & 49.91$\pm$1.78 X & 39.46$\pm$0.8 & 26.92$\pm$3.29 X & 42.51$\pm$2.58 X & \color{blue}{66.11$\pm$1.23 $\bigstar$} \\
bgrl random+deg & \color{violet}{84.89$\pm$1.64} & \color{blue}{30.33$\pm$0.85 $\bigstar$} & \color{violet}{34.88$\pm$3.01 $\bigstar$} & \color{blue}{94.36$\pm$0.6 $\bigstar$} & 18.78$\pm$4.59 & \color{red}{77.88$\pm$1.69 $\bigstar$} & \color{blue}{76.51$\pm$5.06 $\bigstar$} & \color{red}{63.51$\pm$2.83 $\bigstar$} & 15.43$\pm$10.14 X & 38.49$\pm$8.2 X & 58.96$\pm$13.69 $\bigstar$ & \color{blue}{61.72$\pm$1.32 $\bigstar$} & \color{blue}{52.09$\pm$1.63 $\bigstar$} & \color{violet}{43.75$\pm$4.08 $\bigstar$} & 28.97$\pm$4.76 & \color{violet}{46.24$\pm$4.32 $\bigstar$} & 63.73$\pm$4.61 \\
bgrl deg+scom & 84.43$\pm$1.56 & 29.86$\pm$1.42 & 32.08$\pm$3.74 & \color{red}{94.37$\pm$0.5 $\bigstar$} & 17.12$\pm$3.17 X & \color{violet}{77.49$\pm$1.84 $\bigstar$} & \color{red}{76.74$\pm$3.92 $\bigstar$} & 62.29$\pm$1.71 $\bigstar$ & \color{violet}{22.43$\pm$7.75 $\bigstar$} & \color{red}{41.42$\pm$2.87 $\bigstar$} & 60.95$\pm$14.29 $\bigstar$ & \color{violet}{60.79$\pm$1.06 $\bigstar$} & \color{violet}{51.14$\pm$1.57 $\bigstar$} & 43.69$\pm$4.71 & 26.95$\pm$6.21 & 43.01$\pm$8.21 X & 64.95$\pm$1.05 \\
\bottomrule
\end{tabular}

}
\begin{tabular}{lllllllll}
\toprule
 & bgrl random & bgrl deg & bgrl pr & bgrl evc & bgrl scom & bgrl random+scom & bgrl random+deg & bgrl deg+scom \\
\midrule
FINAL_netscience_res.csv & \color{blue}{85.18$\pm$1.28 $\bigstar$} & \color{red}{86.95$\pm$2.33 $\bigstar$} & 83.58$\pm$1.23 X & 84.25$\pm$1.55 & 84.69$\pm$1.39 & 84.84$\pm$1.56 & \color{violet}{84.89$\pm$1.64} & 84.43$\pm$1.56 \\
FINAL_power_res.csv & 29.6$\pm$0.96 & \color{red}{31.79$\pm$1.73 $\bigstar$} & 27.75$\pm$1.17 X & 29.49$\pm$1.11 & \color{violet}{29.92$\pm$1.16} & 29.77$\pm$1.38 & \color{blue}{30.33$\pm$0.85 $\bigstar$} & 29.86$\pm$1.42 \\
FINAL_euroroad_res.csv & 27.31$\pm$3.89 X & \color{red}{38.94$\pm$9.26 $\bigstar$} & 23.39$\pm$2.68 X & \color{blue}{38.27$\pm$8.41 $\bigstar$} & 28.13$\pm$2.69 X & 28.37$\pm$2.86 & \color{violet}{34.88$\pm$3.01 $\bigstar$} & 32.08$\pm$3.74 \\
FINAL_yeast_res.csv & 93.78$\pm$0.54 & \color{violet}{94.26$\pm$0.48 $\bigstar$} & 94.0$\pm$0.38 $\bigstar$ & 93.69$\pm$0.44 X & 93.46$\pm$0.56 X & 93.33$\pm$0.65 X & \color{blue}{94.36$\pm$0.6 $\bigstar$} & \color{red}{94.37$\pm$0.5 $\bigstar$} \\
FINAL_crime_res.csv & \color{blue}{23.73$\pm$2.21 $\bigstar$} & \color{violet}{22.85$\pm$3.54 $\bigstar$} & 17.86$\pm$2.27 X & 22.1$\pm$6.04 & 20.51$\pm$3.5 & \color{red}{24.95$\pm$3.63 $\bigstar$} & 18.78$\pm$4.59 & 17.12$\pm$3.17 X \\
FINAL_cora_res.csv & 73.58$\pm$1.44 X & \color{blue}{77.49$\pm$1.21 $\bigstar$} & 77.46$\pm$1.43 $\bigstar$ & 77.0$\pm$1.73 & 73.79$\pm$1.91 X & 73.31$\pm$1.8 X & \color{red}{77.88$\pm$1.69 $\bigstar$} & \color{violet}{77.49$\pm$1.84 $\bigstar$} \\
FINAL_citeseer_res.csv & 74.08$\pm$1.06 $\bigstar$ & \color{violet}{76.19$\pm$5.97} & 71.93$\pm$1.4 X & 73.31$\pm$1.27 & 74.79$\pm$1.18 $\bigstar$ & 74.53$\pm$0.64 $\bigstar$ & \color{blue}{76.51$\pm$5.06 $\bigstar$} & \color{red}{76.74$\pm$3.92 $\bigstar$} \\
FINAL_pubmed_res.csv & 61.81$\pm$1.76 X & 61.91$\pm$2.07 X & 62.32$\pm$2.03 $\bigstar$ & 62.08$\pm$2.65 $\bigstar$ & \color{blue}{62.99$\pm$2.6 $\bigstar$} & \color{violet}{62.7$\pm$2.43 $\bigstar$} & \color{red}{63.51$\pm$2.83 $\bigstar$} & 62.29$\pm$1.71 $\bigstar$ \\
FINAL_computers_res.csv & 18.71$\pm$7.7 X & 21.22$\pm$5.95 $\bigstar$ & \color{blue}{22.47$\pm$5.24 $\bigstar$} & 20.88$\pm$7.76 $\bigstar$ & 16.13$\pm$9.73 $\bigstar$ & \color{red}{22.93$\pm$3.07 $\bigstar$} & 15.43$\pm$10.14 X & \color{violet}{22.43$\pm$7.75 $\bigstar$} \\
FINAL_photo_res.csv & 35.99$\pm$11.71 X & \color{violet}{39.23$\pm$10.85 $\bigstar$} & 35.51$\pm$10.72 X & \color{blue}{41.13$\pm$3.45 $\bigstar$} & 38.38$\pm$4.96 X & 36.14$\pm$9.57 X & 38.49$\pm$8.2 X & \color{red}{41.42$\pm$2.87 $\bigstar$} \\
FINAL_cs_res.csv & \color{red}{64.42$\pm$4.93 $\bigstar$} & 51.73$\pm$14.51 X & \color{violet}{62.37$\pm$10.33 $\bigstar$} & \color{blue}{62.42$\pm$11.47 $\bigstar$} & 58.24$\pm$8.68 X & 60.88$\pm$12.16 $\bigstar$ & 58.96$\pm$13.69 $\bigstar$ & 60.95$\pm$14.29 $\bigstar$ \\
FINAL_struct_cora_res.csv & 50.93$\pm$1.72 X & \color{red}{62.03$\pm$1.35 $\bigstar$} & 50.03$\pm$1.36 X & 50.55$\pm$1.41 X & 51.88$\pm$1.51 & 51.48$\pm$1.8 X & \color{blue}{61.72$\pm$1.32 $\bigstar$} & \color{violet}{60.79$\pm$1.06 $\bigstar$} \\
FINAL_struct_citeseer_res.csv & 49.63$\pm$1.87 X & \color{red}{52.49$\pm$1.95 $\bigstar$} & 49.29$\pm$1.51 X & 50.13$\pm$1.61 X & 49.34$\pm$1.86 X & 49.91$\pm$1.78 X & \color{blue}{52.09$\pm$1.63 $\bigstar$} & \color{violet}{51.14$\pm$1.57 $\bigstar$} \\
FINAL_struct_pubmed_res.csv & 38.29$\pm$0.88 & \color{blue}{44.51$\pm$6.33 $\bigstar$} & 35.37$\pm$1.12 X & \color{red}{48.28$\pm$1.45 $\bigstar$} & 36.65$\pm$1.17 X & 39.46$\pm$0.8 & \color{violet}{43.75$\pm$4.08 $\bigstar$} & 43.69$\pm$4.71 \\
FINAL_struct_computers_res.csv & 30.52$\pm$3.62 $\bigstar$ & \color{blue}{31.39$\pm$4.16 $\bigstar$} & \color{red}{31.72$\pm$1.92 $\bigstar$} & \color{violet}{30.61$\pm$2.54 $\bigstar$} & 28.24$\pm$2.71 X & 26.92$\pm$3.29 X & 28.97$\pm$4.76 & 26.95$\pm$6.21 \\
FINAL_struct_photo_res.csv & \color{blue}{46.35$\pm$3.91 $\bigstar$} & \color{red}{47.78$\pm$2.91 $\bigstar$} & 45.63$\pm$4.02 $\bigstar$ & 43.71$\pm$2.5 X & 44.4$\pm$4.1 $\bigstar$ & 42.51$\pm$2.58 X & \color{violet}{46.24$\pm$4.32 $\bigstar$} & 43.01$\pm$8.21 X \\
FINAL_struct_cs_res.csv & \color{violet}{65.79$\pm$0.96 $\bigstar$} & 63.34$\pm$2.88 & \color{red}{66.57$\pm$1.2 $\bigstar$} & 54.05$\pm$11.79 X & 65.34$\pm$1.58 & \color{blue}{66.11$\pm$1.23 $\bigstar$} & 63.73$\pm$4.61 & 64.95$\pm$1.05 \\
\bottomrule
\end{tabular}

In [10]:
# full comparatif non attr
names = ['FINAL_netscience_res.csv',
'FINAL_power_res.csv',
'FINAL_euroroad_res.csv',
'FINAL_yeast_res.csv',
'FINAL_crime_res.csv']
filtres = ['baseline','grace','bgrl']
print("                             ROCAUC                      ")
all_data, all_res = ut.mix_dataset(names, 'ROCAUC', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             AP                      ")
all_data, all_res = ut.mix_dataset(names, 'AP', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@100                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@100', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@20                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@20', filtres)
display(ut.tex_table(all_data, all_res).T)

                             ROCAUC
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv \\
\midrule
baseline & 92.69$\pm$0.91 & 67.61$\pm$1.0 & 64.32$\pm$1.25 & 97.05$\pm$0.24 & \color{red}{53.34$\pm$2.52 $\bigstar$} \\
grace random & 90.16$\pm$0.97 & 66.42$\pm$0.96 & 62.79$\pm$2.3 & 96.6$\pm$0.27 & 43.18$\pm$2.55 \\
grace deg & \color{blue}{94.17$\pm$1.89 $\bigstar$} & \color{red}{74.12$\pm$3.67 $\bigstar$} & \color{red}{68.43$\pm$6.66 $\bigstar$} & \color{violet}{97.75$\pm$0.64 $\bigstar$} & 47.49$\pm$4.77 \\
grace pr & 88.97$\pm$1.07 & 66.27$\pm$1.27 & \color{violet}{65.6$\pm$4.3} & 97.65$\pm$0.6 $\bigstar$ & 40.68$\pm$2.21 X \\
grace evc & 90.46$\pm$0.98 & 64.8$\pm$0.53 & \color{blue}{66.5$\pm$5.73} & 96.95$\pm$0.22 & 49.25$\pm$7.52 \\
grace scom & 91.7$\pm$1.28 & 67.56$\pm$2.16 & 62.73$\pm$3.11 & 97.07$\pm$0.37 & 46.54$\pm$5.69 \\
grace random+scom & 90.47$\pm$1.02 & 66.42$\pm$1.05 & 61.95$\pm$0.75 & 96.7$\pm$0.16 & 42.72$\pm$1.8 \\
grace random+deg & \color{violet}{93.47$\pm$2.05 $\bigstar$} & 67.5$\pm$2.31 & 64.3$\pm$2.49 & \color{red}{97.82$\pm$0.64 $\bigstar$} & 42.94$\pm$2.27 \\
grace deg+scom & 93.2$\pm$1.58 & \color{violet}{68.84$\pm$1.59} & 63.72$\pm$3.22 & \color{blue}{97.77$\pm$0.67 $\bigstar$} & 42.96$\pm$2.04 \\
bgrl random & 90.03$\pm$1.09 & 60.74$\pm$1.12 & 52.04$\pm$2.67 & 96.04$\pm$0.25 & 48.56$\pm$2.36 \\
bgrl deg & \color{red}{94.36$\pm$2.52 $\bigstar$} & \color{blue}{69.37$\pm$6.0} & 65.33$\pm$8.35 & 97.65$\pm$0.87 & \color{blue}{52.09$\pm$6.96} \\
bgrl pr & 87.09$\pm$1.22 X & 55.52$\pm$2.32 X & 48.23$\pm$2.62 X & 95.81$\pm$0.25 X & 41.75$\pm$3.38 \\
bgrl evc & 88.93$\pm$0.98 X & 56.23$\pm$1.31 X & 65.45$\pm$8.07 & 96.3$\pm$0.29 & \color{violet}{49.74$\pm$9.49} \\
bgrl scom & 90.2$\pm$1.26 & 60.16$\pm$3.2 & 52.62$\pm$3.33 X & 96.04$\pm$0.18 & 45.74$\pm$5.23 \\
bgrl random+scom & 89.78$\pm$0.82 & 60.45$\pm$1.31 & 53.27$\pm$2.82 & 95.74$\pm$0.24 X & 49.06$\pm$2.4 \\
bgrl random+deg & 91.58$\pm$1.16 & 62.33$\pm$1.98 & 61.98$\pm$3.71 & 96.84$\pm$0.56 & 45.03$\pm$5.07 \\
bgrl deg+scom & 91.06$\pm$1.37 & 61.09$\pm$1.58 & 59.14$\pm$3.5 & 96.71$\pm$0.46 & 40.49$\pm$3.58 X \\
\bottomrule
\end{tabular}

}

,FINAL_netscience_res.csv,FINAL_power_res.csv,FINAL_euroroad_res.csv,FINAL_yeast_res.csv,FINAL_crime_res.csv
baseline,92.69$\pm$0.91,67.61$\pm$1.0,64.32$\pm$1.25,97.05$\pm$0.24,\color{red}{53.34$\pm$2.52 $\bigstar$}
grace random,90.16$\pm$0.97,66.42$\pm$0.96,62.79$\pm$2.3,96.6$\pm$0.27,43.18$\pm$2.55
grace deg,\color{blue}{94.17$\pm$1.89 $\bigstar$},\color{red}{74.12$\pm$3.67 $\bigstar$},\color{red}{68.43$\pm$6.66 $\bigstar$},\color{violet}{97.75$\pm$0.64 $\bigstar$},47.49$\pm$4.77
grace pr,88.97$\pm$1.07,66.27$\pm$1.27,\color{violet}{65.6$\pm$4.3},97.65$\pm$0.6 $\bigstar$,40.68$\pm$2.21 X
grace evc,90.46$\pm$0.98,64.8$\pm$0.53,\color{blue}{66.5$\pm$5.73},96.95$\pm$0.22,49.25$\pm$7.52
grace scom,91.7$\pm$1.28,67.56$\pm$2.16,62.73$\pm$3.11,97.07$\pm$0.37,46.54$\pm$5.69
grace random+scom,90.47$\pm$1.02,66.42$\pm$1.05,61.95$\pm$0.75,96.7$\pm$0.16,42.72$\pm$1.8
grace random+deg,\color{violet}{93.47$\pm$2.05 $\bigstar$},67.5$\pm$2.31,64.3$\pm$2.49,\color{red}{97.82$\pm$0.64 $\bigstar$},42.94$\pm$2.27
grace deg+scom,93.2$\pm$1.58,\color{violet}{68.84$\pm$1.59},63.72$\pm$3.22,\color{blue}{97.77$\pm$0.67 $\bigstar$},42.96$\pm$2.04
bgrl random,90.03$\pm$1.09,60.74$\pm$1.12,52.04$\pm$2.67,96.04$\pm$0.25,48.56$\pm$2.36
bgrl deg,\color{red}{94.36$\pm$2.52 $\bigstar$},\color{blue}{69.37$\pm$6.0},65.33$\pm$8.35,97.65$\pm$0.87,\color{blue}{52.09$\pm$6.96}
bgrl pr,87.09$\pm$1.22 X,55.52$\pm$2.32 X,48.23$\pm$2.62 X,95.81$\pm$0.25 X,41.75$\pm$3.38
bgrl evc,88.93$\pm$0.98 X,56.23$\pm$1.31 X,65.45$\pm$8.07,96.3$\pm$0.29,\color{violet}{49.74$\pm$9.49}
bgrl scom,90.2$\pm$1.26,60.16$\pm$3.2,52.62$\pm$3.33 X,96.04$\pm$0.18,45.74$\pm$5.23
bgrl random+scom,89.78$\pm$0.82,60.45$\pm$1.31,53.27$\pm$2.82,95.74$\pm$0.24 X,49.06$\pm$2.4
bgrl random+deg,91.58$\pm$1.16,62.33$\pm$1.98,61.98$\pm$3.71,96.84$\pm$0.56,45.03$\pm$5.07
bgrl deg+scom,91.06$\pm$1.37,61.09$\pm$1.58,59.14$\pm$3.5,96.71$\pm$0.46,40.49$\pm$3.58 X

                             AP
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv \\
\midrule
baseline & 94.93$\pm$0.59 $\bigstar$ & 73.85$\pm$0.66 & 66.62$\pm$1.44 & 98.01$\pm$0.13 & \color{red}{57.66$\pm$1.55 $\bigstar$} \\
grace random & 93.77$\pm$0.6 & 73.93$\pm$0.9 & 67.16$\pm$1.87 & 97.87$\pm$0.15 & 52.37$\pm$1.75 \\
grace deg & \color{blue}{95.4$\pm$0.96 $\bigstar$} & \color{red}{78.17$\pm$1.95 $\bigstar$} & \color{red}{70.25$\pm$4.52 $\bigstar$} & 98.31$\pm$0.34 $\bigstar$ & 54.96$\pm$2.94 \\
grace pr & 93.21$\pm$0.75 X & 73.93$\pm$0.89 & \color{blue}{68.79$\pm$2.9 $\bigstar$} & \color{blue}{98.41$\pm$0.31 $\bigstar$} & 50.84$\pm$1.48 X \\
grace evc & 93.93$\pm$0.6 & 73.29$\pm$0.74 & \color{violet}{68.53$\pm$3.95 $\bigstar$} & 97.98$\pm$0.16 & 55.34$\pm$4.33 \\
grace scom & 94.47$\pm$0.72 & 74.47$\pm$1.08 & 66.61$\pm$1.79 & 98.07$\pm$0.19 & 53.75$\pm$3.18 \\
grace random+scom & 93.93$\pm$0.59 & 74.0$\pm$0.85 & 66.35$\pm$1.12 & 97.9$\pm$0.09 & 51.64$\pm$1.54 \\
grace random+deg & \color{violet}{95.19$\pm$0.95} & 73.87$\pm$1.34 & 67.95$\pm$2.45 & \color{red}{98.46$\pm$0.32 $\bigstar$} & 52.7$\pm$1.5 \\
grace deg+scom & 95.13$\pm$0.84 & \color{blue}{75.03$\pm$1.09} & 67.88$\pm$2.67 & 98.39$\pm$0.37 $\bigstar$ & 52.24$\pm$1.46 \\
bgrl random & 94.02$\pm$0.6 & 69.73$\pm$0.8 & 58.79$\pm$3.18 X & 97.61$\pm$0.15 & 55.98$\pm$1.79 $\bigstar$ \\
bgrl deg & \color{red}{95.99$\pm$1.33 $\bigstar$} & \color{violet}{74.75$\pm$3.56} & 67.66$\pm$5.98 & \color{violet}{98.4$\pm$0.43 $\bigstar$} & \color{blue}{57.01$\pm$4.33 $\bigstar$} \\
bgrl pr & 92.53$\pm$0.65 X & 66.6$\pm$1.36 X & 56.04$\pm$1.79 X & 97.57$\pm$0.11 & 50.75$\pm$2.2 X \\
bgrl evc & 93.42$\pm$0.58 X & 67.3$\pm$0.91 X & 67.39$\pm$5.44 & 97.71$\pm$0.14 & 55.85$\pm$5.77 \\
bgrl scom & 93.97$\pm$0.71 & 69.29$\pm$1.89 & 58.72$\pm$2.67 X & 97.57$\pm$0.1 & 53.57$\pm$3.2 \\
bgrl random+scom & 93.86$\pm$0.53 & 69.61$\pm$0.97 & 59.78$\pm$2.37 & 97.43$\pm$0.13 X & \color{violet}{56.72$\pm$2.55 $\bigstar$} \\
bgrl random+deg & 94.59$\pm$0.7 & 70.77$\pm$1.15 & 65.49$\pm$2.77 & 98.02$\pm$0.28 & 53.14$\pm$3.64 \\
bgrl deg+scom & 94.28$\pm$0.74 & 69.91$\pm$1.22 & 63.41$\pm$2.77 & 97.97$\pm$0.23 & 50.39$\pm$2.3 X \\
\bottomrule
\end{tabular}

}

,FINAL_netscience_res.csv,FINAL_power_res.csv,FINAL_euroroad_res.csv,FINAL_yeast_res.csv,FINAL_crime_res.csv
baseline,94.93$\pm$0.59 $\bigstar$,73.85$\pm$0.66,66.62$\pm$1.44,98.01$\pm$0.13,\color{red}{57.66$\pm$1.55 $\bigstar$}
grace random,93.77$\pm$0.6,73.93$\pm$0.9,67.16$\pm$1.87,97.87$\pm$0.15,52.37$\pm$1.75
grace deg,\color{blue}{95.4$\pm$0.96 $\bigstar$},\color{red}{78.17$\pm$1.95 $\bigstar$},\color{red}{70.25$\pm$4.52 $\bigstar$},98.31$\pm$0.34 $\bigstar$,54.96$\pm$2.94
grace pr,93.21$\pm$0.75 X,73.93$\pm$0.89,\color{blue}{68.79$\pm$2.9 $\bigstar$},\color{blue}{98.41$\pm$0.31 $\bigstar$},50.84$\pm$1.48 X
grace evc,93.93$\pm$0.6,73.29$\pm$0.74,\color{violet}{68.53$\pm$3.95 $\bigstar$},97.98$\pm$0.16,55.34$\pm$4.33
grace scom,94.47$\pm$0.72,74.47$\pm$1.08,66.61$\pm$1.79,98.07$\pm$0.19,53.75$\pm$3.18
grace random+scom,93.93$\pm$0.59,74.0$\pm$0.85,66.35$\pm$1.12,97.9$\pm$0.09,51.64$\pm$1.54
grace random+deg,\color{violet}{95.19$\pm$0.95},73.87$\pm$1.34,67.95$\pm$2.45,\color{red}{98.46$\pm$0.32 $\bigstar$},52.7$\pm$1.5
grace deg+scom,95.13$\pm$0.84,\color{blue}{75.03$\pm$1.09},67.88$\pm$2.67,98.39$\pm$0.37 $\bigstar$,52.24$\pm$1.46
bgrl random,94.02$\pm$0.6,69.73$\pm$0.8,58.79$\pm$3.18 X,97.61$\pm$0.15,55.98$\pm$1.79 $\bigstar$
bgrl deg,\color{red}{95.99$\pm$1.33 $\bigstar$},\color{violet}{74.75$\pm$3.56},67.66$\pm$5.98,\color{violet}{98.4$\pm$0.43 $\bigstar$},\color{blue}{57.01$\pm$4.33 $\bigstar$}
bgrl pr,92.53$\pm$0.65 X,66.6$\pm$1.36 X,56.04$\pm$1.79 X,97.57$\pm$0.11,50.75$\pm$2.2 X
bgrl evc,93.42$\pm$0.58 X,67.3$\pm$0.91 X,67.39$\pm$5.44,97.71$\pm$0.14,55.85$\pm$5.77
bgrl scom,93.97$\pm$0.71,69.29$\pm$1.89,58.72$\pm$2.67 X,97.57$\pm$0.1,53.57$\pm$3.2
bgrl random+scom,93.86$\pm$0.53,69.61$\pm$0.97,59.78$\pm$2.37,97.43$\pm$0.13 X,\color{violet}{56.72$\pm$2.55 $\bigstar$}
bgrl random+deg,94.59$\pm$0.7,70.77$\pm$1.15,65.49$\pm$2.77,98.02$\pm$0.28,53.14$\pm$3.64
bgrl deg+scom,94.28$\pm$0.74,69.91$\pm$1.22,63.41$\pm$2.77,97.97$\pm$0.23,50.39$\pm$2.3 X

                             Hits@100
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv \\
\midrule
baseline & 87.55$\pm$1.47 & 36.84$\pm$1.22 & 55.09$\pm$2.31 & 94.55$\pm$0.29 & \color{red}{38.78$\pm$3.36 $\bigstar$} \\
grace random & 85.31$\pm$1.41 & 39.4$\pm$1.39 & 51.84$\pm$3.9 & 94.61$\pm$0.26 & 27.12$\pm$3.32 \\
grace deg & \color{red}{91.26$\pm$3.25 $\bigstar$} & \color{red}{42.11$\pm$1.53 $\bigstar$} & \color{red}{61.59$\pm$9.64 $\bigstar$} & 94.45$\pm$0.36 & 32.37$\pm$5.53 \\
grace pr & 84.73$\pm$1.5 X & 39.77$\pm$1.33 & 56.71$\pm$6.92 & \color{blue}{94.9$\pm$0.29 $\bigstar$} & 25.36$\pm$3.11 X \\
grace evc & 85.33$\pm$1.49 & 39.88$\pm$1.2 & \color{blue}{59.15$\pm$8.87 $\bigstar$} & 94.63$\pm$0.3 & 34.98$\pm$10.47 \\
grace scom & 85.82$\pm$1.64 & 39.39$\pm$0.97 & 51.48$\pm$4.92 & 94.66$\pm$0.3 & 29.83$\pm$6.19 \\
grace random+scom & 85.29$\pm$1.17 & 39.89$\pm$1.09 & 50.11$\pm$2.39 & 94.6$\pm$0.31 & 25.73$\pm$2.91 X \\
grace random+deg & \color{violet}{89.64$\pm$3.05 $\bigstar$} & \color{violet}{40.83$\pm$1.06 $\bigstar$} & 54.49$\pm$5.37 & \color{red}{94.94$\pm$0.52 $\bigstar$} & 27.53$\pm$1.42 \\
grace deg+scom & 89.22$\pm$2.16 $\bigstar$ & \color{blue}{41.18$\pm$1.42 $\bigstar$} & 54.77$\pm$5.11 & \color{violet}{94.84$\pm$0.45 $\bigstar$} & 27.36$\pm$3.17 \\
bgrl random & 86.31$\pm$1.26 & 33.03$\pm$0.87 & 40.21$\pm$3.37 X & 94.16$\pm$0.4 & 34.81$\pm$2.19 \\
bgrl deg & \color{blue}{89.89$\pm$2.88 $\bigstar$} & 36.43$\pm$2.34 & \color{violet}{58.34$\pm$11.86} & 94.7$\pm$0.51 & \color{blue}{38.2$\pm$6.85 $\bigstar$} \\
bgrl pr & 84.25$\pm$1.28 X & 30.64$\pm$1.65 X & 36.25$\pm$4.74 X & 94.32$\pm$0.35 & 28.78$\pm$3.25 \\
bgrl evc & 85.22$\pm$1.22 & 32.19$\pm$1.05 X & 58.06$\pm$10.85 & 94.24$\pm$0.4 & \color{violet}{37.56$\pm$9.88} \\
bgrl scom & 85.75$\pm$1.31 & 32.7$\pm$1.49 & 40.71$\pm$3.81 X & 94.11$\pm$0.42 & 32.34$\pm$5.07 \\
bgrl random+scom & 85.71$\pm$1.47 & 33.07$\pm$1.1 & 40.71$\pm$3.31 X & 93.84$\pm$0.51 X & 35.97$\pm$1.93 $\bigstar$ \\
bgrl random+deg & 86.5$\pm$1.54 & 33.91$\pm$0.99 & 51.8$\pm$4.39 & 94.59$\pm$0.51 & 29.39$\pm$6.35 \\
bgrl deg+scom & 85.6$\pm$1.42 & 33.08$\pm$1.79 & 47.53$\pm$3.86 & 94.63$\pm$0.39 & 25.56$\pm$4.88 X \\
\bottomrule
\end{tabular}

}

,FINAL_netscience_res.csv,FINAL_power_res.csv,FINAL_euroroad_res.csv,FINAL_yeast_res.csv,FINAL_crime_res.csv
baseline,87.55$\pm$1.47,36.84$\pm$1.22,55.09$\pm$2.31,94.55$\pm$0.29,\color{red}{38.78$\pm$3.36 $\bigstar$}
grace random,85.31$\pm$1.41,39.4$\pm$1.39,51.84$\pm$3.9,94.61$\pm$0.26,27.12$\pm$3.32
grace deg,\color{red}{91.26$\pm$3.25 $\bigstar$},\color{red}{42.11$\pm$1.53 $\bigstar$},\color{red}{61.59$\pm$9.64 $\bigstar$},94.45$\pm$0.36,32.37$\pm$5.53
grace pr,84.73$\pm$1.5 X,39.77$\pm$1.33,56.71$\pm$6.92,\color{blue}{94.9$\pm$0.29 $\bigstar$},25.36$\pm$3.11 X
grace evc,85.33$\pm$1.49,39.88$\pm$1.2,\color{blue}{59.15$\pm$8.87 $\bigstar$},94.63$\pm$0.3,34.98$\pm$10.47
grace scom,85.82$\pm$1.64,39.39$\pm$0.97,51.48$\pm$4.92,94.66$\pm$0.3,29.83$\pm$6.19
grace random+scom,85.29$\pm$1.17,39.89$\pm$1.09,50.11$\pm$2.39,94.6$\pm$0.31,25.73$\pm$2.91 X
grace random+deg,\color{violet}{89.64$\pm$3.05 $\bigstar$},\color{violet}{40.83$\pm$1.06 $\bigstar$},54.49$\pm$5.37,\color{red}{94.94$\pm$0.52 $\bigstar$},27.53$\pm$1.42
grace deg+scom,89.22$\pm$2.16 $\bigstar$,\color{blue}{41.18$\pm$1.42 $\bigstar$},54.77$\pm$5.11,\color{violet}{94.84$\pm$0.45 $\bigstar$},27.36$\pm$3.17
bgrl random,86.31$\pm$1.26,33.03$\pm$0.87,40.21$\pm$3.37 X,94.16$\pm$0.4,34.81$\pm$2.19
bgrl deg,\color{blue}{89.89$\pm$2.88 $\bigstar$},36.43$\pm$2.34,\color{violet}{58.34$\pm$11.86},94.7$\pm$0.51,\color{blue}{38.2$\pm$6.85 $\bigstar$}
bgrl pr,84.25$\pm$1.28 X,30.64$\pm$1.65 X,36.25$\pm$4.74 X,94.32$\pm$0.35,28.78$\pm$3.25
bgrl evc,85.22$\pm$1.22,32.19$\pm$1.05 X,58.06$\pm$10.85,94.24$\pm$0.4,\color{violet}{37.56$\pm$9.88}
bgrl scom,85.75$\pm$1.31,32.7$\pm$1.49,40.71$\pm$3.81 X,94.11$\pm$0.42,32.34$\pm$5.07
bgrl random+scom,85.71$\pm$1.47,33.07$\pm$1.1,40.71$\pm$3.31 X,93.84$\pm$0.51 X,35.97$\pm$1.93 $\bigstar$
bgrl random+deg,86.5$\pm$1.54,33.91$\pm$0.99,51.8$\pm$4.39,94.59$\pm$0.51,29.39$\pm$6.35
bgrl deg+scom,85.6$\pm$1.42,33.08$\pm$1.79,47.53$\pm$3.86,94.63$\pm$0.39,25.56$\pm$4.88 X

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv \\
\midrule
baseline & 85.18$\pm$1.85 & 32.24$\pm$0.75 & 36.71$\pm$3.26 & 93.98$\pm$0.55 & \color{violet}{23.02$\pm$2.9 $\bigstar$} \\
grace random & 84.34$\pm$1.29 & 36.05$\pm$1.17 & 37.42$\pm$2.96 & 94.28$\pm$0.28 & 18.34$\pm$2.03 \\
grace deg & \color{violet}{86.28$\pm$2.0 $\bigstar$} & \color{violet}{36.46$\pm$1.26 $\bigstar$} & \color{red}{43.46$\pm$7.72 $\bigstar$} & 93.66$\pm$0.56 & 21.05$\pm$3.22 \\
grace pr & 84.0$\pm$1.65 & 36.44$\pm$0.93 $\bigstar$ & \color{violet}{39.65$\pm$4.48 $\bigstar$} & 94.32$\pm$0.3 $\bigstar$ & 17.12$\pm$1.93 X \\
grace evc & 84.32$\pm$1.58 & \color{blue}{36.57$\pm$1.3 $\bigstar$} & \color{blue}{42.08$\pm$7.26 $\bigstar$} & 94.24$\pm$0.3 & 21.63$\pm$5.49 \\
grace scom & 84.32$\pm$1.3 & 36.34$\pm$1.11 $\bigstar$ & 36.22$\pm$3.33 & \color{red}{94.37$\pm$0.24 $\bigstar$} & 18.85$\pm$3.06 \\
grace random+scom & 84.11$\pm$1.34 & 36.4$\pm$0.94 $\bigstar$ & 34.88$\pm$1.91 & 94.26$\pm$0.33 & 16.95$\pm$2.03 X \\
grace random+deg & \color{blue}{86.93$\pm$2.53 $\bigstar$} & 36.27$\pm$1.03 $\bigstar$ & 38.37$\pm$3.28 & 94.2$\pm$0.48 & 18.27$\pm$2.03 \\
grace deg+scom & 86.04$\pm$2.0 $\bigstar$ & \color{red}{36.8$\pm$1.64 $\bigstar$} & 38.94$\pm$5.06 & 94.02$\pm$0.49 & 17.59$\pm$2.47 X \\
bgrl random & 85.18$\pm$1.28 & 29.6$\pm$0.96 & 27.31$\pm$3.89 & 93.78$\pm$0.54 & \color{blue}{23.73$\pm$2.21 $\bigstar$} \\
bgrl deg & \color{red}{86.95$\pm$2.33 $\bigstar$} & 31.79$\pm$1.73 & 38.94$\pm$9.26 & 94.26$\pm$0.48 $\bigstar$ & 22.85$\pm$3.54 \\
bgrl pr & 83.58$\pm$1.23 X & 27.75$\pm$1.17 X & 23.39$\pm$2.68 X & 94.0$\pm$0.38 & 17.86$\pm$2.27 X \\
bgrl evc & 84.25$\pm$1.55 & 29.49$\pm$1.11 & 38.27$\pm$8.41 & 93.69$\pm$0.44 & 22.1$\pm$6.04 \\
bgrl scom & 84.69$\pm$1.39 & 29.92$\pm$1.16 & 28.13$\pm$2.69 X & 93.46$\pm$0.56 X & 20.51$\pm$3.5 \\
bgrl random+scom & 84.84$\pm$1.56 & 29.77$\pm$1.38 & 28.37$\pm$2.86 & 93.33$\pm$0.65 X & \color{red}{24.95$\pm$3.63 $\bigstar$} \\
bgrl random+deg & 84.89$\pm$1.64 & 30.33$\pm$0.85 & 34.88$\pm$3.01 & \color{violet}{94.36$\pm$0.6 $\bigstar$} & 18.78$\pm$4.59 \\
bgrl deg+scom & 84.43$\pm$1.56 & 29.86$\pm$1.42 & 32.08$\pm$3.74 & \color{blue}{94.37$\pm$0.5 $\bigstar$} & 17.12$\pm$3.17 X \\
\bottomrule
\end{tabular}

}

,FINAL_netscience_res.csv,FINAL_power_res.csv,FINAL_euroroad_res.csv,FINAL_yeast_res.csv,FINAL_crime_res.csv
baseline,85.18$\pm$1.85,32.24$\pm$0.75,36.71$\pm$3.26,93.98$\pm$0.55,\color{violet}{23.02$\pm$2.9 $\bigstar$}
grace random,84.34$\pm$1.29,36.05$\pm$1.17,37.42$\pm$2.96,94.28$\pm$0.28,18.34$\pm$2.03
grace deg,\color{violet}{86.28$\pm$2.0 $\bigstar$},\color{violet}{36.46$\pm$1.26 $\bigstar$},\color{red}{43.46$\pm$7.72 $\bigstar$},93.66$\pm$0.56,21.05$\pm$3.22
grace pr,84.0$\pm$1.65,36.44$\pm$0.93 $\bigstar$,\color{violet}{39.65$\pm$4.48 $\bigstar$},94.32$\pm$0.3 $\bigstar$,17.12$\pm$1.93 X
grace evc,84.32$\pm$1.58,\color{blue}{36.57$\pm$1.3 $\bigstar$},\color{blue}{42.08$\pm$7.26 $\bigstar$},94.24$\pm$0.3,21.63$\pm$5.49
grace scom,84.32$\pm$1.3,36.34$\pm$1.11 $\bigstar$,36.22$\pm$3.33,\color{red}{94.37$\pm$0.24 $\bigstar$},18.85$\pm$3.06
grace random+scom,84.11$\pm$1.34,36.4$\pm$0.94 $\bigstar$,34.88$\pm$1.91,94.26$\pm$0.33,16.95$\pm$2.03 X
grace random+deg,\color{blue}{86.93$\pm$2.53 $\bigstar$},36.27$\pm$1.03 $\bigstar$,38.37$\pm$3.28,94.2$\pm$0.48,18.27$\pm$2.03
grace deg+scom,86.04$\pm$2.0 $\bigstar$,\color{red}{36.8$\pm$1.64 $\bigstar$},38.94$\pm$5.06,94.02$\pm$0.49,17.59$\pm$2.47 X
bgrl random,85.18$\pm$1.28,29.6$\pm$0.96,27.31$\pm$3.89,93.78$\pm$0.54,\color{blue}{23.73$\pm$2.21 $\bigstar$}
bgrl deg,\color{red}{86.95$\pm$2.33 $\bigstar$},31.79$\pm$1.73,38.94$\pm$9.26,94.26$\pm$0.48 $\bigstar$,22.85$\pm$3.54
bgrl pr,83.58$\pm$1.23 X,27.75$\pm$1.17 X,23.39$\pm$2.68 X,94.0$\pm$0.38,17.86$\pm$2.27 X
bgrl evc,84.25$\pm$1.55,29.49$\pm$1.11,38.27$\pm$8.41,93.69$\pm$0.44,22.1$\pm$6.04
bgrl scom,84.69$\pm$1.39,29.92$\pm$1.16,28.13$\pm$2.69 X,93.46$\pm$0.56 X,20.51$\pm$3.5
bgrl random+scom,84.84$\pm$1.56,29.77$\pm$1.38,28.37$\pm$2.86,93.33$\pm$0.65 X,\color{red}{24.95$\pm$3.63 $\bigstar$}
bgrl random+deg,84.89$\pm$1.64,30.33$\pm$0.85,34.88$\pm$3.01,\color{violet}{94.36$\pm$0.6 $\bigstar$},18.78$\pm$4.59
bgrl deg+scom,84.43$\pm$1.56,29.86$\pm$1.42,32.08$\pm$3.74,\color{blue}{94.37$\pm$0.5 $\bigstar$},17.12$\pm$3.17 X

                             Hits@20
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & FINAL_netscience_res.csv & FINAL_power_res.csv & FINAL_euroroad_res.csv & FINAL_yeast_res.csv & FINAL_crime_res.csv \\
\midrule
baseline & 83.18$\pm$1.69 & 27.37$\pm$1.92 & 23.64$\pm$1.54 & 91.53$\pm$1.3 X & \color{violet}{14.64$\pm$2.25 $\bigstar$} \\
grace random & 83.56$\pm$1.23 & \color{violet}{32.88$\pm$1.33 $\bigstar$} & 25.27$\pm$2.58 & 92.7$\pm$1.1 & 13.32$\pm$1.73 \\
grace deg & 82.46$\pm$1.48 X & 30.93$\pm$2.51 & \color{blue}{26.57$\pm$6.03} & 89.69$\pm$2.5 X & 13.49$\pm$1.96 \\
grace pr & 83.19$\pm$1.56 & 32.75$\pm$1.22 $\bigstar$ & \color{violet}{26.4$\pm$3.35 $\bigstar$} & 92.7$\pm$1.27 & 12.31$\pm$1.55 \\
grace evc & 83.54$\pm$1.4 & 32.72$\pm$1.75 $\bigstar$ & 25.97$\pm$4.91 & 92.36$\pm$1.95 & 12.64$\pm$2.07 X \\
grace scom & 83.54$\pm$1.52 & \color{blue}{32.92$\pm$1.4 $\bigstar$} & 24.63$\pm$1.91 & 92.47$\pm$1.91 & 12.31$\pm$1.06 \\
grace random+scom & 83.43$\pm$1.64 & \color{red}{33.06$\pm$1.1 $\bigstar$} & 25.97$\pm$1.92 $\bigstar$ & 92.56$\pm$1.15 & 12.14$\pm$1.58 X \\
grace random+deg & \color{red}{84.74$\pm$1.79 $\bigstar$} & 31.33$\pm$2.56 & 25.69$\pm$2.94 & 91.82$\pm$1.29 & 13.19$\pm$1.07 \\
grace deg+scom & 83.65$\pm$1.88 & 32.27$\pm$2.17 $\bigstar$ & \color{red}{27.56$\pm$3.27 $\bigstar$} & 91.68$\pm$1.37 & 12.88$\pm$1.7 \\
bgrl random & \color{blue}{84.38$\pm$1.45 $\bigstar$} & 26.91$\pm$1.23 & 17.35$\pm$3.12 X & 92.89$\pm$0.79 & \color{blue}{15.29$\pm$3.03 $\bigstar$} \\
bgrl deg & \color{violet}{84.34$\pm$1.81} & 28.29$\pm$1.29 & 23.0$\pm$4.81 & \color{violet}{92.99$\pm$0.91} & 14.0$\pm$2.84 \\
bgrl pr & 82.34$\pm$1.48 X & 25.27$\pm$0.98 X & 15.94$\pm$1.23 X & 92.98$\pm$0.73 & 11.15$\pm$2.11 X \\
bgrl evc & 83.69$\pm$1.67 & 27.03$\pm$1.01 & 22.51$\pm$4.61 & 92.51$\pm$1.13 & 13.59$\pm$2.93 \\
bgrl scom & 83.83$\pm$1.45 & 27.25$\pm$1.07 & 16.89$\pm$2.62 X & 91.96$\pm$0.82 & 13.69$\pm$1.76 \\
bgrl random+scom & 84.12$\pm$1.7 & 26.99$\pm$1.26 & 18.76$\pm$2.43 & 92.11$\pm$1.01 & \color{red}{16.1$\pm$3.42 $\bigstar$} \\
bgrl random+deg & 83.96$\pm$1.77 & 27.68$\pm$0.84 & 23.22$\pm$2.39 & \color{blue}{93.22$\pm$0.77 $\bigstar$} & 12.71$\pm$2.34 \\
bgrl deg+scom & 83.47$\pm$1.68 & 27.26$\pm$1.04 & 20.57$\pm$2.77 & \color{red}{93.38$\pm$0.83 $\bigstar$} & 11.69$\pm$1.77 X \\
\bottomrule
\end{tabular}

}

,FINAL_netscience_res.csv,FINAL_power_res.csv,FINAL_euroroad_res.csv,FINAL_yeast_res.csv,FINAL_crime_res.csv
baseline,83.18$\pm$1.69,27.37$\pm$1.92,23.64$\pm$1.54,91.53$\pm$1.3 X,\color{violet}{14.64$\pm$2.25 $\bigstar$}
grace random,83.56$\pm$1.23,\color{violet}{32.88$\pm$1.33 $\bigstar$},25.27$\pm$2.58,92.7$\pm$1.1,13.32$\pm$1.73
grace deg,82.46$\pm$1.48 X,30.93$\pm$2.51,\color{blue}{26.57$\pm$6.03},89.69$\pm$2.5 X,13.49$\pm$1.96
grace pr,83.19$\pm$1.56,32.75$\pm$1.22 $\bigstar$,\color{violet}{26.4$\pm$3.35 $\bigstar$},92.7$\pm$1.27,12.31$\pm$1.55
grace evc,83.54$\pm$1.4,32.72$\pm$1.75 $\bigstar$,25.97$\pm$4.91,92.36$\pm$1.95,12.64$\pm$2.07 X
grace scom,83.54$\pm$1.52,\color{blue}{32.92$\pm$1.4 $\bigstar$},24.63$\pm$1.91,92.47$\pm$1.91,12.31$\pm$1.06
grace random+scom,83.43$\pm$1.64,\color{red}{33.06$\pm$1.1 $\bigstar$},25.97$\pm$1.92 $\bigstar$,92.56$\pm$1.15,12.14$\pm$1.58 X
grace random+deg,\color{red}{84.74$\pm$1.79 $\bigstar$},31.33$\pm$2.56,25.69$\pm$2.94,91.82$\pm$1.29,13.19$\pm$1.07
grace deg+scom,83.65$\pm$1.88,32.27$\pm$2.17 $\bigstar$,\color{red}{27.56$\pm$3.27 $\bigstar$},91.68$\pm$1.37,12.88$\pm$1.7
bgrl random,\color{blue}{84.38$\pm$1.45 $\bigstar$},26.91$\pm$1.23,17.35$\pm$3.12 X,92.89$\pm$0.79,\color{blue}{15.29$\pm$3.03 $\bigstar$}
bgrl deg,\color{violet}{84.34$\pm$1.81},28.29$\pm$1.29,23.0$\pm$4.81,\color{violet}{92.99$\pm$0.91},14.0$\pm$2.84
bgrl pr,82.34$\pm$1.48 X,25.27$\pm$0.98 X,15.94$\pm$1.23 X,92.98$\pm$0.73,11.15$\pm$2.11 X
bgrl evc,83.69$\pm$1.67,27.03$\pm$1.01,22.51$\pm$4.61,92.51$\pm$1.13,13.59$\pm$2.93
bgrl scom,83.83$\pm$1.45,27.25$\pm$1.07,16.89$\pm$2.62 X,91.96$\pm$0.82,13.69$\pm$1.76
bgrl random+scom,84.12$\pm$1.7,26.99$\pm$1.26,18.76$\pm$2.43,92.11$\pm$1.01,\color{red}{16.1$\pm$3.42 $\bigstar$}
bgrl random+deg,83.96$\pm$1.77,27.68$\pm$0.84,23.22$\pm$2.39,\color{blue}{93.22$\pm$0.77 $\bigstar$},12.71$\pm$2.34
bgrl deg+scom,83.47$\pm$1.68,27.26$\pm$1.04,20.57$\pm$2.77,\color{red}{93.38$\pm$0.83 $\bigstar$},11.69$\pm$1.77 X

In [4]:
# score attr
names = ['FINAL_cora_res.csv',
'FINAL_citeseer_res.csv',
'FINAL_pubmed_res.csv',
'FINAL_computers_res.csv',
'FINAL_photo_res.csv',
'FINAL_cs_res.csv']
filtres = ['baseline','grace','bgrl']

print("                             ROCAUC                      ")
all_data, all_res = ut.mix_dataset(names, 'ROCAUC', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             AP                      ")
all_data, all_res = ut.mix_dataset(names, 'AP', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@100                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@100', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@20                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@20', filtres)
display(ut.tex_table(all_data, all_res).T)

                             ROCAUC
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_pubmed_res.csv & FINAL_computers_res.csv & FINAL_photo_res.csv & FINAL_cs_res.csv \\
\midrule
baseline & 90.61$\pm$0.77 & 50.01$\pm$0.02 X & \color{red}{98.29$\pm$0.09 $\bigstar$} & 59.2$\pm$18.41 X & 76.85$\pm$22.69 X & \color{red}{97.8$\pm$0.11 $\bigstar$} \\
grace random & 91.73$\pm$0.78 & 93.38$\pm$0.6 & 97.5$\pm$0.1 & 87.96$\pm$4.69 & 97.94$\pm$0.16 X & 96.7$\pm$0.15 \\
grace deg & \color{violet}{93.43$\pm$0.5 $\bigstar$} & \color{red}{94.48$\pm$0.66 $\bigstar$} & 97.65$\pm$0.14 & 86.15$\pm$5.29 & 97.9$\pm$0.27 X & 96.77$\pm$0.17 \\
grace pr & 93.39$\pm$0.47 $\bigstar$ & 94.08$\pm$0.46 $\bigstar$ & \color{blue}{97.66$\pm$0.14} & 85.53$\pm$5.93 & 98.05$\pm$0.19 & 96.77$\pm$0.16 \\
grace evc & 93.41$\pm$0.4 $\bigstar$ & 94.04$\pm$0.42 $\bigstar$ & 97.61$\pm$0.13 & 90.45$\pm$8.86 & 97.82$\pm$0.48 X & 96.76$\pm$0.12 \\
grace scom & 91.7$\pm$0.9 & \color{violet}{94.2$\pm$0.48 $\bigstar$} & 97.58$\pm$0.09 & 86.08$\pm$5.2 & 97.98$\pm$0.28 X & 96.63$\pm$0.1 \\
grace random+scom & 91.57$\pm$0.84 & 93.82$\pm$0.53 & 97.56$\pm$0.15 & 85.6$\pm$6.94 & 97.83$\pm$0.43 X & 96.56$\pm$0.19 X \\
grace random+deg & \color{red}{93.8$\pm$0.52 $\bigstar$} & 94.16$\pm$0.9 & 97.54$\pm$0.09 & 86.71$\pm$3.0 & 97.99$\pm$0.22 X & 96.79$\pm$0.16 \\
grace deg+scom & \color{blue}{93.62$\pm$0.58 $\bigstar$} & \color{blue}{94.48$\pm$0.7 $\bigstar$} & \color{violet}{97.66$\pm$0.17} & 86.4$\pm$6.45 & 97.86$\pm$0.17 X & 96.67$\pm$0.21 \\
bgrl random & 89.62$\pm$0.79 X & 90.02$\pm$0.66 & 95.96$\pm$0.13 X & 92.22$\pm$14.37 & 96.3$\pm$7.37 & 96.42$\pm$0.54 X \\
bgrl deg & 92.18$\pm$0.68 & 90.97$\pm$2.79 & 96.41$\pm$0.14 & \color{blue}{97.91$\pm$1.16 $\bigstar$} & 97.23$\pm$4.85 & \color{blue}{97.09$\pm$0.43} \\
bgrl pr & 92.22$\pm$0.68 & 89.23$\pm$0.77 X & 96.38$\pm$0.15 & \color{violet}{97.65$\pm$2.16 $\bigstar$} & 97.83$\pm$2.07 & \color{violet}{97.0$\pm$0.32} \\
bgrl evc & 92.1$\pm$0.83 & 90.09$\pm$0.45 & 96.42$\pm$0.15 & 93.52$\pm$13.99 $\bigstar$ & \color{red}{98.85$\pm$0.11 $\bigstar$} & 96.95$\pm$0.28 \\
bgrl scom & 89.59$\pm$0.88 X & 90.24$\pm$0.4 & 96.56$\pm$0.16 & 87.46$\pm$18.88 & \color{violet}{98.66$\pm$0.33} & 96.94$\pm$0.51 \\
bgrl random+scom & 89.38$\pm$1.0 X & 89.98$\pm$0.45 & 96.37$\pm$0.11 & \color{red}{98.33$\pm$0.09 $\bigstar$} & 97.52$\pm$3.75 & 96.63$\pm$0.48 \\
bgrl random+deg & 91.73$\pm$0.83 & 90.87$\pm$2.43 & 96.49$\pm$0.2 & 88.17$\pm$18.43 & 98.26$\pm$1.72 & 96.8$\pm$0.48 \\
bgrl deg+scom & 91.46$\pm$1.06 & 91.05$\pm$1.91 & 96.4$\pm$0.16 & 93.63$\pm$13.88 $\bigstar$ & \color{blue}{98.75$\pm$0.28 $\bigstar$} & 96.93$\pm$0.35 \\
\bottomrule
\end{tabular}

}

,FINAL_cora_res.csv,FINAL_citeseer_res.csv,FINAL_pubmed_res.csv,FINAL_computers_res.csv,FINAL_photo_res.csv,FINAL_cs_res.csv
baseline,90.61$\pm$0.77,50.01$\pm$0.02 X,\color{red}{98.29$\pm$0.09 $\bigstar$},59.2$\pm$18.41 X,76.85$\pm$22.69 X,\color{red}{97.8$\pm$0.11 $\bigstar$}
grace random,91.73$\pm$0.78,93.38$\pm$0.6,97.5$\pm$0.1,87.96$\pm$4.69,97.94$\pm$0.16 X,96.7$\pm$0.15
grace deg,\color{violet}{93.43$\pm$0.5 $\bigstar$},\color{red}{94.48$\pm$0.66 $\bigstar$},97.65$\pm$0.14,86.15$\pm$5.29,97.9$\pm$0.27 X,96.77$\pm$0.17
grace pr,93.39$\pm$0.47 $\bigstar$,94.08$\pm$0.46 $\bigstar$,\color{blue}{97.66$\pm$0.14},85.53$\pm$5.93,98.05$\pm$0.19,96.77$\pm$0.16
grace evc,93.41$\pm$0.4 $\bigstar$,94.04$\pm$0.42 $\bigstar$,97.61$\pm$0.13,90.45$\pm$8.86,97.82$\pm$0.48 X,96.76$\pm$0.12
grace scom,91.7$\pm$0.9,\color{violet}{94.2$\pm$0.48 $\bigstar$},97.58$\pm$0.09,86.08$\pm$5.2,97.98$\pm$0.28 X,96.63$\pm$0.1
grace random+scom,91.57$\pm$0.84,93.82$\pm$0.53,97.56$\pm$0.15,85.6$\pm$6.94,97.83$\pm$0.43 X,96.56$\pm$0.19 X
grace random+deg,\color{red}{93.8$\pm$0.52 $\bigstar$},94.16$\pm$0.9,97.54$\pm$0.09,86.71$\pm$3.0,97.99$\pm$0.22 X,96.79$\pm$0.16
grace deg+scom,\color{blue}{93.62$\pm$0.58 $\bigstar$},\color{blue}{94.48$\pm$0.7 $\bigstar$},\color{violet}{97.66$\pm$0.17},86.4$\pm$6.45,97.86$\pm$0.17 X,96.67$\pm$0.21
bgrl random,89.62$\pm$0.79 X,90.02$\pm$0.66,95.96$\pm$0.13 X,92.22$\pm$14.37,96.3$\pm$7.37,96.42$\pm$0.54 X
bgrl deg,92.18$\pm$0.68,90.97$\pm$2.79,96.41$\pm$0.14,\color{blue}{97.91$\pm$1.16 $\bigstar$},97.23$\pm$4.85,\color{blue}{97.09$\pm$0.43}
bgrl pr,92.22$\pm$0.68,89.23$\pm$0.77 X,96.38$\pm$0.15,\color{violet}{97.65$\pm$2.16 $\bigstar$},97.83$\pm$2.07,\color{violet}{97.0$\pm$0.32}
bgrl evc,92.1$\pm$0.83,90.09$\pm$0.45,96.42$\pm$0.15,93.52$\pm$13.99 $\bigstar$,\color{red}{98.85$\pm$0.11 $\bigstar$},96.95$\pm$0.28
bgrl scom,89.59$\pm$0.88 X,90.24$\pm$0.4,96.56$\pm$0.16,87.46$\pm$18.88,\color{violet}{98.66$\pm$0.33},96.94$\pm$0.51
bgrl random+scom,89.38$\pm$1.0 X,89.98$\pm$0.45,96.37$\pm$0.11,\color{red}{98.33$\pm$0.09 $\bigstar$},97.52$\pm$3.75,96.63$\pm$0.48
bgrl random+deg,91.73$\pm$0.83,90.87$\pm$2.43,96.49$\pm$0.2,88.17$\pm$18.43,98.26$\pm$1.72,96.8$\pm$0.48
bgrl deg+scom,91.46$\pm$1.06,91.05$\pm$1.91,96.4$\pm$0.16,93.63$\pm$13.88 $\bigstar$,\color{blue}{98.75$\pm$0.28 $\bigstar$},96.93$\pm$0.35

                             AP
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_pubmed_res.csv & FINAL_computers_res.csv & FINAL_photo_res.csv & FINAL_cs_res.csv \\
\midrule
baseline & 92.5$\pm$0.52 X & 50.01$\pm$0.01 X & \color{red}{98.32$\pm$0.09 $\bigstar$} & 59.14$\pm$18.27 X & 76.77$\pm$22.55 X & \color{red}{98.08$\pm$0.09 $\bigstar$} \\
grace random & 93.49$\pm$0.57 & 94.66$\pm$0.5 & 97.83$\pm$0.12 & 82.57$\pm$6.8 & 97.38$\pm$0.37 X & 97.41$\pm$0.09 \\
grace deg & 93.78$\pm$0.5 & \color{blue}{95.16$\pm$0.4 $\bigstar$} & \color{violet}{97.93$\pm$0.11} & 79.72$\pm$6.59 & 97.32$\pm$0.52 X & 97.46$\pm$0.11 \\
grace pr & 93.66$\pm$0.48 & 95.03$\pm$0.38 $\bigstar$ & 97.93$\pm$0.14 & 79.21$\pm$7.84 & 97.51$\pm$0.35 & 97.46$\pm$0.08 \\
grace evc & 93.7$\pm$0.42 & 95.02$\pm$0.42 $\bigstar$ & 97.89$\pm$0.1 & 87.63$\pm$12.21 & 97.09$\pm$0.81 X & 97.46$\pm$0.07 \\
grace scom & 93.5$\pm$0.65 & \color{violet}{95.16$\pm$0.4 $\bigstar$} & 97.91$\pm$0.1 & 80.2$\pm$5.52 & 97.54$\pm$0.38 & 97.35$\pm$0.06 X \\
grace random+scom & 93.34$\pm$0.62 & 94.96$\pm$0.43 $\bigstar$ & 97.88$\pm$0.14 & 79.07$\pm$9.14 & 97.17$\pm$0.86 X & 97.31$\pm$0.12 X \\
grace random+deg & \color{red}{94.26$\pm$0.49 $\bigstar$} & 95.11$\pm$0.56 $\bigstar$ & 97.86$\pm$0.1 & 80.74$\pm$3.42 & 97.51$\pm$0.36 & 97.48$\pm$0.1 \\
grace deg+scom & \color{blue}{94.14$\pm$0.46 $\bigstar$} & \color{red}{95.25$\pm$0.52 $\bigstar$} & \color{blue}{97.94$\pm$0.15} & 81.06$\pm$9.08 & 97.0$\pm$0.58 X & 97.4$\pm$0.13 \\
bgrl random & 92.26$\pm$0.62 X & 92.59$\pm$0.56 & 96.79$\pm$0.1 X & 92.15$\pm$14.32 & 96.13$\pm$7.34 & 97.31$\pm$0.27 X \\
bgrl deg & 93.98$\pm$0.49 $\bigstar$ & 93.24$\pm$2.01 & 97.07$\pm$0.11 & \color{blue}{97.65$\pm$1.28 $\bigstar$} & 97.14$\pm$4.69 & 97.44$\pm$0.41 \\
bgrl pr & \color{violet}{94.02$\pm$0.45 $\bigstar$} & 91.95$\pm$0.61 X & 97.06$\pm$0.11 & \color{violet}{97.49$\pm$2.11 $\bigstar$} & 97.56$\pm$2.32 & \color{blue}{97.62$\pm$0.15} \\
bgrl evc & 93.93$\pm$0.6 $\bigstar$ & 92.53$\pm$0.4 & 97.07$\pm$0.12 & 93.27$\pm$14.16 $\bigstar$ & \color{red}{98.69$\pm$0.15 $\bigstar$} & \color{violet}{97.55$\pm$0.15} \\
bgrl scom & 92.3$\pm$0.61 X & 92.69$\pm$0.41 & 97.19$\pm$0.15 & 87.32$\pm$18.81 & \color{violet}{98.46$\pm$0.4} & 97.54$\pm$0.21 \\
bgrl random+scom & 92.1$\pm$0.75 X & 92.57$\pm$0.34 & 97.08$\pm$0.11 & \color{red}{98.14$\pm$0.1 $\bigstar$} & 97.43$\pm$3.48 & 97.38$\pm$0.14 \\
bgrl random+deg & 93.8$\pm$0.59 & 93.23$\pm$1.76 & 97.16$\pm$0.17 & 87.83$\pm$18.41 & 98.03$\pm$1.9 & 97.43$\pm$0.1 \\
bgrl deg+scom & 93.64$\pm$0.69 & 93.34$\pm$1.39 & 97.08$\pm$0.12 & 93.43$\pm$13.99 $\bigstar$ & \color{blue}{98.6$\pm$0.3 $\bigstar$} & 97.5$\pm$0.3 \\
\bottomrule
\end{tabular}

}

,FINAL_cora_res.csv,FINAL_citeseer_res.csv,FINAL_pubmed_res.csv,FINAL_computers_res.csv,FINAL_photo_res.csv,FINAL_cs_res.csv
baseline,92.5$\pm$0.52 X,50.01$\pm$0.01 X,\color{red}{98.32$\pm$0.09 $\bigstar$},59.14$\pm$18.27 X,76.77$\pm$22.55 X,\color{red}{98.08$\pm$0.09 $\bigstar$}
grace random,93.49$\pm$0.57,94.66$\pm$0.5,97.83$\pm$0.12,82.57$\pm$6.8,97.38$\pm$0.37 X,97.41$\pm$0.09
grace deg,93.78$\pm$0.5,\color{blue}{95.16$\pm$0.4 $\bigstar$},\color{violet}{97.93$\pm$0.11},79.72$\pm$6.59,97.32$\pm$0.52 X,97.46$\pm$0.11
grace pr,93.66$\pm$0.48,95.03$\pm$0.38 $\bigstar$,97.93$\pm$0.14,79.21$\pm$7.84,97.51$\pm$0.35,97.46$\pm$0.08
grace evc,93.7$\pm$0.42,95.02$\pm$0.42 $\bigstar$,97.89$\pm$0.1,87.63$\pm$12.21,97.09$\pm$0.81 X,97.46$\pm$0.07
grace scom,93.5$\pm$0.65,\color{violet}{95.16$\pm$0.4 $\bigstar$},97.91$\pm$0.1,80.2$\pm$5.52,97.54$\pm$0.38,97.35$\pm$0.06 X
grace random+scom,93.34$\pm$0.62,94.96$\pm$0.43 $\bigstar$,97.88$\pm$0.14,79.07$\pm$9.14,97.17$\pm$0.86 X,97.31$\pm$0.12 X
grace random+deg,\color{red}{94.26$\pm$0.49 $\bigstar$},95.11$\pm$0.56 $\bigstar$,97.86$\pm$0.1,80.74$\pm$3.42,97.51$\pm$0.36,97.48$\pm$0.1
grace deg+scom,\color{blue}{94.14$\pm$0.46 $\bigstar$},\color{red}{95.25$\pm$0.52 $\bigstar$},\color{blue}{97.94$\pm$0.15},81.06$\pm$9.08,97.0$\pm$0.58 X,97.4$\pm$0.13
bgrl random,92.26$\pm$0.62 X,92.59$\pm$0.56,96.79$\pm$0.1 X,92.15$\pm$14.32,96.13$\pm$7.34,97.31$\pm$0.27 X
bgrl deg,93.98$\pm$0.49 $\bigstar$,93.24$\pm$2.01,97.07$\pm$0.11,\color{blue}{97.65$\pm$1.28 $\bigstar$},97.14$\pm$4.69,97.44$\pm$0.41
bgrl pr,\color{violet}{94.02$\pm$0.45 $\bigstar$},91.95$\pm$0.61 X,97.06$\pm$0.11,\color{violet}{97.49$\pm$2.11 $\bigstar$},97.56$\pm$2.32,\color{blue}{97.62$\pm$0.15}
bgrl evc,93.93$\pm$0.6 $\bigstar$,92.53$\pm$0.4,97.07$\pm$0.12,93.27$\pm$14.16 $\bigstar$,\color{red}{98.69$\pm$0.15 $\bigstar$},\color{violet}{97.55$\pm$0.15}
bgrl scom,92.3$\pm$0.61 X,92.69$\pm$0.41,97.19$\pm$0.15,87.32$\pm$18.81,\color{violet}{98.46$\pm$0.4},97.54$\pm$0.21
bgrl random+scom,92.1$\pm$0.75 X,92.57$\pm$0.34,97.08$\pm$0.11,\color{red}{98.14$\pm$0.1 $\bigstar$},97.43$\pm$3.48,97.38$\pm$0.14
bgrl random+deg,93.8$\pm$0.59,93.23$\pm$1.76,97.16$\pm$0.17,87.83$\pm$18.41,98.03$\pm$1.9,97.43$\pm$0.1
bgrl deg+scom,93.64$\pm$0.69,93.34$\pm$1.39,97.08$\pm$0.12,93.43$\pm$13.99 $\bigstar$,\color{blue}{98.6$\pm$0.3 $\bigstar$},97.5$\pm$0.3

                             Hits@100
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_pubmed_res.csv & FINAL_computers_res.csv & FINAL_photo_res.csv & FINAL_cs_res.csv \\
\midrule
baseline & 77.84$\pm$1.7 X & 0.0$\pm$0.0 X & 77.46$\pm$2.27 & 4.21$\pm$8.49 X & 24.09$\pm$24.24 X & \color{blue}{72.33$\pm$1.96} \\
grace random & 81.79$\pm$1.1 & 83.62$\pm$1.62 & 77.59$\pm$1.87 & 2.21$\pm$6.22 X & 37.07$\pm$4.65 & 70.88$\pm$1.34 X \\
grace deg & \color{blue}{84.4$\pm$1.15 $\bigstar$} & \color{blue}{85.82$\pm$2.4 $\bigstar$} & 77.86$\pm$1.6 & 0.39$\pm$1.12 X & 36.09$\pm$5.48 X & 71.41$\pm$1.94 \\
grace pr & \color{violet}{84.22$\pm$1.18 $\bigstar$} & 84.93$\pm$0.9 $\bigstar$ & \color{violet}{77.87$\pm$1.89} & 2.21$\pm$6.35 X & 37.97$\pm$3.92 & 71.96$\pm$2.46 \\
grace evc & 83.82$\pm$1.07 & 84.63$\pm$1.55 $\bigstar$ & 77.5$\pm$1.37 & 16.13$\pm$11.43 & 33.56$\pm$9.93 X & 71.78$\pm$1.56 \\
grace scom & 81.61$\pm$1.52 & 84.66$\pm$1.05 & \color{blue}{78.47$\pm$1.57 $\bigstar$} & 1.13$\pm$3.2 X & 39.79$\pm$5.25 & 71.01$\pm$1.99 X \\
grace random+scom & 81.31$\pm$1.51 & 84.46$\pm$1.54 & 77.62$\pm$1.96 & 2.54$\pm$7.44 X & 34.47$\pm$10.61 X & 70.24$\pm$1.14 X \\
grace random+deg & \color{red}{84.64$\pm$1.14 $\bigstar$} & \color{violet}{85.26$\pm$2.41 $\bigstar$} & 77.54$\pm$1.38 & 0.01$\pm$0.01 X & 38.47$\pm$5.35 & 71.56$\pm$1.39 \\
grace deg+scom & 84.21$\pm$1.28 $\bigstar$ & \color{red}{85.96$\pm$2.03 $\bigstar$} & \color{red}{78.85$\pm$1.19 $\bigstar$} & 6.39$\pm$8.15 & 30.63$\pm$8.85 X & 71.21$\pm$1.61 \\
bgrl random & 78.39$\pm$1.14 X & 78.4$\pm$1.49 & 71.03$\pm$1.43 X & 27.47$\pm$11.05 & 49.05$\pm$14.99 & \color{red}{73.96$\pm$3.98 $\bigstar$} \\
bgrl deg & 82.98$\pm$1.31 & 80.31$\pm$5.48 & 72.44$\pm$1.97 & 31.64$\pm$7.72 $\bigstar$ & 52.02$\pm$13.75 $\bigstar$ & 63.72$\pm$12.48 \\
bgrl pr & 82.93$\pm$1.33 & 76.33$\pm$1.62 X & 72.62$\pm$1.7 & \color{red}{33.43$\pm$7.59 $\bigstar$} & 48.54$\pm$14.03 & \color{violet}{72.31$\pm$8.48 $\bigstar$} \\
bgrl evc & 82.7$\pm$1.52 & 78.09$\pm$1.04 & 72.47$\pm$1.77 & 30.05$\pm$10.89 $\bigstar$ & \color{red}{55.9$\pm$3.58 $\bigstar$} & 71.42$\pm$9.9 $\bigstar$ \\
bgrl scom & 78.64$\pm$1.06 X & 79.05$\pm$1.41 & 72.95$\pm$1.87 & 23.77$\pm$13.94 & \color{violet}{52.46$\pm$5.08} & 70.7$\pm$6.22 \\
bgrl random+scom & 78.11$\pm$1.57 X & 78.27$\pm$0.58 & 73.33$\pm$1.76 & \color{blue}{33.26$\pm$2.86 $\bigstar$} & 49.34$\pm$11.9 & 71.81$\pm$8.57 $\bigstar$ \\
bgrl random+deg & 82.38$\pm$1.59 & 80.34$\pm$4.75 & 73.79$\pm$2.18 & 22.93$\pm$15.41 & 51.59$\pm$10.71 & 69.12$\pm$11.81 $\bigstar$ \\
bgrl deg+scom & 82.53$\pm$1.31 & 80.43$\pm$3.8 & 72.8$\pm$1.8 & \color{violet}{32.01$\pm$10.93 $\bigstar$} & \color{blue}{54.62$\pm$4.1 $\bigstar$} & 70.6$\pm$11.31 $\bigstar$ \\
\bottomrule
\end{tabular}

}

,FINAL_cora_res.csv,FINAL_citeseer_res.csv,FINAL_pubmed_res.csv,FINAL_computers_res.csv,FINAL_photo_res.csv,FINAL_cs_res.csv
baseline,77.84$\pm$1.7 X,0.0$\pm$0.0 X,77.46$\pm$2.27,4.21$\pm$8.49 X,24.09$\pm$24.24 X,\color{blue}{72.33$\pm$1.96}
grace random,81.79$\pm$1.1,83.62$\pm$1.62,77.59$\pm$1.87,2.21$\pm$6.22 X,37.07$\pm$4.65,70.88$\pm$1.34 X
grace deg,\color{blue}{84.4$\pm$1.15 $\bigstar$},\color{blue}{85.82$\pm$2.4 $\bigstar$},77.86$\pm$1.6,0.39$\pm$1.12 X,36.09$\pm$5.48 X,71.41$\pm$1.94
grace pr,\color{violet}{84.22$\pm$1.18 $\bigstar$},84.93$\pm$0.9 $\bigstar$,\color{violet}{77.87$\pm$1.89},2.21$\pm$6.35 X,37.97$\pm$3.92,71.96$\pm$2.46
grace evc,83.82$\pm$1.07,84.63$\pm$1.55 $\bigstar$,77.5$\pm$1.37,16.13$\pm$11.43,33.56$\pm$9.93 X,71.78$\pm$1.56
grace scom,81.61$\pm$1.52,84.66$\pm$1.05,\color{blue}{78.47$\pm$1.57 $\bigstar$},1.13$\pm$3.2 X,39.79$\pm$5.25,71.01$\pm$1.99 X
grace random+scom,81.31$\pm$1.51,84.46$\pm$1.54,77.62$\pm$1.96,2.54$\pm$7.44 X,34.47$\pm$10.61 X,70.24$\pm$1.14 X
grace random+deg,\color{red}{84.64$\pm$1.14 $\bigstar$},\color{violet}{85.26$\pm$2.41 $\bigstar$},77.54$\pm$1.38,0.01$\pm$0.01 X,38.47$\pm$5.35,71.56$\pm$1.39
grace deg+scom,84.21$\pm$1.28 $\bigstar$,\color{red}{85.96$\pm$2.03 $\bigstar$},\color{red}{78.85$\pm$1.19 $\bigstar$},6.39$\pm$8.15,30.63$\pm$8.85 X,71.21$\pm$1.61
bgrl random,78.39$\pm$1.14 X,78.4$\pm$1.49,71.03$\pm$1.43 X,27.47$\pm$11.05,49.05$\pm$14.99,\color{red}{73.96$\pm$3.98 $\bigstar$}
bgrl deg,82.98$\pm$1.31,80.31$\pm$5.48,72.44$\pm$1.97,31.64$\pm$7.72 $\bigstar$,52.02$\pm$13.75 $\bigstar$,63.72$\pm$12.48
bgrl pr,82.93$\pm$1.33,76.33$\pm$1.62 X,72.62$\pm$1.7,\color{red}{33.43$\pm$7.59 $\bigstar$},48.54$\pm$14.03,\color{violet}{72.31$\pm$8.48 $\bigstar$}
bgrl evc,82.7$\pm$1.52,78.09$\pm$1.04,72.47$\pm$1.77,30.05$\pm$10.89 $\bigstar$,\color{red}{55.9$\pm$3.58 $\bigstar$},71.42$\pm$9.9 $\bigstar$
bgrl scom,78.64$\pm$1.06 X,79.05$\pm$1.41,72.95$\pm$1.87,23.77$\pm$13.94,\color{violet}{52.46$\pm$5.08},70.7$\pm$6.22
bgrl random+scom,78.11$\pm$1.57 X,78.27$\pm$0.58,73.33$\pm$1.76,\color{blue}{33.26$\pm$2.86 $\bigstar$},49.34$\pm$11.9,71.81$\pm$8.57 $\bigstar$
bgrl random+deg,82.38$\pm$1.59,80.34$\pm$4.75,73.79$\pm$2.18,22.93$\pm$15.41,51.59$\pm$10.71,69.12$\pm$11.81 $\bigstar$
bgrl deg+scom,82.53$\pm$1.31,80.43$\pm$3.8,72.8$\pm$1.8,\color{violet}{32.01$\pm$10.93 $\bigstar$},\color{blue}{54.62$\pm$4.1 $\bigstar$},70.6$\pm$11.31 $\bigstar$

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_pubmed_res.csv & FINAL_computers_res.csv & FINAL_photo_res.csv & FINAL_cs_res.csv \\
\midrule
baseline & 71.55$\pm$1.75 X & 0.0$\pm$0.0 X & 65.59$\pm$3.52 & 2.93$\pm$5.88 X & 16.41$\pm$16.66 X & 59.85$\pm$3.93 X \\
grace random & 75.85$\pm$1.75 & 77.99$\pm$1.21 & 66.17$\pm$3.49 & 1.4$\pm$3.91 X & 22.54$\pm$7.0 & 60.04$\pm$2.19 \\
grace deg & 73.9$\pm$2.04 & \color{blue}{79.16$\pm$2.24 $\bigstar$} & 65.18$\pm$2.13 & 0.18$\pm$0.51 X & 21.3$\pm$8.02 X & 60.35$\pm$2.55 \\
grace pr & 73.73$\pm$1.97 & 78.67$\pm$1.27 $\bigstar$ & \color{blue}{66.31$\pm$2.26 $\bigstar$} & 1.47$\pm$4.13 X & 23.74$\pm$5.38 & 60.31$\pm$3.69 \\
grace evc & 73.55$\pm$2.85 & 78.31$\pm$1.82 $\bigstar$ & 65.21$\pm$2.19 & 10.97$\pm$8.14 & 18.94$\pm$8.59 X & 60.03$\pm$3.67 \\
grace scom & 76.3$\pm$2.02 & 78.6$\pm$1.31 $\bigstar$ & \color{red}{67.24$\pm$2.77 $\bigstar$} & 0.32$\pm$0.83 X & 25.96$\pm$4.65 & 59.57$\pm$2.75 X \\
grace random+scom & 75.37$\pm$1.78 & 78.44$\pm$1.54 $\bigstar$ & 66.16$\pm$3.29 & 1.79$\pm$5.3 X & 21.08$\pm$9.43 X & 58.35$\pm$1.3 X \\
grace random+deg & 77.02$\pm$1.56 $\bigstar$ & \color{red}{79.65$\pm$2.56 $\bigstar$} & 65.66$\pm$2.45 & 0.0$\pm$0.0 X & 24.58$\pm$5.23 & 59.52$\pm$2.51 X \\
grace deg+scom & 76.62$\pm$1.79 & \color{violet}{79.15$\pm$2.62 $\bigstar$} & \color{violet}{66.23$\pm$3.12} & 2.36$\pm$4.95 X & 15.63$\pm$9.45 X & 59.18$\pm$2.04 X \\
bgrl random & 73.58$\pm$1.44 & 74.08$\pm$1.06 & 61.81$\pm$1.76 X & 18.71$\pm$7.7 & 35.99$\pm$11.71 & \color{red}{64.42$\pm$4.93 $\bigstar$} \\
bgrl deg & \color{blue}{77.49$\pm$1.21 $\bigstar$} & 76.19$\pm$5.97 & 61.91$\pm$2.07 X & 21.22$\pm$5.95 $\bigstar$ & \color{violet}{39.23$\pm$10.85 $\bigstar$} & 51.73$\pm$14.51 X \\
bgrl pr & 77.46$\pm$1.43 $\bigstar$ & 71.93$\pm$1.4 X & 62.32$\pm$2.03 X & \color{blue}{22.47$\pm$5.24 $\bigstar$} & 35.51$\pm$10.72 & \color{violet}{62.37$\pm$10.33 $\bigstar$} \\
bgrl evc & 77.0$\pm$1.73 & 73.31$\pm$1.27 & 62.08$\pm$2.65 X & 20.88$\pm$7.76 $\bigstar$ & \color{blue}{41.13$\pm$3.45 $\bigstar$} & \color{blue}{62.42$\pm$11.47 $\bigstar$} \\
bgrl scom & 73.79$\pm$1.91 & 74.79$\pm$1.18 & 62.99$\pm$2.6 & 16.13$\pm$9.73 & 38.38$\pm$4.96 & 58.24$\pm$8.68 X \\
bgrl random+scom & 73.31$\pm$1.8 & 74.53$\pm$0.64 & 62.7$\pm$2.43 & \color{red}{22.93$\pm$3.07 $\bigstar$} & 36.14$\pm$9.57 & 60.88$\pm$12.16 \\
bgrl random+deg & \color{red}{77.88$\pm$1.69 $\bigstar$} & 76.51$\pm$5.06 & 63.51$\pm$2.83 & 15.43$\pm$10.14 & 38.49$\pm$8.2 & 58.96$\pm$13.69 \\
bgrl deg+scom & \color{violet}{77.49$\pm$1.84 $\bigstar$} & 76.74$\pm$3.92 & 62.29$\pm$1.71 & \color{violet}{22.43$\pm$7.75 $\bigstar$} & \color{red}{41.42$\pm$2.87 $\bigstar$} & 60.95$\pm$14.29 $\bigstar$ \\
\bottomrule
\end{tabular}

}

,FINAL_cora_res.csv,FINAL_citeseer_res.csv,FINAL_pubmed_res.csv,FINAL_computers_res.csv,FINAL_photo_res.csv,FINAL_cs_res.csv
baseline,71.55$\pm$1.75 X,0.0$\pm$0.0 X,65.59$\pm$3.52,2.93$\pm$5.88 X,16.41$\pm$16.66 X,59.85$\pm$3.93 X
grace random,75.85$\pm$1.75,77.99$\pm$1.21,66.17$\pm$3.49,1.4$\pm$3.91 X,22.54$\pm$7.0,60.04$\pm$2.19
grace deg,73.9$\pm$2.04,\color{blue}{79.16$\pm$2.24 $\bigstar$},65.18$\pm$2.13,0.18$\pm$0.51 X,21.3$\pm$8.02 X,60.35$\pm$2.55
grace pr,73.73$\pm$1.97,78.67$\pm$1.27 $\bigstar$,\color{blue}{66.31$\pm$2.26 $\bigstar$},1.47$\pm$4.13 X,23.74$\pm$5.38,60.31$\pm$3.69
grace evc,73.55$\pm$2.85,78.31$\pm$1.82 $\bigstar$,65.21$\pm$2.19,10.97$\pm$8.14,18.94$\pm$8.59 X,60.03$\pm$3.67
grace scom,76.3$\pm$2.02,78.6$\pm$1.31 $\bigstar$,\color{red}{67.24$\pm$2.77 $\bigstar$},0.32$\pm$0.83 X,25.96$\pm$4.65,59.57$\pm$2.75 X
grace random+scom,75.37$\pm$1.78,78.44$\pm$1.54 $\bigstar$,66.16$\pm$3.29,1.79$\pm$5.3 X,21.08$\pm$9.43 X,58.35$\pm$1.3 X
grace random+deg,77.02$\pm$1.56 $\bigstar$,\color{red}{79.65$\pm$2.56 $\bigstar$},65.66$\pm$2.45,0.0$\pm$0.0 X,24.58$\pm$5.23,59.52$\pm$2.51 X
grace deg+scom,76.62$\pm$1.79,\color{violet}{79.15$\pm$2.62 $\bigstar$},\color{violet}{66.23$\pm$3.12},2.36$\pm$4.95 X,15.63$\pm$9.45 X,59.18$\pm$2.04 X
bgrl random,73.58$\pm$1.44,74.08$\pm$1.06,61.81$\pm$1.76 X,18.71$\pm$7.7,35.99$\pm$11.71,\color{red}{64.42$\pm$4.93 $\bigstar$}
bgrl deg,\color{blue}{77.49$\pm$1.21 $\bigstar$},76.19$\pm$5.97,61.91$\pm$2.07 X,21.22$\pm$5.95 $\bigstar$,\color{violet}{39.23$\pm$10.85 $\bigstar$},51.73$\pm$14.51 X
bgrl pr,77.46$\pm$1.43 $\bigstar$,71.93$\pm$1.4 X,62.32$\pm$2.03 X,\color{blue}{22.47$\pm$5.24 $\bigstar$},35.51$\pm$10.72,\color{violet}{62.37$\pm$10.33 $\bigstar$}
bgrl evc,77.0$\pm$1.73,73.31$\pm$1.27,62.08$\pm$2.65 X,20.88$\pm$7.76 $\bigstar$,\color{blue}{41.13$\pm$3.45 $\bigstar$},\color{blue}{62.42$\pm$11.47 $\bigstar$}
bgrl scom,73.79$\pm$1.91,74.79$\pm$1.18,62.99$\pm$2.6,16.13$\pm$9.73,38.38$\pm$4.96,58.24$\pm$8.68 X
bgrl random+scom,73.31$\pm$1.8,74.53$\pm$0.64,62.7$\pm$2.43,\color{red}{22.93$\pm$3.07 $\bigstar$},36.14$\pm$9.57,60.88$\pm$12.16
bgrl random+deg,\color{red}{77.88$\pm$1.69 $\bigstar$},76.51$\pm$5.06,63.51$\pm$2.83,15.43$\pm$10.14,38.49$\pm$8.2,58.96$\pm$13.69
bgrl deg+scom,\color{violet}{77.49$\pm$1.84 $\bigstar$},76.74$\pm$3.92,62.29$\pm$1.71,\color{violet}{22.43$\pm$7.75 $\bigstar$},\color{red}{41.42$\pm$2.87 $\bigstar$},60.95$\pm$14.29 $\bigstar$

                             Hits@20
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & FINAL_cora_res.csv & FINAL_citeseer_res.csv & FINAL_pubmed_res.csv & FINAL_computers_res.csv & FINAL_photo_res.csv & FINAL_cs_res.csv \\
\midrule
baseline & 61.48$\pm$2.88 & 0.0$\pm$0.0 X & \color{red}{47.89$\pm$3.19 $\bigstar$} & 1.67$\pm$3.33 X & 10.12$\pm$10.85 & 41.75$\pm$4.96 X \\
grace random & 66.7$\pm$2.83 & 70.76$\pm$1.82 & 45.93$\pm$4.66 X & 0.64$\pm$1.92 X & 9.82$\pm$6.0 & 42.56$\pm$5.09 \\
grace deg & 54.14$\pm$5.76 X & 69.44$\pm$2.37 & \color{blue}{47.68$\pm$4.36 $\bigstar$} & 0.01$\pm$0.01 X & 9.94$\pm$6.55 & 42.66$\pm$3.74 X \\
grace pr & 53.7$\pm$4.41 X & 69.86$\pm$1.89 & 45.21$\pm$5.78 & 0.73$\pm$2.01 X & 9.32$\pm$6.93 & 43.03$\pm$5.15 \\
grace evc & 53.33$\pm$4.7 X & 70.24$\pm$2.51 & 45.68$\pm$3.77 X & 5.68$\pm$5.15 & 7.07$\pm$6.17 X & 42.75$\pm$4.6 X \\
grace scom & 66.33$\pm$3.98 & 70.98$\pm$1.8 $\bigstar$ & \color{violet}{47.68$\pm$3.93 $\bigstar$} & 0.01$\pm$0.01 X & 12.37$\pm$3.72 & 42.09$\pm$5.89 X \\
grace random+scom & 66.39$\pm$2.51 & 70.74$\pm$2.07 $\bigstar$ & 46.48$\pm$3.04 & 1.05$\pm$3.13 X & 9.13$\pm$5.56 X & 40.68$\pm$2.12 X \\
grace random+deg & 59.93$\pm$4.64 & 71.01$\pm$2.06 $\bigstar$ & 46.27$\pm$3.7 & 0.0$\pm$0.0 X & 12.09$\pm$4.1 & 41.78$\pm$3.65 X \\
grace deg+scom & 59.45$\pm$5.58 & 69.95$\pm$2.44 & 46.43$\pm$6.04 & 1.17$\pm$2.72 X & 5.06$\pm$5.51 X & 43.32$\pm$4.92 \\
bgrl random & 65.92$\pm$2.07 & 69.34$\pm$1.69 & 45.29$\pm$2.1 X & 10.2$\pm$4.7 & 20.96$\pm$7.72 & \color{red}{47.53$\pm$5.64 $\bigstar$} \\
bgrl deg & 68.39$\pm$2.1 & \color{blue}{71.55$\pm$5.48} & 44.27$\pm$3.45 X & 11.71$\pm$4.53 $\bigstar$ & 22.85$\pm$7.08 $\bigstar$ & 36.06$\pm$13.38 X \\
bgrl pr & \color{violet}{68.64$\pm$1.61} & 68.13$\pm$1.62 & 46.41$\pm$3.45 $\bigstar$ & \color{violet}{12.27$\pm$4.55 $\bigstar$} & 21.7$\pm$7.32 & \color{blue}{46.05$\pm$11.1 $\bigstar$} \\
bgrl evc & 68.58$\pm$2.88 & 68.26$\pm$1.34 & 45.65$\pm$3.47 & 12.07$\pm$4.46 & \color{blue}{24.78$\pm$3.47 $\bigstar$} & \color{violet}{45.0$\pm$12.14 $\bigstar$} \\
bgrl scom & 66.73$\pm$2.01 & 68.86$\pm$2.19 & 47.16$\pm$2.9 & 9.03$\pm$6.45 & \color{violet}{22.98$\pm$5.21 $\bigstar$} & 41.07$\pm$9.99 X \\
bgrl random+scom & 65.3$\pm$3.37 & 69.42$\pm$1.32 & 46.66$\pm$4.24 & \color{red}{13.1$\pm$2.36 $\bigstar$} & 21.0$\pm$6.17 $\bigstar$ & 43.49$\pm$10.25 \\
bgrl random+deg & \color{red}{69.69$\pm$2.47 $\bigstar$} & \color{red}{71.84$\pm$5.03} & 46.35$\pm$4.08 & 8.94$\pm$5.8 & 22.66$\pm$4.68 & 42.05$\pm$12.22 \\
bgrl deg+scom & \color{blue}{68.71$\pm$2.76 $\bigstar$} & \color{violet}{71.29$\pm$3.68} & 47.35$\pm$2.53 $\bigstar$ & \color{blue}{13.06$\pm$4.51 $\bigstar$} & \color{red}{25.07$\pm$2.53 $\bigstar$} & 44.76$\pm$12.55 $\bigstar$ \\
\bottomrule
\end{tabular}

}

,FINAL_cora_res.csv,FINAL_citeseer_res.csv,FINAL_pubmed_res.csv,FINAL_computers_res.csv,FINAL_photo_res.csv,FINAL_cs_res.csv
baseline,61.48$\pm$2.88,0.0$\pm$0.0 X,\color{red}{47.89$\pm$3.19 $\bigstar$},1.67$\pm$3.33 X,10.12$\pm$10.85,41.75$\pm$4.96 X
grace random,66.7$\pm$2.83,70.76$\pm$1.82,45.93$\pm$4.66 X,0.64$\pm$1.92 X,9.82$\pm$6.0,42.56$\pm$5.09
grace deg,54.14$\pm$5.76 X,69.44$\pm$2.37,\color{blue}{47.68$\pm$4.36 $\bigstar$},0.01$\pm$0.01 X,9.94$\pm$6.55,42.66$\pm$3.74 X
grace pr,53.7$\pm$4.41 X,69.86$\pm$1.89,45.21$\pm$5.78,0.73$\pm$2.01 X,9.32$\pm$6.93,43.03$\pm$5.15
grace evc,53.33$\pm$4.7 X,70.24$\pm$2.51,45.68$\pm$3.77 X,5.68$\pm$5.15,7.07$\pm$6.17 X,42.75$\pm$4.6 X
grace scom,66.33$\pm$3.98,70.98$\pm$1.8 $\bigstar$,\color{violet}{47.68$\pm$3.93 $\bigstar$},0.01$\pm$0.01 X,12.37$\pm$3.72,42.09$\pm$5.89 X
grace random+scom,66.39$\pm$2.51,70.74$\pm$2.07 $\bigstar$,46.48$\pm$3.04,1.05$\pm$3.13 X,9.13$\pm$5.56 X,40.68$\pm$2.12 X
grace random+deg,59.93$\pm$4.64,71.01$\pm$2.06 $\bigstar$,46.27$\pm$3.7,0.0$\pm$0.0 X,12.09$\pm$4.1,41.78$\pm$3.65 X
grace deg+scom,59.45$\pm$5.58,69.95$\pm$2.44,46.43$\pm$6.04,1.17$\pm$2.72 X,5.06$\pm$5.51 X,43.32$\pm$4.92
bgrl random,65.92$\pm$2.07,69.34$\pm$1.69,45.29$\pm$2.1 X,10.2$\pm$4.7,20.96$\pm$7.72,\color{red}{47.53$\pm$5.64 $\bigstar$}
bgrl deg,68.39$\pm$2.1,\color{blue}{71.55$\pm$5.48},44.27$\pm$3.45 X,11.71$\pm$4.53 $\bigstar$,22.85$\pm$7.08 $\bigstar$,36.06$\pm$13.38 X
bgrl pr,\color{violet}{68.64$\pm$1.61},68.13$\pm$1.62,46.41$\pm$3.45 $\bigstar$,\color{violet}{12.27$\pm$4.55 $\bigstar$},21.7$\pm$7.32,\color{blue}{46.05$\pm$11.1 $\bigstar$}
bgrl evc,68.58$\pm$2.88,68.26$\pm$1.34,45.65$\pm$3.47,12.07$\pm$4.46,\color{blue}{24.78$\pm$3.47 $\bigstar$},\color{violet}{45.0$\pm$12.14 $\bigstar$}
bgrl scom,66.73$\pm$2.01,68.86$\pm$2.19,47.16$\pm$2.9,9.03$\pm$6.45,\color{violet}{22.98$\pm$5.21 $\bigstar$},41.07$\pm$9.99 X
bgrl random+scom,65.3$\pm$3.37,69.42$\pm$1.32,46.66$\pm$4.24,\color{red}{13.1$\pm$2.36 $\bigstar$},21.0$\pm$6.17 $\bigstar$,43.49$\pm$10.25
bgrl random+deg,\color{red}{69.69$\pm$2.47 $\bigstar$},\color{red}{71.84$\pm$5.03},46.35$\pm$4.08,8.94$\pm$5.8,22.66$\pm$4.68,42.05$\pm$12.22
bgrl deg+scom,\color{blue}{68.71$\pm$2.76 $\bigstar$},\color{violet}{71.29$\pm$3.68},47.35$\pm$2.53 $\bigstar$,\color{blue}{13.06$\pm$4.51 $\bigstar$},\color{red}{25.07$\pm$2.53 $\bigstar$},44.76$\pm$12.55 $\bigstar$

In [9]:
# score struct
names = ['FINAL_struct_cora_res.csv',
'FINAL_struct_citeseer_res.csv',
'FINAL_struct_pubmed_res.csv',
'FINAL_struct_computers_res.csv',
'FINAL_struct_photo_res.csv',
'FINAL_struct_cs_res.csv']
filtres = ['grace','bgrl']
print("                             ROCAUC                      ")
all_data, all_res = ut.mix_dataset(names, 'ROCAUC', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             AP                      ")
all_data, all_res = ut.mix_dataset(names, 'AP', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@100                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@100', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50', filtres)
display(ut.tex_table(all_data, all_res).T)
print("                             Hits@20                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@20', filtres)
display(ut.tex_table(all_data, all_res).T)

                             ROCAUC
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv & FINAL_struct_pubmed_res.csv & FINAL_struct_computers_res.csv & FINAL_struct_photo_res.csv & FINAL_struct_cs_res.csv \\
\midrule
grace random & 78.14$\pm$0.73 & 74.3$\pm$1.75 & 72.9$\pm$0.55 & \color{violet}{98.62$\pm$0.04} & \color{violet}{98.9$\pm$0.04} & 94.1$\pm$0.26 \\
grace deg & \color{red}{83.5$\pm$1.03 $\bigstar$} & \color{red}{78.6$\pm$2.08 $\bigstar$} & \color{violet}{74.47$\pm$1.15} & 98.47$\pm$0.13 & 98.89$\pm$0.05 & \color{blue}{95.12$\pm$0.67 $\bigstar$} \\
grace pr & 78.34$\pm$1.28 & 71.8$\pm$2.17 & 72.56$\pm$0.89 & \color{blue}{98.66$\pm$0.05 $\bigstar$} & \color{blue}{98.92$\pm$0.04 $\bigstar$} & 94.74$\pm$0.53 \\
grace evc & 77.62$\pm$0.93 & 73.87$\pm$1.81 & \color{red}{76.31$\pm$0.92 $\bigstar$} & \color{red}{98.68$\pm$0.04 $\bigstar$} & \color{red}{98.93$\pm$0.04 $\bigstar$} & \color{red}{95.59$\pm$0.13 $\bigstar$} \\
grace scom & \color{violet}{80.97$\pm$1.31} & 76.7$\pm$1.83 & \color{blue}{74.65$\pm$2.21} & 98.5$\pm$0.16 & 98.87$\pm$0.04 & 94.88$\pm$0.3 \\
grace random+scom & 78.57$\pm$0.93 & 73.96$\pm$1.76 & 72.86$\pm$0.27 & 98.55$\pm$0.05 & 98.87$\pm$0.04 & 93.97$\pm$0.28 \\
grace random+deg & \color{blue}{81.72$\pm$1.39 $\bigstar$} & 76.59$\pm$1.65 & 73.61$\pm$0.73 & 98.41$\pm$0.14 & 98.73$\pm$0.06 & 94.84$\pm$0.45 \\
grace deg+scom & 80.93$\pm$1.21 & \color{violet}{77.06$\pm$1.43} & 73.78$\pm$0.88 & 98.37$\pm$0.11 & 98.7$\pm$0.02 & \color{violet}{94.95$\pm$0.64} \\
bgrl random & 76.49$\pm$1.13 & 70.36$\pm$1.36 & 68.99$\pm$0.48 X & 97.83$\pm$0.08 X & 98.19$\pm$0.2 & 91.89$\pm$0.11 X \\
bgrl deg & 80.3$\pm$0.8 & \color{blue}{77.59$\pm$3.15} & 70.07$\pm$1.8 & 98.53$\pm$0.18 & 98.87$\pm$0.04 & 93.42$\pm$1.13 \\
bgrl pr & 73.97$\pm$0.82 X & 67.46$\pm$2.1 X & 68.43$\pm$0.82 X & 98.0$\pm$0.07 & 98.22$\pm$0.07 & 92.35$\pm$0.26 \\
bgrl evc & 73.96$\pm$0.46 X & 70.49$\pm$1.78 & 73.25$\pm$0.49 & 97.95$\pm$0.04 & 98.17$\pm$0.09 & 94.25$\pm$0.79 \\
bgrl scom & 77.74$\pm$0.8 & 72.4$\pm$1.31 & 69.85$\pm$0.77 & 97.8$\pm$0.29 X & 98.2$\pm$0.3 & 92.29$\pm$0.2 \\
bgrl random+scom & 76.23$\pm$0.99 & 69.96$\pm$1.57 & 69.32$\pm$0.34 & 97.63$\pm$0.16 X & 97.89$\pm$0.14 X & 91.91$\pm$0.21 X \\
bgrl random+deg & 79.47$\pm$0.95 & 71.26$\pm$1.25 & 70.66$\pm$1.39 & 98.46$\pm$0.21 & 98.77$\pm$0.16 & 93.23$\pm$1.03 \\
bgrl deg+scom & 79.14$\pm$0.99 & 69.64$\pm$1.56 X & 70.17$\pm$1.5 & 98.31$\pm$0.49 & 98.63$\pm$0.26 & 93.03$\pm$0.83 \\
\bottomrule
\end{tabular}

}

,FINAL_struct_cora_res.csv,FINAL_struct_citeseer_res.csv,FINAL_struct_pubmed_res.csv,FINAL_struct_computers_res.csv,FINAL_struct_photo_res.csv,FINAL_struct_cs_res.csv
grace random,78.14$\pm$0.73,74.3$\pm$1.75,72.9$\pm$0.55,\color{violet}{98.62$\pm$0.04},\color{violet}{98.9$\pm$0.04},94.1$\pm$0.26
grace deg,\color{red}{83.5$\pm$1.03 $\bigstar$},\color{red}{78.6$\pm$2.08 $\bigstar$},\color{violet}{74.47$\pm$1.15},98.47$\pm$0.13,98.89$\pm$0.05,\color{blue}{95.12$\pm$0.67 $\bigstar$}
grace pr,78.34$\pm$1.28,71.8$\pm$2.17,72.56$\pm$0.89,\color{blue}{98.66$\pm$0.05 $\bigstar$},\color{blue}{98.92$\pm$0.04 $\bigstar$},94.74$\pm$0.53
grace evc,77.62$\pm$0.93,73.87$\pm$1.81,\color{red}{76.31$\pm$0.92 $\bigstar$},\color{red}{98.68$\pm$0.04 $\bigstar$},\color{red}{98.93$\pm$0.04 $\bigstar$},\color{red}{95.59$\pm$0.13 $\bigstar$}
grace scom,\color{violet}{80.97$\pm$1.31},76.7$\pm$1.83,\color{blue}{74.65$\pm$2.21},98.5$\pm$0.16,98.87$\pm$0.04,94.88$\pm$0.3
grace random+scom,78.57$\pm$0.93,73.96$\pm$1.76,72.86$\pm$0.27,98.55$\pm$0.05,98.87$\pm$0.04,93.97$\pm$0.28
grace random+deg,\color{blue}{81.72$\pm$1.39 $\bigstar$},76.59$\pm$1.65,73.61$\pm$0.73,98.41$\pm$0.14,98.73$\pm$0.06,94.84$\pm$0.45
grace deg+scom,80.93$\pm$1.21,\color{violet}{77.06$\pm$1.43},73.78$\pm$0.88,98.37$\pm$0.11,98.7$\pm$0.02,\color{violet}{94.95$\pm$0.64}
bgrl random,76.49$\pm$1.13,70.36$\pm$1.36,68.99$\pm$0.48 X,97.83$\pm$0.08 X,98.19$\pm$0.2,91.89$\pm$0.11 X
bgrl deg,80.3$\pm$0.8,\color{blue}{77.59$\pm$3.15},70.07$\pm$1.8,98.53$\pm$0.18,98.87$\pm$0.04,93.42$\pm$1.13
bgrl pr,73.97$\pm$0.82 X,67.46$\pm$2.1 X,68.43$\pm$0.82 X,98.0$\pm$0.07,98.22$\pm$0.07,92.35$\pm$0.26
bgrl evc,73.96$\pm$0.46 X,70.49$\pm$1.78,73.25$\pm$0.49,97.95$\pm$0.04,98.17$\pm$0.09,94.25$\pm$0.79
bgrl scom,77.74$\pm$0.8,72.4$\pm$1.31,69.85$\pm$0.77,97.8$\pm$0.29 X,98.2$\pm$0.3,92.29$\pm$0.2
bgrl random+scom,76.23$\pm$0.99,69.96$\pm$1.57,69.32$\pm$0.34,97.63$\pm$0.16 X,97.89$\pm$0.14 X,91.91$\pm$0.21 X
bgrl random+deg,79.47$\pm$0.95,71.26$\pm$1.25,70.66$\pm$1.39,98.46$\pm$0.21,98.77$\pm$0.16,93.23$\pm$1.03
bgrl deg+scom,79.14$\pm$0.99,69.64$\pm$1.56 X,70.17$\pm$1.5,98.31$\pm$0.49,98.63$\pm$0.26,93.03$\pm$0.83

                             AP
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv & FINAL_struct_pubmed_res.csv & FINAL_struct_computers_res.csv & FINAL_struct_photo_res.csv & FINAL_struct_cs_res.csv \\
\midrule
grace random & 84.92$\pm$0.61 & 81.59$\pm$1.26 & 83.3$\pm$0.36 & \color{violet}{98.67$\pm$0.05 $\bigstar$} & \color{red}{98.91$\pm$0.05 $\bigstar$} & 95.95$\pm$0.15 \\
grace deg & \color{red}{87.67$\pm$0.69 $\bigstar$} & \color{blue}{83.26$\pm$1.23 $\bigstar$} & \color{blue}{84.13$\pm$0.73} & 98.38$\pm$0.18 & 98.79$\pm$0.08 & \color{blue}{96.34$\pm$0.26 $\bigstar$} \\
grace pr & 84.91$\pm$0.89 & 80.46$\pm$1.4 & 82.94$\pm$0.55 & \color{red}{98.7$\pm$0.06 $\bigstar$} & \color{blue}{98.91$\pm$0.04 $\bigstar$} & 96.21$\pm$0.26 \\
grace evc & 84.59$\pm$0.69 & 81.22$\pm$1.32 & \color{red}{84.9$\pm$0.45 $\bigstar$} & \color{blue}{98.7$\pm$0.05 $\bigstar$} & \color{violet}{98.91$\pm$0.05 $\bigstar$} & \color{red}{96.53$\pm$0.12 $\bigstar$} \\
grace scom & 86.17$\pm$0.95 & \color{violet}{82.81$\pm$1.19 $\bigstar$} & \color{violet}{83.87$\pm$1.03} & 98.55$\pm$0.14 & 98.84$\pm$0.07 & 96.24$\pm$0.15 \\
grace random+scom & 85.25$\pm$0.71 & 81.33$\pm$1.13 & 83.23$\pm$0.14 & 98.62$\pm$0.06 & 98.88$\pm$0.04 & 95.84$\pm$0.16 \\
grace random+deg & \color{blue}{87.06$\pm$0.87 $\bigstar$} & 82.09$\pm$0.92 & 83.85$\pm$0.45 & 98.39$\pm$0.16 & 98.65$\pm$0.07 & 96.08$\pm$0.22 \\
grace deg+scom & \color{violet}{86.61$\pm$0.82} & 82.03$\pm$0.95 & 83.54$\pm$0.55 & 98.35$\pm$0.15 & 98.63$\pm$0.04 & \color{violet}{96.26$\pm$0.27} \\
bgrl random & 82.67$\pm$0.71 & 79.22$\pm$0.93 & 78.76$\pm$0.33 & 98.12$\pm$0.08 X & 98.38$\pm$0.18 & 94.49$\pm$0.06 X \\
bgrl deg & 86.24$\pm$0.55 & \color{red}{83.54$\pm$1.87 $\bigstar$} & 80.59$\pm$2.31 & 98.5$\pm$0.22 & 98.84$\pm$0.05 & 95.48$\pm$0.74 \\
bgrl pr & 81.35$\pm$0.59 X & 77.88$\pm$1.27 X & 78.01$\pm$0.51 X & 98.25$\pm$0.07 & 98.4$\pm$0.08 & 94.79$\pm$0.19 \\
bgrl evc & 81.38$\pm$0.56 X & 79.33$\pm$1.09 & 83.17$\pm$0.28 & 98.19$\pm$0.03 & 98.3$\pm$0.1 X & 95.69$\pm$1.11 \\
bgrl scom & 83.34$\pm$0.67 & 80.0$\pm$0.89 & 78.86$\pm$0.32 & 98.06$\pm$0.24 & 98.34$\pm$0.27 & 94.67$\pm$0.11 \\
bgrl random+scom & 82.55$\pm$0.7 & 79.06$\pm$1.04 & 79.07$\pm$0.28 & 97.94$\pm$0.14 X & 98.14$\pm$0.12 X & 94.5$\pm$0.11 X \\
bgrl random+deg & 85.87$\pm$0.53 & 80.12$\pm$0.93 & 80.95$\pm$1.72 & 98.44$\pm$0.25 & 98.74$\pm$0.22 & 95.37$\pm$0.68 \\
bgrl deg+scom & 85.64$\pm$0.67 & 79.12$\pm$0.96 & 80.55$\pm$1.89 & 98.26$\pm$0.55 & 98.56$\pm$0.36 & 95.28$\pm$0.58 \\
\bottomrule
\end{tabular}

}

,FINAL_struct_cora_res.csv,FINAL_struct_citeseer_res.csv,FINAL_struct_pubmed_res.csv,FINAL_struct_computers_res.csv,FINAL_struct_photo_res.csv,FINAL_struct_cs_res.csv
grace random,84.92$\pm$0.61,81.59$\pm$1.26,83.3$\pm$0.36,\color{violet}{98.67$\pm$0.05 $\bigstar$},\color{red}{98.91$\pm$0.05 $\bigstar$},95.95$\pm$0.15
grace deg,\color{red}{87.67$\pm$0.69 $\bigstar$},\color{blue}{83.26$\pm$1.23 $\bigstar$},\color{blue}{84.13$\pm$0.73},98.38$\pm$0.18,98.79$\pm$0.08,\color{blue}{96.34$\pm$0.26 $\bigstar$}
grace pr,84.91$\pm$0.89,80.46$\pm$1.4,82.94$\pm$0.55,\color{red}{98.7$\pm$0.06 $\bigstar$},\color{blue}{98.91$\pm$0.04 $\bigstar$},96.21$\pm$0.26
grace evc,84.59$\pm$0.69,81.22$\pm$1.32,\color{red}{84.9$\pm$0.45 $\bigstar$},\color{blue}{98.7$\pm$0.05 $\bigstar$},\color{violet}{98.91$\pm$0.05 $\bigstar$},\color{red}{96.53$\pm$0.12 $\bigstar$}
grace scom,86.17$\pm$0.95,\color{violet}{82.81$\pm$1.19 $\bigstar$},\color{violet}{83.87$\pm$1.03},98.55$\pm$0.14,98.84$\pm$0.07,96.24$\pm$0.15
grace random+scom,85.25$\pm$0.71,81.33$\pm$1.13,83.23$\pm$0.14,98.62$\pm$0.06,98.88$\pm$0.04,95.84$\pm$0.16
grace random+deg,\color{blue}{87.06$\pm$0.87 $\bigstar$},82.09$\pm$0.92,83.85$\pm$0.45,98.39$\pm$0.16,98.65$\pm$0.07,96.08$\pm$0.22
grace deg+scom,\color{violet}{86.61$\pm$0.82},82.03$\pm$0.95,83.54$\pm$0.55,98.35$\pm$0.15,98.63$\pm$0.04,\color{violet}{96.26$\pm$0.27}
bgrl random,82.67$\pm$0.71,79.22$\pm$0.93,78.76$\pm$0.33,98.12$\pm$0.08 X,98.38$\pm$0.18,94.49$\pm$0.06 X
bgrl deg,86.24$\pm$0.55,\color{red}{83.54$\pm$1.87 $\bigstar$},80.59$\pm$2.31,98.5$\pm$0.22,98.84$\pm$0.05,95.48$\pm$0.74
bgrl pr,81.35$\pm$0.59 X,77.88$\pm$1.27 X,78.01$\pm$0.51 X,98.25$\pm$0.07,98.4$\pm$0.08,94.79$\pm$0.19
bgrl evc,81.38$\pm$0.56 X,79.33$\pm$1.09,83.17$\pm$0.28,98.19$\pm$0.03,98.3$\pm$0.1 X,95.69$\pm$1.11
bgrl scom,83.34$\pm$0.67,80.0$\pm$0.89,78.86$\pm$0.32,98.06$\pm$0.24,98.34$\pm$0.27,94.67$\pm$0.11
bgrl random+scom,82.55$\pm$0.7,79.06$\pm$1.04,79.07$\pm$0.28,97.94$\pm$0.14 X,98.14$\pm$0.12 X,94.5$\pm$0.11 X
bgrl random+deg,85.87$\pm$0.53,80.12$\pm$0.93,80.95$\pm$1.72,98.44$\pm$0.25,98.74$\pm$0.22,95.37$\pm$0.68
bgrl deg+scom,85.64$\pm$0.67,79.12$\pm$0.96,80.55$\pm$1.89,98.26$\pm$0.55,98.56$\pm$0.36,95.28$\pm$0.58

                             Hits@100
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv & FINAL_struct_pubmed_res.csv & FINAL_struct_computers_res.csv & FINAL_struct_photo_res.csv & FINAL_struct_cs_res.csv \\
\midrule
grace random & 64.0$\pm$1.45 & 56.03$\pm$2.15 & \color{violet}{54.73$\pm$1.2 $\bigstar$} & 47.17$\pm$1.71 $\bigstar$ & \color{red}{65.58$\pm$2.29 $\bigstar$} & 71.25$\pm$2.24 \\
grace deg & \color{violet}{67.75$\pm$1.38 $\bigstar$} & \color{violet}{57.79$\pm$3.13} & \color{blue}{55.22$\pm$1.9 $\bigstar$} & 38.8$\pm$3.71 X & 59.1$\pm$2.89 X & 64.85$\pm$5.76 \\
grace pr & 64.4$\pm$1.29 & 56.1$\pm$2.05 & 53.9$\pm$1.0 & \color{red}{47.7$\pm$2.34 $\bigstar$} & \color{blue}{64.56$\pm$1.82 $\bigstar$} & 70.39$\pm$1.89 \\
grace evc & 64.14$\pm$1.5 & 55.62$\pm$1.62 & 54.17$\pm$2.57 & \color{blue}{47.63$\pm$1.78 $\bigstar$} & 64.28$\pm$2.42 & 60.86$\pm$1.9 X \\
grace scom & 64.73$\pm$1.52 & 57.0$\pm$1.76 & 54.16$\pm$1.15 & 45.25$\pm$3.26 & 63.58$\pm$2.72 & 69.88$\pm$1.56 \\
grace random+scom & 65.02$\pm$1.7 & 55.64$\pm$1.86 & 54.1$\pm$0.75 & \color{violet}{47.56$\pm$2.24 $\bigstar$} & \color{violet}{64.54$\pm$1.58 $\bigstar$} & 69.9$\pm$1.56 \\
grace random+deg & \color{red}{68.42$\pm$2.06 $\bigstar$} & \color{blue}{59.03$\pm$2.54 $\bigstar$} & \color{red}{55.28$\pm$1.76 $\bigstar$} & 41.3$\pm$3.04 & 57.94$\pm$2.44 X & 62.94$\pm$7.84 \\
grace deg+scom & \color{blue}{67.83$\pm$1.82 $\bigstar$} & \color{red}{59.82$\pm$2.46 $\bigstar$} & 53.14$\pm$2.65 & 40.18$\pm$3.89 & 57.21$\pm$2.39 X & 65.93$\pm$4.32 \\
bgrl random & 56.63$\pm$1.18 X & 52.69$\pm$1.77 X & 41.92$\pm$0.59 & 44.92$\pm$3.36 & 61.07$\pm$3.77 & \color{violet}{72.14$\pm$0.78 $\bigstar$} \\
bgrl deg & 65.8$\pm$1.21 & 57.76$\pm$2.57 & 48.4$\pm$6.81 & 44.14$\pm$5.28 & 62.0$\pm$3.14 & 71.24$\pm$1.55 \\
bgrl pr & 55.54$\pm$1.32 X & 52.19$\pm$1.75 X & 38.52$\pm$0.97 X & 45.98$\pm$2.26 & 62.06$\pm$3.26 & \color{red}{72.4$\pm$0.79 $\bigstar$} \\
bgrl evc & 55.36$\pm$1.18 X & 53.31$\pm$1.76 & 53.48$\pm$0.91 & 44.5$\pm$2.1 & 58.21$\pm$2.29 X & 64.05$\pm$12.2 \\
bgrl scom & 57.3$\pm$1.66 & 52.84$\pm$1.4 X & 40.81$\pm$0.99 X & 42.99$\pm$3.56 & 60.74$\pm$4.68 & 71.68$\pm$0.87 \\
bgrl random+scom & 56.42$\pm$1.64 X & 52.91$\pm$1.68 X & 43.03$\pm$0.97 & 40.48$\pm$3.05 & 59.7$\pm$2.68 & 71.96$\pm$0.43 $\bigstar$ \\
bgrl random+deg & 65.61$\pm$1.13 & 54.88$\pm$1.73 & 48.42$\pm$4.89 & 41.61$\pm$4.53 & 60.4$\pm$4.84 & 71.97$\pm$3.03 $\bigstar$ \\
bgrl deg+scom & 64.87$\pm$1.43 & 53.55$\pm$1.77 & 47.99$\pm$5.33 & 39.59$\pm$7.65 & 56.9$\pm$7.76 & \color{blue}{72.16$\pm$1.03 $\bigstar$} \\
\bottomrule
\end{tabular}

}

,FINAL_struct_cora_res.csv,FINAL_struct_citeseer_res.csv,FINAL_struct_pubmed_res.csv,FINAL_struct_computers_res.csv,FINAL_struct_photo_res.csv,FINAL_struct_cs_res.csv
grace random,64.0$\pm$1.45,56.03$\pm$2.15,\color{violet}{54.73$\pm$1.2 $\bigstar$},47.17$\pm$1.71 $\bigstar$,\color{red}{65.58$\pm$2.29 $\bigstar$},71.25$\pm$2.24
grace deg,\color{violet}{67.75$\pm$1.38 $\bigstar$},\color{violet}{57.79$\pm$3.13},\color{blue}{55.22$\pm$1.9 $\bigstar$},38.8$\pm$3.71 X,59.1$\pm$2.89 X,64.85$\pm$5.76
grace pr,64.4$\pm$1.29,56.1$\pm$2.05,53.9$\pm$1.0,\color{red}{47.7$\pm$2.34 $\bigstar$},\color{blue}{64.56$\pm$1.82 $\bigstar$},70.39$\pm$1.89
grace evc,64.14$\pm$1.5,55.62$\pm$1.62,54.17$\pm$2.57,\color{blue}{47.63$\pm$1.78 $\bigstar$},64.28$\pm$2.42,60.86$\pm$1.9 X
grace scom,64.73$\pm$1.52,57.0$\pm$1.76,54.16$\pm$1.15,45.25$\pm$3.26,63.58$\pm$2.72,69.88$\pm$1.56
grace random+scom,65.02$\pm$1.7,55.64$\pm$1.86,54.1$\pm$0.75,\color{violet}{47.56$\pm$2.24 $\bigstar$},\color{violet}{64.54$\pm$1.58 $\bigstar$},69.9$\pm$1.56
grace random+deg,\color{red}{68.42$\pm$2.06 $\bigstar$},\color{blue}{59.03$\pm$2.54 $\bigstar$},\color{red}{55.28$\pm$1.76 $\bigstar$},41.3$\pm$3.04,57.94$\pm$2.44 X,62.94$\pm$7.84
grace deg+scom,\color{blue}{67.83$\pm$1.82 $\bigstar$},\color{red}{59.82$\pm$2.46 $\bigstar$},53.14$\pm$2.65,40.18$\pm$3.89,57.21$\pm$2.39 X,65.93$\pm$4.32
bgrl random,56.63$\pm$1.18 X,52.69$\pm$1.77 X,41.92$\pm$0.59,44.92$\pm$3.36,61.07$\pm$3.77,\color{violet}{72.14$\pm$0.78 $\bigstar$}
bgrl deg,65.8$\pm$1.21,57.76$\pm$2.57,48.4$\pm$6.81,44.14$\pm$5.28,62.0$\pm$3.14,71.24$\pm$1.55
bgrl pr,55.54$\pm$1.32 X,52.19$\pm$1.75 X,38.52$\pm$0.97 X,45.98$\pm$2.26,62.06$\pm$3.26,\color{red}{72.4$\pm$0.79 $\bigstar$}
bgrl evc,55.36$\pm$1.18 X,53.31$\pm$1.76,53.48$\pm$0.91,44.5$\pm$2.1,58.21$\pm$2.29 X,64.05$\pm$12.2
bgrl scom,57.3$\pm$1.66,52.84$\pm$1.4 X,40.81$\pm$0.99 X,42.99$\pm$3.56,60.74$\pm$4.68,71.68$\pm$0.87
bgrl random+scom,56.42$\pm$1.64 X,52.91$\pm$1.68 X,43.03$\pm$0.97,40.48$\pm$3.05,59.7$\pm$2.68,71.96$\pm$0.43 $\bigstar$
bgrl random+deg,65.61$\pm$1.13,54.88$\pm$1.73,48.42$\pm$4.89,41.61$\pm$4.53,60.4$\pm$4.84,71.97$\pm$3.03 $\bigstar$
bgrl deg+scom,64.87$\pm$1.43,53.55$\pm$1.77,47.99$\pm$5.33,39.59$\pm$7.65,56.9$\pm$7.76,\color{blue}{72.16$\pm$1.03 $\bigstar$}

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv & FINAL_struct_pubmed_res.csv & FINAL_struct_computers_res.csv & FINAL_struct_photo_res.csv & FINAL_struct_cs_res.csv \\
\midrule
grace random & 60.67$\pm$1.42 & 53.31$\pm$2.03 & \color{blue}{48.92$\pm$1.85 $\bigstar$} & \color{red}{33.79$\pm$2.32 $\bigstar$} & \color{red}{49.77$\pm$3.72 $\bigstar$} & 61.51$\pm$2.28 \\
grace deg & 62.02$\pm$1.7 $\bigstar$ & 52.53$\pm$2.22 & \color{violet}{48.63$\pm$2.47 $\bigstar$} & 26.42$\pm$4.12 X & 44.13$\pm$3.48 & 52.7$\pm$6.78 X \\
grace pr & 60.52$\pm$1.31 & 53.04$\pm$1.87 & 47.72$\pm$1.95 & \color{violet}{33.59$\pm$2.6 $\bigstar$} & \color{blue}{48.98$\pm$3.16 $\bigstar$} & 60.06$\pm$3.52 \\
grace evc & 59.93$\pm$0.93 & 52.75$\pm$1.78 & 46.36$\pm$3.62 & 33.47$\pm$1.75 $\bigstar$ & 48.42$\pm$1.87 $\bigstar$ & 48.89$\pm$2.81 X \\
grace scom & 60.77$\pm$1.77 & \color{violet}{53.95$\pm$1.92 $\bigstar$} & 48.05$\pm$2.12 & 32.0$\pm$3.37 & 47.81$\pm$4.4 & 59.5$\pm$1.91 \\
grace random+scom & 61.76$\pm$1.5 $\bigstar$ & 52.79$\pm$1.71 & 48.61$\pm$1.51 & \color{blue}{33.71$\pm$2.51 $\bigstar$} & \color{violet}{48.59$\pm$2.83 $\bigstar$} & 59.29$\pm$3.23 \\
grace random+deg & \color{blue}{62.13$\pm$1.97 $\bigstar$} & \color{blue}{54.0$\pm$2.52 $\bigstar$} & \color{red}{49.1$\pm$1.87 $\bigstar$} & 28.62$\pm$2.87 & 43.01$\pm$3.29 X & 51.1$\pm$9.9 \\
grace deg+scom & \color{red}{62.29$\pm$1.62 $\bigstar$} & \color{red}{54.75$\pm$2.17 $\bigstar$} & 46.51$\pm$3.8 & 27.66$\pm$4.76 X & 43.23$\pm$3.24 X & 54.53$\pm$5.67 \\
bgrl random & 50.93$\pm$1.72 X & 49.63$\pm$1.87 X & 38.29$\pm$0.88 & 30.52$\pm$3.62 & 46.35$\pm$3.91 & \color{violet}{65.79$\pm$0.96 $\bigstar$} \\
bgrl deg & \color{violet}{62.03$\pm$1.35 $\bigstar$} & 52.49$\pm$1.95 & 44.51$\pm$6.33 & 31.39$\pm$4.16 & 47.78$\pm$2.91 & 63.34$\pm$2.88 \\
bgrl pr & 50.03$\pm$1.36 X & 49.29$\pm$1.51 X & 35.37$\pm$1.12 X & 31.72$\pm$1.92 & 45.63$\pm$4.02 & \color{red}{66.57$\pm$1.2 $\bigstar$} \\
bgrl evc & 50.55$\pm$1.41 X & 50.13$\pm$1.61 X & 48.28$\pm$1.45 & 30.61$\pm$2.54 & 43.71$\pm$2.5 X & 54.05$\pm$11.79 \\
bgrl scom & 51.88$\pm$1.51 & 49.34$\pm$1.86 X & 36.65$\pm$1.17 X & 28.24$\pm$2.71 X & 44.4$\pm$4.1 & 65.34$\pm$1.58 \\
bgrl random+scom & 51.48$\pm$1.8 X & 49.91$\pm$1.78 X & 39.46$\pm$0.8 & 26.92$\pm$3.29 X & 42.51$\pm$2.58 X & \color{blue}{66.11$\pm$1.23 $\bigstar$} \\
bgrl random+deg & 61.72$\pm$1.32 & 52.09$\pm$1.63 & 43.75$\pm$4.08 & 28.97$\pm$4.76 & 46.24$\pm$4.32 & 63.73$\pm$4.61 \\
bgrl deg+scom & 60.79$\pm$1.06 & 51.14$\pm$1.57 & 43.69$\pm$4.71 & 26.95$\pm$6.21 & 43.01$\pm$8.21 & 64.95$\pm$1.05 \\
\bottomrule
\end{tabular}

}

,FINAL_struct_cora_res.csv,FINAL_struct_citeseer_res.csv,FINAL_struct_pubmed_res.csv,FINAL_struct_computers_res.csv,FINAL_struct_photo_res.csv,FINAL_struct_cs_res.csv
grace random,60.67$\pm$1.42,53.31$\pm$2.03,\color{blue}{48.92$\pm$1.85 $\bigstar$},\color{red}{33.79$\pm$2.32 $\bigstar$},\color{red}{49.77$\pm$3.72 $\bigstar$},61.51$\pm$2.28
grace deg,62.02$\pm$1.7 $\bigstar$,52.53$\pm$2.22,\color{violet}{48.63$\pm$2.47 $\bigstar$},26.42$\pm$4.12 X,44.13$\pm$3.48,52.7$\pm$6.78 X
grace pr,60.52$\pm$1.31,53.04$\pm$1.87,47.72$\pm$1.95,\color{violet}{33.59$\pm$2.6 $\bigstar$},\color{blue}{48.98$\pm$3.16 $\bigstar$},60.06$\pm$3.52
grace evc,59.93$\pm$0.93,52.75$\pm$1.78,46.36$\pm$3.62,33.47$\pm$1.75 $\bigstar$,48.42$\pm$1.87 $\bigstar$,48.89$\pm$2.81 X
grace scom,60.77$\pm$1.77,\color{violet}{53.95$\pm$1.92 $\bigstar$},48.05$\pm$2.12,32.0$\pm$3.37,47.81$\pm$4.4,59.5$\pm$1.91
grace random+scom,61.76$\pm$1.5 $\bigstar$,52.79$\pm$1.71,48.61$\pm$1.51,\color{blue}{33.71$\pm$2.51 $\bigstar$},\color{violet}{48.59$\pm$2.83 $\bigstar$},59.29$\pm$3.23
grace random+deg,\color{blue}{62.13$\pm$1.97 $\bigstar$},\color{blue}{54.0$\pm$2.52 $\bigstar$},\color{red}{49.1$\pm$1.87 $\bigstar$},28.62$\pm$2.87,43.01$\pm$3.29 X,51.1$\pm$9.9
grace deg+scom,\color{red}{62.29$\pm$1.62 $\bigstar$},\color{red}{54.75$\pm$2.17 $\bigstar$},46.51$\pm$3.8,27.66$\pm$4.76 X,43.23$\pm$3.24 X,54.53$\pm$5.67
bgrl random,50.93$\pm$1.72 X,49.63$\pm$1.87 X,38.29$\pm$0.88,30.52$\pm$3.62,46.35$\pm$3.91,\color{violet}{65.79$\pm$0.96 $\bigstar$}
bgrl deg,\color{violet}{62.03$\pm$1.35 $\bigstar$},52.49$\pm$1.95,44.51$\pm$6.33,31.39$\pm$4.16,47.78$\pm$2.91,63.34$\pm$2.88
bgrl pr,50.03$\pm$1.36 X,49.29$\pm$1.51 X,35.37$\pm$1.12 X,31.72$\pm$1.92,45.63$\pm$4.02,\color{red}{66.57$\pm$1.2 $\bigstar$}
bgrl evc,50.55$\pm$1.41 X,50.13$\pm$1.61 X,48.28$\pm$1.45,30.61$\pm$2.54,43.71$\pm$2.5 X,54.05$\pm$11.79
bgrl scom,51.88$\pm$1.51,49.34$\pm$1.86 X,36.65$\pm$1.17 X,28.24$\pm$2.71 X,44.4$\pm$4.1,65.34$\pm$1.58
bgrl random+scom,51.48$\pm$1.8 X,49.91$\pm$1.78 X,39.46$\pm$0.8,26.92$\pm$3.29 X,42.51$\pm$2.58 X,\color{blue}{66.11$\pm$1.23 $\bigstar$}
bgrl random+deg,61.72$\pm$1.32,52.09$\pm$1.63,43.75$\pm$4.08,28.97$\pm$4.76,46.24$\pm$4.32,63.73$\pm$4.61
bgrl deg+scom,60.79$\pm$1.06,51.14$\pm$1.57,43.69$\pm$4.71,26.95$\pm$6.21,43.01$\pm$8.21,64.95$\pm$1.05

                             Hits@20
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & FINAL_struct_cora_res.csv & FINAL_struct_citeseer_res.csv & FINAL_struct_pubmed_res.csv & FINAL_struct_computers_res.csv & FINAL_struct_photo_res.csv & FINAL_struct_cs_res.csv \\
\midrule
grace random & 55.2$\pm$2.0 & \color{blue}{50.54$\pm$2.4 $\bigstar$} & \color{red}{40.06$\pm$2.28 $\bigstar$} & 18.48$\pm$2.53 $\bigstar$ & \color{red}{32.45$\pm$3.77 $\bigstar$} & 46.53$\pm$4.82 \\
grace deg & 52.64$\pm$2.9 & 48.85$\pm$2.64 & 37.13$\pm$3.79 & 13.96$\pm$3.81 X & 26.81$\pm$5.86 & 36.06$\pm$8.76 \\
grace pr & 54.18$\pm$2.78 & \color{violet}{50.25$\pm$1.92} & \color{blue}{39.45$\pm$2.37 $\bigstar$} & 18.07$\pm$3.01 $\bigstar$ & \color{violet}{30.88$\pm$3.4 $\bigstar$} & 43.4$\pm$4.64 \\
grace evc & 53.32$\pm$1.9 & 49.79$\pm$2.11 & 33.6$\pm$4.52 & \color{blue}{19.12$\pm$3.71 $\bigstar$} & \color{blue}{31.12$\pm$3.07 $\bigstar$} & 30.95$\pm$4.12 X \\
grace scom & 55.17$\pm$1.82 & \color{red}{51.14$\pm$2.17 $\bigstar$} & 38.57$\pm$2.97 & \color{red}{19.18$\pm$4.24 $\bigstar$} & 29.25$\pm$4.98 & 42.91$\pm$3.21 \\
grace random+scom & 55.18$\pm$2.48 & 50.25$\pm$2.09 & 39.31$\pm$2.21 $\bigstar$ & \color{violet}{18.73$\pm$4.05 $\bigstar$} & 29.68$\pm$3.4 & 44.27$\pm$4.87 \\
grace random+deg & 54.75$\pm$3.01 & 49.01$\pm$2.62 & 38.2$\pm$2.52 & 16.75$\pm$3.36 & 26.92$\pm$4.01 & 35.21$\pm$9.12 \\
grace deg+scom & 54.36$\pm$2.81 & 49.64$\pm$2.3 & 36.65$\pm$4.95 & 17.16$\pm$4.75 & 25.85$\pm$3.63 X & 37.95$\pm$6.36 \\
bgrl random & 45.83$\pm$2.07 X & 46.87$\pm$1.74 & 32.71$\pm$1.7 & 14.37$\pm$2.85 X & 27.07$\pm$5.09 & \color{blue}{53.81$\pm$3.74 $\bigstar$} \\
bgrl deg & \color{violet}{55.36$\pm$2.2} & 49.74$\pm$1.96 & 37.52$\pm$4.66 & 16.94$\pm$3.58 & 30.06$\pm$2.65 & 48.7$\pm$4.71 \\
bgrl pr & 44.72$\pm$1.53 X & 46.09$\pm$1.57 X & 29.67$\pm$1.78 X & 16.08$\pm$3.95 & 25.86$\pm$4.89 & \color{violet}{53.08$\pm$2.78 $\bigstar$} \\
bgrl evc & 45.19$\pm$1.95 X & 46.7$\pm$1.62 X & \color{violet}{39.33$\pm$2.14 $\bigstar$} & 15.82$\pm$2.16 & 26.01$\pm$3.77 & 40.85$\pm$10.36 \\
bgrl scom & 45.85$\pm$1.8 X & 46.2$\pm$2.05 X & 30.14$\pm$2.23 X & 13.93$\pm$2.53 X & 25.39$\pm$5.11 & 52.24$\pm$3.01 \\
bgrl random+scom & 45.42$\pm$1.79 X & 46.81$\pm$1.95 & 33.28$\pm$1.69 & 14.24$\pm$3.08 X & 24.22$\pm$2.29 X & \color{red}{54.2$\pm$2.76 $\bigstar$} \\
bgrl random+deg & \color{red}{56.82$\pm$1.75 $\bigstar$} & 49.66$\pm$1.8 & 36.82$\pm$3.68 & 17.03$\pm$3.33 & 29.0$\pm$4.2 & 49.49$\pm$5.84 \\
bgrl deg+scom & \color{blue}{55.37$\pm$1.48 $\bigstar$} & 48.69$\pm$1.75 & 36.49$\pm$3.67 & 15.76$\pm$4.5 & 25.9$\pm$6.48 & 52.4$\pm$2.06 $\bigstar$ \\
\bottomrule
\end{tabular}

}

,FINAL_struct_cora_res.csv,FINAL_struct_citeseer_res.csv,FINAL_struct_pubmed_res.csv,FINAL_struct_computers_res.csv,FINAL_struct_photo_res.csv,FINAL_struct_cs_res.csv
grace random,55.2$\pm$2.0,\color{blue}{50.54$\pm$2.4 $\bigstar$},\color{red}{40.06$\pm$2.28 $\bigstar$},18.48$\pm$2.53 $\bigstar$,\color{red}{32.45$\pm$3.77 $\bigstar$},46.53$\pm$4.82
grace deg,52.64$\pm$2.9,48.85$\pm$2.64,37.13$\pm$3.79,13.96$\pm$3.81 X,26.81$\pm$5.86,36.06$\pm$8.76
grace pr,54.18$\pm$2.78,\color{violet}{50.25$\pm$1.92},\color{blue}{39.45$\pm$2.37 $\bigstar$},18.07$\pm$3.01 $\bigstar$,\color{violet}{30.88$\pm$3.4 $\bigstar$},43.4$\pm$4.64
grace evc,53.32$\pm$1.9,49.79$\pm$2.11,33.6$\pm$4.52,\color{blue}{19.12$\pm$3.71 $\bigstar$},\color{blue}{31.12$\pm$3.07 $\bigstar$},30.95$\pm$4.12 X
grace scom,55.17$\pm$1.82,\color{red}{51.14$\pm$2.17 $\bigstar$},38.57$\pm$2.97,\color{red}{19.18$\pm$4.24 $\bigstar$},29.25$\pm$4.98,42.91$\pm$3.21
grace random+scom,55.18$\pm$2.48,50.25$\pm$2.09,39.31$\pm$2.21 $\bigstar$,\color{violet}{18.73$\pm$4.05 $\bigstar$},29.68$\pm$3.4,44.27$\pm$4.87
grace random+deg,54.75$\pm$3.01,49.01$\pm$2.62,38.2$\pm$2.52,16.75$\pm$3.36,26.92$\pm$4.01,35.21$\pm$9.12
grace deg+scom,54.36$\pm$2.81,49.64$\pm$2.3,36.65$\pm$4.95,17.16$\pm$4.75,25.85$\pm$3.63 X,37.95$\pm$6.36
bgrl random,45.83$\pm$2.07 X,46.87$\pm$1.74,32.71$\pm$1.7,14.37$\pm$2.85 X,27.07$\pm$5.09,\color{blue}{53.81$\pm$3.74 $\bigstar$}
bgrl deg,\color{violet}{55.36$\pm$2.2},49.74$\pm$1.96,37.52$\pm$4.66,16.94$\pm$3.58,30.06$\pm$2.65,48.7$\pm$4.71
bgrl pr,44.72$\pm$1.53 X,46.09$\pm$1.57 X,29.67$\pm$1.78 X,16.08$\pm$3.95,25.86$\pm$4.89,\color{violet}{53.08$\pm$2.78 $\bigstar$}
bgrl evc,45.19$\pm$1.95 X,46.7$\pm$1.62 X,\color{violet}{39.33$\pm$2.14 $\bigstar$},15.82$\pm$2.16,26.01$\pm$3.77,40.85$\pm$10.36
bgrl scom,45.85$\pm$1.8 X,46.2$\pm$2.05 X,30.14$\pm$2.23 X,13.93$\pm$2.53 X,25.39$\pm$5.11,52.24$\pm$3.01
bgrl random+scom,45.42$\pm$1.79 X,46.81$\pm$1.95,33.28$\pm$1.69,14.24$\pm$3.08 X,24.22$\pm$2.29 X,\color{red}{54.2$\pm$2.76 $\bigstar$}
bgrl random+deg,\color{red}{56.82$\pm$1.75 $\bigstar$},49.66$\pm$1.8,36.82$\pm$3.68,17.03$\pm$3.33,29.0$\pm$4.2,49.49$\pm$5.84
bgrl deg+scom,\color{blue}{55.37$\pm$1.48 $\bigstar$},48.69$\pm$1.75,36.49$\pm$3.67,15.76$\pm$4.5,25.9$\pm$6.48,52.4$\pm$2.06 $\bigstar$

In [17]:
# sbm
names = ['FINAL_SBM_cora_res.csv',
'FINAL_SBM_citeseer_res.csv',
'FINAL_SBM_netscience_res.csv',
'FINAL_SBM_power_res.csv',
'FINAL_SBM_euroroad_res.csv',
'FINAL_SBM_yeast_res.csv',
'FINAL_SBM_crime_res.csv']
names_base = ['FINAL_cora_res.csv',
'FINAL_citeseer_res.csv',
'FINAL_netscience_res.csv',
'FINAL_power_res.csv',
'FINAL_euroroad_res.csv',
'FINAL_yeast_res.csv',
'FINAL_crime_res.csv']

all_data_base, all_res_base = ut.mix_dataset(names_base, 'Hits@50',['baseline','bgrl', 'grace'], ['evc', 'pr', "\+"])
all_data_base.index = ["cora", "citeseer", "netscience", "power", "euroroad", "yeast", "crime"]
all_res_base.index = ["cora", "citeseer", "netscience", "power", "euroroad", "yeast", "crime"]

print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50')
all_data.index = ["cora", "citeseer", "netscience", "power", "euroroad", "yeast", "crime"]
all_res.index = ["cora", "citeseer", "netscience", "power", "euroroad", "yeast", "crime"]
all_data = all_data_base.join(all_data)
all_res = all_res_base.join(all_res)
display(ut.tex_table(all_data, all_res).T)


# print("                             ROCAUC                      ")
# all_data, all_res = ut.mix_dataset(names, 'ROCAUC',filtres)
# display(ut.tex_table(all_data, all_res).T)
# print("                             AP                      ")
# all_data, all_res = ut.mix_dataset(names, 'AP', filtres)
# display(ut.tex_table(all_data, all_res).T)
# print("                             Hits@100                      ")
# all_data, all_res = ut.mix_dataset(names, 'Hits@100', filtres)
# display(ut.tex_table(all_data, all_res).T)
# print("                             Hits@50                      ")
# all_data, all_res = ut.mix_dataset(names, 'Hits@50', filtres)
# display(ut.tex_table(all_data, all_res).T)
# print("                             Hits@20                      ")
# all_data, all_res = ut.mix_dataset(names, 'Hits@20', filtres)
# display(ut.tex_table(all_data, all_res).T)

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{llllllll}
\toprule
 & cora & citeseer & netscience & power & euroroad & yeast & crime \\
\midrule
baseline & 71.55$\pm$1.75 & 0.0$\pm$0.0 X & 85.18$\pm$1.85 & 32.24$\pm$0.75 & 36.71$\pm$3.26 & 93.98$\pm$0.55 & 23.02$\pm$2.9 \\
grace random & 75.85$\pm$1.75 & 77.99$\pm$1.21 $\bigstar$ & 84.34$\pm$1.29 & 36.05$\pm$1.17 & 37.42$\pm$2.96 & 94.28$\pm$0.28 & 18.34$\pm$2.03 X \\
grace deg & 73.9$\pm$2.04 & \color{red}{79.16$\pm$2.24 $\bigstar$} & 86.28$\pm$2.0 & 36.46$\pm$1.26 & 43.46$\pm$7.72 & 93.66$\pm$0.56 & 21.05$\pm$3.22 \\
grace scom & 76.3$\pm$2.02 & \color{blue}{78.6$\pm$1.31 $\bigstar$} & 84.32$\pm$1.3 & 36.34$\pm$1.11 & 36.22$\pm$3.33 & 94.37$\pm$0.24 & 18.85$\pm$3.06 X \\
bgrl random & 73.58$\pm$1.44 & 74.08$\pm$1.06 & 85.18$\pm$1.28 & 29.6$\pm$0.96 X & 27.31$\pm$3.89 X & 93.78$\pm$0.54 & 23.73$\pm$2.21 \\
bgrl deg & 77.49$\pm$1.21 & 76.19$\pm$5.97 & 86.95$\pm$2.33 & 31.79$\pm$1.73 & 38.94$\pm$9.26 & 94.26$\pm$0.48 & 22.85$\pm$3.54 \\
bgrl scom & 73.79$\pm$1.91 & 74.79$\pm$1.18 & 84.69$\pm$1.39 & 29.92$\pm$1.16 X & 28.13$\pm$2.69 X & 93.46$\pm$0.56 & 20.51$\pm$3.5 \\
louvain prob pred & 52.83$\pm$1.21 X & 50.24$\pm$1.59 X & 80.62$\pm$1.44 X & 33.69$\pm$1.47 & 33.43$\pm$4.01 & 89.99$\pm$1.05 X & 23.36$\pm$2.73 \\
grace sbm & 76.28$\pm$1.69 & 65.65$\pm$3.18 & 91.42$\pm$1.03 & \color{violet}{59.59$\pm$2.6 $\bigstar$} & 69.68$\pm$2.71 & 92.08$\pm$0.61 X & 31.53$\pm$4.0 \\
grace sbm+random & \color{blue}{77.75$\pm$1.66} & 67.64$\pm$1.87 & \color{red}{92.43$\pm$0.97 $\bigstar$} & \color{blue}{63.01$\pm$2.91 $\bigstar$} & \color{red}{75.37$\pm$2.89 $\bigstar$} & 93.56$\pm$0.68 & 33.69$\pm$4.59 \\
grace sbm+deg & \color{violet}{77.68$\pm$2.05} & 73.64$\pm$7.46 & \color{violet}{92.23$\pm$0.88 $\bigstar$} & 54.41$\pm$5.27 & \color{violet}{74.06$\pm$4.63 $\bigstar$} & \color{blue}{94.98$\pm$0.54 $\bigstar$} & 32.37$\pm$3.48 \\
grace sbm+scom & 77.18$\pm$1.94 & 69.08$\pm$1.83 & \color{blue}{92.43$\pm$1.34 $\bigstar$} & \color{red}{63.57$\pm$2.25 $\bigstar$} & \color{blue}{75.34$\pm$2.55 $\bigstar$} & 94.25$\pm$0.62 & \color{violet}{36.07$\pm$4.89 $\bigstar$} \\
grace sbm2 & 58.88$\pm$2.29 X & NaN & 90.91$\pm$0.98 & NaN & 68.41$\pm$4.9 & 93.12$\pm$0.97 & \color{blue}{38.2$\pm$4.14 $\bigstar$} \\
bgrl sbm & 72.79$\pm$1.71 & 73.53$\pm$1.85 & 88.52$\pm$2.02 & 44.94$\pm$3.18 & 47.84$\pm$4.25 & 93.75$\pm$0.59 & 26.92$\pm$2.38 \\
bgrl sbm+random & 75.75$\pm$1.95 & 75.25$\pm$2.42 & 89.36$\pm$1.35 & 50.46$\pm$2.31 & 59.51$\pm$4.25 & 93.91$\pm$0.48 & 26.64$\pm$3.0 \\
bgrl sbm+deg & \color{red}{79.28$\pm$1.72 $\bigstar$} & \color{violet}{78.55$\pm$3.62 $\bigstar$} & 88.39$\pm$1.72 & 41.66$\pm$4.16 & 55.12$\pm$4.05 & \color{red}{95.09$\pm$0.58 $\bigstar$} & 22.37$\pm$4.35 \\
bgrl sbm+scom & 76.83$\pm$1.51 & 74.91$\pm$1.62 & 89.62$\pm$1.57 & 49.86$\pm$2.3 & 55.37$\pm$2.63 & 94.43$\pm$0.55 & 27.42$\pm$3.11 \\
bgrl sbm2 & 76.92$\pm$2.18 & NaN & 92.19$\pm$1.38 $\bigstar$ & NaN & 69.93$\pm$4.08 & \color{violet}{94.62$\pm$0.48} & \color{red}{40.64$\pm$3.76 $\bigstar$} \\
\bottomrule
\end{tabular}

}

,cora,citeseer,netscience,power,euroroad,yeast,crime
baseline,71.55$\pm$1.75,0.0$\pm$0.0 X,85.18$\pm$1.85,32.24$\pm$0.75,36.71$\pm$3.26,93.98$\pm$0.55,23.02$\pm$2.9
grace random,75.85$\pm$1.75,77.99$\pm$1.21 $\bigstar$,84.34$\pm$1.29,36.05$\pm$1.17,37.42$\pm$2.96,94.28$\pm$0.28,18.34$\pm$2.03 X
grace deg,73.9$\pm$2.04,\color{red}{79.16$\pm$2.24 $\bigstar$},86.28$\pm$2.0,36.46$\pm$1.26,43.46$\pm$7.72,93.66$\pm$0.56,21.05$\pm$3.22
grace scom,76.3$\pm$2.02,\color{blue}{78.6$\pm$1.31 $\bigstar$},84.32$\pm$1.3,36.34$\pm$1.11,36.22$\pm$3.33,94.37$\pm$0.24,18.85$\pm$3.06 X
bgrl random,73.58$\pm$1.44,74.08$\pm$1.06,85.18$\pm$1.28,29.6$\pm$0.96 X,27.31$\pm$3.89 X,93.78$\pm$0.54,23.73$\pm$2.21
bgrl deg,77.49$\pm$1.21,76.19$\pm$5.97,86.95$\pm$2.33,31.79$\pm$1.73,38.94$\pm$9.26,94.26$\pm$0.48,22.85$\pm$3.54
bgrl scom,73.79$\pm$1.91,74.79$\pm$1.18,84.69$\pm$1.39,29.92$\pm$1.16 X,28.13$\pm$2.69 X,93.46$\pm$0.56,20.51$\pm$3.5
louvain prob pred,52.83$\pm$1.21 X,50.24$\pm$1.59 X,80.62$\pm$1.44 X,33.69$\pm$1.47,33.43$\pm$4.01,89.99$\pm$1.05 X,23.36$\pm$2.73
grace sbm,76.28$\pm$1.69,65.65$\pm$3.18,91.42$\pm$1.03,\color{violet}{59.59$\pm$2.6 $\bigstar$},69.68$\pm$2.71,92.08$\pm$0.61 X,31.53$\pm$4.0
grace sbm+random,\color{blue}{77.75$\pm$1.66},67.64$\pm$1.87,\color{red}{92.43$\pm$0.97 $\bigstar$},\color{blue}{63.01$\pm$2.91 $\bigstar$},\color{red}{75.37$\pm$2.89 $\bigstar$},93.56$\pm$0.68,33.69$\pm$4.59
grace sbm+deg,\color{violet}{77.68$\pm$2.05},73.64$\pm$7.46,\color{violet}{92.23$\pm$0.88 $\bigstar$},54.41$\pm$5.27,\color{violet}{74.06$\pm$4.63 $\bigstar$},\color{blue}{94.98$\pm$0.54 $\bigstar$},32.37$\pm$3.48
grace sbm+scom,77.18$\pm$1.94,69.08$\pm$1.83,\color{blue}{92.43$\pm$1.34 $\bigstar$},\color{red}{63.57$\pm$2.25 $\bigstar$},\color{blue}{75.34$\pm$2.55 $\bigstar$},94.25$\pm$0.62,\color{violet}{36.07$\pm$4.89 $\bigstar$}
grace sbm2,58.88$\pm$2.29 X,NaN,90.91$\pm$0.98,NaN,68.41$\pm$4.9,93.12$\pm$0.97,\color{blue}{38.2$\pm$4.14 $\bigstar$}
bgrl sbm,72.79$\pm$1.71,73.53$\pm$1.85,88.52$\pm$2.02,44.94$\pm$3.18,47.84$\pm$4.25,93.75$\pm$0.59,26.92$\pm$2.38
bgrl sbm+random,75.75$\pm$1.95,75.25$\pm$2.42,89.36$\pm$1.35,50.46$\pm$2.31,59.51$\pm$4.25,93.91$\pm$0.48,26.64$\pm$3.0
bgrl sbm+deg,\color{red}{79.28$\pm$1.72 $\bigstar$},\color{violet}{78.55$\pm$3.62 $\bigstar$},88.39$\pm$1.72,41.66$\pm$4.16,55.12$\pm$4.05,\color{red}{95.09$\pm$0.58 $\bigstar$},22.37$\pm$4.35
bgrl sbm+scom,76.83$\pm$1.51,74.91$\pm$1.62,89.62$\pm$1.57,49.86$\pm$2.3,55.37$\pm$2.63,94.43$\pm$0.55,27.42$\pm$3.11
bgrl sbm2,76.92$\pm$2.18,NaN,92.19$\pm$1.38 $\bigstar$,NaN,69.93$\pm$4.08,\color{violet}{94.62$\pm$0.48},\color{red}{40.64$\pm$3.76 $\bigstar$}

In [15]:
# reconstruction
names = [
'R_FINAL_cora_res.csv',
'R_FINAL_citeseer_res.csv',
'R_FINAL_netscience_res.csv',
'R_FINAL_power_res.csv',
'R_FINAL_euroroad_res.csv',
'R_FINAL_yeast_res.csv',
'R_FINAL_crime_res.csv']
names_base = ['FINAL_cora_res.csv',
'FINAL_citeseer_res.csv',
'FINAL_netscience_res.csv',
'FINAL_power_res.csv',
'FINAL_euroroad_res.csv',
'FINAL_yeast_res.csv',
'FINAL_crime_res.csv']

all_data_base, all_res_base = ut.mix_dataset(names_base, 'Hits@50',['baseline','bgrl', 'grace'], ['evc', 'pr','\+'])
all_data_base.index = ["cora", "citeseer", "netscience", "power", "euroroad", "yeast", "crime"]
all_res_base.index = ["cora", "citeseer", "netscience", "power", "euroroad", "yeast", "crime"]

print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50', filtre2=['\+'])
all_data.index = ["cora", "citeseer", "netscience", "power", "euroroad", "yeast", "crime"]
all_res.index = ["cora", "citeseer", "netscience", "power", "euroroad", "yeast", "crime"]
all_data = all_data_base.join(all_data)
all_res = all_res_base.join(all_res)
res = ut.tex_table(all_data, all_res).T
res = res.reindex(['baseline', 'grace random', 'grace deg', 'grace scom', 'grace rjc', 'grace raa', 'grace rra',
				   'bgrl random', 'bgrl deg', 'bgrl scom', 'bgrl rjc', 'bgrl raa', 'bgrl rra'])
print(res.to_latex(
        index=True, formatters={"name": str.upper}, float_format="{:.1f}".format
    ))

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{llllllll}
\toprule
 & cora & citeseer & netscience & power & euroroad & yeast & crime \\
\midrule
baseline & 71.55$\pm$1.75 X & 0.0$\pm$0.0 X & \color{violet}{85.18$\pm$1.85} & 32.24$\pm$0.75 & 36.71$\pm$3.26 & 93.98$\pm$0.55 & \color{blue}{23.02$\pm$2.9 $\bigstar$} \\
grace random & 75.85$\pm$1.75 & 77.99$\pm$1.21 & 84.34$\pm$1.29 & \color{violet}{36.05$\pm$1.17 $\bigstar$} & \color{violet}{37.42$\pm$2.96 $\bigstar$} & \color{blue}{94.28$\pm$0.28 $\bigstar$} & 18.34$\pm$2.03 \\
grace deg & 73.9$\pm$2.04 & \color{blue}{79.16$\pm$2.24 $\bigstar$} & \color{blue}{86.28$\pm$2.0 $\bigstar$} & \color{red}{36.46$\pm$1.26 $\bigstar$} & \color{red}{43.46$\pm$7.72 $\bigstar$} & 93.66$\pm$0.56 & 21.05$\pm$3.22 \\
grace scom & \color{blue}{76.3$\pm$2.02} & 78.6$\pm$1.31 $\bigstar$ & 84.32$\pm$1.3 & \color{blue}{36.34$\pm$1.11 $\bigstar$} & 36.22$\pm$3.33 & \color{red}{94.37$\pm$0.24 $\bigstar$} & 18.85$\pm$3.06 \\
bgrl random & 73.58$\pm$1.44 & 74.08$\pm$1.06 & 85.18$\pm$1.28 $\bigstar$ & 29.6$\pm$0.96 & 27.31$\pm$3.89 & 93.78$\pm$0.54 & \color{red}{23.73$\pm$2.21 $\bigstar$} \\
bgrl deg & \color{red}{77.49$\pm$1.21 $\bigstar$} & 76.19$\pm$5.97 & \color{red}{86.95$\pm$2.33 $\bigstar$} & 31.79$\pm$1.73 & \color{blue}{38.94$\pm$9.26 $\bigstar$} & \color{violet}{94.26$\pm$0.48 $\bigstar$} & \color{violet}{22.85$\pm$3.54 $\bigstar$} \\
bgrl scom & 73.79$\pm$1.91 & 74.79$\pm$1.18 & 84.69$\pm$1.39 & 29.92$\pm$1.16 & 28.13$\pm$2.69 & 93.46$\pm$0.56 X & 20.51$\pm$3.5 \\
grace rjc & 74.45$\pm$2.23 & 78.19$\pm$1.31 $\bigstar$ & 83.5$\pm$1.63 X & 35.43$\pm$1.18 & 33.18$\pm$2.71 & 94.2$\pm$0.31 & 15.76$\pm$2.06 X \\
grace raa & \color{violet}{76.1$\pm$1.72} & \color{red}{79.25$\pm$1.41 $\bigstar$} & 83.83$\pm$1.23 & 35.18$\pm$1.0 & 34.17$\pm$2.92 & 94.25$\pm$0.29 & 16.51$\pm$2.51 X \\
grace rra & 75.59$\pm$1.92 & \color{violet}{78.74$\pm$1.42 $\bigstar$} & 83.8$\pm$1.62 X & 35.82$\pm$0.63 $\bigstar$ & 35.12$\pm$4.68 & 94.18$\pm$0.3 & 17.05$\pm$2.75 X \\
bgrl rjc & 73.0$\pm$1.49 & 73.46$\pm$1.47 & 84.31$\pm$1.38 & 28.97$\pm$0.83 X & 23.71$\pm$3.5 X & 93.61$\pm$0.62 X & 19.39$\pm$2.19 \\
bgrl raa & 71.72$\pm$1.14 X & 71.08$\pm$1.22 X & 84.18$\pm$1.39 & 29.1$\pm$0.74 X & 24.35$\pm$1.04 X & 94.08$\pm$0.48 & 17.32$\pm$1.84 X \\
bgrl rra & 72.25$\pm$1.29 & 72.05$\pm$1.01 & 84.38$\pm$1.58 & 29.08$\pm$1.0 X & 25.02$\pm$1.76 X & 93.45$\pm$0.47 X & 17.46$\pm$3.44 \\
\bottomrule
\end{tabular}

}
\begin{tabular}{llllllll}
\toprule
 & cora & citeseer & netscience & power & euroroad & yeast & crime \\
\midrule
baseline & 71.55$\pm$1.75 X & 0.0$\pm$0.0 X & \color{violet}{85.18$\pm$1.85} & 32.24$\pm$0.75 & 36.71$\pm$3.26 & 93.98$\pm$0.55 & \color{blue}{23.02$\pm$2.9 $\bigstar$} \\
grace random & 75.85$\pm$1.75 & 77.99$\pm$1.21 & 84.34$\pm$1.29 & \color{violet}{36.05$\pm$1.17 $\bigstar$} & \color{violet}{37.42$\pm$2.96 $\bigstar$} & \color{blue}{94.28$\pm$0.28 $\bigstar$} & 18.34$\pm$2.03 \\
grace deg & 73.9$\pm$2.04 & \color{blue}{79.16$\pm$2.24 $\bigstar$} & \color{blue}{86.28$\pm$2.0 $\bigstar$} & \color{red}{36.46$\pm$1.26 $\bigstar$} & \color{red}{43.46$\pm$7.72 $\bigstar$} & 93.66$\pm$0.56 & 21.05$\pm$3.22 \\
grace scom & \color{blue}{76.3$\pm$2.02} & 78.6$\pm$1.31 $\bigstar$ & 84.32$\pm$1.3 & \color{blue}{36.34$\pm$1.11 $\bigstar$} & 36.22$\pm$3.33 & \color{red}{94.37$\pm$0.24 $\bigstar$} & 18.85$\pm$3.06 \\
grace rjc & 74.45$\pm$2.23 & 78.19$\pm$1.31 $\bigstar$ & 83.5$\pm$1.63 X & 35.43$\pm$1.18 & 33.18$\pm$2.71 & 94.2$\pm$0.31 & 15.76$\pm$2.06 X \\
grace raa & \color{violet}{76.1$\pm$1.72} & \color{red}{79.25$\pm$1.41 $\bigstar$} & 83.83$\pm$1.23 & 35.18$\pm$1.0 & 34.17$\pm$2.92 & 94.25$\pm$0.29 & 16.51$\pm$2.51 X \\
grace rra & 75.59$\pm$1.92 & \color{violet}{78.74$\pm$1.42 $\bigstar$} & 83.8$\pm$1.62 X & 35.82$\pm$0.63 $\bigstar$ & 35.12$\pm$4.68 & 94.18$\pm$0.3 & 17.05$\pm$2.75 X \\
bgrl random & 73.58$\pm$1.44 & 74.08$\pm$1.06 & 85.18$\pm$1.28 $\bigstar$ & 29.6$\pm$0.96 & 27.31$\pm$3.89 & 93.78$\pm$0.54 & \color{red}{23.73$\pm$2.21 $\bigstar$} \\
bgrl deg & \color{red}{77.49$\pm$1.21 $\bigstar$} & 76.19$\pm$5.97 & \color{red}{86.95$\pm$2.33 $\bigstar$} & 31.79$\pm$1.73 & \color{blue}{38.94$\pm$9.26 $\bigstar$} & \color{violet}{94.26$\pm$0.48 $\bigstar$} & \color{violet}{22.85$\pm$3.54 $\bigstar$} \\
bgrl scom & 73.79$\pm$1.91 & 74.79$\pm$1.18 & 84.69$\pm$1.39 & 29.92$\pm$1.16 & 28.13$\pm$2.69 & 93.46$\pm$0.56 X & 20.51$\pm$3.5 \\
bgrl rjc & 73.0$\pm$1.49 & 73.46$\pm$1.47 & 84.31$\pm$1.38 & 28.97$\pm$0.83 X & 23.71$\pm$3.5 X & 93.61$\pm$0.62 X & 19.39$\pm$2.19 \\
bgrl raa & 71.72$\pm$1.14 X & 71.08$\pm$1.22 X & 84.18$\pm$1.39 & 29.1$\pm$0.74 X & 24.35$\pm$1.04 X & 94.08$\pm$0.48 & 17.32$\pm$1.84 X \\
bgrl rra & 72.25$\pm$1.29 & 72.05$\pm$1.01 & 84.38$\pm$1.58 & 29.08$\pm$1.0 X & 25.02$\pm$1.76 X & 93.45$\pm$0.47 X & 17.46$\pm$3.44 \\
\bottomrule
\end{tabular}

In [ ]:
# Â
names = [
'A2_FINAL_cora_res.csv',
'A2_FINAL_netscience_res.csv',
'A2_FINAL_euroroad_res.csv',
'A2_FINAL_yeast_res.csv',
'A2_FINAL_crime_res.csv']
names_base = ['FINAL_cora_res.csv',
'FINAL_netscience_res.csv',
'FINAL_euroroad_res.csv',
'FINAL_yeast_res.csv',
'FINAL_crime_res.csv']

all_data_base, all_res_base = ut.mix_dataset(names_base, 'Hits@50',['baseline','bgrl', 'grace'], ['evc', 'pr', 'scom', '\+'])
all_data_base.index = ["cora", "netscience", "euroroad", "yeast", "crime"]
all_res_base.index = ["cora", "netscience", "euroroad", "yeast", "crime"]

print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50', filtre2=['sbm', 'raa'])
all_data.index = ["cora", "netscience", "euroroad", "yeast", "crime"]
all_res.index = ["cora", "netscience", "euroroad", "yeast", "crime"]
all_data = all_data_base.join(all_data)
all_res = all_res_base.join(all_res)
res = ut.tex_table(all_data, all_res).T
res = res.reindex(['baseline', 'grace random', 'grace deg', 'a2grace random', 'a2grace deg',
				   'bgrl random', 'bgrl deg', 'a2bgrl random', 'a2bgrl deg'])
res
print(res.to_latex(
        index=True, formatters={"name": str.upper}, float_format="{:.1f}".format
    ))

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & cora & netscience & euroroad & yeast & crime \\
\midrule
baseline & 71.55$\pm$1.75 X & 85.18$\pm$1.85 & 36.71$\pm$3.26 & 93.98$\pm$0.55 & \color{violet}{23.02$\pm$2.9} \\
grace random & \color{violet}{75.85$\pm$1.75 $\bigstar$} & 84.34$\pm$1.29 X & 37.42$\pm$2.96 $\bigstar$ & \color{violet}{94.28$\pm$0.28} & 18.34$\pm$2.03 X \\
grace deg & 73.9$\pm$2.04 & \color{violet}{86.28$\pm$2.0} & \color{red}{43.46$\pm$7.72 $\bigstar$} & 93.66$\pm$0.56 X & 21.05$\pm$3.22 \\
bgrl random & 73.58$\pm$1.44 & 85.18$\pm$1.28 & 27.31$\pm$3.89 X & 93.78$\pm$0.54 X & \color{blue}{23.73$\pm$2.21 $\bigstar$} \\
bgrl deg & \color{red}{77.49$\pm$1.21 $\bigstar$} & \color{blue}{86.95$\pm$2.33 $\bigstar$} & \color{violet}{38.94$\pm$9.26 $\bigstar$} & 94.26$\pm$0.48 & 22.85$\pm$3.54 \\
a2grace random & 75.53$\pm$1.79 $\bigstar$ & 84.01$\pm$1.6 X & 36.04$\pm$2.05 & 94.23$\pm$0.3 & 17.8$\pm$2.01 X \\
a2grace deg & 73.84$\pm$2.33 & \color{red}{87.96$\pm$2.63 $\bigstar$} & \color{blue}{42.97$\pm$6.99 $\bigstar$} & 93.91$\pm$0.44 X & 22.68$\pm$5.33 \\
a2bgrl random & 70.78$\pm$1.72 X & 85.95$\pm$2.05 & 26.93$\pm$3.2 X & \color{blue}{94.31$\pm$0.42 $\bigstar$} & \color{red}{31.86$\pm$5.01 $\bigstar$} \\
a2bgrl deg & \color{blue}{76.55$\pm$1.51 $\bigstar$} & 86.02$\pm$1.44 & 29.61$\pm$4.0 X & \color{red}{94.58$\pm$0.45 $\bigstar$} & 23.02$\pm$4.77 \\
\bottomrule
\end{tabular}

}
\begin{tabular}{llllll}
\toprule
 & cora & netscience & euroroad & yeast & crime \\
\midrule
baseline & 71.55$\pm$1.75 X & 85.18$\pm$1.85 & 36.71$\pm$3.26 & 93.98$\pm$0.55 & \color{violet}{23.02$\pm$2.9} \\
grace random & \color{violet}{75.85$\pm$1.75 $\bigstar$} & 84.34$\pm$1.29 X & 37.42$\pm$2.96 $\bigstar$ & \color{violet}{94.28$\pm$0.28} & 18.34$\pm$2.03 X \\
grace deg & 73.9$\pm$2.04 & \color{violet}{86.28$\pm$2.0} & \color{red}{43.46$\pm$7.72 $\bigstar$} & 93.66$\pm$0.56 X & 21.05$\pm$3.22 \\
a2grace random & 75.53$\pm$1.79 $\bigstar$ & 84.01$\pm$1.6 X & 36.04$\pm$2.05 & 94.23$\pm$0.3 & 17.8$\pm$2.01 X \\
a2grace deg & 73.84$\pm$2.33 & \color{red}{87.96$\pm$2.63 $\bigstar$} & \color{blue}{42.97$\pm$6.99 $\bigstar$} & 93.91$\pm$0.44 X & 22.68$\pm$5.33 \\
bgrl random & 73.58$\pm$1.44 & 85.18$\pm$1.28 & 27.31$\pm$3.89 X & 93.78$\pm$0.54 X & \color{blue}{23.73$\pm$2.21 $\bigstar$} \\
bgrl deg & \color{red}{77.49$\pm$1.21 $\bigstar$} & \color{blue}{86.95$\pm$2.33 $\bigstar$} & \color{violet}{38.94$\pm$9.26 $\bigstar$} & 94.26$\pm$0.48 & 22.85$\pm$3.54 \\
a2bgrl random & 70.78$\pm$1.72 X & 85.95$\pm$2.05 & 26.93$\pm$3.2 X & \color{blue}{94.31$\pm$0.42 $\bigstar$} & \color{red}{31.86$\pm$5.01 $\bigstar$} \\
a2bgrl deg & \color{blue}{76.55$\pm$1.51 $\bigstar$} & 86.02$\pm$1.44 & 29.61$\pm$4.0 X & \color{red}{94.58$\pm$0.45 $\bigstar$} & 23.02$\pm$4.77 \\
\bottomrule
\end{tabular}

In [37]:
# Â
names = [
'A2_FINAL_cora_res.csv',
'A2_FINAL_netscience_res.csv',
'A2_FINAL_euroroad_res.csv',
'A2_FINAL_yeast_res.csv',
'A2_FINAL_crime_res.csv']
names_base = ['FINAL_SBM_cora_res.csv',
'FINAL_SBM_netscience_res.csv',
'FINAL_SBM_euroroad_res.csv',
'FINAL_SBM_yeast_res.csv',
'FINAL_SBM_crime_res.csv']

all_data_base, all_res_base = ut.mix_dataset(names_base, 'Hits@50',['baseline','sbm+', 'grace'], ['sbm2','scom'])
all_data_base.index = ["cora", "netscience", "euroroad", "yeast", "crime"]
all_res_base.index = ["cora", "netscience", "euroroad", "yeast", "crime"]

print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50', ['sbm'], ['raa'])
all_data.index = ["cora", "netscience", "euroroad", "yeast", "crime"]
all_res.index = ["cora", "netscience", "euroroad", "yeast", "crime"]
all_data = all_data_base.join(all_data)
all_res = all_res_base.join(all_res)
res = ut.tex_table(all_data, all_res).T
res = res.reindex(['grace sbm+random', 'grace sbm+deg', 'a2grace sbm+random', 'a2grace sbm+deg', 'bgrl sbm+random', 'bgrl sbm+deg', 'a2bgrl sbm+random', 'a2bgrl sbm+deg'])
res
print(res.to_latex(
        index=True, formatters={"name": str.upper}, float_format="{:.1f}".format
    ))

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{llllll}
\toprule
 & cora & netscience & euroroad & yeast & crime \\
\midrule
grace sbm & 76.28$\pm$1.69 & 91.42$\pm$1.03 & 69.68$\pm$2.71 & 92.08$\pm$0.61 X & 31.53$\pm$4.0 \\
grace sbm+random & \color{blue}{77.75$\pm$1.66} & \color{blue}{92.43$\pm$0.97 $\bigstar$} & \color{blue}{75.37$\pm$2.89 $\bigstar$} & 93.56$\pm$0.68 & \color{blue}{33.69$\pm$4.59 $\bigstar$} \\
grace sbm+deg & \color{violet}{77.68$\pm$2.05} & \color{violet}{92.23$\pm$0.88 $\bigstar$} & \color{violet}{74.06$\pm$4.63 $\bigstar$} & \color{blue}{94.98$\pm$0.54 $\bigstar$} & \color{violet}{32.37$\pm$3.48} \\
bgrl sbm & 72.79$\pm$1.71 X & 88.52$\pm$2.02 X & 47.84$\pm$4.25 X & 93.75$\pm$0.59 & 26.92$\pm$2.38 \\
bgrl sbm+random & 75.75$\pm$1.95 & 89.36$\pm$1.35 & 59.51$\pm$4.25 & 93.91$\pm$0.48 & 26.64$\pm$3.0 \\
bgrl sbm+deg & \color{red}{79.28$\pm$1.72 $\bigstar$} & 88.39$\pm$1.72 X & 55.12$\pm$4.05 & \color{red}{95.09$\pm$0.58 $\bigstar$} & 22.37$\pm$4.35 X \\
a2grace sbm+random & 77.52$\pm$2.0 & \color{red}{92.7$\pm$0.87 $\bigstar$} & \color{red}{76.64$\pm$4.48 $\bigstar$} & \color{violet}{94.9$\pm$0.44 $\bigstar$} & \color{red}{35.8$\pm$3.2 $\bigstar$} \\
a2grace sbm+deg & 76.87$\pm$1.92 & 92.01$\pm$1.7 $\bigstar$ & 71.27$\pm$4.59 & 94.87$\pm$0.66 $\bigstar$ & 30.95$\pm$4.56 \\
a2bgrl sbm+random & 74.54$\pm$1.77 X & 87.01$\pm$1.45 X & 32.76$\pm$4.86 X & 94.54$\pm$0.36 & 28.44$\pm$4.12 \\
a2bgrl sbm+deg & 76.46$\pm$1.52 & 88.56$\pm$1.26 X & 36.68$\pm$3.77 X & 94.52$\pm$0.39 & 28.78$\pm$2.0 \\
\bottomrule
\end{tabular}

}
\begin{tabular}{llllll}
\toprule
 & cora & netscience & euroroad & yeast & crime \\
\midrule
grace sbm+random & \color{blue}{77.75$\pm$1.66} & \color{blue}{92.43$\pm$0.97 $\bigstar$} & \color{blue}{75.37$\pm$2.89 $\bigstar$} & 93.56$\pm$0.68 & \color{blue}{33.69$\pm$4.59 $\bigstar$} \\
grace sbm+deg & \color{violet}{77.68$\pm$2.05} & \color{violet}{92.23$\pm$0.88 $\bigstar$} & \color{violet}{74.06$\pm$4.63 $\bigstar$} & \color{blue}{94.98$\pm$0.54 $\bigstar$} & \color{violet}{32.37$\pm$3.48} \\
a2grace sbm+random & 77.52$\pm$2.0 & \color{red}{92.7$\pm$0.87 $\bigstar$} & \color{red}{76.64$\pm$4.48 $\bigstar$} & \color{violet}{94.9$\pm$0.44 $\bigstar$} & \color{red}{35.8$\pm$3.2 $\bigstar$} \\
a2grace sbm+deg & 76.87$\pm$1.92 & 92.01$\pm$1.7 $\bigstar$ & 71.27$\pm$4.59 & 94.87$\pm$0.66 $\bigstar$ & 30.95$\pm$4.56 \\
bgrl sbm+random & 75.75$\pm$1.95 & 89.36$\pm$1.35 & 59.51$\pm$4.25 & 93.91$\pm$0.48 & 26.64$\pm$3.0 \\
bgrl sbm+deg & \color{red}{79.28$\pm$1.72 $\bigstar$} & 88.39$\pm$1.72 X & 55.12$\pm$4.05 & \color{red}{95.09$\pm$0.58 $\bigstar$} & 22.37$\pm$4.35 X \\
a2bgrl sbm+random & 74.54$\pm$1.77 X & 87.01$\pm$1.45 X & 32.76$\pm$4.86 X & 94.54$\pm$0.36 & 28.44$\pm$4.12 \\
a2bgrl sbm+deg & 76.46$\pm$1.52 & 88.56$\pm$1.26 X & 36.68$\pm$3.77 X & 94.52$\pm$0.39 & 28.78$\pm$2.0 \\
\bottomrule
\end{tabular}

In [59]:
# Link-loss
names = [
'L_FINAL_cora_res.csv',
'L_FINAL_netscience_res.csv',
'L_FINAL_power_res.csv',
'L_FINAL_euroroad_res.csv',
'L_FINAL_yeast_res.csv',
'L_FINAL_crime_res.csv']
names_base = [
'FINAL_cora_res.csv',
'FINAL_netscience_res.csv',
'FINAL_power_res.csv',
'FINAL_euroroad_res.csv',
'FINAL_yeast_res.csv',
'FINAL_crime_res.csv']


all_data_base, all_res_base = ut.mix_dataset(names_base, 'Hits@50',['baseline','bgrl', 'grace'], ['evc', 'pr', 'scom', '\+'])


all_data_base.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]
all_res_base.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]


print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50', filtre2=['sbm','raa'])
all_data.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]
all_res.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]
all_data1 = all_data_base.join(all_data)
all_res1 = all_res_base.join(all_res)


res1 = ut.tex_table(all_data1, all_res1).T
res1
print(res1.to_latex(
        index=True, formatters={"name": str.upper}, float_format="{:.1f}".format
    ))

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & cora & netscience & power & euroroad & yeast & crime \\
\midrule
baseline & 71.55$\pm$1.75 X & \color{violet}{85.18$\pm$1.85} & 32.24$\pm$0.75 & 36.71$\pm$3.26 & 93.98$\pm$0.55 $\bigstar$ & \color{violet}{23.02$\pm$2.9} \\
grace random & \color{violet}{75.85$\pm$1.75 $\bigstar$} & 84.34$\pm$1.29 X & \color{blue}{36.05$\pm$1.17 $\bigstar$} & 37.42$\pm$2.96 $\bigstar$ & \color{red}{94.28$\pm$0.28 $\bigstar$} & 18.34$\pm$2.03 X \\
grace deg & 73.9$\pm$2.04 & \color{blue}{86.28$\pm$2.0 $\bigstar$} & \color{red}{36.46$\pm$1.26 $\bigstar$} & \color{red}{43.46$\pm$7.72 $\bigstar$} & 93.66$\pm$0.56 & 21.05$\pm$3.22 \\
bgrl random & 73.58$\pm$1.44 & 85.18$\pm$1.28 & 29.6$\pm$0.96 X & 27.31$\pm$3.89 X & 93.78$\pm$0.54 & \color{blue}{23.73$\pm$2.21 $\bigstar$} \\
bgrl deg & \color{blue}{77.49$\pm$1.21 $\bigstar$} & \color{red}{86.95$\pm$2.33 $\bigstar$} & 31.79$\pm$1.73 & \color{violet}{38.94$\pm$9.26 $\bigstar$} & \color{blue}{94.26$\pm$0.48 $\bigstar$} & 22.85$\pm$3.54 \\
lgrace random & 73.27$\pm$1.36 & 84.71$\pm$1.61 & 33.04$\pm$2.63 & 32.19$\pm$2.64 & 94.01$\pm$0.34 & 18.2$\pm$1.77 X \\
lgrace deg & 74.21$\pm$1.84 & 85.04$\pm$1.61 & \color{violet}{34.44$\pm$2.35} & 37.6$\pm$4.6 & 94.0$\pm$0.41 & 19.73$\pm$2.94 X \\
lbgrl random & \color{red}{78.29$\pm$1.43 $\bigstar$} & 84.25$\pm$1.72 X & 29.63$\pm$0.95 X & 26.25$\pm$5.64 X & \color{violet}{94.22$\pm$0.32 $\bigstar$} & 19.42$\pm$3.94 \\
lbgrl deg & 72.64$\pm$2.23 X & 82.1$\pm$4.49 X & 26.43$\pm$3.69 X & \color{blue}{43.11$\pm$8.41 $\bigstar$} & 91.03$\pm$2.83 X & \color{red}{27.59$\pm$4.74 $\bigstar$} \\
\bottomrule
\end{tabular}

}
\begin{tabular}{lllllll}
\toprule
 & cora & netscience & power & euroroad & yeast & crime \\
\midrule
baseline & 71.55$\pm$1.75 X & \color{violet}{85.18$\pm$1.85} & 32.24$\pm$0.75 & 36.71$\pm$3.26 & 93.98$\pm$0.55 $\bigstar$ & \color{violet}{23.02$\pm$2.9} \\
grace random & \color{violet}{75.85$\pm$1.75 $\bigstar$} & 84.34$\pm$1.29 X & \color{blue}{36.05$\pm$1.17 $\bigstar$} & 37.42$\pm$2.96 $\bigstar$ & \color{red}{94.28$\pm$0.28 $\bigstar$} & 18.34$\pm$2.03 X \\
grace deg & 73.9$\pm$2.04 & \color{blue}{86.28$\pm$2.0 $\bigstar$} & \color{red}{36.46$\pm$1.26 $\bigstar$} & \color{red}{43.46$\pm$7.72 $\bigstar$} & 93.66$\pm$0.56 & 21.05$\pm$3.22 \\
bgrl random & 73.58$\pm$1.44 & 85.18$\pm$1.28 & 29.6$\pm$0.96 X & 27.31$\pm$3.89 X & 93.78$\pm$0.54 & \color{blue}{23.73$\pm$2.21 $\bigstar$} \\
bgrl deg & \color{blue}{77.49$\pm$1.21 $\bigstar$} & \color{red}{86.95$\pm$2.33 $\bigstar$} & 31.79$\pm$1.73 & \color{violet}{38.94$\pm$9.26 $\bigstar$} & \color{blue}{94.26$\pm$0.48 $\bigstar$} & 22.85$\pm$3.54 \\
lgrace random & 73.27$\pm$1.36 & 84.71$\pm$1.61 & 33.04$\pm$2.63 & 32.19$\pm$2.64 & 94.01$\pm$0.34 & 18.2$\pm$1.77 X \\
lgrace deg & 74.21$\pm$1.84 & 85.04$\pm$1.61 & \color{violet}{34.44$\pm$2.35} & 37.6$\pm$4.6 & 94.0$\pm$0.41 & 19.73$\pm$2.94 X \\
lbgrl random & \color{red}{78.29$\pm$1.43 $\bigstar$} & 84.25$\pm$1.72 X & 29.63$\pm$0.95 X & 26.25$\pm$5.64 X & \color{violet}{94.22$\pm$0.32 $\bigstar$} & 19.42$\pm$3.94 \\
lbgrl deg & 72.64$\pm$2.23 X & 82.1$\pm$4.49 X & 26.43$\pm$3.69 X & \color{blue}{43.11$\pm$8.41 $\bigstar$} & 91.03$\pm$2.83 X & \color{red}{27.59$\pm$4.74 $\bigstar$} \\
\bottomrule
\end{tabular}

In [60]:
# Link-loss
names = [
'L_FINAL_cora_res.csv',
'L_FINAL_netscience_res.csv',
'L_FINAL_power_res.csv',
'L_FINAL_euroroad_res.csv',
'L_FINAL_yeast_res.csv',
'L_FINAL_crime_res.csv']

names_sbm = [
'FINAL_SBM_cora_res.csv',
'FINAL_SBM_netscience_res.csv',
'FINAL_SBM_power_res.csv',
'FINAL_SBM_euroroad_res.csv',
'FINAL_SBM_yeast_res.csv',
'FINAL_SBM_crime_res.csv']

all_data_sbm, all_res_sbm = ut.mix_dataset(names_sbm, 'Hits@50', ['\+deg', '\+random'])

all_data_sbm.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]
all_res_sbm.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]


print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50', filtre=['sbm'], filtre2=['raa'])
all_data.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]
all_res.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]

all_data2 = all_data.join(all_data_sbm)
all_res2 = all_res.join(all_res_sbm)

res2 = ut.tex_table(all_data2, all_res2).T
res2
print(res2.to_latex(
        index=True, formatters={"name": str.upper}, float_format="{:.1f}".format
    ))

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & cora & netscience & power & euroroad & yeast & crime \\
\midrule
lgrace sbm+random & 53.68$\pm$3.8 X & 82.99$\pm$2.2 X & 11.29$\pm$2.06 X & 24.35$\pm$3.65 X & 92.99$\pm$0.83 X & 28.14$\pm$7.05 \\
lgrace sbm+deg & 53.31$\pm$5.71 X & 82.52$\pm$2.6 X & 12.38$\pm$3.17 X & 24.06$\pm$3.84 X & 92.68$\pm$0.58 X & 28.14$\pm$7.05 \\
lbgrl sbm+random & 67.0$\pm$2.05 & 88.56$\pm$1.85 & 24.97$\pm$2.4 & 35.55$\pm$2.94 & 93.73$\pm$0.51 & \color{violet}{28.24$\pm$7.84} \\
lbgrl sbm+deg & 62.23$\pm$3.06 X & 87.5$\pm$1.54 & 16.88$\pm$7.69 X & 32.05$\pm$7.02 X & 92.81$\pm$1.43 X & 27.32$\pm$5.37 X \\
grace sbm+random & \color{blue}{77.75$\pm$1.66 $\bigstar$} & \color{red}{92.43$\pm$0.97 $\bigstar$} & \color{red}{63.01$\pm$2.91 $\bigstar$} & \color{red}{75.37$\pm$2.89 $\bigstar$} & 93.56$\pm$0.68 & \color{red}{33.69$\pm$4.59 $\bigstar$} \\
grace sbm+deg & \color{violet}{77.68$\pm$2.05 $\bigstar$} & \color{blue}{92.23$\pm$0.88 $\bigstar$} & \color{blue}{54.41$\pm$5.27 $\bigstar$} & \color{blue}{74.06$\pm$4.63 $\bigstar$} & \color{blue}{94.98$\pm$0.54 $\bigstar$} & \color{blue}{32.37$\pm$3.48 $\bigstar$} \\
bgrl sbm+random & 75.75$\pm$1.95 & \color{violet}{89.36$\pm$1.35} & \color{violet}{50.46$\pm$2.31} & \color{violet}{59.51$\pm$4.25} & \color{violet}{93.91$\pm$0.48} & 26.64$\pm$3.0 \\
bgrl sbm+deg & \color{red}{79.28$\pm$1.72 $\bigstar$} & 88.39$\pm$1.72 & 41.66$\pm$4.16 & 55.12$\pm$4.05 & \color{red}{95.09$\pm$0.58 $\bigstar$} & 22.37$\pm$4.35 X \\
\bottomrule
\end{tabular}

}
\begin{tabular}{lllllll}
\toprule
 & cora & netscience & power & euroroad & yeast & crime \\
\midrule
lgrace sbm+random & 53.68$\pm$3.8 X & 82.99$\pm$2.2 X & 11.29$\pm$2.06 X & 24.35$\pm$3.65 X & 92.99$\pm$0.83 X & 28.14$\pm$7.05 \\
lgrace sbm+deg & 53.31$\pm$5.71 X & 82.52$\pm$2.6 X & 12.38$\pm$3.17 X & 24.06$\pm$3.84 X & 92.68$\pm$0.58 X & 28.14$\pm$7.05 \\
lbgrl sbm+random & 67.0$\pm$2.05 & 88.56$\pm$1.85 & 24.97$\pm$2.4 & 35.55$\pm$2.94 & 93.73$\pm$0.51 & \color{violet}{28.24$\pm$7.84} \\
lbgrl sbm+deg & 62.23$\pm$3.06 X & 87.5$\pm$1.54 & 16.88$\pm$7.69 X & 32.05$\pm$7.02 X & 92.81$\pm$1.43 X & 27.32$\pm$5.37 X \\
grace sbm+random & \color{blue}{77.75$\pm$1.66 $\bigstar$} & \color{red}{92.43$\pm$0.97 $\bigstar$} & \color{red}{63.01$\pm$2.91 $\bigstar$} & \color{red}{75.37$\pm$2.89 $\bigstar$} & 93.56$\pm$0.68 & \color{red}{33.69$\pm$4.59 $\bigstar$} \\
grace sbm+deg & \color{violet}{77.68$\pm$2.05 $\bigstar$} & \color{blue}{92.23$\pm$0.88 $\bigstar$} & \color{blue}{54.41$\pm$5.27 $\bigstar$} & \color{blue}{74.06$\pm$4.63 $\bigstar$} & \color{blue}{94.98$\pm$0.54 $\bigstar$} & \color{blue}{32.37$\pm$3.48 $\bigstar$} \\
bgrl sbm+random & 75.75$\pm$1.95 & \color{violet}{89.36$\pm$1.35} & \color{violet}{50.46$\pm$2.31} & \color{violet}{59.51$\pm$4.25} & \color{violet}{93.91$\pm$0.48} & 26.64$\pm$3.0 \\
bgrl sbm+deg & \color{red}{79.28$\pm$1.72 $\bigstar$} & 88.39$\pm$1.72 & 41.66$\pm$4.16 & 55.12$\pm$4.05 & \color{red}{95.09$\pm$0.58 $\bigstar$} & 22.37$\pm$4.35 X \\
\bottomrule
\end{tabular}

In [61]:
# Link-loss
names = [
'L_FINAL_cora_res.csv',
'L_FINAL_netscience_res.csv',
'L_FINAL_power_res.csv',
'L_FINAL_euroroad_res.csv',
'L_FINAL_yeast_res.csv',
'L_FINAL_crime_res.csv']

names_r = [
'R_FINAL_cora_res.csv',
'R_FINAL_netscience_res.csv',
'R_FINAL_power_res.csv',
'R_FINAL_euroroad_res.csv',
'R_FINAL_yeast_res.csv',
'R_FINAL_crime_res.csv'
]
all_data_r, all_res_r = ut.mix_dataset(names_r, 'Hits@50',['raa'], ['\+'])


all_data_r.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]
all_res_r.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]


print("                             Hits@50                      ")
all_data, all_res = ut.mix_dataset(names, 'Hits@50', filtre=['raa'], filtre2=['sbm'])
all_data.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]
all_res.index = ["cora", "netscience", "power", "euroroad", "yeast", "crime"]

all_data = all_data.join(all_data_r)
all_res = all_res.join(all_res_r)
res = ut.tex_table(all_data).T
res
print(res.to_latex(
        index=True, formatters={"name": str.upper}, float_format="{:.1f}".format
    ))

                             Hits@50
\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & cora & netscience & power & euroroad & yeast & crime \\
\midrule
lgrace raa & \color{violet}{73.46$\pm$1.19} & \color{red}{85.09$\pm$1.19} & \color{red}{35.51$\pm$0.82} & \color{red}{38.48$\pm$4.51} & 93.81$\pm$0.47 & \color{blue}{18.47$\pm$2.24} \\
lbgrl raa & \color{red}{77.23$\pm$1.65} & \color{violet}{84.14$\pm$1.94} & \color{violet}{32.49$\pm$1.12} & \color{blue}{38.3$\pm$6.45} & \color{blue}{94.08$\pm$0.37} & \color{red}{25.02$\pm$5.46} \\
grace raa & \color{blue}{76.1$\pm$1.72} & 83.83$\pm$1.23 & \color{blue}{35.18$\pm$1.0} & \color{violet}{34.17$\pm$2.92} & \color{red}{94.25$\pm$0.29} & 16.51$\pm$2.51 \\
bgrl raa & 71.72$\pm$1.14 & \color{blue}{84.18$\pm$1.39} & 29.1$\pm$0.74 & 24.35$\pm$1.04 & \color{violet}{94.08$\pm$0.48} & \color{violet}{17.32$\pm$1.84} \\
\bottomrule
\end{tabular}

}
\begin{tabular}{lllllll}
\toprule
 & cora & netscience & power & euroroad & yeast & crime \\
\midrule
lgrace raa & \color{violet}{73.46$\pm$1.19} & \color{red}{85.09$\pm$1.19} & \color{red}{35.51$\pm$0.82} & \color{red}{38.48$\pm$4.51} & 93.81$\pm$0.47 & \color{blue}{18.47$\pm$2.24} \\
lbgrl raa & \color{red}{77.23$\pm$1.65} & \color{violet}{84.14$\pm$1.94} & \color{violet}{32.49$\pm$1.12} & \color{blue}{38.3$\pm$6.45} & \color{blue}{94.08$\pm$0.37} & \color{red}{25.02$\pm$5.46} \\
grace raa & \color{blue}{76.1$\pm$1.72} & 83.83$\pm$1.23 & \color{blue}{35.18$\pm$1.0} & \color{violet}{34.17$\pm$2.92} & \color{red}{94.25$\pm$0.29} & 16.51$\pm$2.51 \\
bgrl raa & 71.72$\pm$1.14 & \color{blue}{84.18$\pm$1.39} & 29.1$\pm$0.74 & 24.35$\pm$1.04 & \color{violet}{94.08$\pm$0.48} & \color{violet}{17.32$\pm$1.84} \\
\bottomrule
\end{tabular}