In [1]:
import utils as ut
import pandas as pd
import numpy as np

In [3]:
names = [
    '95/_USAir.csv',
    '95/_NS.csv',
    '95/_PB.csv',
    '95/_Yeast.csv',
    '95/_Celegans.csv',
    '95/_power.csv',
    '95/_Router.csv',
    '95/_Ecoli.csv',
]
data1, res1 = ut.mix_dataset(names, 'Hits@50', filtre=['grace'])
combined_data = ut.tex_table(data1, res1)
combined_data.T

\resizebox{\textwidth}{!}{
\begin{tabular}{lllllllll}
\toprule
 & 95/_USAir.csv & 95/_NS.csv & 95/_PB.csv & 95/_Yeast.csv & 95/_Celegans.csv & 95/_power.csv & 95/_Router.csv & 95/_Ecoli.csv \\
\midrule
grace,enc:gcn bgrl,pred:mlp,random & \color{violet}{98.57$\pm$1.5 $\bigstar$} & 96.77$\pm$2.16 $\bigstar$ & 71.22$\pm$4.29 X & 90.13$\pm$1.24 & 97.58$\pm$2.18 $\bigstar$ & 77.61$\pm$3.59 & 81.47$\pm$2.91 & 91.33$\pm$1.49 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast & 93.02$\pm$3.27 X & 92.8$\pm$2.91 X & \color{violet}{82.12$\pm$2.57 $\bigstar$} & 83.0$\pm$1.48 X & 97.27$\pm$2.09 & 66.07$\pm$2.79 X & 59.04$\pm$4.87 & 89.48$\pm$1.48 X \\
grace,enc:gcn bgrl,pred:mlp,sbm fast2 & 92.38$\pm$6.71 X & 94.51$\pm$3.1 & \color{blue}{82.18$\pm$3.25 $\bigstar$} & 88.41$\pm$1.56 X & 93.28$\pm$2.89 X & 80.28$\pm$3.24 & 53.45$\pm$5.32 X & 91.97$\pm$1.26 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast cheat & 97.06$\pm$2.32 & 96.59$\pm$2.33 $\bigstar$ & 82.11$\pm$2.89 $\bigstar$ & \color{violet}{95.7$\pm$1.43 $\bigstar$} & 95.55$\pm$4.59 & \color{red}{98.68$\pm$0.76 $\bigstar$} & \color{red}{99.33$\pm$0.47 $\bigstar$} & 91.91$\pm$1.43 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast2 cheat & 95.95$\pm$10.14 & \color{violet}{97.2$\pm$2.08 $\bigstar$} & \color{red}{82.87$\pm$3.81 $\bigstar$} & \color{red}{96.6$\pm$0.93 $\bigstar$} & 97.27$\pm$2.2 & \color{violet}{97.08$\pm$2.02 $\bigstar$} & \color{blue}{99.14$\pm$0.57 $\bigstar$} & 88.93$\pm$1.67 X \\
lgrace,enc:gcn bgrl,pred:mlp,random & \color{blue}{98.65$\pm$1.53 $\bigstar$} & 90.37$\pm$8.41 X & NaN & 91.26$\pm$1.24 & \color{red}{98.52$\pm$1.35 $\bigstar$} & 72.54$\pm$3.51 & 68.88$\pm$7.72 & \color{blue}{95.67$\pm$0.82 $\bigstar$} \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast & 96.19$\pm$2.53 & \color{blue}{97.26$\pm$1.84 $\bigstar$} & NaN & 91.21$\pm$1.31 & 97.5$\pm$2.12 & 72.34$\pm$4.24 & 40.13$\pm$4.37 X & 92.27$\pm$1.22 \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast2 & 97.38$\pm$1.9 & 93.35$\pm$3.75 X & NaN & 90.79$\pm$1.66 & \color{violet}{97.66$\pm$1.75 $\bigstar$} & 74.26$\pm$2.79 & 57.65$\pm$4.86 & 90.88$\pm$1.43 \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast cheat & 91.03$\pm$10.7 X & 95.37$\pm$3.0 & NaN & 94.49$\pm$1.15 & \color{blue}{97.73$\pm$2.18 $\bigstar$} & \color{blue}{97.18$\pm$1.27 $\bigstar$} & 90.86$\pm$2.31 & \color{violet}{94.02$\pm$1.21} \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast2 cheat & \color{red}{99.68$\pm$0.63 $\bigstar$} & \color{red}{97.68$\pm$1.8 $\bigstar$} & NaN & \color{blue}{96.21$\pm$1.04 $\bigstar$} & 93.52$\pm$5.17 X & 97.03$\pm$1.75 $\bigstar$ & \color{violet}{98.18$\pm$0.78 $\bigstar$} & \color{red}{96.53$\pm$0.97 $\bigstar$} \\
\bottomrule
\end{tabular}

}

,95/_USAir.csv,95/_NS.csv,95/_PB.csv,95/_Yeast.csv,95/_Celegans.csv,95/_power.csv,95/_Router.csv,95/_Ecoli.csv
"grace,enc:gcn bgrl,pred:mlp,random",\color{violet}{98.57$\pm$1.5 $\bigstar$},96.77$\pm$2.16 $\bigstar$,71.22$\pm$4.29 X,90.13$\pm$1.24,97.58$\pm$2.18 $\bigstar$,77.61$\pm$3.59,81.47$\pm$2.91,91.33$\pm$1.49
"grace,enc:gcn bgrl,pred:mlp,sbm fast",93.02$\pm$3.27 X,92.8$\pm$2.91 X,\color{violet}{82.12$\pm$2.57 $\bigstar$},83.0$\pm$1.48 X,97.27$\pm$2.09,66.07$\pm$2.79 X,59.04$\pm$4.87,89.48$\pm$1.48 X
"grace,enc:gcn bgrl,pred:mlp,sbm fast2",92.38$\pm$6.71 X,94.51$\pm$3.1,\color{blue}{82.18$\pm$3.25 $\bigstar$},88.41$\pm$1.56 X,93.28$\pm$2.89 X,80.28$\pm$3.24,53.45$\pm$5.32 X,91.97$\pm$1.26
"grace,enc:gcn bgrl,pred:mlp,sbm fast cheat",97.06$\pm$2.32,96.59$\pm$2.33 $\bigstar$,82.11$\pm$2.89 $\bigstar$,\color{violet}{95.7$\pm$1.43 $\bigstar$},95.55$\pm$4.59,\color{red}{98.68$\pm$0.76 $\bigstar$},\color{red}{99.33$\pm$0.47 $\bigstar$},91.91$\pm$1.43
"grace,enc:gcn bgrl,pred:mlp,sbm fast2 cheat",95.95$\pm$10.14,\color{violet}{97.2$\pm$2.08 $\bigstar$},\color{red}{82.87$\pm$3.81 $\bigstar$},\color{red}{96.6$\pm$0.93 $\bigstar$},97.27$\pm$2.2,\color{violet}{97.08$\pm$2.02 $\bigstar$},\color{blue}{99.14$\pm$0.57 $\bigstar$},88.93$\pm$1.67 X
"lgrace,enc:gcn bgrl,pred:mlp,random",\color{blue}{98.65$\pm$1.53 $\bigstar$},90.37$\pm$8.41 X,NaN,91.26$\pm$1.24,\color{red}{98.52$\pm$1.35 $\bigstar$},72.54$\pm$3.51,68.88$\pm$7.72,\color{blue}{95.67$\pm$0.82 $\bigstar$}
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast",96.19$\pm$2.53,\color{blue}{97.26$\pm$1.84 $\bigstar$},NaN,91.21$\pm$1.31,97.5$\pm$2.12,72.34$\pm$4.24,40.13$\pm$4.37 X,92.27$\pm$1.22
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast2",97.38$\pm$1.9,93.35$\pm$3.75 X,NaN,90.79$\pm$1.66,\color{violet}{97.66$\pm$1.75 $\bigstar$},74.26$\pm$2.79,57.65$\pm$4.86,90.88$\pm$1.43
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast cheat",91.03$\pm$10.7 X,95.37$\pm$3.0,NaN,94.49$\pm$1.15,\color{blue}{97.73$\pm$2.18 $\bigstar$},\color{blue}{97.18$\pm$1.27 $\bigstar$},90.86$\pm$2.31,\color{violet}{94.02$\pm$1.21}
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast2 cheat",\color{red}{99.68$\pm$0.63 $\bigstar$},\color{red}{97.68$\pm$1.8 $\bigstar$},NaN,\color{blue}{96.21$\pm$1.04 $\bigstar$},93.52$\pm$5.17 X,97.03$\pm$1.75 $\bigstar$,\color{violet}{98.18$\pm$0.78 $\bigstar$},\color{red}{96.53$\pm$0.97 $\bigstar$}

In [2]:
mplp_score = pd.DataFrame(data=
    {
        'CN*': ['80.52$\pm$4.07', '74$\pm$1.98', '37.22$\pm$3.52', '72.6$\pm$3.85', '47.67$\pm$10.87', '11.57$\pm$0.55', '9.38$\pm$1.05', '51.74$\pm$2.7'],
        'AA*': ['85.51$\pm$2.25', '74$\pm$1.98', '39.48$\pm$3.53', '73.62$\pm$1.01', '58.34$\pm$2.88', '11.57$\pm$0.55', '9.38$\pm$1.05', '68.13$\pm$1.61'],
        'RA*': ['85.95$\pm$1.83', '74$\pm$1.98', '39.84$\pm$3.54', '73.62$\pm$1.01', '61.47$\pm$4.59', '11.57$\pm$0.55', '9.38$\pm$1.05', '74.45$\pm$0.55'],
        'GCN*': ['73.29$\pm$4.70', '78.32$\pm$2.57', '37.32$\pm$4.69', '73.15$\pm$2.41', '40.68$\pm$5.45', '15.40$\pm$2.90', '24.42$\pm$4.59', '61.02$\pm$11.91',],
        'SEAL*': ['90.47$\pm$3.00', '86.59$\pm$3.03', '44.47$\pm$2.86', '83.92$\pm$1.17', '64.80$\pm$4.23', '31.46$\pm$3.25', '61.00$\pm$10.10', '83.42$\pm$1.01',],
        'ELPH*': ['87.60$\pm$1.49', '88.49$\pm$2.14', '46.91$\pm$2.21', '82.74$\pm$1.19', '64.45$\pm$3.91', '26.61$\pm$1.73', '61.07$\pm$3.06', '75.25$\pm$1.44',],
        'NCNC*': ['86.16$\pm$1.77', '83.18$\pm$3.17', '46.85$\pm$3.18', '82.00$\pm$0.97', '60.49$\pm$5.09', '23.28$\pm$1.55', '52.45$\pm$8.77', '83.94$\pm$1.57',],
        'MPLP*': ['92.12$\pm$2.21', '90.02$\pm$2.04', '52.55$\pm$2.90', '85.36$\pm$0.72', '74.28$\pm$2.09', '32.66$\pm$3.58', '64.68$\pm$3.14', '86.11$\pm$0.83',],
        'MPLP+*': ['91.24$\pm$2.11', '88.91$\pm$2.04', '51.81$\pm$2.39', '84.95$\pm$0.66', '72.73$\pm$2.99', '31.86$\pm$2.59', '60.94$\pm$2.51', '87.07$\pm$0.89',],
    }
)

tbgrl_score = pd.DataFrame(data=
    {
        'GCN*': ['81.6$\pm$1.3', '82.2$\pm$1.17', '64.2$\pm$2.9', '42.6$\pm$3.6', '76.2$\pm$1', '79.8$\pm$1.8'],
        'GRACE*': ['68.6$\pm$5.6', '70.7$\pm$6.8', '48.6$\pm$2.5', '24$\pm$2.7', '45.6$\pm$6.6', np.nan],
        'BGRL*': ['79.2$\pm$1.5', '85.8$\pm$2', '56.2$\pm$1.3', '34.6$\pm$1.8', '51.5$\pm$1.6', '47.6$\pm$1.5'],
        'T-BGRL*': ['77.3$\pm$2', '86.8$\pm$2.3', '51.7$\pm$1.6', '31.5$\pm$1.5', '55.5$\pm$0.9', '47.1$\pm$2.1'],
    }
)

<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:18: SyntaxWarning: invalid escape sequence '\p'
<>:18: SyntaxWarning: invalid escape sequence '\p'
<>:18: SyntaxWarning: invalid escape sequence '\p'
<>:18: SyntaxWarning: invalid escape sequence '\p'
<>:18: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:5: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:7: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:8: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:10: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:17: SyntaxWarning: invalid escape sequence '\p'
<>:18: SyntaxWarning: invalid escape sequence '\p'
<>:18: SyntaxWarning: invalid escape sequence '\p'
<>:18: SyntaxWarning: invalid escape sequence '\p'
<>:18: SyntaxWarning: invalid escape sequence '\p'
<>:18: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:19: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
<>:20: SyntaxWarning: invalid escape sequence '\p'
/tmp/ipykernel_269/652861326.py:3: SyntaxWarning: invalid escape sequence '\p'
  'CN*': ['80.52$\pm$4.07', '74$\pm$1.98', '37.22$\pm$3.52', '72.6$\pm$3.85', '47.67$\pm$10.87', '11.57$\pm$0.55', '9.38$\pm$1.05', '51.74$\pm$2.7'],
/tmp/ipykernel_269/652861326.py:3: SyntaxWarning: invalid escape sequence '\p'
  'CN*': ['80.52$\pm$4.07', '74$\pm$1.98', '37.22$\pm$3.52', '72.6$\pm$3.85', '47.67$\pm$10.87', '11.57$\pm$0.55', '9.38$\pm$1.05', '51.74$\pm$2.7'],
/tmp/ipykernel_269/652861326.py:3: SyntaxWarning: invalid escape sequence '\p'
  'CN*': ['80.52$\pm$4.07', '74$\pm$1.98', '37.22$\pm$3.52', '72.6$\pm$3.85', '47.67$\pm$10.87', '11.57$\pm$0.55', '9.38$\pm$1.05', '51.74$\pm$2.7'],
/tmp/ipykernel_269/652861326.py:3: SyntaxWarning: invalid escape sequence '\p'
  'CN*': ['80.52$\pm$4.07', '74$\pm$1.98', '37.22$\pm$3.52', '72.6$\pm$3.85', '47.67$\pm$10.87', '11.57$\pm$0.55', '9.38$\pm$1.05', '51.74$\pm$2.7'],
/tmp/ipykernel_269/652861326.py:3: SyntaxWarning: invalid escape sequence '\p'
  'CN*': ['80.52$\pm$4.07', '74$\pm$1.98', '37.22$\pm$3.52', '72.6$\pm$3.85', '47.67$\pm$10.87', '11.57$\pm$0.55', '9.38$\pm$1.05', '51.74$\pm$2.7'],
/tmp/ipykernel_269/652861326.py:3: SyntaxWarning: invalid escape sequence '\p'
  'CN*': ['80.52$\pm$4.07', '74$\pm$1.98', '37.22$\pm$3.52', '72.6$\pm$3.85', '47.67$\pm$10.87', '11.57$\pm$0.55', '9.38$\pm$1.05', '51.74$\pm$2.7'],
/tmp/ipykernel_269/652861326.py:3: SyntaxWarning: invalid escape sequence '\p'
  'CN*': ['80.52$\pm$4.07', '74$\pm$1.98', '37.22$\pm$3.52', '72.6$\pm$3.85', '47.67$\pm$10.87', '11.57$\pm$0.55', '9.38$\pm$1.05', '51.74$\pm$2.7'],
/tmp/ipykernel_269/652861326.py:3: SyntaxWarning: invalid escape sequence '\p'
  'CN*': ['80.52$\pm$4.07', '74$\pm$1.98', '37.22$\pm$3.52', '72.6$\pm$3.85', '47.67$\pm$10.87', '11.57$\pm$0.55', '9.38$\pm$1.05', '51.74$\pm$2.7'],
/tmp/ipykernel_269/652861326.py:4: SyntaxWarning: invalid escape sequence '\p'
  'AA*': ['85.51$\pm$2.25', '74$\pm$1.98', '39.48$\pm$3.53', '73.62$\pm$1.01', '58.34$\pm$2.88', '11.57$\pm$0.55', '9.38$\pm$1.05', '68.13$\pm$1.61'],
/tmp/ipykernel_269/652861326.py:4: SyntaxWarning: invalid escape sequence '\p'
  'AA*': ['85.51$\pm$2.25', '74$\pm$1.98', '39.48$\pm$3.53', '73.62$\pm$1.01', '58.34$\pm$2.88', '11.57$\pm$0.55', '9.38$\pm$1.05', '68.13$\pm$1.61'],
/tmp/ipykernel_269/652861326.py:4: SyntaxWarning: invalid escape sequence '\p'
  'AA*': ['85.51$\pm$2.25', '74$\pm$1.98', '39.48$\pm$3.53', '73.62$\pm$1.01', '58.34$\pm$2.88', '11.57$\pm$0.55', '9.38$\pm$1.05', '68.13$\pm$1.61'],
/tmp/ipykernel_269/652861326.py:4: SyntaxWarning: invalid escape sequence '\p'
  'AA*': ['85.51$\pm$2.25', '74$\pm$1.98', '39.48$\pm$3.53', '73.62$\pm$1.01', '58.34$\pm$2.88', '11.57$\pm$0.55', '9.38$\pm$1.05', '68.13$\pm$1.61'],
/tmp/ipykernel_269/652861326.py:4: SyntaxWarning: invalid escape sequence '\p'
  'AA*': ['85.51$\pm$2.25', '74$\pm$1.98', '39.48$\pm$3.53', '73.62$\pm$1.01', '58.34$\pm$2.88', '11.57$\pm$0.55', '9.38$\pm$1.05', '68.13$\pm$1.61'],
/tmp/ipykernel_269/652861326.py:4: SyntaxWarning: invalid escape sequence '\p'
  'AA*': ['85.51$\pm$2.25', '74$\pm$1.98', '39.48$\pm$3.53', '73.62$\pm$1.01', '58.34$\pm$2.88', '11.57$\pm$0.55', '9.38$\pm$1.05', '68.13$\pm$1.61'],
/tmp/ipykernel_269/652861326.py:4: SyntaxWarning: invalid escape sequence '\p'
  'AA*': ['85.51$\pm$2.25', '74$\pm$1.98', '39.48$\pm$3.53', '73.62$\pm$1.01', '58.34$\pm$2.88', '11.57$\pm$0.55', '9.38$\pm$1.05', '68.13$\pm$1.61'],
/tmp/ipykernel_269/652861326.py:4: SyntaxWarning: invalid escape sequence '\p'
  'AA*': ['85.51$\pm$2.25', '74$\pm$1.98', '39.48$\pm$3.53', '73.62$\pm$1.01', '58.34$\pm$2.88', '11.57$\pm$0.55', '9.38$\pm$1.05', '68.13$\pm$1.61'],
/tmp/ipykernel_269/652861326.py:5: SyntaxWarning: invalid escape sequence '\p'
  'RA*': ['85.95$\pm$1.83', '74$\pm$1.98', '39.84$\pm$3.54', '73.62$\pm$1.01', '61.47$\pm$4.59', '11.57$\pm$0.55', '9.38$\pm$1.05', '74.45$\pm$0.55'],
/tmp/ipykernel_269/652861326.py:5: SyntaxWarning: invalid escape sequence '\p'
  'RA*': ['85.95$\pm$1.83', '74$\pm$1.98', '39.84$\pm$3.54', '73.62$\pm$1.01', '61.47$\pm$4.59', '11.57$\pm$0.55', '9.38$\pm$1.05', '74.45$\pm$0.55'],
/tmp/ipykernel_269/652861326.py:5: SyntaxWarning: invalid escape sequence '\p'
  'RA*': ['85.95$\pm$1.83', '74$\pm$1.98', '39.84$\pm$3.54', '73.62$\pm$1.01', '61.47$\pm$4.59', '11.57$\pm$0.55', '9.38$\pm$1.05', '74.45$\pm$0.55'],
/tmp/ipykernel_269/652861326.py:5: SyntaxWarning: invalid escape sequence '\p'
  'RA*': ['85.95$\pm$1.83', '74$\pm$1.98', '39.84$\pm$3.54', '73.62$\pm$1.01', '61.47$\pm$4.59', '11.57$\pm$0.55', '9.38$\pm$1.05', '74.45$\pm$0.55'],
/tmp/ipykernel_269/652861326.py:5: SyntaxWarning: invalid escape sequence '\p'
  'RA*': ['85.95$\pm$1.83', '74$\pm$1.98', '39.84$\pm$3.54', '73.62$\pm$1.01', '61.47$\pm$4.59', '11.57$\pm$0.55', '9.38$\pm$1.05', '74.45$\pm$0.55'],
/tmp/ipykernel_269/652861326.py:5: SyntaxWarning: invalid escape sequence '\p'
  'RA*': ['85.95$\pm$1.83', '74$\pm$1.98', '39.84$\pm$3.54', '73.62$\pm$1.01', '61.47$\pm$4.59', '11.57$\pm$0.55', '9.38$\pm$1.05', '74.45$\pm$0.55'],
/tmp/ipykernel_269/652861326.py:5: SyntaxWarning: invalid escape sequence '\p'
  'RA*': ['85.95$\pm$1.83', '74$\pm$1.98', '39.84$\pm$3.54', '73.62$\pm$1.01', '61.47$\pm$4.59', '11.57$\pm$0.55', '9.38$\pm$1.05', '74.45$\pm$0.55'],
/tmp/ipykernel_269/652861326.py:5: SyntaxWarning: invalid escape sequence '\p'
  'RA*': ['85.95$\pm$1.83', '74$\pm$1.98', '39.84$\pm$3.54', '73.62$\pm$1.01', '61.47$\pm$4.59', '11.57$\pm$0.55', '9.38$\pm$1.05', '74.45$\pm$0.55'],
/tmp/ipykernel_269/652861326.py:6: SyntaxWarning: invalid escape sequence '\p'
  'GCN*': ['73.29$\pm$4.70', '78.32$\pm$2.57', '37.32$\pm$4.69', '73.15$\pm$2.41', '40.68$\pm$5.45', '15.40$\pm$2.90', '24.42$\pm$4.59', '61.02$\pm$11.91',],
/tmp/ipykernel_269/652861326.py:6: SyntaxWarning: invalid escape sequence '\p'
  'GCN*': ['73.29$\pm$4.70', '78.32$\pm$2.57', '37.32$\pm$4.69', '73.15$\pm$2.41', '40.68$\pm$5.45', '15.40$\pm$2.90', '24.42$\pm$4.59', '61.02$\pm$11.91',],
/tmp/ipykernel_269/652861326.py:6: SyntaxWarning: invalid escape sequence '\p'
  'GCN*': ['73.29$\pm$4.70', '78.32$\pm$2.57', '37.32$\pm$4.69', '73.15$\pm$2.41', '40.68$\pm$5.45', '15.40$\pm$2.90', '24.42$\pm$4.59', '61.02$\pm$11.91',],
/tmp/ipykernel_269/652861326.py:6: SyntaxWarning: invalid escape sequence '\p'
  'GCN*': ['73.29$\pm$4.70', '78.32$\pm$2.57', '37.32$\pm$4.69', '73.15$\pm$2.41', '40.68$\pm$5.45', '15.40$\pm$2.90', '24.42$\pm$4.59', '61.02$\pm$11.91',],
/tmp/ipykernel_269/652861326.py:6: SyntaxWarning: invalid escape sequence '\p'
  'GCN*': ['73.29$\pm$4.70', '78.32$\pm$2.57', '37.32$\pm$4.69', '73.15$\pm$2.41', '40.68$\pm$5.45', '15.40$\pm$2.90', '24.42$\pm$4.59', '61.02$\pm$11.91',],
/tmp/ipykernel_269/652861326.py:6: SyntaxWarning: invalid escape sequence '\p'
  'GCN*': ['73.29$\pm$4.70', '78.32$\pm$2.57', '37.32$\pm$4.69', '73.15$\pm$2.41', '40.68$\pm$5.45', '15.40$\pm$2.90', '24.42$\pm$4.59', '61.02$\pm$11.91',],
/tmp/ipykernel_269/652861326.py:6: SyntaxWarning: invalid escape sequence '\p'
  'GCN*': ['73.29$\pm$4.70', '78.32$\pm$2.57', '37.32$\pm$4.69', '73.15$\pm$2.41', '40.68$\pm$5.45', '15.40$\pm$2.90', '24.42$\pm$4.59', '61.02$\pm$11.91',],
/tmp/ipykernel_269/652861326.py:6: SyntaxWarning: invalid escape sequence '\p'
  'GCN*': ['73.29$\pm$4.70', '78.32$\pm$2.57', '37.32$\pm$4.69', '73.15$\pm$2.41', '40.68$\pm$5.45', '15.40$\pm$2.90', '24.42$\pm$4.59', '61.02$\pm$11.91',],
/tmp/ipykernel_269/652861326.py:7: SyntaxWarning: invalid escape sequence '\p'
  'SEAL*': ['90.47$\pm$3.00', '86.59$\pm$3.03', '44.47$\pm$2.86', '83.92$\pm$1.17', '64.80$\pm$4.23', '31.46$\pm$3.25', '61.00$\pm$10.10', '83.42$\pm$1.01',],
/tmp/ipykernel_269/652861326.py:7: SyntaxWarning: invalid escape sequence '\p'
  'SEAL*': ['90.47$\pm$3.00', '86.59$\pm$3.03', '44.47$\pm$2.86', '83.92$\pm$1.17', '64.80$\pm$4.23', '31.46$\pm$3.25', '61.00$\pm$10.10', '83.42$\pm$1.01',],
/tmp/ipykernel_269/652861326.py:7: SyntaxWarning: invalid escape sequence '\p'
  'SEAL*': ['90.47$\pm$3.00', '86.59$\pm$3.03', '44.47$\pm$2.86', '83.92$\pm$1.17', '64.80$\pm$4.23', '31.46$\pm$3.25', '61.00$\pm$10.10', '83.42$\pm$1.01',],
/tmp/ipykernel_269/652861326.py:7: SyntaxWarning: invalid escape sequence '\p'
  'SEAL*': ['90.47$\pm$3.00', '86.59$\pm$3.03', '44.47$\pm$2.86', '83.92$\pm$1.17', '64.80$\pm$4.23', '31.46$\pm$3.25', '61.00$\pm$10.10', '83.42$\pm$1.01',],
/tmp/ipykernel_269/652861326.py:7: SyntaxWarning: invalid escape sequence '\p'
  'SEAL*': ['90.47$\pm$3.00', '86.59$\pm$3.03', '44.47$\pm$2.86', '83.92$\pm$1.17', '64.80$\pm$4.23', '31.46$\pm$3.25', '61.00$\pm$10.10', '83.42$\pm$1.01',],
/tmp/ipykernel_269/652861326.py:7: SyntaxWarning: invalid escape sequence '\p'
  'SEAL*': ['90.47$\pm$3.00', '86.59$\pm$3.03', '44.47$\pm$2.86', '83.92$\pm$1.17', '64.80$\pm$4.23', '31.46$\pm$3.25', '61.00$\pm$10.10', '83.42$\pm$1.01',],
/tmp/ipykernel_269/652861326.py:7: SyntaxWarning: invalid escape sequence '\p'
  'SEAL*': ['90.47$\pm$3.00', '86.59$\pm$3.03', '44.47$\pm$2.86', '83.92$\pm$1.17', '64.80$\pm$4.23', '31.46$\pm$3.25', '61.00$\pm$10.10', '83.42$\pm$1.01',],
/tmp/ipykernel_269/652861326.py:7: SyntaxWarning: invalid escape sequence '\p'
  'SEAL*': ['90.47$\pm$3.00', '86.59$\pm$3.03', '44.47$\pm$2.86', '83.92$\pm$1.17', '64.80$\pm$4.23', '31.46$\pm$3.25', '61.00$\pm$10.10', '83.42$\pm$1.01',],
/tmp/ipykernel_269/652861326.py:8: SyntaxWarning: invalid escape sequence '\p'
  'ELPH*': ['87.60$\pm$1.49', '88.49$\pm$2.14', '46.91$\pm$2.21', '82.74$\pm$1.19', '64.45$\pm$3.91', '26.61$\pm$1.73', '61.07$\pm$3.06', '75.25$\pm$1.44',],
/tmp/ipykernel_269/652861326.py:8: SyntaxWarning: invalid escape sequence '\p'
  'ELPH*': ['87.60$\pm$1.49', '88.49$\pm$2.14', '46.91$\pm$2.21', '82.74$\pm$1.19', '64.45$\pm$3.91', '26.61$\pm$1.73', '61.07$\pm$3.06', '75.25$\pm$1.44',],
/tmp/ipykernel_269/652861326.py:8: SyntaxWarning: invalid escape sequence '\p'
  'ELPH*': ['87.60$\pm$1.49', '88.49$\pm$2.14', '46.91$\pm$2.21', '82.74$\pm$1.19', '64.45$\pm$3.91', '26.61$\pm$1.73', '61.07$\pm$3.06', '75.25$\pm$1.44',],
/tmp/ipykernel_269/652861326.py:8: SyntaxWarning: invalid escape sequence '\p'
  'ELPH*': ['87.60$\pm$1.49', '88.49$\pm$2.14', '46.91$\pm$2.21', '82.74$\pm$1.19', '64.45$\pm$3.91', '26.61$\pm$1.73', '61.07$\pm$3.06', '75.25$\pm$1.44',],
/tmp/ipykernel_269/652861326.py:8: SyntaxWarning: invalid escape sequence '\p'

In [44]:
# tab 1 non -attr
names1  = [
    '70_first/_USAir.csv',
    '70_first/_NS.csv',
    '70_first/_PB.csv',
    '70_first/_Yeast.csv',
    '70_first/_Celegans.csv',
    '70_first/_power.csv',
    '70_first/_Router.csv',
    '70_first/_Ecoli.csv',
]
names2 = [
    '70_first/a_USAir.csv',
    '70_first/a_NS.csv',
    '70_first/a_PB.csv',
    '70_first/a_Yeast.csv',
    '70_first/a_Celegans.csv',
    '70_first/a_power.csv',
    '70_first/a_Router.csv',
    '70_first/a_Ecoli.csv',
]
names3 = [
    '70_first/b_USAir.csv',
    '70_first/b_NS.csv',
    '70_first/b_PB.csv',
    '70_first/b_Yeast.csv',
    '70_first/b_Celegans.csv',
    '70_first/b_power.csv',
    '70_first/b_Router.csv',
    '70_first/b_Ecoli.csv',
]
names4 = [
    '70_first/c_USAir.csv',
    '70_first/c_NS.csv',
    '70_first/c_PB.csv',
    '70_first/c_Yeast.csv',
    '70_first/c_Celegans.csv',
    '70_first/c_power.csv',
    '70_first/c_Router.csv',
    '70_first/c_Ecoli.csv',
]
data1, res1 = ut.mix_dataset(names1, 'Hits@50', filtre2=['\+', 'prob', 'cheat'])
data2, res2 = ut.mix_dataset(names2, 'Hits@50', filtre2=['\+', 'prob', 'cheat'])
data3, res3 = ut.mix_dataset(names3, 'Hits@50', filtre2=['prob', 'cheat'])
data4, res4 = ut.mix_dataset(names4, 'Hits@50', filtre2=['prob', 'cheat'])

power_data, power_res = ut.mix_dataset(['70_first/d_power.csv'], 'Hits@50', filtre2=['\+', 'prob', 'cheat'])
power_data.index =  ['70_first/_power.csv']

mplp_score.index = data1.index
data2.index = data1.index
data3.index = data1.index
data4.index = data1.index

res2.index = res1.index
res3.index = res1.index
res4.index = res1.index

power_data = pd.concat([mplp_score.loc['70_first/_power.csv'].to_frame().T, power_data], axis=1)
combined_data = pd.concat([mplp_score, data1, data2, data3, data4], axis=1)
combined_data.loc['70_first/_power.csv'] = power_data.loc['70_first/_power.csv']
combined_res = pd.concat([res1, res2, res3, res4], axis=1)
combined_res.loc['70_first/_power.csv'] = power_res.loc['70_first/d_power.csv']
combined_data = ut.tex_table(combined_data, combined_res)
combined_data.T

<>:42: SyntaxWarning: invalid escape sequence '\+'
<>:43: SyntaxWarning: invalid escape sequence '\+'
<>:47: SyntaxWarning: invalid escape sequence '\+'
<>:42: SyntaxWarning: invalid escape sequence '\+'
<>:43: SyntaxWarning: invalid escape sequence '\+'
<>:47: SyntaxWarning: invalid escape sequence '\+'
/tmp/ipykernel_263/1822799127.py:42: SyntaxWarning: invalid escape sequence '\+'
  data1, res1 = ut.mix_dataset(names1, 'Hits@50', filtre2=['\+', 'prob', 'cheat'])
/tmp/ipykernel_263/1822799127.py:43: SyntaxWarning: invalid escape sequence '\+'
  data2, res2 = ut.mix_dataset(names2, 'Hits@50', filtre2=['\+', 'prob', 'cheat'])
/tmp/ipykernel_263/1822799127.py:47: SyntaxWarning: invalid escape sequence '\+'
  power_data, power_res = ut.mix_dataset(['70_first/d_power.csv'], 'Hits@50', filtre2=['\+', 'prob', 'cheat'])

\resizebox{\textwidth}{!}{
\begin{tabular}{lllllllll}
\toprule
 & 70_first/_USAir.csv & 70_first/_NS.csv & 70_first/_PB.csv & 70_first/_Yeast.csv & 70_first/_Celegans.csv & 70_first/_power.csv & 70_first/_Router.csv & 70_first/_Ecoli.csv \\
\midrule
CN* & 80.52$\pm$4.07 & 74$\pm$1.98 & 37.22$\pm$3.52 & 72.6$\pm$3.85 & 47.67$\pm$10.87 & 11.57$\pm$0.55 & 9.38$\pm$1.05 & 51.74$\pm$2.7 \\
AA* & 85.51$\pm$2.25 & 74$\pm$1.98 & 39.48$\pm$3.53 & 73.62$\pm$1.01 & 58.34$\pm$2.88 & 11.57$\pm$0.55 & 9.38$\pm$1.05 & 68.13$\pm$1.61 \\
RA* & 85.95$\pm$1.83 & 74$\pm$1.98 & 39.84$\pm$3.54 & 73.62$\pm$1.01 & 61.47$\pm$4.59 & 11.57$\pm$0.55 & 9.38$\pm$1.05 & 74.45$\pm$0.55 \\
GCN* & 73.29$\pm$4.70 & 78.32$\pm$2.57 & 37.32$\pm$4.69 & 73.15$\pm$2.41 & 40.68$\pm$5.45 & 15.40$\pm$2.90 & 24.42$\pm$4.59 & 61.02$\pm$11.91 \\
SEAL* & 90.47$\pm$3.00 & 86.59$\pm$3.03 & 44.47$\pm$2.86 & 83.92$\pm$1.17 & 64.80$\pm$4.23 & 31.46$\pm$3.25 & \color{violet}{61.00$\pm$10.10} & 83.42$\pm$1.01 \\
ELPH* & 87.60$\pm$1.49 & \color{violet}{88.49$\pm$2.14} & 46.91$\pm$2.21 & 82.74$\pm$1.19 & 64.45$\pm$3.91 & 26.61$\pm$1.73 & \color{blue}{61.07$\pm$3.06} & 75.25$\pm$1.44 \\
NCNC* & 86.16$\pm$1.77 & 83.18$\pm$3.17 & 46.85$\pm$3.18 & 82.00$\pm$0.97 & 60.49$\pm$5.09 & 23.28$\pm$1.55 & 52.45$\pm$8.77 & 83.94$\pm$1.57 \\
MPLP* & \color{blue}{92.12$\pm$2.21} & \color{red}{90.02$\pm$2.04} & \color{red}{52.55$\pm$2.90} & \color{red}{85.36$\pm$0.72} & \color{red}{74.28$\pm$2.09} & 32.66$\pm$3.58 & \color{red}{64.68$\pm$3.14} & \color{blue}{86.11$\pm$0.83} \\
MPLP+* & 91.24$\pm$2.11 & \color{blue}{88.91$\pm$2.04} & \color{violet}{51.81$\pm$2.39} & \color{blue}{84.95$\pm$0.66} & 72.73$\pm$2.99 & 31.86$\pm$2.59 & 60.94$\pm$2.51 & \color{red}{87.07$\pm$0.89} \\
baseline,enc:gcn bgrl,pred:mlp & 89.74$\pm$2.29 & 80.91$\pm$1.18 & 50.94$\pm$3.3 & 84.19$\pm$0.94 $\bigstar$ & 63.61$\pm$3.65 & 30.37$\pm$0.86 & 26.36$\pm$1.52 & 81.91$\pm$1.1 \\
bgrl,enc:gcn bgrl,pred:mlp,random & 87.11$\pm$1.9 & 80.49$\pm$1.29 & 47.24$\pm$3.24 & 82.72$\pm$1.01 & 67.41$\pm$3.44 & 25.67$\pm$0.74 & 30.95$\pm$1.16 & 81.63$\pm$0.72 \\
bgrl,enc:gcn bgrl,pred:mlp,deg & 86.47$\pm$3.22 & 83.47$\pm$2.74 & 47.75$\pm$3.57 & 80.99$\pm$1.49 & 68.72$\pm$3.37 & 28.92$\pm$2.63 & 41.41$\pm$6.38 & 82.73$\pm$0.83 \\
bgrl,enc:gcn bgrl,pred:mlp,evc & 88.82$\pm$1.47 & 80.42$\pm$0.81 & 49.0$\pm$3.9 & 84.25$\pm$0.57 $\bigstar$ & 60.47$\pm$4.94 & 21.4$\pm$1.2 X & 47.79$\pm$6.0 & 82.79$\pm$1.45 \\
bgrl,enc:gcn bgrl,pred:mlp,pr & 86.24$\pm$2.51 & 80.29$\pm$1.4 & 44.47$\pm$2.73 & 81.65$\pm$1.54 & 66.67$\pm$3.77 & 26.05$\pm$1.12 & 48.2$\pm$2.92 & 82.95$\pm$0.81 \\
bgrl,enc:gcn bgrl,pred:mlp,scom & 89.74$\pm$2.13 & 81.3$\pm$0.8 & 44.67$\pm$2.61 & 84.08$\pm$0.74 & 70.51$\pm$3.43 & 25.86$\pm$1.07 & 54.25$\pm$3.26 $\bigstar$ & 82.36$\pm$1.04 \\
grace,enc:gcn bgrl,pred:mlp,random & \color{violet}{91.48$\pm$1.72} & 79.84$\pm$0.86 & 48.03$\pm$2.32 & 84.23$\pm$0.52 $\bigstar$ & 72.1$\pm$2.43 & 32.15$\pm$1.25 & 29.91$\pm$2.21 & 81.93$\pm$0.63 \\
grace,enc:gcn bgrl,pred:mlp,deg & 87.39$\pm$10.03 & 80.86$\pm$2.18 & 46.12$\pm$3.78 & 83.14$\pm$1.26 & 69.23$\pm$2.68 & 27.02$\pm$9.75 & 17.79$\pm$10.89 X & 71.05$\pm$24.03 \\
grace,enc:gcn bgrl,pred:mlp,evc & 59.46$\pm$4.74 X & 74.01$\pm$3.76 & 44.36$\pm$3.17 & 82.72$\pm$0.9 & 70.4$\pm$2.77 & 31.93$\pm$1.33 & 21.46$\pm$4.59 X & 82.19$\pm$1.2 \\
grace,enc:gcn bgrl,pred:mlp,pr & 90.33$\pm$1.95 & 82.24$\pm$1.95 & 49.56$\pm$3.68 & 82.48$\pm$0.72 & \color{violet}{72.75$\pm$1.57 $\bigstar$} & 33.45$\pm$1.24 & 53.76$\pm$2.91 $\bigstar$ & \color{violet}{84.32$\pm$0.85 $\bigstar$} \\
grace,enc:gcn bgrl,pred:mlp,scom & 88.4$\pm$2.93 & 80.31$\pm$1.34 & 46.01$\pm$3.11 & 81.88$\pm$1.23 & 67.32$\pm$2.46 & \color{blue}{36.15$\pm$1.51 $\bigstar$} & 42.33$\pm$1.6 & 82.88$\pm$1.39 \\
lbgrl,enc:gcn bgrl,pred:mlp,random & 79.81$\pm$3.92 & 80.02$\pm$1.24 & 47.72$\pm$2.3 & 81.52$\pm$1.16 & 65.52$\pm$2.25 & 23.66$\pm$0.95 & 39.72$\pm$8.46 & 81.75$\pm$1.01 \\
lbgrl,enc:gcn bgrl,pred:mlp,deg & 83.6$\pm$3.96 & 81.51$\pm$1.81 & 46.8$\pm$3.25 & 81.92$\pm$1.04 & 71.03$\pm$4.36 & 27.76$\pm$2.46 & 49.9$\pm$3.3 & 73.27$\pm$1.14 X \\
lbgrl,enc:gcn bgrl,pred:mlp,evc & 89.39$\pm$2.4 & 67.96$\pm$4.61 X & 34.51$\pm$3.75 X & 84.22$\pm$0.73 $\bigstar$ & 67.3$\pm$2.55 & 27.54$\pm$0.92 & 34.83$\pm$4.65 & 82.07$\pm$0.93 \\
lbgrl,enc:gcn bgrl,pred:mlp,pr & 90.66$\pm$1.93 & 85.0$\pm$1.88 $\bigstar$ & 47.59$\pm$2.18 & 83.52$\pm$1.12 & 70.05$\pm$2.87 & 19.58$\pm$1.23 X & 45.02$\pm$6.75 & 83.34$\pm$1.08 \\
lbgrl,enc:gcn bgrl,pred:mlp,scom & 89.22$\pm$2.76 & 76.86$\pm$1.38 & 47.68$\pm$3.35 & 83.14$\pm$0.55 & 69.04$\pm$2.79 & 20.4$\pm$0.92 X & 33.96$\pm$1.24 & 83.22$\pm$0.71 \\
lgrace,enc:gcn bgrl,pred:mlp,random & \color{red}{92.47$\pm$0.8 $\bigstar$} & 80.8$\pm$1.45 & \color{blue}{51.98$\pm$3.28 $\bigstar$} & 84.33$\pm$1.09 & 70.56$\pm$3.27 & 30.58$\pm$1.81 & 34.67$\pm$10.92 & 81.67$\pm$1.22 \\
lgrace,enc:gcn bgrl,pred:mlp,deg & 90.71$\pm$1.88 & 80.27$\pm$1.44 & 48.52$\pm$2.79 & 82.03$\pm$1.59 & 65.9$\pm$3.9 & 33.7$\pm$2.51 & 29.34$\pm$6.84 & 84.27$\pm$0.78 $\bigstar$ \\
lgrace,enc:gcn bgrl,pred:mlp,evc & 90.61$\pm$2.57 & 83.16$\pm$1.43 & 50.51$\pm$3.81 & 83.75$\pm$1.05 & 72.54$\pm$4.24 $\bigstar$ & 28.83$\pm$0.89 & 26.09$\pm$5.79 & 79.19$\pm$0.93 \\
lgrace,enc:gcn bgrl,pred:mlp,pr & 90.0$\pm$2.02 & 83.34$\pm$1.49 & 48.7$\pm$2.61 & \color{violet}{84.38$\pm$0.68 $\bigstar$} & \color{blue}{72.89$\pm$2.3 $\bigstar$} & 29.5$\pm$1.19 & 33.12$\pm$1.88 & 83.08$\pm$0.45 \\
lgrace,enc:gcn bgrl,pred:mlp,scom & 90.8$\pm$1.84 & 81.13$\pm$1.21 & 49.92$\pm$2.82 & 79.85$\pm$7.51 & 65.31$\pm$4.03 & 27.67$\pm$1.68 & 31.41$\pm$1.33 & 82.45$\pm$0.88 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast & 88.82$\pm$2.35 & 79.18$\pm$1.49 & 43.95$\pm$2.45 & 81.01$\pm$1.37 & 58.72$\pm$3.18 & \color{violet}{35.34$\pm$1.33} & 49.48$\pm$3.53 & 79.21$\pm$1.4 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast2 & 80.59$\pm$3.58 & 80.46$\pm$1.36 & 42.7$\pm$2.91 & 79.58$\pm$1.59 X & 57.2$\pm$3.6 & 31.18$\pm$1.64 & 43.33$\pm$3.33 & 79.77$\pm$1.02 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast & 87.01$\pm$2.03 & 73.72$\pm$4.33 & 45.65$\pm$2.74 & 79.84$\pm$1.61 X & 64.71$\pm$3.17 & 32.61$\pm$1.17 & 33.83$\pm$1.93 & 79.54$\pm$1.14 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast2 & 86.21$\pm$3.63 & 80.89$\pm$1.41 & 45.54$\pm$2.5 & 79.46$\pm$1.49 X & 61.98$\pm$3.55 & 33.87$\pm$1.68 & 26.43$\pm$2.69 & 82.36$\pm$0.64 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fast & 79.06$\pm$2.75 & 84.31$\pm$1.97 $\bigstar$ & 44.46$\pm$2.91 & 80.77$\pm$1.18 & 65.22$\pm$2.76 & 34.94$\pm$1.37 & 42.29$\pm$3.98 & 77.81$\pm$0.98 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fast2 & 87.95$\pm$2.58 & 82.97$\pm$1.67 & 44.23$\pm$2.29 & 81.19$\pm$0.91 & 42.73$\pm$2.57 X & 33.11$\pm$1.47 & 35.94$\pm$2.44 & 79.21$\pm$1.47 \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast & 90.38$\pm$2.54 & 53.41$\pm$17.6 X & 48.54$\pm$2.99 & 83.22$\pm$0.96 & 67.02$\pm$2.6 & 33.45$\pm$1.08 & 29.76$\pm$3.38 & 82.9$\pm$0.59 \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast2 & 88.33$\pm$2.57 & 80.58$\pm$1.14 & 44.43$\pm$4.54 & 79.77$\pm$1.78 & 60.44$\pm$3.16 & 35.08$\pm$1.91 & 27.6$\pm$1.06 & 81.28$\pm$1.0 \\
csgcl,enc:gcn bgrl,pred:mlp,random & 86.26$\pm$3.28 & 81.73$\pm$0.87 & 47.92$\pm$2.02 & 81.68$\pm$1.07 & 70.09$\pm$2.1 & 35.08$\pm$1.32 & 40.11$\pm$2.23 & 81.5$\pm$1.11 \\
csgcl,enc:gcn bgrl,pred:mlp,deg & 88.94$\pm$2.81 & 80.33$\pm$3.89 & 48.95$\pm$2.73 & 82.06$\pm$1.56 & 71.7$\pm$2.12 & 33.47$\pm$2.17 & 21.19$\pm$8.68 & 82.06$\pm$0.61 \\
csgcl,enc:gcn bgrl,pred:mlp,pr & 85.25$\pm$2.51 & 79.07$\pm$2.65 & 41.48$\pm$2.74 & 80.76$\pm$0.88 & 71.4$\pm$2.43 & 34.41$\pm$1.0 & 33.57$\pm$5.53 & 82.09$\pm$1.32 \\
csgcl,enc:gcn bgrl,pred:mlp,evc & 81.53$\pm$2.98 & 71.33$\pm$2.75 & 49.42$\pm$2.8 & 83.53$\pm$0.8 & 70.96$\pm$3.13 & 35.12$\pm$1.39 & 27.19$\pm$1.47 & 84.16$\pm$1.38 \\
csgcl,enc:gcn bgrl,pred:mlp,scom & 90.16$\pm$1.61 & 82.45$\pm$1.69 & 47.75$\pm$3.5 & 83.32$\pm$0.72 & 69.37$\pm$3.29 & 34.58$\pm$1.1 & 45.59$\pm$3.15 & 74.07$\pm$1.43 X \\
csgcl,enc:gcn bgrl,pred:mlp,sbm fast & 86.75$\pm$2.73 & 80.51$\pm$1.09 & 43.37$\pm$3.21 & 81.51$\pm$1.29 & 51.59$\pm$2.58 X & 35.14$\pm$1.83 & 27.74$\pm$1.49 & 75.1$\pm$0.82 X \\
csgcl,enc:gcn bgrl,pred:mlp,sbm fast2 & 88.89$\pm$2.39 & 80.2$\pm$1.22 & 44.97$\pm$2.46 & 79.95$\pm$1.41 & 54.03$\pm$1.83 & \color{red}{36.22$\pm$1.6 $\bigstar$} & 27.03$\pm$3.64 & 80.45$\pm$1.06 \\
\bottomrule
\end{tabular}

}

,70_first/_USAir.csv,70_first/_NS.csv,70_first/_PB.csv,70_first/_Yeast.csv,70_first/_Celegans.csv,70_first/_power.csv,70_first/_Router.csv,70_first/_Ecoli.csv
CN*,80.52$\pm$4.07,74$\pm$1.98,37.22$\pm$3.52,72.6$\pm$3.85,47.67$\pm$10.87,11.57$\pm$0.55,9.38$\pm$1.05,51.74$\pm$2.7
AA*,85.51$\pm$2.25,74$\pm$1.98,39.48$\pm$3.53,73.62$\pm$1.01,58.34$\pm$2.88,11.57$\pm$0.55,9.38$\pm$1.05,68.13$\pm$1.61
RA*,85.95$\pm$1.83,74$\pm$1.98,39.84$\pm$3.54,73.62$\pm$1.01,61.47$\pm$4.59,11.57$\pm$0.55,9.38$\pm$1.05,74.45$\pm$0.55
GCN*,73.29$\pm$4.70,78.32$\pm$2.57,37.32$\pm$4.69,73.15$\pm$2.41,40.68$\pm$5.45,15.40$\pm$2.90,24.42$\pm$4.59,61.02$\pm$11.91
SEAL*,90.47$\pm$3.00,86.59$\pm$3.03,44.47$\pm$2.86,83.92$\pm$1.17,64.80$\pm$4.23,31.46$\pm$3.25,\color{violet}{61.00$\pm$10.10},83.42$\pm$1.01
ELPH*,87.60$\pm$1.49,\color{violet}{88.49$\pm$2.14},46.91$\pm$2.21,82.74$\pm$1.19,64.45$\pm$3.91,26.61$\pm$1.73,\color{blue}{61.07$\pm$3.06},75.25$\pm$1.44
NCNC*,86.16$\pm$1.77,83.18$\pm$3.17,46.85$\pm$3.18,82.00$\pm$0.97,60.49$\pm$5.09,23.28$\pm$1.55,52.45$\pm$8.77,83.94$\pm$1.57
MPLP*,\color{blue}{92.12$\pm$2.21},\color{red}{90.02$\pm$2.04},\color{red}{52.55$\pm$2.90},\color{red}{85.36$\pm$0.72},\color{red}{74.28$\pm$2.09},32.66$\pm$3.58,\color{red}{64.68$\pm$3.14},\color{blue}{86.11$\pm$0.83}
MPLP+*,91.24$\pm$2.11,\color{blue}{88.91$\pm$2.04},\color{violet}{51.81$\pm$2.39},\color{blue}{84.95$\pm$0.66},72.73$\pm$2.99,31.86$\pm$2.59,60.94$\pm$2.51,\color{red}{87.07$\pm$0.89}
"baseline,enc:gcn bgrl,pred:mlp",89.74$\pm$2.29,80.91$\pm$1.18,50.94$\pm$3.3,84.19$\pm$0.94 $\bigstar$,63.61$\pm$3.65,30.37$\pm$0.86,26.36$\pm$1.52,81.91$\pm$1.1
"bgrl,enc:gcn bgrl,pred:mlp,random",87.11$\pm$1.9,80.49$\pm$1.29,47.24$\pm$3.24,82.72$\pm$1.01,67.41$\pm$3.44,25.67$\pm$0.74,30.95$\pm$1.16,81.63$\pm$0.72
"bgrl,enc:gcn bgrl,pred:mlp,deg",86.47$\pm$3.22,83.47$\pm$2.74,47.75$\pm$3.57,80.99$\pm$1.49,68.72$\pm$3.37,28.92$\pm$2.63,41.41$\pm$6.38,82.73$\pm$0.83
"bgrl,enc:gcn bgrl,pred:mlp,evc",88.82$\pm$1.47,80.42$\pm$0.81,49.0$\pm$3.9,84.25$\pm$0.57 $\bigstar$,60.47$\pm$4.94,21.4$\pm$1.2 X,47.79$\pm$6.0,82.79$\pm$1.45
"bgrl,enc:gcn bgrl,pred:mlp,pr",86.24$\pm$2.51,80.29$\pm$1.4,44.47$\pm$2.73,81.65$\pm$1.54,66.67$\pm$3.77,26.05$\pm$1.12,48.2$\pm$2.92,82.95$\pm$0.81
"bgrl,enc:gcn bgrl,pred:mlp,scom",89.74$\pm$2.13,81.3$\pm$0.8,44.67$\pm$2.61,84.08$\pm$0.74,70.51$\pm$3.43,25.86$\pm$1.07,54.25$\pm$3.26 $\bigstar$,82.36$\pm$1.04
"grace,enc:gcn bgrl,pred:mlp,random",\color{violet}{91.48$\pm$1.72},79.84$\pm$0.86,48.03$\pm$2.32,84.23$\pm$0.52 $\bigstar$,72.1$\pm$2.43,32.15$\pm$1.25,29.91$\pm$2.21,81.93$\pm$0.63
"grace,enc:gcn bgrl,pred:mlp,deg",87.39$\pm$10.03,80.86$\pm$2.18,46.12$\pm$3.78,83.14$\pm$1.26,69.23$\pm$2.68,27.02$\pm$9.75,17.79$\pm$10.89 X,71.05$\pm$24.03
"grace,enc:gcn bgrl,pred:mlp,evc",59.46$\pm$4.74 X,74.01$\pm$3.76,44.36$\pm$3.17,82.72$\pm$0.9,70.4$\pm$2.77,31.93$\pm$1.33,21.46$\pm$4.59 X,82.19$\pm$1.2
"grace,enc:gcn bgrl,pred:mlp,pr",90.33$\pm$1.95,82.24$\pm$1.95,49.56$\pm$3.68,82.48$\pm$0.72,\color{violet}{72.75$\pm$1.57 $\bigstar$},33.45$\pm$1.24,53.76$\pm$2.91 $\bigstar$,\color{violet}{84.32$\pm$0.85 $\bigstar$}
"grace,enc:gcn bgrl,pred:mlp,scom",88.4$\pm$2.93,80.31$\pm$1.34,46.01$\pm$3.11,81.88$\pm$1.23,67.32$\pm$2.46,\color{blue}{36.15$\pm$1.51 $\bigstar$},42.33$\pm$1.6,82.88$\pm$1.39
"lbgrl,enc:gcn bgrl,pred:mlp,random",79.81$\pm$3.92,80.02$\pm$1.24,47.72$\pm$2.3,81.52$\pm$1.16,65.52$\pm$2.25,23.66$\pm$0.95,39.72$\pm$8.46,81.75$\pm$1.01
"lbgrl,enc:gcn bgrl,pred:mlp,deg",83.6$\pm$3.96,81.51$\pm$1.81,46.8$\pm$3.25,81.92$\pm$1.04,71.03$\pm$4.36,27.76$\pm$2.46,49.9$\pm$3.3,73.27$\pm$1.14 X
"lbgrl,enc:gcn bgrl,pred:mlp,evc",89.39$\pm$2.4,67.96$\pm$4.61 X,34.51$\pm$3.75 X,84.22$\pm$0.73 $\bigstar$,67.3$\pm$2.55,27.54$\pm$0.92,34.83$\pm$4.65,82.07$\pm$0.93
"lbgrl,enc:gcn bgrl,pred:mlp,pr",90.66$\pm$1.93,85.0$\pm$1.88 $\bigstar$,47.59$\pm$2.18,83.52$\pm$1.12,70.05$\pm$2.87,19.58$\pm$1.23 X,45.02$\pm$6.75,83.34$\pm$1.08
"lbgrl,enc:gcn bgrl,pred:mlp,scom",89.22$\pm$2.76,76.86$\pm$1.38,47.68$\pm$3.35,83.14$\pm$0.55,69.04$\pm$2.79,20.4$\pm$0.92 X,33.96$\pm$1.24,83.22$\pm$0.71
"lgrace,enc:gcn bgrl,pred:mlp,random",\color{red}{92.47$\pm$0.8 $\bigstar$},80.8$\pm$1.45,\color{blue}{51.98$\pm$3.28 $\bigstar$},84.33$\pm$1.09,70.56$\pm$3.27,30.58$\pm$1.81,34.67$\pm$10.92,81.67$\pm$1.22
"lgrace,enc:gcn bgrl,pred:mlp,deg",90.71$\pm$1.88,80.27$\pm$1.44,48.52$\pm$2.79,82.03$\pm$1.59,65.9$\pm$3.9,33.7$\pm$2.51,29.34$\pm$6.84,84.27$\pm$0.78 $\bigstar$
"lgrace,enc:gcn bgrl,pred:mlp,evc",90.61$\pm$2.57,83.16$\pm$1.43,50.51$\pm$3.81,83.75$\pm$1.05,72.54$\pm$4.24 $\bigstar$,28.83$\pm$0.89,26.09$\pm$5.79,79.19$\pm$0.93
"lgrace,enc:gcn bgrl,pred:mlp,pr",90.0$\pm$2.02,83.34$\pm$1.49,48.7$\pm$2.61,\color{violet}{84.38$\pm$0.68 $\bigstar$},\color{blue}{72.89$\pm$2.3 $\bigstar$},29.5$\pm$1.19,33.12$\pm$1.88,83.08$\pm$0.45
"lgrace,enc:gcn bgrl,pred:mlp,scom",90.8$\pm$1.84,81.13$\pm$1.21,49.92$\pm$2.82,79.85$\pm$7.51,65.31$\pm$4.03,27.67$\pm$1.68,31.41$\pm$1.33,82.45$\pm$0.88
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast",88.82$\pm$2.35,79.18$\pm$1.49,43.95$\pm$2.45,81.01$\pm$1.37,58.72$\pm$3.18,\color{violet}{35.34$\pm$1.33},49.48$\pm$3.53,79.21$\pm$1.4
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast2",80.59$\pm$3.58,80.46$\pm$1.36,42.7$\pm$2.91,79.58$\pm$1.59 X,57.2$\pm$3.6,31.18$\pm$1.64,43.33$\pm$3.33,79.77$\pm$1.02
"grace,enc:gcn bgrl,pred:mlp,sbm fast",87.01$\pm$2.03,73.72$\pm$4.33,45.65$\pm$2.74,79.84$\pm$1.61 X,64.71$\pm$3.17,32.61$\pm$1.17,33.83$\pm$1.93,79.54$\pm$1.14
"grace,enc:gcn bgrl,pred:mlp,sbm fast2",86.21$\pm$3.63,80.89$\pm$1.41,45.54$\pm$2.5,79.46$\pm$1.49 X,61.98$\pm$3.55,33.87$\pm$1.68,26.43$\pm$2.69,82.36$\pm$0.64
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fast",79.06$\pm$2.75,84.31$\pm$1.97 $\bigstar$,44.46$\pm$2.91,80.77$\pm$1.18,65.22$\pm$2.76,34.94$\pm$1.37,42.29$\pm$3.98,77.81$\pm$0.98
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fast2",87.95$\pm$2.58,82.97$\pm$1.67,44.23$\pm$2.29,81.19$\pm$0.91,42.73$\pm$2.57 X,33.11$\pm$1.47,35.94$\pm$2.44,79.21$\pm$1.47
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast",90.38$\pm$2.54,53.41$\pm$17.6 X,48.54$\pm$2.99,83.22$\pm$0.96,67.02$\pm$2.6,33.45$\pm$1.08,29.76$\pm$3.38,82.9$\pm$0.59
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast2",88.33$\pm$2.57,80.58$\pm$1.14,44.43$\pm$4.54,79.77$\pm$1.78,60.44$\pm$3.16,35.08$\pm$1.91,27.6$\pm$1.06,81.28$\pm$1.0
"csgcl,enc:gcn bgrl,pred:mlp,random",86.26$\pm$3.28,81.73$\pm$0.87,47.92$\pm$2.02,81.68$\pm$1.07,70.09$\pm$2.1,35.08$\pm$1.32,40.11$\pm$2.23,81.5$\pm$1.11
"csgcl,enc:gcn bgrl,pred:mlp,deg",88.94$\pm$2.81,80.33$\pm$3.89,48.95$\pm$2.73,82.06$\pm$1.56,71.7$\pm$2.12,33.47$\pm$2.17,21.19$\pm$8.68,82.06$\pm$0.61
"csgcl,enc:gcn bgrl,pred:mlp,pr",85.25$\pm$2.51,79.07$\pm$2.65,41.48$\pm$2.74,80.76$\pm$0.88,71.4$\pm$2.43,34.41$\pm$1.0,33.57$\pm$5.53,82.09$\pm$1.32
"csgcl,enc:gcn bgrl,pred:mlp,evc",81.53$\pm$2.98,71.33$\pm$2.75,49.42$\pm$2.8,83.53$\pm$0.8,70.96$\pm$3.13,35.12$\pm$1.39,27.19$\pm$1.47,84.16$\pm$1.38
"csgcl,enc:gcn bgrl,pred:mlp,scom",90.16$\pm$1.61,82.45$\pm$1.69,47.75$\pm$3.5,83.32$\pm$0.72,69.37$\pm$3.29,34.58$\pm$1.1,45.59$\pm$3.15,74.07$\pm$1.43 X
"csgcl,enc:gcn bgrl,pred:mlp,sbm fast",86.75$\pm$2.73,80.51$\pm$1.09,43.37$\pm$3.21,81.51$\pm$1.29,51.59$\pm$2.58 X,35.14$\pm$1.83,27.74$\pm$1.49,75.1$\pm$0.82 X
"csgcl,enc:gcn bgrl,pred:mlp,sbm fast2",88.89$\pm$2.39,80.2$\pm$1.22,44.97$\pm$2.46,79.95$\pm$1.41,54.03$\pm$1.83,\color{red}{36.22$\pm$1.6 $\bigstar$},27.03$\pm$3.64,80.45$\pm$1.06

In [43]:
# tab 1 non -attr
names1  = [
    '70_first/_USAir.csv',
    '70_first/_NS.csv',
    '70_first/_PB.csv',
    '70_first/_Yeast.csv',
    '70_first/_Celegans.csv',
    '70_first/_power.csv',
    '70_first/_Router.csv',
    '70_first/_Ecoli.csv',
]
names2 = [
    '70_first/a_USAir.csv',
    '70_first/a_NS.csv',
    '70_first/a_PB.csv',
    '70_first/a_Yeast.csv',
    '70_first/a_Celegans.csv',
    '70_first/a_power.csv',
    '70_first/a_Router.csv',
    '70_first/a_Ecoli.csv',
]
names3 = [
    '70_first/b_USAir.csv',
    '70_first/b_NS.csv',
    '70_first/b_PB.csv',
    '70_first/b_Yeast.csv',
    '70_first/b_Celegans.csv',
    '70_first/b_power.csv',
    '70_first/b_Router.csv',
    '70_first/b_Ecoli.csv',
]
names4 = [
    '70_first/c_USAir.csv',
    '70_first/c_NS.csv',
    '70_first/c_PB.csv',
    '70_first/c_Yeast.csv',
    '70_first/c_Celegans.csv',
    '70_first/c_power.csv',
    '70_first/c_Router.csv',
    '70_first/c_Ecoli.csv',
]
data1, res1 = ut.mix_dataset(names1, 'Hits@50', filtre=['sbm'], filtre2=['\+', 'prob'])
data2, res2 = ut.mix_dataset(names2, 'Hits@50', filtre=['sbm'], filtre2=['\+', 'prob'])
data3, res3 = ut.mix_dataset(names3, 'Hits@50', filtre=['sbm'], filtre2=['prob'])
data4, res4 = ut.mix_dataset(names4, 'Hits@50', filtre=['sbm'], filtre2=['prob'])

power_data, power_res = ut.mix_dataset(['70_first/d_power.csv'], 'Hits@50', filtre=['sbm'], filtre2=['\+', 'prob'])
power_data.index =  ['70_first/_power.csv']

mplp_score.index = data1.index
data2.index = data1.index
data3.index = data1.index
data4.index = data1.index

res2.index = res1.index
res3.index = res1.index
res4.index = res1.index

combined_data = pd.concat([mplp_score, data1, data2, data3, data4], axis=1)
power_data = pd.concat([mplp_score.loc['70_first/_power.csv'].to_frame().T, power_data], axis=1)
combined_data.loc['70_first/_power.csv'] = power_data.loc['70_first/_power.csv']
combined_res = pd.concat([res1, res2, res3, res4], axis=1)
combined_res.loc['70_first/_power.csv'] = power_res.loc['70_first/d_power.csv']
combined_data = ut.tex_table(combined_data, combined_res)
combined_data.T

<>:42: SyntaxWarning: invalid escape sequence '\+'
<>:43: SyntaxWarning: invalid escape sequence '\+'
<>:47: SyntaxWarning: invalid escape sequence '\+'
<>:42: SyntaxWarning: invalid escape sequence '\+'
<>:43: SyntaxWarning: invalid escape sequence '\+'
<>:47: SyntaxWarning: invalid escape sequence '\+'
/tmp/ipykernel_263/3779004615.py:42: SyntaxWarning: invalid escape sequence '\+'
  data1, res1 = ut.mix_dataset(names1, 'Hits@50', filtre=['sbm'], filtre2=['\+', 'prob'])
/tmp/ipykernel_263/3779004615.py:43: SyntaxWarning: invalid escape sequence '\+'
  data2, res2 = ut.mix_dataset(names2, 'Hits@50', filtre=['sbm'], filtre2=['\+', 'prob'])
/tmp/ipykernel_263/3779004615.py:47: SyntaxWarning: invalid escape sequence '\+'
  power_data, power_res = ut.mix_dataset(['70_first/d_power.csv'], 'Hits@50', filtre=['sbm'], filtre2=['\+', 'prob'])

\resizebox{\textwidth}{!}{
\begin{tabular}{lllllllll}
\toprule
 & 70_first/_USAir.csv & 70_first/_NS.csv & 70_first/_PB.csv & 70_first/_Yeast.csv & 70_first/_Celegans.csv & 70_first/_power.csv & 70_first/_Router.csv & 70_first/_Ecoli.csv \\
\midrule
CN* & 80.52$\pm$4.07 & 74$\pm$1.98 & 37.22$\pm$3.52 & 72.6$\pm$3.85 & 47.67$\pm$10.87 & 11.57$\pm$0.55 & 9.38$\pm$1.05 & 51.74$\pm$2.7 \\
AA* & 85.51$\pm$2.25 & 74$\pm$1.98 & 39.48$\pm$3.53 & 73.62$\pm$1.01 & 58.34$\pm$2.88 & 11.57$\pm$0.55 & 9.38$\pm$1.05 & 68.13$\pm$1.61 \\
RA* & 85.95$\pm$1.83 & 74$\pm$1.98 & 39.84$\pm$3.54 & 73.62$\pm$1.01 & 61.47$\pm$4.59 & 11.57$\pm$0.55 & 9.38$\pm$1.05 & 74.45$\pm$0.55 \\
GCN* & 73.29$\pm$4.70 & 78.32$\pm$2.57 & 37.32$\pm$4.69 & 73.15$\pm$2.41 & 40.68$\pm$5.45 & 15.40$\pm$2.90 & 24.42$\pm$4.59 & 61.02$\pm$11.91 \\
SEAL* & \color{violet}{90.47$\pm$3.00} & 86.59$\pm$3.03 & 44.47$\pm$2.86 & 83.92$\pm$1.17 & 64.80$\pm$4.23 & 31.46$\pm$3.25 & 61.00$\pm$10.10 & 83.42$\pm$1.01 \\
ELPH* & 87.60$\pm$1.49 & 88.49$\pm$2.14 & 46.91$\pm$2.21 & 82.74$\pm$1.19 & 64.45$\pm$3.91 & 26.61$\pm$1.73 & 61.07$\pm$3.06 & 75.25$\pm$1.44 \\
NCNC* & 86.16$\pm$1.77 & 83.18$\pm$3.17 & 46.85$\pm$3.18 & 82.00$\pm$0.97 & 60.49$\pm$5.09 & 23.28$\pm$1.55 & 52.45$\pm$8.77 & \color{violet}{83.94$\pm$1.57} \\
MPLP* & \color{red}{92.12$\pm$2.21} & 90.02$\pm$2.04 & \color{red}{52.55$\pm$2.90} & 85.36$\pm$0.72 & \color{red}{74.28$\pm$2.09} & 32.66$\pm$3.58 & 64.68$\pm$3.14 & \color{blue}{86.11$\pm$0.83} \\
MPLP+* & \color{blue}{91.24$\pm$2.11} & 88.91$\pm$2.04 & \color{blue}{51.81$\pm$2.39} & 84.95$\pm$0.66 & \color{blue}{72.73$\pm$2.99} & 31.86$\pm$2.59 & 60.94$\pm$2.51 & \color{red}{87.07$\pm$0.89} \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast & 88.82$\pm$2.35 & 79.18$\pm$1.49 & 43.95$\pm$2.45 & 81.01$\pm$1.37 & 58.72$\pm$3.18 & 35.34$\pm$1.33 & 49.48$\pm$3.53 & 79.21$\pm$1.4 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast2 & 80.59$\pm$3.58 & 80.46$\pm$1.36 & 42.7$\pm$2.91 & 79.58$\pm$1.59 X & 57.2$\pm$3.6 & 31.18$\pm$1.64 X & 43.33$\pm$3.33 & 79.77$\pm$1.02 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast & 87.01$\pm$2.03 & 73.72$\pm$4.33 X & 45.65$\pm$2.74 & 79.84$\pm$1.61 & 64.71$\pm$3.17 & 32.61$\pm$1.17 X & 33.83$\pm$1.93 & 79.54$\pm$1.14 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast2 & 86.21$\pm$3.63 & 80.89$\pm$1.41 & 45.54$\pm$2.5 & 79.46$\pm$1.49 X & 61.98$\pm$3.55 & 33.87$\pm$1.68 & 26.43$\pm$2.69 X & 82.36$\pm$0.64 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fast & 79.06$\pm$2.75 X & 84.31$\pm$1.97 & 44.46$\pm$2.91 & 80.77$\pm$1.18 & 65.22$\pm$2.76 & 34.94$\pm$1.37 & 42.29$\pm$3.98 & 77.81$\pm$0.98 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fast2 & 87.95$\pm$2.58 & 82.97$\pm$1.67 & 44.23$\pm$2.29 & 81.19$\pm$0.91 & 42.73$\pm$2.57 X & 33.11$\pm$1.47 & 35.94$\pm$2.44 & 79.21$\pm$1.47 \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast & 90.38$\pm$2.54 $\bigstar$ & 53.41$\pm$17.6 X & 48.54$\pm$2.99 $\bigstar$ & 83.22$\pm$0.96 & 67.02$\pm$2.6 & 33.45$\pm$1.08 & 29.76$\pm$3.38 X & 82.9$\pm$0.59 $\bigstar$ \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast2 & 88.33$\pm$2.57 & 80.58$\pm$1.14 & 44.43$\pm$4.54 & 79.77$\pm$1.78 & 60.44$\pm$3.16 & 35.08$\pm$1.91 & 27.6$\pm$1.06 X & 81.28$\pm$1.0 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast cheat & 87.76$\pm$2.86 & 94.65$\pm$1.1 & 43.83$\pm$3.02 & 86.74$\pm$1.48 & 55.8$\pm$3.38 & 94.77$\pm$2.28 & 87.87$\pm$1.94 & 81.65$\pm$0.69 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast2 cheat & 87.46$\pm$2.54 & \color{violet}{95.09$\pm$0.9} & 45.0$\pm$2.84 & 86.94$\pm$1.4 & 59.09$\pm$3.19 & \color{blue}{96.52$\pm$0.81 $\bigstar$} & 75.97$\pm$2.35 & 82.25$\pm$0.75 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast cheat & 83.01$\pm$3.3 & 80.44$\pm$5.17 & 43.99$\pm$2.84 & 85.52$\pm$2.08 & 65.97$\pm$3.24 & 95.49$\pm$1.25 & \color{violet}{96.63$\pm$0.94 $\bigstar$} & 81.86$\pm$1.51 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast2 cheat & 83.53$\pm$4.55 & \color{red}{95.69$\pm$0.89 $\bigstar$} & 37.12$\pm$2.94 X & 85.28$\pm$0.9 & 62.17$\pm$5.04 & \color{violet}{96.46$\pm$1.87 $\bigstar$} & 94.7$\pm$2.67 & 81.25$\pm$1.35 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fast cheat & 86.61$\pm$3.36 & 88.41$\pm$2.65 & 42.16$\pm$3.4 & 84.24$\pm$0.49 & 65.71$\pm$4.32 & 90.04$\pm$2.32 & 89.31$\pm$2.11 & 78.15$\pm$1.03 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fast2 cheat & 86.02$\pm$2.73 & 90.42$\pm$0.95 & 42.36$\pm$3.63 & 78.66$\pm$1.52 X & 62.07$\pm$4.52 & 93.47$\pm$1.71 & 90.27$\pm$1.56 & 81.71$\pm$1.3 \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast cheat & 72.0$\pm$4.93 X & 88.01$\pm$1.43 & \color{violet}{49.71$\pm$3.73 $\bigstar$} & \color{blue}{87.17$\pm$1.42} & \color{violet}{69.49$\pm$2.78 $\bigstar$} & 84.39$\pm$1.4 & 84.63$\pm$1.0 & 81.57$\pm$0.54 \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast2 cheat & 88.85$\pm$2.66 & 90.51$\pm$1.14 & 40.25$\pm$1.86 X & \color{violet}{87.09$\pm$0.91} & 55.5$\pm$3.49 & 80.4$\pm$1.88 & 87.27$\pm$1.31 & 83.36$\pm$0.93 $\bigstar$ \\
csgcl,enc:gcn bgrl,pred:mlp,sbm fast & 86.75$\pm$2.73 & 80.51$\pm$1.09 & 43.37$\pm$3.21 & 81.51$\pm$1.29 & 51.59$\pm$2.58 & 35.14$\pm$1.83 & 27.74$\pm$1.49 X & 75.1$\pm$0.82 X \\
csgcl,enc:gcn bgrl,pred:mlp,sbm fast2 & 88.89$\pm$2.39 & 80.2$\pm$1.22 & 44.97$\pm$2.46 & 79.95$\pm$1.41 & 54.03$\pm$1.83 & 36.22$\pm$1.6 & 27.03$\pm$3.64 X & 80.45$\pm$1.06 \\
csgcl,enc:gcn bgrl,pred:mlp,sbm fast cheat & 85.6$\pm$3.44 & \color{blue}{95.27$\pm$0.62 $\bigstar$} & 45.72$\pm$3.05 & \color{red}{89.69$\pm$1.12 $\bigstar$} & 64.41$\pm$2.79 & 96.35$\pm$0.88 $\bigstar$ & \color{blue}{97.42$\pm$0.7 $\bigstar$} & 78.67$\pm$1.49 \\
csgcl,enc:gcn bgrl,pred:mlp,sbm fast2 cheat & 87.91$\pm$3.02 & 94.78$\pm$0.75 & 44.63$\pm$3.25 & 82.66$\pm$2.02 & 58.28$\pm$5.7 & \color{red}{96.63$\pm$0.96 $\bigstar$} & \color{red}{97.55$\pm$0.97 $\bigstar$} & 80.91$\pm$1.17 \\
\bottomrule
\end{tabular}

}

,70_first/_USAir.csv,70_first/_NS.csv,70_first/_PB.csv,70_first/_Yeast.csv,70_first/_Celegans.csv,70_first/_power.csv,70_first/_Router.csv,70_first/_Ecoli.csv
CN*,80.52$\pm$4.07,74$\pm$1.98,37.22$\pm$3.52,72.6$\pm$3.85,47.67$\pm$10.87,11.57$\pm$0.55,9.38$\pm$1.05,51.74$\pm$2.7
AA*,85.51$\pm$2.25,74$\pm$1.98,39.48$\pm$3.53,73.62$\pm$1.01,58.34$\pm$2.88,11.57$\pm$0.55,9.38$\pm$1.05,68.13$\pm$1.61
RA*,85.95$\pm$1.83,74$\pm$1.98,39.84$\pm$3.54,73.62$\pm$1.01,61.47$\pm$4.59,11.57$\pm$0.55,9.38$\pm$1.05,74.45$\pm$0.55
GCN*,73.29$\pm$4.70,78.32$\pm$2.57,37.32$\pm$4.69,73.15$\pm$2.41,40.68$\pm$5.45,15.40$\pm$2.90,24.42$\pm$4.59,61.02$\pm$11.91
SEAL*,\color{violet}{90.47$\pm$3.00},86.59$\pm$3.03,44.47$\pm$2.86,83.92$\pm$1.17,64.80$\pm$4.23,31.46$\pm$3.25,61.00$\pm$10.10,83.42$\pm$1.01
ELPH*,87.60$\pm$1.49,88.49$\pm$2.14,46.91$\pm$2.21,82.74$\pm$1.19,64.45$\pm$3.91,26.61$\pm$1.73,61.07$\pm$3.06,75.25$\pm$1.44
NCNC*,86.16$\pm$1.77,83.18$\pm$3.17,46.85$\pm$3.18,82.00$\pm$0.97,60.49$\pm$5.09,23.28$\pm$1.55,52.45$\pm$8.77,\color{violet}{83.94$\pm$1.57}
MPLP*,\color{red}{92.12$\pm$2.21},90.02$\pm$2.04,\color{red}{52.55$\pm$2.90},85.36$\pm$0.72,\color{red}{74.28$\pm$2.09},32.66$\pm$3.58,64.68$\pm$3.14,\color{blue}{86.11$\pm$0.83}
MPLP+*,\color{blue}{91.24$\pm$2.11},88.91$\pm$2.04,\color{blue}{51.81$\pm$2.39},84.95$\pm$0.66,\color{blue}{72.73$\pm$2.99},31.86$\pm$2.59,60.94$\pm$2.51,\color{red}{87.07$\pm$0.89}
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast",88.82$\pm$2.35,79.18$\pm$1.49,43.95$\pm$2.45,81.01$\pm$1.37,58.72$\pm$3.18,35.34$\pm$1.33,49.48$\pm$3.53,79.21$\pm$1.4
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast2",80.59$\pm$3.58,80.46$\pm$1.36,42.7$\pm$2.91,79.58$\pm$1.59 X,57.2$\pm$3.6,31.18$\pm$1.64 X,43.33$\pm$3.33,79.77$\pm$1.02
"grace,enc:gcn bgrl,pred:mlp,sbm fast",87.01$\pm$2.03,73.72$\pm$4.33 X,45.65$\pm$2.74,79.84$\pm$1.61,64.71$\pm$3.17,32.61$\pm$1.17 X,33.83$\pm$1.93,79.54$\pm$1.14
"grace,enc:gcn bgrl,pred:mlp,sbm fast2",86.21$\pm$3.63,80.89$\pm$1.41,45.54$\pm$2.5,79.46$\pm$1.49 X,61.98$\pm$3.55,33.87$\pm$1.68,26.43$\pm$2.69 X,82.36$\pm$0.64
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fast",79.06$\pm$2.75 X,84.31$\pm$1.97,44.46$\pm$2.91,80.77$\pm$1.18,65.22$\pm$2.76,34.94$\pm$1.37,42.29$\pm$3.98,77.81$\pm$0.98
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fast2",87.95$\pm$2.58,82.97$\pm$1.67,44.23$\pm$2.29,81.19$\pm$0.91,42.73$\pm$2.57 X,33.11$\pm$1.47,35.94$\pm$2.44,79.21$\pm$1.47
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast",90.38$\pm$2.54 $\bigstar$,53.41$\pm$17.6 X,48.54$\pm$2.99 $\bigstar$,83.22$\pm$0.96,67.02$\pm$2.6,33.45$\pm$1.08,29.76$\pm$3.38 X,82.9$\pm$0.59 $\bigstar$
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast2",88.33$\pm$2.57,80.58$\pm$1.14,44.43$\pm$4.54,79.77$\pm$1.78,60.44$\pm$3.16,35.08$\pm$1.91,27.6$\pm$1.06 X,81.28$\pm$1.0
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast cheat",87.76$\pm$2.86,94.65$\pm$1.1,43.83$\pm$3.02,86.74$\pm$1.48,55.8$\pm$3.38,94.77$\pm$2.28,87.87$\pm$1.94,81.65$\pm$0.69
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast2 cheat",87.46$\pm$2.54,\color{violet}{95.09$\pm$0.9},45.0$\pm$2.84,86.94$\pm$1.4,59.09$\pm$3.19,\color{blue}{96.52$\pm$0.81 $\bigstar$},75.97$\pm$2.35,82.25$\pm$0.75
"grace,enc:gcn bgrl,pred:mlp,sbm fast cheat",83.01$\pm$3.3,80.44$\pm$5.17,43.99$\pm$2.84,85.52$\pm$2.08,65.97$\pm$3.24,95.49$\pm$1.25,\color{violet}{96.63$\pm$0.94 $\bigstar$},81.86$\pm$1.51
"grace,enc:gcn bgrl,pred:mlp,sbm fast2 cheat",83.53$\pm$4.55,\color{red}{95.69$\pm$0.89 $\bigstar$},37.12$\pm$2.94 X,85.28$\pm$0.9,62.17$\pm$5.04,\color{violet}{96.46$\pm$1.87 $\bigstar$},94.7$\pm$2.67,81.25$\pm$1.35
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fast cheat",86.61$\pm$3.36,88.41$\pm$2.65,42.16$\pm$3.4,84.24$\pm$0.49,65.71$\pm$4.32,90.04$\pm$2.32,89.31$\pm$2.11,78.15$\pm$1.03
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fast2 cheat",86.02$\pm$2.73,90.42$\pm$0.95,42.36$\pm$3.63,78.66$\pm$1.52 X,62.07$\pm$4.52,93.47$\pm$1.71,90.27$\pm$1.56,81.71$\pm$1.3
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast cheat",72.0$\pm$4.93 X,88.01$\pm$1.43,\color{violet}{49.71$\pm$3.73 $\bigstar$},\color{blue}{87.17$\pm$1.42},\color{violet}{69.49$\pm$2.78 $\bigstar$},84.39$\pm$1.4,84.63$\pm$1.0,81.57$\pm$0.54
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast2 cheat",88.85$\pm$2.66,90.51$\pm$1.14,40.25$\pm$1.86 X,\color{violet}{87.09$\pm$0.91},55.5$\pm$3.49,80.4$\pm$1.88,87.27$\pm$1.31,83.36$\pm$0.93 $\bigstar$
"csgcl,enc:gcn bgrl,pred:mlp,sbm fast",86.75$\pm$2.73,80.51$\pm$1.09,43.37$\pm$3.21,81.51$\pm$1.29,51.59$\pm$2.58,35.14$\pm$1.83,27.74$\pm$1.49 X,75.1$\pm$0.82 X
"csgcl,enc:gcn bgrl,pred:mlp,sbm fast2",88.89$\pm$2.39,80.2$\pm$1.22,44.97$\pm$2.46,79.95$\pm$1.41,54.03$\pm$1.83,36.22$\pm$1.6,27.03$\pm$3.64 X,80.45$\pm$1.06
"csgcl,enc:gcn bgrl,pred:mlp,sbm fast cheat",85.6$\pm$3.44,\color{blue}{95.27$\pm$0.62 $\bigstar$},45.72$\pm$3.05,\color{red}{89.69$\pm$1.12 $\bigstar$},64.41$\pm$2.79,96.35$\pm$0.88 $\bigstar$,\color{blue}{97.42$\pm$0.7 $\bigstar$},78.67$\pm$1.49
"csgcl,enc:gcn bgrl,pred:mlp,sbm fast2 cheat",87.91$\pm$3.02,94.78$\pm$0.75,44.63$\pm$3.25,82.66$\pm$2.02,58.28$\pm$5.7,\color{red}{96.63$\pm$0.96 $\bigstar$},\color{red}{97.55$\pm$0.97 $\bigstar$},80.91$\pm$1.17

In [64]:
data2.loc["85_second/_photo.csv"].fillna(photo_end_data.loc["85_second/_photo.csv"])

csgcl,enc:gcn_bgrl,pred:mlp,random_mean        55.82$\pm$4.02
csgcl,enc:gcn_bgrl,pred:mlp,deg_mean           60.37$\pm$2.47
csgcl,enc:gcn_bgrl,pred:mlp,evc_mean           55.07$\pm$2.19
csgcl,enc:gcn_bgrl,pred:mlp,pr_mean            62.72$\pm$3.16
csgcl,enc:gcn_bgrl,pred:mlp,scom_mean           65.4$\pm$2.95
csgcl,enc:gcn_bgrl,pred:mlp,sbm_fast_mean                 NaN
csgcl,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean                NaN
lbgrl,enc:gcn_bgrl,pred:mlp,random_mean         56.5$\pm$3.14
lbgrl,enc:gcn_bgrl,pred:mlp,deg_mean           52.99$\pm$3.19
lbgrl,enc:gcn_bgrl,pred:mlp,evc_mean           61.86$\pm$3.57
lbgrl,enc:gcn_bgrl,pred:mlp,pr_mean            61.98$\pm$3.47
lbgrl,enc:gcn_bgrl,pred:mlp,scom_mean          51.26$\pm$2.92
lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_mean      47.69$\pm$4.21
lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean     36.29$\pm$4.56
lgrace,enc:gcn_bgrl,pred:mlp,random_mean                  NaN
lgrace,enc:gcn_bgrl,pred:mlp,deg_mean                     NaN
lgrace,enc:gcn_bgrl,pred:mlp,evc_mean                     NaN
lgrace,enc:gcn_bgrl,pred:mlp,pr_mean                      NaN
lgrace,enc:gcn_bgrl,pred:mlp,scom_mean                    NaN
lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast_mean                NaN
lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean               NaN
Name: 85_second/_photo.csv, dtype: object

In [5]:
names1 = [
    "85_second/_cora.csv",
    '85_second/_citeseer.csv',
    "85_second/_cs.csv",
    "85_second/_physics.csv",
    "85_second/_computers.csv",
    "85_second/_photo.csv"
]

names2 = [
    "85_second/2_cora.csv",
    '85_second/2_citeseer.csv',
    "85_second/2_cs.csv",
    "85_second/2_physics.csv",
    "85_second/2_computers.csv",
    "85_second/2_photo.csv"
]
data1, res1 = ut.mix_dataset(names1, 'Hits@50', filtre2=['prob', 'cheat'])
data2, res2 = ut.mix_dataset(names2, 'Hits@50', filtre2=['prob', 'cheat'])
physics_end_data, physics_end_res = ut.mix_dataset(['85_second/3_physics.csv'], 'Hits@50', filtre2=['prob', 'cheat'])
photo_end_data, photo_end_res = ut.mix_dataset(['85_second/3_photo.csv'], 'Hits@50', filtre2=['prob', 'cheat'])
photo2_end_data, photo2_end_res = ut.mix_dataset(['85_second/4_photo.csv'], 'Hits@50', filtre2=['prob', 'cheat'])

tbgrl_score.index = data1.index
physics_end_data.index = ["85_second/_physics.csv"]
physics_end_res.index = ["85_second/_physics.csv"]
photo_end_data.index = ["85_second/_photo.csv"]
photo_end_res.index = ["85_second/_photo.csv"]
photo2_end_data.index = ["85_second/_photo.csv"]
photo2_end_res.index = ["85_second/_photo.csv"]
data2.index = data1.index
res2.index = res1.index

data1.loc["85_second/_physics.csv"].fillna(physics_end_data.loc["85_second/_physics.csv"], inplace=True)
data2.loc["85_second/_photo.csv"].fillna(photo_end_data.loc["85_second/_photo.csv"], inplace=True)
data2.loc["85_second/_photo.csv"].fillna(photo2_end_data.loc["85_second/_photo.csv"], inplace=True)

res1.loc["85_second/_physics.csv"].fillna(physics_end_res.loc["85_second/_physics.csv"], inplace=True)
res2.loc["85_second/_photo.csv"].fillna(photo_end_res.loc["85_second/_photo.csv"], inplace=True)
res2.loc["85_second/_photo.csv"].fillna(photo2_end_res.loc["85_second/_photo.csv"], inplace=True)

combined_data = pd.concat([tbgrl_score, data1, data2,], axis=1)
combined_res = pd.concat([res1, res2], axis=1)

data = ut.tex_table(combined_data, combined_res)
data.T

\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & 85_second/_cora.csv & 85_second/_citeseer.csv & 85_second/_cs.csv & 85_second/_physics.csv & 85_second/_computers.csv & 85_second/_photo.csv \\
\midrule
GCN* & 81.6$\pm$1.3 & 82.2$\pm$1.17 & 64.2$\pm$2.9 & 42.6$\pm$3.6 & \color{red}{76.2$\pm$1} & \color{red}{79.8$\pm$1.8} \\
GRACE* & 68.6$\pm$5.6 & 70.7$\pm$6.8 & 48.6$\pm$2.5 & 24$\pm$2.7 & 45.6$\pm$6.6 & NaN \\
BGRL* & 79.2$\pm$1.5 & 85.8$\pm$2 & 56.2$\pm$1.3 & 34.6$\pm$1.8 & 51.5$\pm$1.6 & 47.6$\pm$1.5 \\
T-BGRL* & 77.3$\pm$2 & 86.8$\pm$2.3 & 51.7$\pm$1.6 & 31.5$\pm$1.5 & \color{blue}{55.5$\pm$0.9} & 47.1$\pm$2.1 \\
baseline,enc:gcn bgrl,pred:mlp & 81.97$\pm$2.31 & 75.01$\pm$3.03 X & \color{red}{83.89$\pm$1.28 $\bigstar$} & \color{red}{83.9$\pm$1.31 $\bigstar$} & \color{violet}{51.81$\pm$3.74 $\bigstar$} & \color{blue}{67.23$\pm$4.1 $\bigstar$} \\
bgrl,enc:gcn bgrl,pred:mlp,random & \color{blue}{86.81$\pm$1.54 $\bigstar$} & 89.27$\pm$1.0 & 60.46$\pm$3.09 & 52.03$\pm$2.92 & 40.24$\pm$2.77 & 48.83$\pm$2.55 \\
bgrl,enc:gcn bgrl,pred:mlp,deg & 85.67$\pm$2.09 & 82.48$\pm$2.12 & 69.55$\pm$2.59 & 38.94$\pm$2.06 & 41.8$\pm$2.55 & 59.18$\pm$2.81 \\
bgrl,enc:gcn bgrl,pred:mlp,evc & \color{red}{87.55$\pm$1.19 $\bigstar$} & 83.23$\pm$3.03 & 69.17$\pm$2.77 & 47.39$\pm$2.43 & 40.48$\pm$2.34 & 59.57$\pm$3.42 \\
bgrl,enc:gcn bgrl,pred:mlp,pr & 76.87$\pm$3.55 X & 85.78$\pm$2.65 & 67.8$\pm$2.4 & 38.59$\pm$3.02 & 43.6$\pm$2.4 & 57.43$\pm$3.14 \\
bgrl,enc:gcn bgrl,pred:mlp,scom & 83.11$\pm$1.49 & 82.99$\pm$1.94 & 66.69$\pm$3.06 & 54.85$\pm$2.12 & 41.51$\pm$2.03 & 52.05$\pm$4.06 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast & 83.83$\pm$1.77 & 88.64$\pm$1.6 & 60.18$\pm$2.4 & 41.91$\pm$3.11 & 36.44$\pm$2.2 & 54.34$\pm$4.41 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast2 & 81.35$\pm$2.35 & 81.67$\pm$2.64 & 55.05$\pm$2.61 & 46.64$\pm$4.49 & 38.33$\pm$2.71 & 48.25$\pm$3.79 \\
grace,enc:gcn bgrl,pred:mlp,random & 83.49$\pm$2.36 & 89.34$\pm$2.39 & 64.96$\pm$2.32 & 56.56$\pm$2.67 & 46.5$\pm$2.82 & 62.59$\pm$2.56 \\
grace,enc:gcn bgrl,pred:mlp,deg & 81.94$\pm$3.06 & 86.62$\pm$2.19 & 70.4$\pm$1.93 & 39.64$\pm$2.49 & 47.86$\pm$2.26 $\bigstar$ & 62.53$\pm$1.99 \\
grace,enc:gcn bgrl,pred:mlp,evc & 85.28$\pm$1.75 & 84.95$\pm$2.85 & 68.23$\pm$2.38 & 41.46$\pm$1.97 & 40.9$\pm$3.5 & 59.97$\pm$2.49 \\
grace,enc:gcn bgrl,pred:mlp,pr & 80.15$\pm$2.15 & 88.44$\pm$1.02 & 62.58$\pm$2.08 & 48.0$\pm$3.04 & 45.53$\pm$2.76 & 33.95$\pm$4.42 X \\
grace,enc:gcn bgrl,pred:mlp,scom & \color{violet}{86.2$\pm$2.32} & 90.64$\pm$1.58 $\bigstar$ & 70.38$\pm$2.74 & \color{violet}{57.17$\pm$1.99} & 36.87$\pm$1.95 & 56.45$\pm$3.13 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast & 78.22$\pm$3.35 & 88.46$\pm$1.71 & 60.75$\pm$2.82 & 43.76$\pm$2.35 & 36.16$\pm$2.61 & 56.31$\pm$3.84 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast2 & 83.8$\pm$1.8 & \color{violet}{90.84$\pm$1.92 $\bigstar$} & 36.94$\pm$1.28 X & 54.94$\pm$3.27 & 39.55$\pm$2.63 & 49.37$\pm$3.18 \\
csgcl,enc:gcn bgrl,pred:mlp,random & 83.91$\pm$2.18 & 88.77$\pm$1.51 & \color{violet}{73.41$\pm$2.2 $\bigstar$} & 44.24$\pm$2.41 & 42.12$\pm$1.73 & 55.82$\pm$4.02 \\
csgcl,enc:gcn bgrl,pred:mlp,deg & 85.37$\pm$1.17 & 87.87$\pm$1.72 & \color{blue}{73.65$\pm$2.58} & 53.22$\pm$2.54 & 40.23$\pm$2.33 & 60.37$\pm$2.47 \\
csgcl,enc:gcn bgrl,pred:mlp,evc & 83.66$\pm$2.63 & 84.04$\pm$1.17 & 61.87$\pm$2.83 & 54.6$\pm$2.54 & 48.22$\pm$2.14 $\bigstar$ & 55.07$\pm$2.19 \\
csgcl,enc:gcn bgrl,pred:mlp,pr & 85.43$\pm$2.14 & \color{red}{91.54$\pm$1.63 $\bigstar$} & 64.04$\pm$2.36 & 51.23$\pm$2.29 & 38.71$\pm$2.03 & 62.72$\pm$3.16 \\
csgcl,enc:gcn bgrl,pred:mlp,scom & 81.4$\pm$2.81 & 86.9$\pm$1.41 & 66.21$\pm$2.21 & \color{blue}{60.58$\pm$2.09 $\bigstar$} & 31.39$\pm$2.01 X & \color{violet}{65.4$\pm$2.95 $\bigstar$} \\
csgcl,enc:gcn bgrl,pred:mlp,sbm fast & 85.67$\pm$2.08 & 82.77$\pm$2.08 & 58.36$\pm$2.88 & 46.56$\pm$2.44 & 37.57$\pm$2.25 & 56.28$\pm$2.98 \\
csgcl,enc:gcn bgrl,pred:mlp,sbm fast2 & 80.15$\pm$3.18 & 88.44$\pm$1.72 & 59.71$\pm$1.71 & 41.51$\pm$2.0 & 34.39$\pm$3.14 & 48.97$\pm$2.4 \\
lbgrl,enc:gcn bgrl,pred:mlp,random & 83.89$\pm$2.56 & 90.62$\pm$1.35 & 63.44$\pm$3.13 & 46.42$\pm$1.71 & 38.1$\pm$3.03 & 56.5$\pm$3.14 \\
lbgrl,enc:gcn bgrl,pred:mlp,deg & 77.7$\pm$2.88 X & 86.81$\pm$2.05 & 62.12$\pm$3.26 & 46.78$\pm$2.04 & 41.16$\pm$2.91 & 52.99$\pm$3.19 \\
lbgrl,enc:gcn bgrl,pred:mlp,evc & 83.68$\pm$2.11 & 85.3$\pm$2.34 & 56.85$\pm$2.42 & 41.53$\pm$1.76 & 38.05$\pm$3.09 & 61.86$\pm$3.57 \\
lbgrl,enc:gcn bgrl,pred:mlp,pr & 83.02$\pm$2.33 & 88.33$\pm$1.61 & 61.7$\pm$2.08 & 38.63$\pm$3.21 & 39.75$\pm$2.64 & 61.98$\pm$3.47 \\
lbgrl,enc:gcn bgrl,pred:mlp,scom & 79.72$\pm$3.15 & 90.15$\pm$1.75 & 56.26$\pm$3.61 & 41.22$\pm$1.51 & 32.58$\pm$4.06 X & 51.26$\pm$2.92 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fast & 82.81$\pm$2.0 & 87.19$\pm$2.18 & 55.41$\pm$2.87 & 32.69$\pm$2.15 X & 38.52$\pm$2.51 & 47.69$\pm$4.21 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fast2 & 83.23$\pm$2.0 & 88.79$\pm$1.9 & 54.77$\pm$1.68 & 39.5$\pm$0.7 & 37.98$\pm$3.04 & 36.29$\pm$4.56 X \\
lgrace,enc:gcn bgrl,pred:mlp,random & 83.38$\pm$1.37 & 90.66$\pm$1.19 & NaN & NaN & NaN & NaN \\
lgrace,enc:gcn bgrl,pred:mlp,deg & 82.33$\pm$2.98 & 86.11$\pm$1.87 & NaN & NaN & NaN & NaN \\
lgrace,enc:gcn bgrl,pred:mlp,evc & 76.64$\pm$3.3 X & 88.24$\pm$1.46 & NaN & NaN & NaN & NaN \\
lgrace,enc:gcn bgrl,pred:mlp,pr & 84.76$\pm$1.98 & \color{blue}{91.05$\pm$1.63 $\bigstar$} & NaN & NaN & NaN & NaN \\
lgrace,enc:gcn bgrl,pred:mlp,scom & 86.0$\pm$2.32 & 79.45$\pm$2.87 & NaN & NaN & NaN & NaN \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast & 83.72$\pm$2.07 & 80.29$\pm$2.13 & NaN & NaN & NaN & NaN \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast2 & 80.3$\pm$2.89 & 76.59$\pm$4.42 X & NaN & NaN & NaN & NaN \\
\bottomrule
\end{tabular}

}

/tmp/ipykernel_269/104854619.py:34: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1.loc["85_second/_physics.csv"].fillna(physics_end_data.loc["85_second/_physics.csv"], inplace=True)
/tmp/ipykernel_269/104854619.py:35: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data2.loc["85_second/_photo.csv"].fillna(photo_end_data.loc["85_second/_photo.csv"], inplace=True)
/tmp/ipykernel_269/104854619.py:36: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data2.loc["85_second/_photo.csv"].fillna(photo2_end_data.loc["85_second/_photo.csv"], inplace=True)
/tmp/ipykernel_269/104854619.py:38: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  res1.loc["85_second/_physics.csv"].fillna(physics_end_res.loc["85_second/_physics.csv"], inplace=True)
/tmp/ipykernel_269/104854619.py:39: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  res2.loc["85_second/_photo.csv"].fillna(photo_end_res.loc["85_second/_photo.csv"], inplace=True)
/tmp/ipykernel_269/104854619.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  res2.loc["85_second/_photo.csv"].fillna(photo2_end_res.loc["85_second/_photo.csv"], inplace=True)

,85_second/_cora.csv,85_second/_citeseer.csv,85_second/_cs.csv,85_second/_physics.csv,85_second/_computers.csv,85_second/_photo.csv
GCN*,81.6$\pm$1.3,82.2$\pm$1.17,64.2$\pm$2.9,42.6$\pm$3.6,\color{red}{76.2$\pm$1},\color{red}{79.8$\pm$1.8}
GRACE*,68.6$\pm$5.6,70.7$\pm$6.8,48.6$\pm$2.5,24$\pm$2.7,45.6$\pm$6.6,NaN
BGRL*,79.2$\pm$1.5,85.8$\pm$2,56.2$\pm$1.3,34.6$\pm$1.8,51.5$\pm$1.6,47.6$\pm$1.5
T-BGRL*,77.3$\pm$2,86.8$\pm$2.3,51.7$\pm$1.6,31.5$\pm$1.5,\color{blue}{55.5$\pm$0.9},47.1$\pm$2.1
"baseline,enc:gcn bgrl,pred:mlp",81.97$\pm$2.31,75.01$\pm$3.03 X,\color{red}{83.89$\pm$1.28 $\bigstar$},\color{red}{83.9$\pm$1.31 $\bigstar$},\color{violet}{51.81$\pm$3.74 $\bigstar$},\color{blue}{67.23$\pm$4.1 $\bigstar$}
"bgrl,enc:gcn bgrl,pred:mlp,random",\color{blue}{86.81$\pm$1.54 $\bigstar$},89.27$\pm$1.0,60.46$\pm$3.09,52.03$\pm$2.92,40.24$\pm$2.77,48.83$\pm$2.55
"bgrl,enc:gcn bgrl,pred:mlp,deg",85.67$\pm$2.09,82.48$\pm$2.12,69.55$\pm$2.59,38.94$\pm$2.06,41.8$\pm$2.55,59.18$\pm$2.81
"bgrl,enc:gcn bgrl,pred:mlp,evc",\color{red}{87.55$\pm$1.19 $\bigstar$},83.23$\pm$3.03,69.17$\pm$2.77,47.39$\pm$2.43,40.48$\pm$2.34,59.57$\pm$3.42
"bgrl,enc:gcn bgrl,pred:mlp,pr",76.87$\pm$3.55 X,85.78$\pm$2.65,67.8$\pm$2.4,38.59$\pm$3.02,43.6$\pm$2.4,57.43$\pm$3.14
"bgrl,enc:gcn bgrl,pred:mlp,scom",83.11$\pm$1.49,82.99$\pm$1.94,66.69$\pm$3.06,54.85$\pm$2.12,41.51$\pm$2.03,52.05$\pm$4.06
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast",83.83$\pm$1.77,88.64$\pm$1.6,60.18$\pm$2.4,41.91$\pm$3.11,36.44$\pm$2.2,54.34$\pm$4.41
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast2",81.35$\pm$2.35,81.67$\pm$2.64,55.05$\pm$2.61,46.64$\pm$4.49,38.33$\pm$2.71,48.25$\pm$3.79
"grace,enc:gcn bgrl,pred:mlp,random",83.49$\pm$2.36,89.34$\pm$2.39,64.96$\pm$2.32,56.56$\pm$2.67,46.5$\pm$2.82,62.59$\pm$2.56
"grace,enc:gcn bgrl,pred:mlp,deg",81.94$\pm$3.06,86.62$\pm$2.19,70.4$\pm$1.93,39.64$\pm$2.49,47.86$\pm$2.26 $\bigstar$,62.53$\pm$1.99
"grace,enc:gcn bgrl,pred:mlp,evc",85.28$\pm$1.75,84.95$\pm$2.85,68.23$\pm$2.38,41.46$\pm$1.97,40.9$\pm$3.5,59.97$\pm$2.49
"grace,enc:gcn bgrl,pred:mlp,pr",80.15$\pm$2.15,88.44$\pm$1.02,62.58$\pm$2.08,48.0$\pm$3.04,45.53$\pm$2.76,33.95$\pm$4.42 X
"grace,enc:gcn bgrl,pred:mlp,scom",\color{violet}{86.2$\pm$2.32},90.64$\pm$1.58 $\bigstar$,70.38$\pm$2.74,\color{violet}{57.17$\pm$1.99},36.87$\pm$1.95,56.45$\pm$3.13
"grace,enc:gcn bgrl,pred:mlp,sbm fast",78.22$\pm$3.35,88.46$\pm$1.71,60.75$\pm$2.82,43.76$\pm$2.35,36.16$\pm$2.61,56.31$\pm$3.84
"grace,enc:gcn bgrl,pred:mlp,sbm fast2",83.8$\pm$1.8,\color{violet}{90.84$\pm$1.92 $\bigstar$},36.94$\pm$1.28 X,54.94$\pm$3.27,39.55$\pm$2.63,49.37$\pm$3.18
"csgcl,enc:gcn bgrl,pred:mlp,random",83.91$\pm$2.18,88.77$\pm$1.51,\color{violet}{73.41$\pm$2.2 $\bigstar$},44.24$\pm$2.41,42.12$\pm$1.73,55.82$\pm$4.02
"csgcl,enc:gcn bgrl,pred:mlp,deg",85.37$\pm$1.17,87.87$\pm$1.72,\color{blue}{73.65$\pm$2.58},53.22$\pm$2.54,40.23$\pm$2.33,60.37$\pm$2.47
"csgcl,enc:gcn bgrl,pred:mlp,evc",83.66$\pm$2.63,84.04$\pm$1.17,61.87$\pm$2.83,54.6$\pm$2.54,48.22$\pm$2.14 $\bigstar$,55.07$\pm$2.19
"csgcl,enc:gcn bgrl,pred:mlp,pr",85.43$\pm$2.14,\color{red}{91.54$\pm$1.63 $\bigstar$},64.04$\pm$2.36,51.23$\pm$2.29,38.71$\pm$2.03,62.72$\pm$3.16
"csgcl,enc:gcn bgrl,pred:mlp,scom",81.4$\pm$2.81,86.9$\pm$1.41,66.21$\pm$2.21,\color{blue}{60.58$\pm$2.09 $\bigstar$},31.39$\pm$2.01 X,\color{violet}{65.4$\pm$2.95 $\bigstar$}
"csgcl,enc:gcn bgrl,pred:mlp,sbm fast",85.67$\pm$2.08,82.77$\pm$2.08,58.36$\pm$2.88,46.56$\pm$2.44,37.57$\pm$2.25,56.28$\pm$2.98
"csgcl,enc:gcn bgrl,pred:mlp,sbm fast2",80.15$\pm$3.18,88.44$\pm$1.72,59.71$\pm$1.71,41.51$\pm$2.0,34.39$\pm$3.14,48.97$\pm$2.4
"lbgrl,enc:gcn bgrl,pred:mlp,random",83.89$\pm$2.56,90.62$\pm$1.35,63.44$\pm$3.13,46.42$\pm$1.71,38.1$\pm$3.03,56.5$\pm$3.14
"lbgrl,enc:gcn bgrl,pred:mlp,deg",77.7$\pm$2.88 X,86.81$\pm$2.05,62.12$\pm$3.26,46.78$\pm$2.04,41.16$\pm$2.91,52.99$\pm$3.19
"lbgrl,enc:gcn bgrl,pred:mlp,evc",83.68$\pm$2.11,85.3$\pm$2.34,56.85$\pm$2.42,41.53$\pm$1.76,38.05$\pm$3.09,61.86$\pm$3.57
"lbgrl,enc:gcn bgrl,pred:mlp,pr",83.02$\pm$2.33,88.33$\pm$1.61,61.7$\pm$2.08,38.63$\pm$3.21,39.75$\pm$2.64,61.98$\pm$3.47
"lbgrl,enc:gcn bgrl,pred:mlp,scom",79.72$\pm$3.15,90.15$\pm$1.75,56.26$\pm$3.61,41.22$\pm$1.51,32.58$\pm$4.06 X,51.26$\pm$2.92
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fast",82.81$\pm$2.0,87.19$\pm$2.18,55.41$\pm$2.87,32.69$\pm$2.15 X,38.52$\pm$2.51,47.69$\pm$4.21
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fast2",83.23$\pm$2.0,88.79$\pm$1.9,54.77$\pm$1.68,39.5$\pm$0.7,37.98$\pm$3.04,36.29$\pm$4.56 X
"lgrace,enc:gcn bgrl,pred:mlp,random",83.38$\pm$1.37,90.66$\pm$1.19,NaN,NaN,NaN,NaN
"lgrace,enc:gcn bgrl,pred:mlp,deg",82.33$\pm$2.98,86.11$\pm$1.87,NaN,NaN,NaN,NaN
"lgrace,enc:gcn bgrl,pred:mlp,evc",76.64$\pm$3.3 X,88.24$\pm$1.46,NaN,NaN,NaN,NaN
"lgrace,enc:gcn bgrl,pred:mlp,pr",84.76$\pm$1.98,\color{blue}{91.05$\pm$1.63 $\bigstar$},NaN,NaN,NaN,NaN
"lgrace,enc:gcn bgrl,pred:mlp,scom",86.0$\pm$2.32,79.45$\pm$2.87,NaN,NaN,NaN,NaN
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast",83.72$\pm$2.07,80.29$\pm$2.13,NaN,NaN,NaN,NaN
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast2",80.3$\pm$2.89,76.59$\pm$4.42 X,NaN,NaN,NaN,NaN

In [ ]:
names1  = [
    '70_first/_cora.csv',
    '70_first/_citeseer.csv',
    '70_first/_USAir.csv',
    '70_first/_NS.csv',
    '70_first/_PB.csv',
    '70_first/_Yeast.csv',
    '70_first/_Celegans.csv',
    '70_first/_power.csv',
    '70_first/_Router.csv',
    '70_first/_Ecoli.csv',
]
names2 = [
    '70_first/a_cora.csv',
    '70_first/a_citeseer.csv',
    '70_first/a_USAir.csv',
    '70_first/a_NS.csv',
    '70_first/a_PB.csv',
    '70_first/a_Yeast.csv',
    '70_first/a_Celegans.csv',
    '70_first/a_power.csv',
    '70_first/a_Router.csv',
    '70_first/a_Ecoli.csv',
]
data1, res1 = ut.mix_dataset(names1, 'Hits@50', filtre=['sbm'])
data2, res2 = ut.mix_dataset(names2, 'Hits@50')
data2.index = data.index
combined_data = pd.concat([data, data2], axis=1)
# combined_data = ut.tex_table(combined_data, res)

def rename(idx):
    print(idx)
    if 'mlp,' in idx:
        return idx.split('mlp,')[1]
    else:
        return idx
import numpy as np
combined_data = combined_data.T.rename(index=rename)
for column in combined_data.columns:
        combined_data[column] = combined_data[column].apply(ut.extract_mean).apply(np.mean)
combined_data = combined_data.groupby(combined_data.index).mean()
combined_data['Moyenne'] = combined_data.mean(axis=1)
combined_data = combined_data.sort_values(by='Moyenne')
combined_data

bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast+random_mean
bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_cheat+random_mean
grace,enc:gcn_bgrl,pred:mlp,sbm_fast+random_mean
grace,enc:gcn_bgrl,pred:mlp,sbm_fast_cheat+random_mean
lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast+random_mean
lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_cheat+random_mean
lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast+random_mean
lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast_cheat+random_mean
infomap_prob_pred_mean
bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_mean
louvain_prob_pred_mean
bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast+deg_mean
bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast+evc_mean
bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast+pr_mean
bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast+scom_mean
bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean
grace,enc:gcn_bgrl,pred:mlp,sbm_fast_mean
leiden_prob_pred_mean
grace,enc:gcn_bgrl,pred:mlp,sbm_fast+deg_mean
grace,enc:gcn_bgrl,pred:mlp,sbm_fast+evc_mean
grace,enc:gcn_bgrl,pred:mlp,sbm_fast+pr_mean
grace,enc:gcn_bgrl,pred:mlp,sbm_fast+scom_mean
grace,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean
lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_mean
lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast+deg_mean
lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast+evc_mean
lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast+pr_mean
lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast+scom_mean
lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean
lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast_mean
lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast+deg_mean
lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast+evc_mean
lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast+pr_mean
lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast+scom_mean
lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean

,70_first/_cora.csv,70_first/_citeseer.csv,70_first/_USAir.csv,70_first/_NS.csv,70_first/_PB.csv,70_first/_Yeast.csv,70_first/_Celegans.csv,70_first/_power.csv,70_first/_Router.csv,70_first/_Ecoli.csv,Moyenne
leiden_prob_pred_mean,54.6600,47.4400,46.7800,81.0900,4.0600,NaN,35.5500,33.4700,22.8100,36.9600,40.313333
louvain_prob_pred_mean,54.6600,47.4400,46.9400,80.7100,4.0600,71.8300,35.5500,33.4700,22.8100,36.9600,43.443000
infomap_prob_pred_mean,54.6600,47.4400,46.7800,81.0900,4.0600,71.8300,35.5500,33.4700,22.8100,36.9600,43.465000
sbm_fast2_mean,71.5750,74.5175,85.7700,81.2250,44.2250,80.0000,55.5875,35.6850,33.3250,80.6550,64.256500
sbm_fast+random_mean,71.1750,76.3875,83.0175,81.1775,45.3950,77.6150,62.8275,34.5875,32.4400,78.8400,64.346250
sbm_fast+pr_mean,72.2475,73.8500,88.4600,78.5050,44.6525,80.2775,62.5450,33.8425,33.3575,79.8400,64.757750
sbm_fast+evc_mean,70.5700,76.6275,86.9950,81.1000,46.3825,77.7575,65.8100,35.3150,28.0450,80.5925,64.919500
sbm_fast_mean,69.1250,81.5250,86.3175,72.6550,45.6500,81.2100,63.9175,32.3800,38.8400,79.8650,65.148500
sbm_fast+scom_mean,67.3375,78.5150,87.6100,81.7075,45.0075,81.1925,62.4750,33.8400,41.7025,79.1100,65.849750
sbm_fast+deg_mean,68.1525,78.7800,88.8150,81.8200,45.1175,80.5325,65.5825,34.2425,39.7900,80.5200,66.335250
sbm_fast_cheat+random_mean,81.6075,87.9075,88.7725,92.1225,45.0550,80.1400,63.8400,90.7500,92.3575,80.8900,80.344250

In [79]:
# tab 2 
names  = [
    '85_second/_cora.csv',
    '85_second/_citeseer.csv',
    '85_second/_USAir.csv',
    '85_second/_NS.csv',
    '85_second/_PB.csv',
    '85_second/_Yeast.csv',
    '85_second/_Celegans.csv',
    '85_second/_power.csv',
    '85_second/_Router.csv',
    '85_second/_Ecoli.csv',
]

data1, res1 = ut.mix_dataset(names, 'Hits@50', filtre2=['cheat'])
data1 = data1.T

names  = [
    '70_first/_cora.csv',
    '70_first/_citeseer.csv',
    '70_first/_USAir.csv',
    '70_first/_NS.csv',
    '70_first/_PB.csv',
    '70_first/_Yeast.csv',
    '70_first/_Celegans.csv',
    '70_first/_power.csv',
    '70_first/_Router.csv',
    '70_first/_Ecoli.csv',
]
names2 = [
    '70_first/a_cora.csv',
    '70_first/a_citeseer.csv',
    '70_first/a_USAir.csv',
    '70_first/a_NS.csv',
    '70_first/a_PB.csv',
    '70_first/a_Yeast.csv',
    '70_first/a_Celegans.csv',
    '70_first/a_power.csv',
    '70_first/a_Router.csv',
    '70_first/a_Ecoli.csv',
]
data, res = ut.mix_dataset(names, 'Hits@50', filtre=['baseline', 'random'], filtre2=['louvain', 'leiden', 'infomap', '\+', 'cheat'])
data2, res2 = ut.mix_dataset(names2, 'Hits@50', filtre2=['\+'])
data2.index = data.index
combined_data = pd.concat([data, data2], axis=1)
combined_data = combined_data.T

data1.columns = combined_data.columns
display(combined_data)
display(data1)

for column in combined_data.columns:
        combined_data[column] = combined_data[column].apply(ut.extract_mean).apply(np.mean)

for column in data1.columns:
        data1[column] = data1[column].apply(ut.extract_mean).apply(np.mean)
tab2 = data1 - combined_data
tab2 = tab2.groupby(tab2.index).mean()
tab2['Moyenne'] = tab2.mean(axis=1)
tab2 = tab2.sort_values(by='Moyenne')
tab2

<>:42: SyntaxWarning: invalid escape sequence '\+'
<>:43: SyntaxWarning: invalid escape sequence '\+'
<>:42: SyntaxWarning: invalid escape sequence '\+'
<>:43: SyntaxWarning: invalid escape sequence '\+'
/tmp/ipykernel_10022/1523198393.py:42: SyntaxWarning: invalid escape sequence '\+'
  data, res = ut.mix_dataset(names, 'Hits@50', filtre=['baseline', 'random'], filtre2=['louvain', 'leiden', 'infomap', '\+', 'cheat'])
/tmp/ipykernel_10022/1523198393.py:43: SyntaxWarning: invalid escape sequence '\+'
  data2, res2 = ut.mix_dataset(names2, 'Hits@50', filtre2=['\+'])

,70_first/_cora.csv,70_first/_citeseer.csv,70_first/_USAir.csv,70_first/_NS.csv,70_first/_PB.csv,70_first/_Yeast.csv,70_first/_Celegans.csv,70_first/_power.csv,70_first/_Router.csv,70_first/_Ecoli.csv
"baseline,enc:gcn_bgrl,pred:mlp_mean",65.8$\pm$1.5,74.55$\pm$1.64,89.74$\pm$2.29,80.91$\pm$1.18,50.94$\pm$3.3,84.19$\pm$0.94,63.61$\pm$3.65,28.38$\pm$1.19,26.36$\pm$1.52,81.91$\pm$1.1
"bgrl,enc:gcn_bgrl,pred:mlp,random_mean",68.63$\pm$3.05,77.37$\pm$2.66,87.11$\pm$1.9,80.49$\pm$1.29,47.24$\pm$3.24,82.72$\pm$1.01,67.41$\pm$3.44,24.34$\pm$1.03,30.95$\pm$1.16,81.63$\pm$0.72
"grace,enc:gcn_bgrl,pred:mlp,random_mean",68.47$\pm$2.82,80.03$\pm$1.52,91.48$\pm$1.72,79.84$\pm$0.86,48.03$\pm$2.32,84.23$\pm$0.52,72.1$\pm$2.43,34.8$\pm$1.58,29.91$\pm$2.21,81.93$\pm$0.63
"lbgrl,enc:gcn_bgrl,pred:mlp,random_mean",68.31$\pm$2.88,81.81$\pm$1.38,79.81$\pm$3.92,80.02$\pm$1.24,47.72$\pm$2.3,81.52$\pm$1.16,65.52$\pm$2.25,24.2$\pm$0.68,39.72$\pm$8.46,81.75$\pm$1.01
"lgrace,enc:gcn_bgrl,pred:mlp,random_mean",59.44$\pm$3.72,77.41$\pm$2.0,92.47$\pm$0.8,80.8$\pm$1.45,51.98$\pm$3.28,84.33$\pm$1.09,70.56$\pm$3.27,26.22$\pm$3.13,34.67$\pm$10.92,81.67$\pm$1.22
infomap_prob_pred_mean,54.66$\pm$1.49,47.44$\pm$1.43,46.78$\pm$3.83,81.09$\pm$0.65,4.06$\pm$1.03,71.83$\pm$1.52,35.55$\pm$4.57,33.47$\pm$1.33,22.81$\pm$1.1,36.96$\pm$0.99
"bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",69.87$\pm$1.57,86.33$\pm$1.81,88.82$\pm$2.35,79.18$\pm$1.49,43.95$\pm$2.45,81.01$\pm$1.37,58.72$\pm$3.18,34.36$\pm$1.49,49.48$\pm$3.53,79.21$\pm$1.4
louvain_prob_pred_mean,54.66$\pm$1.49,47.44$\pm$1.43,46.94$\pm$3.99,80.71$\pm$0.99,4.06$\pm$1.03,71.83$\pm$1.52,35.55$\pm$4.57,33.47$\pm$1.33,22.81$\pm$1.1,36.96$\pm$0.99
"bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",72.54$\pm$2.05,66.54$\pm$3.18,80.59$\pm$3.58,80.46$\pm$1.36,42.7$\pm$2.91,79.58$\pm$1.59,57.2$\pm$3.6,33.68$\pm$1.31,43.33$\pm$3.33,79.77$\pm$1.02
"grace,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",69.14$\pm$2.65,81.19$\pm$2.73,87.01$\pm$2.03,73.72$\pm$4.33,45.65$\pm$2.74,79.84$\pm$1.61,64.71$\pm$3.17,28.43$\pm$1.11,33.83$\pm$1.93,79.54$\pm$1.14
leiden_prob_pred_mean,54.66$\pm$1.49,47.44$\pm$1.43,46.78$\pm$3.83,81.09$\pm$0.65,4.06$\pm$1.03,NaN,35.55$\pm$4.57,33.47$\pm$1.33,22.81$\pm$1.1,36.96$\pm$0.99
"grace,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",71.01$\pm$1.99,80.91$\pm$1.72,86.21$\pm$3.63,80.89$\pm$1.41,45.54$\pm$2.5,79.46$\pm$1.49,61.98$\pm$3.55,36.79$\pm$1.46,26.43$\pm$2.69,82.36$\pm$0.64
"lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",59.66$\pm$4.76,75.95$\pm$1.76,79.06$\pm$2.75,84.31$\pm$1.97,44.46$\pm$2.91,80.77$\pm$1.18,65.22$\pm$2.76,34.05$\pm$0.76,42.29$\pm$3.98,77.81$\pm$0.98
"lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",70.13$\pm$3.7,74.33$\pm$2.53,87.95$\pm$2.58,82.97$\pm$1.67,44.23$\pm$2.29,81.19$\pm$0.91,42.73$\pm$2.57,36.22$\pm$1.31,35.94$\pm$2.44,79.21$\pm$1.47
"lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",77.83$\pm$1.62,82.63$\pm$1.34,90.38$\pm$2.54,53.41$\pm$17.6,48.54$\pm$2.99,83.22$\pm$0.96,67.02$\pm$2.6,32.68$\pm$1.14,29.76$\pm$3.38,82.9$\pm$0.59
"lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",72.62$\pm$1.5,76.29$\pm$1.89,88.33$\pm$2.57,80.58$\pm$1.14,44.43$\pm$4.54,79.77$\pm$1.78,60.44$\pm$3.16,36.05$\pm$0.86,27.6$\pm$1.06,81.28$\pm$1.0

,70_first/_cora.csv,70_first/_citeseer.csv,70_first/_USAir.csv,70_first/_NS.csv,70_first/_PB.csv,70_first/_Yeast.csv,70_first/_Celegans.csv,70_first/_power.csv,70_first/_Router.csv,70_first/_Ecoli.csv
"baseline,enc:gcn_bgrl,pred:mlp_mean",76.58$\pm$1.49,76.73$\pm$1.9,95.33$\pm$2.08,89.34$\pm$2.12,67.43$\pm$2.61,88.14$\pm$0.78,90.51$\pm$2.36,45.14$\pm$1.06,32.66$\pm$6.66,89.14$\pm$0.65
"bgrl,enc:gcn_bgrl,pred:mlp,random_mean",85.14$\pm$2.38,88.57$\pm$1.35,92.22$\pm$2.27,88.1$\pm$1.89,61.78$\pm$2.21,86.61$\pm$1.02,81.64$\pm$3.4,34.48$\pm$2.81,49.71$\pm$2.52,88.81$\pm$0.7
infomap_prob_pred_mean,66.03$\pm$2.16,57.23$\pm$2.02,55.94$\pm$7.5,88.76$\pm$2.16,7.48$\pm$1.22,79.06$\pm$1.63,61.21$\pm$4.68,50.74$\pm$1.3,28.56$\pm$0.96,39.07$\pm$1.27
"bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",71.8$\pm$2.96,89.23$\pm$2.26,86.89$\pm$2.08,89.05$\pm$2.28,60.16$\pm$2.49,86.37$\pm$0.85,81.4$\pm$3.91,43.63$\pm$3.36,68.66$\pm$3.39,85.01$\pm$1.18
louvain_prob_pred_mean,66.03$\pm$2.16,57.23$\pm$2.02,55.94$\pm$7.5,89.09$\pm$2.11,7.16$\pm$0.97,79.06$\pm$1.63,61.59$\pm$4.54,50.74$\pm$1.3,28.56$\pm$0.96,39.2$\pm$1.32
"bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",49.66$\pm$9.51,82.24$\pm$2.52,90.52$\pm$2.76,89.01$\pm$2.49,55.86$\pm$2.61,87.31$\pm$1.1,84.35$\pm$5.18,53.66$\pm$1.73,60.78$\pm$3.51,83.27$\pm$1.41
leiden_prob_pred_mean,66.03$\pm$2.16,57.23$\pm$2.02,55.94$\pm$7.5,88.76$\pm$2.16,7.48$\pm$1.22,79.06$\pm$1.63,61.21$\pm$4.68,50.74$\pm$1.3,28.56$\pm$0.96,39.07$\pm$1.27
"grace,enc:gcn_bgrl,pred:mlp,random_mean",87.13$\pm$1.68,88.37$\pm$2.37,93.25$\pm$1.92,89.16$\pm$1.97,44.62$\pm$3.32,87.49$\pm$0.84,89.39$\pm$2.25,56.1$\pm$2.03,57.95$\pm$2.05,85.78$\pm$0.89
"grace,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",83.59$\pm$1.59,88.75$\pm$1.89,94.58$\pm$1.22,88.28$\pm$1.57,56.95$\pm$3.76,82.97$\pm$1.38,85.93$\pm$3.98,50.73$\pm$1.29,40.08$\pm$7.74,82.23$\pm$0.93
"grace,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",83.7$\pm$1.96,87.34$\pm$1.8,89.39$\pm$3.68,88.83$\pm$2.14,60.41$\pm$2.85,81.87$\pm$1.79,84.67$\pm$2.71,NaN,28.77$\pm$3.65,84.17$\pm$1.51
"lbgrl,enc:gcn_bgrl,pred:mlp,random_mean",85.64$\pm$2.04,83.19$\pm$4.94,93.63$\pm$1.57,86.86$\pm$2.38,61.01$\pm$2.32,87.28$\pm$0.67,87.76$\pm$4.6,NaN,47.57$\pm$3.42,87.35$\pm$1.19
"lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",75.33$\pm$2.06,83.98$\pm$2.51,93.58$\pm$1.72,88.43$\pm$1.92,57.72$\pm$1.75,86.3$\pm$1.03,78.69$\pm$3.73,NaN,64.75$\pm$3.16,82.51$\pm$1.35
"lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",81.9$\pm$1.88,88.24$\pm$1.9,84.25$\pm$3.38,89.53$\pm$2.63,59.81$\pm$3.5,84.33$\pm$0.72,83.55$\pm$4.3,NaN,58.06$\pm$2.85,82.37$\pm$0.69
"lgrace,enc:gcn_bgrl,pred:mlp,random_mean",79.7$\pm$3.11,77.6$\pm$4.99,95.0$\pm$1.08,89.23$\pm$2.16,66.29$\pm$2.7,88.31$\pm$0.92,90.37$\pm$3.96,NaN,53.28$\pm$10.56,85.46$\pm$1.02
"lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",82.68$\pm$1.91,80.35$\pm$2.09,90.38$\pm$2.65,90.15$\pm$2.38,64.11$\pm$2.75,85.5$\pm$1.07,85.61$\pm$3.41,NaN,34.75$\pm$3.86,87.07$\pm$1.28
"lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",82.64$\pm$2.14,86.2$\pm$2.21,91.89$\pm$2.85,89.89$\pm$2.23,58.74$\pm$2.98,86.67$\pm$0.77,82.99$\pm$2.05,NaN,38.82$\pm$2.15,88.19$\pm$0.92

,70_first/_cora.csv,70_first/_citeseer.csv,70_first/_USAir.csv,70_first/_NS.csv,70_first/_PB.csv,70_first/_Yeast.csv,70_first/_Celegans.csv,70_first/_power.csv,70_first/_Router.csv,70_first/_Ecoli.csv,Moyenne
"grace,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",12.69,6.43,3.18,7.94,14.87,2.41,22.69,NaN,2.34,1.81,8.262222
"bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",1.93,2.90,-1.93,9.87,16.21,5.36,22.68,9.27,19.18,5.80,9.127000
"lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",4.85,-2.28,0.00,36.74,15.57,2.28,18.59,NaN,4.99,4.17,9.434444
infomap_prob_pred_mean,11.37,9.79,9.16,7.67,3.42,7.23,25.66,17.27,5.75,2.11,9.943000
louvain_prob_pred_mean,11.37,9.79,9.00,8.38,3.10,7.23,26.04,17.27,5.75,2.24,10.017000
"bgrl,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",-22.88,15.70,9.93,8.55,13.16,7.73,27.15,19.98,17.45,3.50,10.027000
"lgrace,enc:gcn_bgrl,pred:mlp,random_mean",20.26,0.19,2.53,8.43,14.31,3.98,19.81,NaN,18.61,3.79,10.212222
leiden_prob_pred_mean,11.37,9.79,9.16,7.67,3.42,NaN,25.66,17.27,5.75,2.11,10.244444
"lbgrl,enc:gcn_bgrl,pred:mlp,random_mean",17.33,1.38,13.82,6.84,13.29,5.76,22.24,NaN,7.85,5.60,10.456667
"baseline,enc:gcn_bgrl,pred:mlp_mean",10.78,2.18,5.59,8.43,16.49,3.95,26.90,16.76,6.30,7.23,10.461000
"lgrace,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",10.02,9.91,3.56,9.31,14.31,6.90,22.55,NaN,11.22,6.91,10.521111
"grace,enc:gcn_bgrl,pred:mlp,random_mean",18.66,8.34,1.77,9.32,-3.41,3.26,17.29,21.30,28.04,3.85,10.842000
"bgrl,enc:gcn_bgrl,pred:mlp,random_mean",16.51,11.20,5.11,7.61,14.54,3.89,14.23,10.14,18.76,7.18,10.917000
"grace,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",14.45,7.56,7.57,14.56,11.30,3.13,21.22,22.30,6.25,2.69,11.103000
"lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast_mean",15.67,8.03,14.52,4.12,13.26,5.53,13.47,NaN,22.46,4.70,11.306667
"lbgrl,enc:gcn_bgrl,pred:mlp,sbm_fast2_mean",11.77,13.91,-3.70,6.56,15.58,3.14,40.82,NaN,22.12,3.16,12.595556

In [9]:
names = [
    'POS/_crime.csv',
    'POS/_euroroad.csv',
    'POS/_netscience.csv',
    'POS/_power.csv',
    'POS/_wiki_science.csv',
    'POS/_yeast.csv',
]
data, res = ut.mix_dataset(names, 'Hits@50', filtre=['pred:mlp', 'baseline'], filtre2=['bgrl,enc'])
data = ut.tex_table(data,res)
data.T

\resizebox{\textwidth}{!}{
\begin{tabular}{lllllll}
\toprule
 & POS/_crime.csv & POS/_euroroad.csv & POS/_netscience.csv & POS/_power.csv & POS/_wiki_science.csv & POS/_yeast.csv \\
\midrule
baseline,enc:gcn bgrl,pred:inner & 31.02$\pm$4.46 & \color{blue}{70.42$\pm$3.53 $\bigstar$} & \color{blue}{83.1$\pm$1.35} & \color{violet}{50.3$\pm$1.83} & 89.01$\pm$1.27 & 92.92$\pm$0.75 X \\
baseline,enc:gcn bgrl,pred:mlp & \color{violet}{37.73$\pm$4.45} & 27.99$\pm$3.97 X & 75.89$\pm$1.8 X & 30.16$\pm$0.71 X & \color{red}{90.78$\pm$1.31 $\bigstar$} & 93.45$\pm$0.43 \\
baseline,enc:gcn bgrl,pred:ncn & 27.53$\pm$2.99 X & 34.06$\pm$4.6 & 79.51$\pm$1.83 & 24.07$\pm$1.74 X & 86.91$\pm$4.19 & 93.65$\pm$0.35 \\
grace,enc:gcn bgrl,pred:mlp,random & 28.44$\pm$4.99 X & 34.17$\pm$2.83 & 79.01$\pm$4.05 & 36.63$\pm$1.5 & 86.42$\pm$1.98 & \color{blue}{93.83$\pm$0.44} \\
grace,enc:gcn bgrl,pred:mlp,deg & 25.66$\pm$3.72 X & 37.35$\pm$5.66 & 80.33$\pm$1.66 & 37.12$\pm$1.47 & \color{violet}{89.25$\pm$1.23} & 93.55$\pm$0.52 \\
grace,enc:gcn bgrl,pred:mlp,evc & 30.85$\pm$5.03 & 33.85$\pm$4.22 & 79.95$\pm$1.97 & 35.71$\pm$1.17 & 87.62$\pm$1.36 & 93.48$\pm$0.46 \\
grace,enc:gcn bgrl,pred:mlp,pr & 23.56$\pm$6.93 X & 29.19$\pm$1.97 X & 79.45$\pm$1.74 & 36.79$\pm$1.6 & \color{blue}{89.43$\pm$1.7} & 93.59$\pm$0.47 \\
grace,enc:gcn bgrl,pred:mlp,scom & 24.37$\pm$4.29 X & 36.78$\pm$3.79 & 80.05$\pm$1.87 & 34.04$\pm$1.06 & 88.64$\pm$1.49 & \color{violet}{93.72$\pm$0.33} \\
grace,enc:gcn bgrl,pred:mlp,sbm fast+random & 31.9$\pm$8.27 & 19.58$\pm$13.1 X & \color{violet}{81.37$\pm$1.25} & 35.06$\pm$1.55 & 86.79$\pm$1.58 & 93.25$\pm$0.53 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast bug+random & \color{blue}{41.66$\pm$1.8 $\bigstar$} & \color{violet}{70.35$\pm$2.91 $\bigstar$} & 81.37$\pm$1.92 & \color{blue}{54.17$\pm$2.35 $\bigstar$} & 5.81$\pm$17.44 X & 92.37$\pm$0.6 X \\
grace,enc:gcn bgrl,pred:mlp,kmeans+random & \color{red}{82.58$\pm$3.25 $\bigstar$} & \color{red}{86.61$\pm$1.89 $\bigstar$} & \color{red}{96.97$\pm$1.03 $\bigstar$} & \color{red}{98.41$\pm$0.33 $\bigstar$} & 87.97$\pm$1.3 & \color{red}{96.1$\pm$0.49 $\bigstar$} \\
\bottomrule
\end{tabular}

}

,POS/_crime.csv,POS/_euroroad.csv,POS/_netscience.csv,POS/_power.csv,POS/_wiki_science.csv,POS/_yeast.csv
"baseline,enc:gcn bgrl,pred:inner",31.02$\pm$4.46,\color{blue}{70.42$\pm$3.53 $\bigstar$},\color{blue}{83.1$\pm$1.35},\color{violet}{50.3$\pm$1.83},89.01$\pm$1.27,92.92$\pm$0.75 X
"baseline,enc:gcn bgrl,pred:mlp",\color{violet}{37.73$\pm$4.45},27.99$\pm$3.97 X,75.89$\pm$1.8 X,30.16$\pm$0.71 X,\color{red}{90.78$\pm$1.31 $\bigstar$},93.45$\pm$0.43
"baseline,enc:gcn bgrl,pred:ncn",27.53$\pm$2.99 X,34.06$\pm$4.6,79.51$\pm$1.83,24.07$\pm$1.74 X,86.91$\pm$4.19,93.65$\pm$0.35
"grace,enc:gcn bgrl,pred:mlp,random",28.44$\pm$4.99 X,34.17$\pm$2.83,79.01$\pm$4.05,36.63$\pm$1.5,86.42$\pm$1.98,\color{blue}{93.83$\pm$0.44}
"grace,enc:gcn bgrl,pred:mlp,deg",25.66$\pm$3.72 X,37.35$\pm$5.66,80.33$\pm$1.66,37.12$\pm$1.47,\color{violet}{89.25$\pm$1.23},93.55$\pm$0.52
"grace,enc:gcn bgrl,pred:mlp,evc",30.85$\pm$5.03,33.85$\pm$4.22,79.95$\pm$1.97,35.71$\pm$1.17,87.62$\pm$1.36,93.48$\pm$0.46
"grace,enc:gcn bgrl,pred:mlp,pr",23.56$\pm$6.93 X,29.19$\pm$1.97 X,79.45$\pm$1.74,36.79$\pm$1.6,\color{blue}{89.43$\pm$1.7},93.59$\pm$0.47
"grace,enc:gcn bgrl,pred:mlp,scom",24.37$\pm$4.29 X,36.78$\pm$3.79,80.05$\pm$1.87,34.04$\pm$1.06,88.64$\pm$1.49,\color{violet}{93.72$\pm$0.33}
"grace,enc:gcn bgrl,pred:mlp,sbm fast+random",31.9$\pm$8.27,19.58$\pm$13.1 X,\color{violet}{81.37$\pm$1.25},35.06$\pm$1.55,86.79$\pm$1.58,93.25$\pm$0.53
"grace,enc:gcn bgrl,pred:mlp,sbm fast bug+random",\color{blue}{41.66$\pm$1.8 $\bigstar$},\color{violet}{70.35$\pm$2.91 $\bigstar$},81.37$\pm$1.92,\color{blue}{54.17$\pm$2.35 $\bigstar$},5.81$\pm$17.44 X,92.37$\pm$0.6 X
"grace,enc:gcn bgrl,pred:mlp,kmeans+random",\color{red}{82.58$\pm$3.25 $\bigstar$},\color{red}{86.61$\pm$1.89 $\bigstar$},\color{red}{96.97$\pm$1.03 $\bigstar$},\color{red}{98.41$\pm$0.33 $\bigstar$},87.97$\pm$1.3,\color{red}{96.1$\pm$0.49 $\bigstar$}

In [14]:
names = [
    'SBM/Important_cora.csv',
    'SBM/Important2_cora.csv',
    'SBM/Important_NS.csv',
    'SBM/Important2_NS.csv'
]
data, res = ut.mix_dataset(names, 'Hits@100', filtre=['pred:mlp', 'baseline'], )
data = ut.tex_table(data,res)
data.T

\resizebox{\textwidth}{!}{
\begin{tabular}{lllll}
\toprule
 & SBM/Important_cora.csv & SBM/Important2_cora.csv & SBM/Important_NS.csv & SBM/Important2_NS.csv \\
\midrule
baseline,enc:gcn bgrl,pred:inner & \color{blue}{85.72$\pm$1.15 $\bigstar$} & 91.23$\pm$1.31 & \color{violet}{89.87$\pm$1.34} & \color{violet}{94.27$\pm$1.8} \\
baseline,enc:gcn bgrl,pred:mlp & 74.33$\pm$1.39 X & 88.65$\pm$1.13 & 81.95$\pm$1.88 & 94.23$\pm$1.64 \\
baseline,enc:gcn bgrl,pred:ncn & 78.45$\pm$1.8 & 48.58$\pm$13.99 X & 83.41$\pm$1.25 & 84.27$\pm$8.47 X \\
grace,enc:gcn bgrl,pred:mlp,random & \color{violet}{82.88$\pm$1.1} & 89.39$\pm$1.48 & 85.6$\pm$1.76 & 93.83$\pm$2.04 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast+random & 58.3$\pm$3.1 X & 90.06$\pm$1.38 & 79.2$\pm$1.65 X & 92.45$\pm$1.08 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast cheat+random & \color{red}{90.56$\pm$1.16 $\bigstar$} & \color{blue}{92.88$\pm$1.13 $\bigstar$} & \color{blue}{95.6$\pm$0.85 $\bigstar$} & \color{red}{97.99$\pm$1.15 $\bigstar$} \\
bgrl,enc:gcn bgrl,pred:mlp,random & 81.53$\pm$1.53 & \color{violet}{92.3$\pm$1.31 $\bigstar$} & 80.58$\pm$1.13 X & 91.53$\pm$2.09 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast+random & 79.27$\pm$2.09 & 84.1$\pm$2.11 X & 84.2$\pm$0.93 & 91.28$\pm$2.03 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast cheat+random & 75.98$\pm$1.59 & \color{red}{93.42$\pm$0.56 $\bigstar$} & \color{red}{98.89$\pm$0.56 $\bigstar$} & \color{blue}{97.99$\pm$0.82 $\bigstar$} \\
lgrace,enc:gcn bgrl,pred:mlp,random & NaN & NaN & NaN & 89.09$\pm$2.05 X \\
\bottomrule
\end{tabular}

}

,SBM/Important_cora.csv,SBM/Important2_cora.csv,SBM/Important_NS.csv,SBM/Important2_NS.csv
"baseline,enc:gcn bgrl,pred:inner",\color{blue}{85.72$\pm$1.15 $\bigstar$},91.23$\pm$1.31,\color{violet}{89.87$\pm$1.34},\color{violet}{94.27$\pm$1.8}
"baseline,enc:gcn bgrl,pred:mlp",74.33$\pm$1.39 X,88.65$\pm$1.13,81.95$\pm$1.88,94.23$\pm$1.64
"baseline,enc:gcn bgrl,pred:ncn",78.45$\pm$1.8,48.58$\pm$13.99 X,83.41$\pm$1.25,84.27$\pm$8.47 X
"grace,enc:gcn bgrl,pred:mlp,random",\color{violet}{82.88$\pm$1.1},89.39$\pm$1.48,85.6$\pm$1.76,93.83$\pm$2.04
"grace,enc:gcn bgrl,pred:mlp,sbm fast+random",58.3$\pm$3.1 X,90.06$\pm$1.38,79.2$\pm$1.65 X,92.45$\pm$1.08
"grace,enc:gcn bgrl,pred:mlp,sbm fast cheat+random",\color{red}{90.56$\pm$1.16 $\bigstar$},\color{blue}{92.88$\pm$1.13 $\bigstar$},\color{blue}{95.6$\pm$0.85 $\bigstar$},\color{red}{97.99$\pm$1.15 $\bigstar$}
"bgrl,enc:gcn bgrl,pred:mlp,random",81.53$\pm$1.53,\color{violet}{92.3$\pm$1.31 $\bigstar$},80.58$\pm$1.13 X,91.53$\pm$2.09
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast+random",79.27$\pm$2.09,84.1$\pm$2.11 X,84.2$\pm$0.93,91.28$\pm$2.03
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast cheat+random",75.98$\pm$1.59,\color{red}{93.42$\pm$0.56 $\bigstar$},\color{red}{98.89$\pm$0.56 $\bigstar$},\color{blue}{97.99$\pm$0.82 $\bigstar$}
"lgrace,enc:gcn bgrl,pred:mlp,random",NaN,NaN,NaN,89.09$\pm$2.05 X

In [3]:
names = [
    'HP/USAir_res.csv',
    'HP/NS_res.csv',
    'HP/PB_res.csv',
    'HP/Yeast_res.csv',
    'HP/Celegans_res.csv',
    'HP/Power_res.csv',
    'HP/Router_res.csv',
    'HP/Ecoli_res.csv'
]
data, res = ut.mix_dataset(names, 'Hits@50')
data = ut.tex_table(data,res)
data.T

<class 'pandas.core.series.Series'> metrics
Hits@20          [0.84941176 0.87058824 0.80705882 0.83294118 0...
Hits@50          [0.90588235 0.90823529 0.87294118 0.92       0...
Hits@100         [0.94352941 0.93411765 0.93882353 0.95764706 0...
ROCAUC           [0.95338408 0.95022837 0.94849612 0.95899001 0...
AP               [0.96082442 0.96228751 0.95655739 0.96665544 0...
pretrain_time                                                   []
Name: baseline,enc:gcn_ncn,pred:mlp, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.86117647 0.80235294 0.70823529 0.83764706 0...
Hits@50          [0.92235294 0.87764706 0.83529412 0.88941176 0...
Hits@100         [0.95764706 0.92705882 0.92705882 0.92235294 0...
ROCAUC           [0.96032664 0.94667958 0.93026082 0.94280244 0...
AP               [0.96547968 0.95528226 0.93785467 0.95509052 0...
pretrain_time    [7.11123419 7.11418986 7.09919715 7.06552982 7...
Name: grace,enc:gcn_ncn,pred:mlp,random, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.66823529 0.66117647 0.65176471 0.68705882 0...
Hits@50          [0.81411765 0.78588235 0.74823529 0.80705882 0...
Hits@100         [0.88       0.86117647 0.83764706 0.88705882 0...
ROCAUC           [0.91566505 0.89965952 0.89149279 0.91756382 0...
AP               [0.92792776 0.91738517 0.90805165 0.93104996 0...
pretrain_time    [4.97691059 4.99665642 5.01468587 4.96650982 4...
Name: grace,enc:gcn_ncn,pred:mlp,deg, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.84235294 0.82588235 0.77882353 0.80941176 0...
Hits@50          [0.93411765 0.90823529 0.88235294 0.90117647 0...
Hits@100         [0.96470588 0.95058824 0.92941176 0.92941176 0...
ROCAUC           [0.95351142 0.95105882 0.92749168 0.93397891 0...
AP               [0.96528449 0.96208636 0.94851967 0.95417656 0...
pretrain_time    [68.40920067 67.903193   67.77110744 67.851257...
Name: grace,enc:gcn_ncn,pred:mlp,evc, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.85176471 0.82823529 0.75294118 0.85176471 0...
Hits@50          [0.90588235 0.88       0.86823529 0.92705882 0...
Hits@100         [0.94352941 0.94117647 0.91058824 0.94588235 0...
ROCAUC           [0.95480692 0.95022284 0.9422919  0.95796337 0...
AP               [0.96343969 0.96117236 0.95224226 0.96793672 0...
pretrain_time    [3.80977631 3.80299354 3.81623793 3.80779219 3...
Name: grace,enc:gcn_ncn,pred:mlp,pr, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.20941176 0.26588235 0.15294118 0.25176471 0...
Hits@50          [0.44941176 0.57647059 0.32470588 0.56235294 0...
Hits@100         [0.76705882 0.75764706 0.73647059 0.72705882 0...
ROCAUC           [0.81677509 0.83634602 0.78926193 0.81668701 0...
AP               [0.78661203 0.81292032 0.75305876 0.79944861 0...
pretrain_time                                                   []
Name: infomap_prob_pred, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.79764706 0.84470588 0.76941176 0.83529412 0...
Hits@50          [0.90823529 0.90352941 0.85647059 0.90588235 0...
Hits@100         [0.93882353 0.94352941 0.90823529 0.94588235 0...
ROCAUC           [0.95410381 0.95420346 0.93513319 0.95291898 0...
AP               [0.96077716 0.96033234 0.94902341 0.96266913 0...
pretrain_time    [4.92044663 4.92522693 4.97543764 4.98804402 4...
Name: grace,enc:gcn_ncn,pred:mlp,sbm_fast2, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.67294118 0.68235294 0.00470588 0.60705882 0...
Hits@50          [0.77176471 0.79058824 0.00470588 0.81411765 0...
Hits@100         [0.85882353 0.83058824 0.01176471 0.87294118 0...
ROCAUC           [0.90685675 0.87247336 0.17532186 0.90933407 0...
AP               [0.91814958 0.90681383 0.33941621 0.92277606 0...
pretrain_time    [16.74211311 16.74121308 16.77226758 16.727582...
Name: bgrl,enc:gcn_ncn,pred:mlp,random, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.78352941 0.75764706 0.68235294 0.82588235 0...
Hits@50          [0.88470588 0.88       0.83294118 0.91058824 0...
Hits@100         [0.92235294 0.92705882 0.89882353 0.95529412 0...
ROCAUC           [0.94444291 0.94208443 0.92832408 0.95335738 0...
AP               [0.95184942 0.95213221 0.93482445 0.96000183 0...
pretrain_time    [3.82586956 3.82147884 3.99720526 3.87433028 3...
Name: bgrl,enc:gcn_ncn,pred:mlp,deg, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.84235294 0.81176471 0.75294118 0.78117647 0...
Hits@50          [0.88470588 0.89176471 0.86588235 0.88705882 0...
Hits@100         [0.92705882 0.94117647 0.89882353 0.94117647 0...
ROCAUC           [0.94599308 0.94918754 0.9341343  0.94629301 0...
AP               [0.95789031 0.95816717 0.94675649 0.95580706 0...
pretrain_time    [7.14835143 7.14554977 7.20968294 7.20675159 7...
Name: bgrl,enc:gcn_ncn,pred:mlp,evc, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.83058824 0.81882353 0.76941176 0.77882353 0...
Hits@50          [0.92705882 0.91764706 0.86117647 0.86117647 0...
Hits@100         [0.96       0.94823529 0.92235294 0.91294118 0...
ROCAUC           [0.95531626 0.95902007 0.93554384 0.92334073 0...
AP               [0.9601052  0.96389742 0.94940143 0.93665522 0...
pretrain_time    [10.43538094 10.43554974 10.44346261 10.443846...
Name: bgrl,enc:gcn_ncn,pred:mlp,pr, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.20941176 0.26588235 0.15294118 0.25176471 0...
Hits@50          [0.44941176 0.57647059 0.32470588 0.56235294 0...
Hits@100         [0.76705882 0.75764706 0.73647059 0.72705882 0...
ROCAUC           [0.81677509 0.83634602 0.78926193 0.81668701 0...
AP               [0.78661203 0.81292032 0.75305876 0.79944861 0...
pretrain_time                                                   []
Name: leiden_prob_pred, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.79764706 0.76235294 0.68       0.75764706 0...
Hits@50          [0.87058824 0.84705882 0.78823529 0.84235294 0...
Hits@100         [0.92235294 0.90117647 0.87764706 0.90352941 0...
ROCAUC           [0.93988097 0.92750173 0.90586016 0.93155938 0...
AP               [0.94983952 0.94365102 0.92203714 0.94562115 0...
pretrain_time    [29.56888747 30.0624361  29.79607654 29.256180...
Name: bgrl,enc:gcn_ncn,pred:mlp,sbm_fast2, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.83529412 0.83294118 0.78352941 0.8        0...
Hits@50          [0.89882353 0.88941176 0.87529412 0.88470588 0...
Hits@100         [0.93176471 0.93647059 0.93176471 0.93411765 0...
ROCAUC           [0.95257578 0.95584221 0.93450055 0.94937847 0...
AP               [0.96040565 0.96236502 0.9499482  0.95755593 0...
pretrain_time    [39.07920575 39.02566051 39.29232764 39.589688...
Name: lbgrl,enc:gcn_ncn,pred:mlp,random, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.53176471 0.37411765 0.36       0.49411765 0...
Hits@50          [0.71529412 0.61411765 0.62823529 0.68470588 0...
Hits@100         [0.81411765 0.79294118 0.78588235 0.82352941 0...
ROCAUC           [0.8702782  0.83998339 0.84398446 0.87434517 0...
AP               [0.87853271 0.82906823 0.84188397 0.88447383 0...
pretrain_time    [4.41821456 4.44375324 4.42559099 4.39884114 4...
Name: lbgrl,enc:gcn_ncn,pred:mlp,deg, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.68       0.72705882 0.65411765 0.72470588 0...
Hits@50          [0.81647059 0.81882353 0.76941176 0.82352941 0...
Hits@100         [0.86117647 0.85882353 0.84705882 0.88235294 0...
ROCAUC           [0.90754879 0.90711142 0.90440622 0.9113485  0...
AP               [0.92658199 0.92519216 0.91811347 0.93262499 0...
pretrain_time    [72.04226518 70.95878649 71.64848757 71.891476...
Name: lbgrl,enc:gcn_ncn,pred:mlp,evc, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.86352941 0.81176471 0.54117647 0.81411765 0...
Hits@50          [0.93411765 0.90352941 0.69882353 0.89882353 0...
Hits@100         [0.96470588 0.95058824 0.82823529 0.94588235 0...
ROCAUC           [0.9667654  0.95244291 0.86547725 0.95104329 0...
AP               [0.96934135 0.94673565 0.87890691 0.96143568 0...
pretrain_time    [56.68667555 56.79732585 57.6904664  57.280423...
Name: lbgrl,enc:gcn_ncn,pred:mlp,pr, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.20941176 0.26588235 0.15294118 0.25176471 0...
Hits@50          [0.44941176 0.57647059 0.32470588 0.56235294 0...
Hits@100         [0.76705882 0.75764706 0.73647059 0.72705882 0...
ROCAUC           [0.81677509 0.83634602 0.78926193 0.81668701 0...
AP               [0.78661203 0.81292032 0.75305876 0.79944861 0...
pretrain_time                                                   []
Name: louvain_prob_pred, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.80235294 0.76941176 0.74823529 0.79529412 0...
Hits@50          [0.89411765 0.88       0.86352941 0.90117647 0...
Hits@100         [0.92941176 0.93882353 0.90588235 0.94588235 0...
ROCAUC           [0.94923737 0.94967474 0.93597114 0.95212542 0...
AP               [0.95724621 0.9561797  0.94741051 0.95686037 0...
pretrain_time    [10.23771858 10.19402194 10.27339411 10.255838...
Name: lbgrl,enc:gcn_ncn,pred:mlp,sbm_fast2, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.86352941 0.87529412 0.79529412 0.84       0...
Hits@50          [0.94352941 0.92       0.88235294 0.89882353 0...
Hits@100         [0.96       0.94823529 0.90823529 0.92705882 0...
ROCAUC           [0.95245398 0.95277509 0.91418424 0.93195893 0...
AP               [0.96586061 0.96664429 0.94166234 0.95377125 0...
pretrain_time    [17.17030907 17.42856193 24.2781074  17.214909...
Name: lgrace,enc:gcn_ncn,pred:mlp,random, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.85176471 0.88470588 0.81411765 0.85647059 0...
Hits@50          [0.92941176 0.92       0.89647059 0.92       0...
Hits@100         [0.95294118 0.95764706 0.93411765 0.93647059 0...
ROCAUC           [0.95052734 0.96224775 0.94288568 0.95301332 0...
AP               [0.964204   0.97038926 0.95720525 0.9649049  0...
pretrain_time    [21.6983223  21.45916748 23.81302762 21.483457...
Name: lgrace,enc:gcn_ncn,pred:mlp,deg, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.90352941 0.80705882 0.75529412 0.80941176 0...
Hits@50          [0.94117647 0.84941176 0.85882353 0.83529412 0...
Hits@100         [0.96705882 0.89647059 0.91058824 0.88       0...
ROCAUC           [0.97437232 0.93444983 0.92329634 0.92038291 0...
AP               [0.97769503 0.95128631 0.94491411 0.94346408 0...
pretrain_time    [116.07918668 115.32589602 115.82510376 115.24...
Name: lgrace,enc:gcn_ncn,pred:mlp,evc, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.85647059 0.86823529 0.80470588 0.86823529 0...
Hits@50          [0.93176471 0.92       0.91294118 0.93882353 0...
Hits@100         [0.97411765 0.95529412 0.95529412 0.96470588 0...
ROCAUC           [0.96175502 0.96513772 0.9523141  0.96403996 0...
AP               [0.96777335 0.97170659 0.96094223 0.97202795 0...
pretrain_time    [108.19044065 108.06149578 109.04891753 108.16...
Name: lgrace,enc:gcn_ncn,pred:mlp,pr, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.79294118 0.82117647 0.75294118 0.83294118 0...
Hits@50          [0.90588235 0.89647059 0.87294118 0.90588235 0...
Hits@100         [0.95058824 0.94352941 0.93411765 0.94352941 0...
ROCAUC           [0.94666298 0.95202768 0.92605993 0.94874029 0...
AP               [0.95729186 0.96120169 0.93906819 0.96183665 0...
pretrain_time    [56.21734405 55.90955114 56.28932762 55.455359...
Name: lgrace,enc:gcn_ncn,pred:mlp,sbm_fast2, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.77007299 0.7810219  0.79744526 0.74817518 0...
Hits@50          [0.79379562 0.81569343 0.81751825 0.81751825 0...
Hits@100         [0.83029197 0.85036496 0.82846715 0.83394161 0...
ROCAUC           [0.88978502 0.90501958 0.88613538 0.9061884  0...
AP               [0.92655602 0.93324794 0.92640687 0.92924862 0...
pretrain_time                                                   []
Name: baseline,enc:gcn_ncn,pred:mlp, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.78832117 0.83029197 0.81569343 0.79562044 0...
Hits@50          [0.83394161 0.89051095 0.85218978 0.83211679 0...
Hits@100         [0.88868613 0.93065693 0.90328467 0.92335766 0...
ROCAUC           [0.94094318 0.95969085 0.94420321 0.94892842 0...
AP               [0.95537609 0.9693035  0.95973507 0.96019566 0...
pretrain_time    [76.72235918 77.00197649 76.68982697 76.560665...
Name: grace,enc:gcn_ncn,pred:mlp,random, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.76642336 0.76824818 0.7919708  0.79014599 0...
Hits@50          [0.80109489 0.84124088 0.80109489 0.81021898 0...
Hits@100         [0.84671533 0.91605839 0.87773723 0.87226277 0...
ROCAUC           [0.91802973 0.94037042 0.92948146 0.93080012 0...
AP               [0.93937897 0.94800753 0.94821712 0.9475601  0...
pretrain_time    [61.33855939 61.6322639  64.78356957 61.455577...
Name: grace,enc:gcn_ncn,pred:mlp,deg, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.60218978 0.55474453 0.70620438 0.70620438 0...
Hits@50          [0.77007299 0.80474453 0.7919708  0.79562044 0...
Hits@100         [0.8540146  0.84306569 0.86313869 0.84489051 0...
ROCAUC           [0.89949185 0.9031215  0.91038081 0.91060059 0...
AP               [0.91455521 0.90488173 0.92903214 0.92921563 0...
pretrain_time    [12.85766959 11.55088663 11.59554315 11.543675...
Name: grace,enc:gcn_ncn,pred:mlp,evc, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.77372263 0.80474453 0.83029197 0.7919708  0...
Hits@50          [0.79927007 0.82116788 0.86131387 0.80109489 0...
Hits@100         [0.88321168 0.8649635  0.89233577 0.84671533 0...
ROCAUC           [0.93101324 0.93409345 0.94450956 0.90284179 0...
AP               [0.94868344 0.95184399 0.95925675 0.92563542 0...
pretrain_time    [6.78623843 6.82641149 6.80178666 7.03804493 6...
Name: grace,enc:gcn_ncn,pred:mlp,pr, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.76824818 0.80291971 0.80291971 0.80656934 0...
Hits@50          [0.79562044 0.81934307 0.81569343 0.80839416 0...
Hits@100         [0.81934307 0.83394161 0.84306569 0.82846715 0...
ROCAUC           [0.8887161  0.89534605 0.90343785 0.89500306 0...
AP               [0.92666049 0.93261462 0.93727348 0.9315177  0...
pretrain_time                                                   []
Name: infomap_prob_pred, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.74270073 0.63868613 0.69160584 0.72262774 0...
Hits@50          [0.80656934 0.78284672 0.77919708 0.79379562 0...
Hits@100         [0.8649635  0.82481752 0.85036496 0.84854015 0...
ROCAUC           [0.92235535 0.9128583  0.91734043 0.92449651 0...
AP               [0.93632238 0.91731691 0.9268523  0.93628458 0...
pretrain_time    [82.62638974 83.18206811 82.71928501 82.849843...
Name: grace,enc:gcn_ncn,pred:mlp,sbm_fast2, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.68978102 0.6459854  0.70437956 0.76094891 0...
Hits@50          [0.76459854 0.7919708  0.76824818 0.80291971 0...
Hits@100         [0.8229927  0.85766423 0.84306569 0.84124088 0...
ROCAUC           [0.90007459 0.91924849 0.91670441 0.91118    0...
AP               [0.91885119 0.92543174 0.92783218 0.93185118 0...
pretrain_time    [72.76202321 72.4698503  72.6021204  72.783021...
Name: bgrl,enc:gcn_ncn,pred:mlp,random, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.78467153 0.82116788 0.8120438  0.80839416 0...
Hits@50          [0.81569343 0.85948905 0.84489051 0.84489051 0...
Hits@100         [0.87408759 0.91240876 0.89781022 0.87591241 0...
ROCAUC           [0.93384371 0.95145586 0.93850232 0.93553199 0...
AP               [0.95057849 0.96324928 0.95623715 0.95271596 0...
pretrain_time    [90.70360684 90.32996774 91.32693505 89.966617...
Name: bgrl,enc:gcn_ncn,pred:mlp,deg, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.76459854 0.79744526 0.80109489 0.80109489 0...
Hits@50          [0.79744526 0.83029197 0.80839416 0.82664234 0...
Hits@100         [0.84854015 0.86313869 0.85218978 0.8540146  0...
ROCAUC           [0.92255181 0.93325763 0.9347994  0.92887541 0...
AP               [0.94285953 0.95169003 0.95082281 0.94876398 0...
pretrain_time    [70.11602712 70.03831387 68.96316504 69.826060...
Name: bgrl,enc:gcn_ncn,pred:mlp,evc, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.77007299 0.         0.         0.         0...
Hits@50          [0.81386861 0.         0.         0.         0...
Hits@100         [0.87591241 0.         0.         0.         0...
ROCAUC           [0.93932149 0.72445255 0.70678546 0.5        0...
AP               [0.95301758 0.66412038 0.6534687  0.5        0...
pretrain_time    [87.83716249 88.04819846 87.98472548 88.896777...
Name: bgrl,enc:gcn_ncn,pred:mlp,pr, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.76824818 0.80291971 0.80291971 0.80656934 0...
Hits@50          [0.79562044 0.81934307 0.81569343 0.80839416 0...
Hits@100         [0.81934307 0.83394161 0.84306569 0.82846715 0...
ROCAUC           [0.8887161  0.89534605 0.90343785 0.89500306 0...
AP               [0.92666049 0.93261462 0.93727348 0.9315177  0...
pretrain_time                                                   []
Name: louvain_prob_pred, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.77554745 0.79379562 0.79744526 0.80656934 0...
Hits@50          [0.78649635 0.82116788 0.8229927  0.81934307 0...
Hits@100         [0.81569343 0.84306569 0.83211679 0.82846715 0...
ROCAUC           [0.86855486 0.8847035  0.88472681 0.87784878 0...
AP               [0.91349979 0.9193098  0.92793774 0.9220816  0...
pretrain_time    [35.23070049 35.16413879 35.49470115 35.563882...
Name: bgrl,enc:gcn_ncn,pred:mlp,sbm_fast2, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.76459854 0.78832117 0.69708029 0.79379562 0...
Hits@50          [0.78832117 0.82481752 0.77554745 0.82664234 0...
Hits@100         [0.82846715 0.85583942 0.83759124 0.85583942 0...
ROCAUC           [0.90158639 0.91007113 0.9033213  0.91919189 0...
AP               [0.93135737 0.9383056  0.9264196  0.94173198 0...
pretrain_time    [24.54695964 24.5631938  26.48835063 24.346870...
Name: lbgrl,enc:gcn_ncn,pred:mlp,random, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.75912409 0.80474453 0.78832117 0.80474453 0...
Hits@50          [0.76642336 0.80839416 0.79379562 0.81021898 0...
Hits@100         [0.79562044 0.81751825 0.80839416 0.81569343 0...
ROCAUC           [0.89141004 0.91369745 0.90833955 0.89942192 0...
AP               [0.92255761 0.93604817 0.93304151 0.92763677 0...
pretrain_time    [46.95190787 46.70081425 46.76741004 47.465237...
Name: lbgrl,enc:gcn_ncn,pred:mlp,deg, dtype: object
<class 'pandas.core.series.Series'> metrics
Hits@20          [0.78649635 0.79014599 0.57664234 0.80109489 0...
Hits@50          [0.82116788 0.84489051 0.74817518 0.84489051 0...
Hits@100         [0.8540146  0.86678832 0.84489051 0.86861314 0...
ROCAUC           [0.9422402  0.94658413 0.91221895 0.93882532 0...
AP               [0.95388323 0.95613624 0.90669016 0.95354299 0...
pretrain_time    [77.69921207 78.12269092 77.75472403 78.320277...
Name: lbgrl,enc:gcn_ncn,pred:mlp,evc, dtype: object
<class 'pandas.core.series.Series'> metrics

,HP/USAir_res.csv,HP/NS_res.csv,HP/PB_res.csv,HP/Yeast_res.csv,HP/Celegans_res.csv,HP/Power_res.csv,HP/Router_res.csv,HP/Ecoli_res.csv
"baseline,enc:gcn ncn,pred:mlp",88.64$\pm$2.61,80.93$\pm$0.91,\color{blue}{51.57$\pm$3.08 $\bigstar$},84.1$\pm$0.8,51.56$\pm$28.47,21.96$\pm$3.65,52.67$\pm$2.86,\color{red}{86.01$\pm$0.88 $\bigstar$}
"grace,enc:gcn ncn,pred:mlp,random",88.12$\pm$2.32,\color{red}{84.27$\pm$2.12 $\bigstar$},46.47$\pm$2.74,82.41$\pm$0.84,70.23$\pm$3.41,33.73$\pm$1.71,46.57$\pm$3.84,83.26$\pm$0.98
"grace,enc:gcn ncn,pred:mlp,deg",78.33$\pm$3.61,82.28$\pm$1.79,48.08$\pm$3.39,75.24$\pm$4.48,67.18$\pm$3.85,35.28$\pm$1.28,50.59$\pm$3.62,77.78$\pm$1.14
"grace,enc:gcn ncn,pred:mlp,evc",89.84$\pm$2.1,77.99$\pm$1.67,\color{red}{53.61$\pm$3.11 $\bigstar$},83.5$\pm$0.77,69.39$\pm$3.75,\color{red}{36.71$\pm$1.96 $\bigstar$},31.67$\pm$12.82,82.92$\pm$1.09
"grace,enc:gcn ncn,pred:mlp,pr",89.2$\pm$2.7,\color{violet}{83.07$\pm$2.3},43.38$\pm$15.35,82.29$\pm$1.0,70.3$\pm$3.68,26.89$\pm$9.25,52.87$\pm$3.67,81.86$\pm$0.98
infomap prob pred,47.15$\pm$10.78 X,81.02$\pm$0.93,5.23$\pm$1.06 X,71.83$\pm$1.52,35.06$\pm$4.98 X,NaN,22.81$\pm$1.1 X,42.82$\pm$1.33 X
"grace,enc:gcn ncn,pred:mlp,sbm fast2",88.73$\pm$2.51,79.67$\pm$1.64,44.8$\pm$2.25,74.12$\pm$3.15,60.98$\pm$2.74,\color{blue}{36.28$\pm$1.53 $\bigstar$},41.17$\pm$7.99,80.0$\pm$1.35
"bgrl,enc:gcn ncn,pred:mlp,random",70.28$\pm$23.37,77.79$\pm$1.92,44.07$\pm$6.41,83.3$\pm$0.8,60.84$\pm$1.84,24.77$\pm$1.66,51.56$\pm$4.1,81.79$\pm$0.92
"bgrl,enc:gcn ncn,pred:mlp,deg",85.44$\pm$3.46,\color{blue}{83.28$\pm$1.62 $\bigstar$},44.52$\pm$2.9,76.67$\pm$7.02,64.29$\pm$6.21,25.03$\pm$5.68,52.37$\pm$3.66,80.32$\pm$3.81
"bgrl,enc:gcn ncn,pred:mlp,evc",88.31$\pm$2.51,81.35$\pm$1.43,45.88$\pm$3.45,82.33$\pm$0.81,65.69$\pm$4.82,26.3$\pm$0.94,32.6$\pm$26.78,76.02$\pm$1.26
"bgrl,enc:gcn ncn,pred:mlp,pr",89.2$\pm$2.77,21.09$\pm$33.58 X,49.89$\pm$2.8,\color{violet}{84.55$\pm$0.58 $\bigstar$},63.99$\pm$4.38,25.99$\pm$1.67,51.1$\pm$4.59,81.94$\pm$1.09
leiden prob pred,47.15$\pm$10.78 X,NaN,5.23$\pm$1.06 X,NaN,NaN,33.85$\pm$1.48,22.81$\pm$1.1 X,NaN
"bgrl,enc:gcn ncn,pred:mlp,sbm fast2",81.79$\pm$3.91,81.41$\pm$1.13,45.52$\pm$2.53,80.43$\pm$1.58,57.86$\pm$4.03,\color{violet}{36.18$\pm$1.37 $\bigstar$},\color{blue}{53.74$\pm$3.17 $\bigstar$},73.44$\pm$6.0
"lbgrl,enc:gcn ncn,pred:mlp,random",88.71$\pm$2.09,76.51$\pm$6.89,45.97$\pm$3.22,77.71$\pm$1.46,68.67$\pm$3.72,28.56$\pm$1.46,52.03$\pm$3.22,80.56$\pm$0.74
"lbgrl,enc:gcn ncn,pred:mlp,deg",64.87$\pm$4.44,79.12$\pm$1.37,44.28$\pm$3.4,74.47$\pm$7.02,57.02$\pm$4.1,27.7$\pm$2.28,42.03$\pm$8.95,79.45$\pm$1.32
"lbgrl,enc:gcn ncn,pred:mlp,evc",80.38$\pm$4.55,70.97$\pm$17.73,44.79$\pm$2.76,68.34$\pm$2.69 X,57.32$\pm$6.35,24.51$\pm$1.7,52.78$\pm$3.45,78.82$\pm$1.45
"lbgrl,enc:gcn ncn,pred:mlp,pr",88.73$\pm$6.4,69.56$\pm$24.24,41.11$\pm$8.38,80.47$\pm$0.85,57.3$\pm$5.85,25.3$\pm$1.02,\color{red}{53.96$\pm$3.53 $\bigstar$},78.25$\pm$1.08
louvain prob pred,47.15$\pm$10.78 X,81.02$\pm$0.93,5.23$\pm$1.06 X,71.83$\pm$1.52,35.06$\pm$4.98 X,33.85$\pm$1.48,22.81$\pm$1.1 X,NaN
"lbgrl,enc:gcn ncn,pred:mlp,sbm fast2",87.95$\pm$2.12,80.49$\pm$1.28,45.81$\pm$2.4,62.96$\pm$1.99 X,60.42$\pm$3.57,3.0$\pm$8.24 X,52.54$\pm$3.9,76.88$\pm$3.42
"lgrace,enc:gcn ncn,pred:mlp,random",89.95$\pm$2.13,53.67$\pm$32.47 X,44.58$\pm$8.37,76.88$\pm$25.63 $\bigstar$,68.21$\pm$7.37,32.58$\pm$1.96,29.14$\pm$18.37,83.88$\pm$1.11
"lgrace,enc:gcn ncn,pred:mlp,deg",\color{blue}{91.36$\pm$1.78 $\bigstar$},82.65$\pm$1.13,47.91$\pm$1.96,75.76$\pm$10.01,\color{blue}{71.4$\pm$2.93 $\bigstar$},33.17$\pm$2.36,50.64$\pm$4.15,82.98$\pm$0.94
"lgrace,enc:gcn ncn,pred:mlp,evc",\color{violet}{90.21$\pm$4.01},64.95$\pm$32.54,\color{violet}{50.0$\pm$3.68},\color{red}{84.95$\pm$0.54 $\bigstar$},\color{violet}{70.79$\pm$2.56},32.71$\pm$2.49,51.21$\pm$3.19,\color{violet}{84.3$\pm$0.96}
"lgrace,enc:gcn ncn,pred:mlp,pr",\color{red}{92.0$\pm$2.13 $\bigstar$},78.34$\pm$1.48,46.83$\pm$3.04,\color{blue}{84.61$\pm$0.57 $\bigstar$},\color{red}{73.03$\pm$3.04 $\bigstar$},25.39$\pm$1.98,42.9$\pm$14.39,\color{blue}{85.96$\pm$0.71 $\bigstar$}
"lgrace,enc:gcn ncn,pred:mlp,sbm fast2",88.75$\pm$2.62,73.49$\pm$10.8,43.92$\pm$2.78,80.35$\pm$1.77,60.72$\pm$4.46,30.34$\pm$10.28,\color{violet}{53.16$\pm$2.81},82.61$\pm$0.82

In [4]:
data1 = ut.res_load('HP/L_pubmed.csv')
data2 = ut.res_load('HP/pubmed_res.csv')
data2 = data2.T.join(data1.T)
data2.to_csv('HP/pubmed_res.csv', sep=';')

ValueError: columns overlap but no suffix specified: Index(['lbgrl,enc:gcn_ncn,pred:mlp,random_mean',
       'lbgrl,enc:gcn_ncn,pred:mlp,random',
       'lbgrl,enc:gcn_ncn,pred:mlp,deg_mean', 'lbgrl,enc:gcn_ncn,pred:mlp,deg',
       'lbgrl,enc:gcn_ncn,pred:mlp,evc_mean', 'lbgrl,enc:gcn_ncn,pred:mlp,evc',
       'lbgrl,enc:gcn_ncn,pred:mlp,pr_mean', 'lbgrl,enc:gcn_ncn,pred:mlp,pr'],
      dtype='object')

In [ ]:
names = [
    'HP/cora_res.csv',
    'HP/citeseer_res.csv',
    'HP/pubmed_res.csv'
]
data, res = ut.mix_dataset(names, 'Hits@100')
data = ut.tex_table(data,res)
display(data.T)

\resizebox{\textwidth}{!}{
\begin{tabular}{llll}
\toprule
 & HP/cora_res.csv & HP/citeseer_res.csv & HP/pubmed_res.csv \\
\midrule
baseline,enc:gcn ncn,pred:mlp & \color{violet}{85.74$\pm$0.95} & 85.66$\pm$2.07 & \color{red}{81.38$\pm$1.66 $\bigstar$} \\
grace,enc:gcn ncn,pred:mlp,random & 84.04$\pm$0.76 & 89.56$\pm$1.55 & 75.06$\pm$1.22 \\
grace,enc:gcn ncn,pred:mlp,deg & 84.31$\pm$2.6 & 90.22$\pm$0.98 & 75.36$\pm$1.67 \\
grace,enc:gcn ncn,pred:mlp,evc & \color{red}{87.1$\pm$1.76 $\bigstar$} & \color{red}{92.66$\pm$1.28 $\bigstar$} & 75.85$\pm$2.05 \\
grace,enc:gcn ncn,pred:mlp,pr & 84.63$\pm$1.54 & \color{blue}{90.3$\pm$1.03} & \color{violet}{79.88$\pm$1.66} \\
bgrl,enc:gcn ncn,pred:mlp,random & 84.33$\pm$1.29 & 87.99$\pm$2.26 & 72.81$\pm$2.49 \\
bgrl,enc:gcn ncn,pred:mlp,deg & 76.12$\pm$1.52 X & 85.66$\pm$17.82 & 75.35$\pm$1.69 \\
bgrl,enc:gcn ncn,pred:mlp,evc & 84.69$\pm$1.0 & 88.69$\pm$1.59 & 78.04$\pm$1.06 \\
bgrl,enc:gcn ncn,pred:mlp,pr & 84.5$\pm$0.94 & 78.52$\pm$21.32 & 69.59$\pm$1.96 X \\
lbgrl,enc:gcn ncn,pred:mlp,random & 83.29$\pm$1.55 & 64.02$\pm$9.23 X & 75.71$\pm$1.44 \\
lbgrl,enc:gcn ncn,pred:mlp,deg & 83.19$\pm$3.41 & 82.62$\pm$3.37 & \color{blue}{80.32$\pm$1.25 $\bigstar$} \\
lbgrl,enc:gcn ncn,pred:mlp,evc & 81.7$\pm$1.8 & 82.05$\pm$2.38 & 73.77$\pm$1.08 \\
lbgrl,enc:gcn ncn,pred:mlp,pr & 76.57$\pm$7.23 X & 81.8$\pm$10.84 & 78.83$\pm$1.83 \\
lgrace,enc:gcn ncn,pred:mlp,random & 83.07$\pm$1.32 & 82.41$\pm$15.21 & NaN \\
lgrace,enc:gcn ncn,pred:mlp,deg & 79.36$\pm$7.14 & 78.0$\pm$7.32 & NaN \\
lgrace,enc:gcn ncn,pred:mlp,evc & 84.8$\pm$1.96 & \color{violet}{90.26$\pm$1.52} & NaN \\
lgrace,enc:gcn ncn,pred:mlp,pr & \color{blue}{86.93$\pm$1.34 $\bigstar$} & 87.66$\pm$11.02 & NaN \\
\bottomrule
\end{tabular}

}

,HP/cora_res.csv,HP/citeseer_res.csv,HP/pubmed_res.csv
"baseline,enc:gcn ncn,pred:mlp",\color{violet}{85.74$\pm$0.95},85.66$\pm$2.07,\color{red}{81.38$\pm$1.66 $\bigstar$}
"grace,enc:gcn ncn,pred:mlp,random",84.04$\pm$0.76,89.56$\pm$1.55,75.06$\pm$1.22
"grace,enc:gcn ncn,pred:mlp,deg",84.31$\pm$2.6,90.22$\pm$0.98,75.36$\pm$1.67
"grace,enc:gcn ncn,pred:mlp,evc",\color{red}{87.1$\pm$1.76 $\bigstar$},\color{red}{92.66$\pm$1.28 $\bigstar$},75.85$\pm$2.05
"grace,enc:gcn ncn,pred:mlp,pr",84.63$\pm$1.54,\color{blue}{90.3$\pm$1.03},\color{violet}{79.88$\pm$1.66}
"bgrl,enc:gcn ncn,pred:mlp,random",84.33$\pm$1.29,87.99$\pm$2.26,72.81$\pm$2.49
"bgrl,enc:gcn ncn,pred:mlp,deg",76.12$\pm$1.52 X,85.66$\pm$17.82,75.35$\pm$1.69
"bgrl,enc:gcn ncn,pred:mlp,evc",84.69$\pm$1.0,88.69$\pm$1.59,78.04$\pm$1.06
"bgrl,enc:gcn ncn,pred:mlp,pr",84.5$\pm$0.94,78.52$\pm$21.32,69.59$\pm$1.96 X
"lbgrl,enc:gcn ncn,pred:mlp,random",83.29$\pm$1.55,64.02$\pm$9.23 X,75.71$\pm$1.44
"lbgrl,enc:gcn ncn,pred:mlp,deg",83.19$\pm$3.41,82.62$\pm$3.37,\color{blue}{80.32$\pm$1.25 $\bigstar$}
"lbgrl,enc:gcn ncn,pred:mlp,evc",81.7$\pm$1.8,82.05$\pm$2.38,73.77$\pm$1.08
"lbgrl,enc:gcn ncn,pred:mlp,pr",76.57$\pm$7.23 X,81.8$\pm$10.84,78.83$\pm$1.83
"lgrace,enc:gcn ncn,pred:mlp,random",83.07$\pm$1.32,82.41$\pm$15.21,NaN
"lgrace,enc:gcn ncn,pred:mlp,deg",79.36$\pm$7.14,78.0$\pm$7.32,NaN
"lgrace,enc:gcn ncn,pred:mlp,evc",84.8$\pm$1.96,\color{violet}{90.26$\pm$1.52},NaN
"lgrace,enc:gcn ncn,pred:mlp,pr",\color{blue}{86.93$\pm$1.34 $\bigstar$},87.66$\pm$11.02,NaN

In [ ]:
names = [
    'HP_SBM/_Celegans.csv',
    'HP_SBM/_USAir.csv'
]
data, res = ut.mix_dataset(names, 'Hits@50')
data = ut.tex_table(data,res)
display(data.T)

\resizebox{\textwidth}{!}{
\begin{tabular}{lll}
\toprule
 & HP_SBM/_Celegans.csv & HP_SBM/_USAir.csv \\
\midrule
louvain prob pred & 32.28$\pm$3.88 X & 47.18$\pm$5.16 X \\
grace,enc:gcn ncn,pred:mlp,sbm & 64.78$\pm$4.89 & 90.02$\pm$2.26 \\
grace,enc:gcn ncn,pred:mlp,sbm+random & 67.74$\pm$2.38 $\bigstar$ & 86.16$\pm$3.96 \\
grace,enc:gcn ncn,pred:mlp,sbm+deg & 65.94$\pm$4.76 & \color{red}{92.33$\pm$1.62 $\bigstar$} \\
grace,enc:gcn ncn,pred:mlp,sbm+evc & \color{red}{70.51$\pm$2.72 $\bigstar$} & 87.27$\pm$2.53 \\
grace,enc:gcn ncn,pred:mlp,sbm+pr & \color{blue}{68.23$\pm$3.54 $\bigstar$} & \color{violet}{90.75$\pm$2.05 $\bigstar$} \\
bgrl,enc:gcn ncn,pred:mlp,sbm & 57.48$\pm$3.33 & 80.47$\pm$3.32 \\
bgrl,enc:gcn ncn,pred:mlp,sbm+random & 54.57$\pm$6.23 & 88.19$\pm$2.18 \\
bgrl,enc:gcn ncn,pred:mlp,sbm+deg & 57.39$\pm$4.86 & \color{blue}{91.93$\pm$2.26 $\bigstar$} \\
bgrl,enc:gcn ncn,pred:mlp,sbm+evc & 63.8$\pm$4.16 & 76.59$\pm$4.02 \\
bgrl,enc:gcn ncn,pred:mlp,sbm+pr & \color{violet}{67.79$\pm$5.1 $\bigstar$} & 75.6$\pm$3.63 \\
lbgrl,enc:gcn ncn,pred:mlp,sbm & 42.19$\pm$3.06 X & 77.67$\pm$4.3 \\
lbgrl,enc:gcn ncn,pred:mlp,sbm+random & 54.48$\pm$4.32 & 83.51$\pm$2.62 \\
lbgrl,enc:gcn ncn,pred:mlp,sbm+deg & 55.59$\pm$3.45 & 77.79$\pm$3.6 \\
lbgrl,enc:gcn ncn,pred:mlp,sbm+evc & 46.83$\pm$3.25 & 85.84$\pm$3.1 \\
lbgrl,enc:gcn ncn,pred:mlp,sbm+pr & 56.57$\pm$6.14 & 82.96$\pm$3.4 \\
\bottomrule
\end{tabular}

}

,HP_SBM/_Celegans.csv,HP_SBM/_USAir.csv
louvain prob pred,32.28$\pm$3.88 X,47.18$\pm$5.16 X
"grace,enc:gcn ncn,pred:mlp,sbm",64.78$\pm$4.89,90.02$\pm$2.26
"grace,enc:gcn ncn,pred:mlp,sbm+random",67.74$\pm$2.38 $\bigstar$,86.16$\pm$3.96
"grace,enc:gcn ncn,pred:mlp,sbm+deg",65.94$\pm$4.76,\color{red}{92.33$\pm$1.62 $\bigstar$}
"grace,enc:gcn ncn,pred:mlp,sbm+evc",\color{red}{70.51$\pm$2.72 $\bigstar$},87.27$\pm$2.53
"grace,enc:gcn ncn,pred:mlp,sbm+pr",\color{blue}{68.23$\pm$3.54 $\bigstar$},\color{violet}{90.75$\pm$2.05 $\bigstar$}
"bgrl,enc:gcn ncn,pred:mlp,sbm",57.48$\pm$3.33,80.47$\pm$3.32
"bgrl,enc:gcn ncn,pred:mlp,sbm+random",54.57$\pm$6.23,88.19$\pm$2.18
"bgrl,enc:gcn ncn,pred:mlp,sbm+deg",57.39$\pm$4.86,\color{blue}{91.93$\pm$2.26 $\bigstar$}
"bgrl,enc:gcn ncn,pred:mlp,sbm+evc",63.8$\pm$4.16,76.59$\pm$4.02
"bgrl,enc:gcn ncn,pred:mlp,sbm+pr",\color{violet}{67.79$\pm$5.1 $\bigstar$},75.6$\pm$3.63
"lbgrl,enc:gcn ncn,pred:mlp,sbm",42.19$\pm$3.06 X,77.67$\pm$4.3
"lbgrl,enc:gcn ncn,pred:mlp,sbm+random",54.48$\pm$4.32,83.51$\pm$2.62
"lbgrl,enc:gcn ncn,pred:mlp,sbm+deg",55.59$\pm$3.45,77.79$\pm$3.6
"lbgrl,enc:gcn ncn,pred:mlp,sbm+evc",46.83$\pm$3.25,85.84$\pm$3.1
"lbgrl,enc:gcn ncn,pred:mlp,sbm+pr",56.57$\pm$6.14,82.96$\pm$3.4

In [6]:
names = [
    'HP_SBM/Final_citeseer.csv',
    'HP_SBM/Final_cora.csv',
    'HP_SBM/Final_USAir.csv',
    'HP_SBM/Final_NS.csv',
    'HP_SBM/Final_PB.csv',
    'HP_SBM/Final_Yeast.csv',
    'HP_SBM/Final_Celegans.csv',
    'HP_SBM/Important3_power.csv',
    'HP_SBM/Final_Router.csv',
    'HP_SBM/Final_Ecoli.csv',
    ]
data, res = ut.mix_dataset(names, 'Hits@50', filtre2=['kmeans'])
data = ut.tex_table(data,res)
display(data.T)

\resizebox{\textwidth}{!}{
\begin{tabular}{lllllllllll}
\toprule
 & HP_SBM/Final_citeseer.csv & HP_SBM/Final_cora.csv & HP_SBM/Final_USAir.csv & HP_SBM/Final_NS.csv & HP_SBM/Final_PB.csv & HP_SBM/Final_Yeast.csv & HP_SBM/Final_Celegans.csv & HP_SBM/Important3_power.csv & HP_SBM/Final_Router.csv & HP_SBM/Final_Ecoli.csv \\
\midrule
louvain prob pred & 50.24$\pm$1.59 X & 52.83$\pm$1.21 X & 47.41$\pm$4.42 X & 80.71$\pm$0.99 & 4.44$\pm$0.69 X & 62.04$\pm$3.76 X & 34.99$\pm$5.17 X & 33.69$\pm$1.47 & 21.91$\pm$1.42 X & 36.44$\pm$1.02 X \\
grace,enc:gcn bgrl,pred:mlp,sbm+random & 63.01$\pm$1.83 X & 67.97$\pm$1.48 & 89.6$\pm$2.17 & \color{red}{91.48$\pm$1.26 $\bigstar$} & \color{red}{47.95$\pm$3.38 $\bigstar$} & 76.07$\pm$1.88 & 68.16$\pm$4.08 & \color{red}{59.58$\pm$2.24 $\bigstar$} & \color{blue}{49.61$\pm$1.03 $\bigstar$} & 79.1$\pm$1.19 \\
grace,enc:gcn bgrl,pred:mlp,sbm fix+random & 66.9$\pm$1.99 & 61.73$\pm$1.6 & 89.76$\pm$2.15 & 80.27$\pm$1.28 X & 46.89$\pm$3.87 & 70.85$\pm$2.79 & 60.7$\pm$3.24 & 36.02$\pm$1.79 & 27.15$\pm$1.01 & 77.07$\pm$1.42 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast+random & 66.99$\pm$1.35 & 62.02$\pm$1.1 X & 89.98$\pm$1.95 & 80.69$\pm$1.5 & \color{violet}{47.8$\pm$2.55 $\bigstar$} & 71.7$\pm$2.73 & 63.45$\pm$3.41 & \color{violet}{36.21$\pm$1.22} & 26.95$\pm$1.22 & 78.55$\pm$1.03 \\
grace,enc:gcn bgrl,pred:mlp,sbm fast bug+random & 75.44$\pm$1.0 & \color{red}{74.46$\pm$1.35 $\bigstar$} & 90.26$\pm$2.44 & \color{blue}{90.77$\pm$1.15 $\bigstar$} & \color{blue}{47.94$\pm$2.88 $\bigstar$} & \color{violet}{79.69$\pm$1.14} & 69.42$\pm$4.2 & \color{blue}{52.06$\pm$3.03 $\bigstar$} & \color{red}{50.3$\pm$2.2 $\bigstar$} & 78.19$\pm$1.69 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm+random & 68.9$\pm$2.54 & 68.98$\pm$1.52 & 88.71$\pm$2.61 & \color{violet}{88.5$\pm$1.03} & 45.69$\pm$2.24 & 75.66$\pm$2.58 & 67.37$\pm$3.64 & 20.84$\pm$1.56 X & 35.17$\pm$2.14 & 77.73$\pm$1.84 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fix+random & 67.58$\pm$2.08 & 68.07$\pm$1.21 & 90.05$\pm$1.85 & 80.6$\pm$1.07 X & 42.22$\pm$2.96 & 75.23$\pm$2.41 & 58.67$\pm$4.53 & 23.2$\pm$1.13 & 25.66$\pm$0.69 & 77.8$\pm$1.0 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast+random & 67.53$\pm$1.65 & 68.03$\pm$1.08 & 90.75$\pm$1.99 & 80.78$\pm$1.07 & 43.58$\pm$2.98 & 75.06$\pm$2.04 & 62.54$\pm$4.28 & 23.07$\pm$0.99 & 25.69$\pm$0.79 & 77.67$\pm$1.67 \\
bgrl,enc:gcn bgrl,pred:mlp,sbm fast bug+random & 70.05$\pm$1.44 & 68.59$\pm$2.03 & 89.95$\pm$1.47 & 82.96$\pm$1.02 & 45.95$\pm$3.18 & 77.14$\pm$1.61 & 69.79$\pm$3.92 & 19.28$\pm$1.03 X & 37.35$\pm$1.58 & 77.81$\pm$1.38 \\
lgrace,enc:gcn bgrl,pred:mlp,sbm+random & 73.7$\pm$2.81 & 68.06$\pm$1.18 & 91.18$\pm$1.74 & 86.35$\pm$1.46 & 46.41$\pm$4.53 & \color{blue}{81.81$\pm$1.07 $\bigstar$} & \color{red}{72.17$\pm$3.01 $\bigstar$} & 27.12$\pm$2.15 & 32.29$\pm$2.92 & \color{red}{80.78$\pm$1.28 $\bigstar$} \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fix+random & \color{violet}{77.55$\pm$1.81 $\bigstar$} & \color{violet}{72.46$\pm$1.1} & \color{violet}{91.22$\pm$1.79 $\bigstar$} & 81.11$\pm$1.3 & 46.03$\pm$2.85 & 78.06$\pm$2.4 & 68.81$\pm$3.9 & 29.63$\pm$1.33 & 27.83$\pm$1.46 & 80.19$\pm$0.78 \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast+random & \color{blue}{79.14$\pm$2.69 $\bigstar$} & \color{blue}{73.11$\pm$1.28 $\bigstar$} & \color{blue}{91.44$\pm$2.31 $\bigstar$} & 80.78$\pm$1.0 & 45.86$\pm$2.33 & 78.93$\pm$1.75 & \color{violet}{70.63$\pm$4.22 $\bigstar$} & 30.69$\pm$2.27 & 27.17$\pm$2.12 & \color{violet}{80.46$\pm$0.73 $\bigstar$} \\
lgrace,enc:gcn bgrl,pred:mlp,sbm fast bug+random & \color{red}{79.18$\pm$2.14 $\bigstar$} & 69.89$\pm$2.23 & \color{red}{91.51$\pm$1.68 $\bigstar$} & 82.63$\pm$1.18 & 47.16$\pm$3.41 & \color{red}{82.27$\pm$1.13 $\bigstar$} & \color{blue}{71.45$\pm$2.45 $\bigstar$} & 23.81$\pm$1.28 & 31.09$\pm$3.42 & \color{blue}{80.65$\pm$0.88 $\bigstar$} \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm+random & 67.37$\pm$2.02 & 65.55$\pm$1.53 & 89.34$\pm$2.3 & 84.78$\pm$1.83 & 45.34$\pm$3.1 & 76.93$\pm$2.23 & 66.41$\pm$3.73 & 23.25$\pm$1.73 & 38.81$\pm$1.16 & 79.44$\pm$0.85 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fix+random & 72.24$\pm$1.75 & 68.6$\pm$2.07 & 90.78$\pm$2.09 & 80.53$\pm$1.54 X & 44.59$\pm$2.96 & 73.55$\pm$2.36 & 63.59$\pm$3.24 & 30.52$\pm$1.24 & 29.74$\pm$1.5 & 76.93$\pm$1.04 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fast+random & 73.3$\pm$1.95 & 69.9$\pm$2.09 & 90.92$\pm$2.04 & 80.31$\pm$1.15 X & 43.96$\pm$3.38 & 73.9$\pm$2.05 & 65.87$\pm$5.56 & 30.95$\pm$1.04 & 29.92$\pm$0.97 & 77.33$\pm$1.03 \\
lbgrl,enc:gcn bgrl,pred:mlp,sbm fast bug+random & 73.41$\pm$2.62 & 66.35$\pm$2.69 & 91.22$\pm$1.44 $\bigstar$ & 82.39$\pm$0.9 & 45.57$\pm$2.6 & 78.67$\pm$1.28 & 70.35$\pm$3.37 $\bigstar$ & 24.76$\pm$3.16 & \color{violet}{39.35$\pm$2.19} & 79.05$\pm$0.97 \\
\bottomrule
\end{tabular}

}

,HP_SBM/Final_citeseer.csv,HP_SBM/Final_cora.csv,HP_SBM/Final_USAir.csv,HP_SBM/Final_NS.csv,HP_SBM/Final_PB.csv,HP_SBM/Final_Yeast.csv,HP_SBM/Final_Celegans.csv,HP_SBM/Important3_power.csv,HP_SBM/Final_Router.csv,HP_SBM/Final_Ecoli.csv
louvain prob pred,50.24$\pm$1.59 X,52.83$\pm$1.21 X,47.41$\pm$4.42 X,80.71$\pm$0.99,4.44$\pm$0.69 X,62.04$\pm$3.76 X,34.99$\pm$5.17 X,33.69$\pm$1.47,21.91$\pm$1.42 X,36.44$\pm$1.02 X
"grace,enc:gcn bgrl,pred:mlp,sbm+random",63.01$\pm$1.83 X,67.97$\pm$1.48,89.6$\pm$2.17,\color{red}{91.48$\pm$1.26 $\bigstar$},\color{red}{47.95$\pm$3.38 $\bigstar$},76.07$\pm$1.88,68.16$\pm$4.08,\color{red}{59.58$\pm$2.24 $\bigstar$},\color{blue}{49.61$\pm$1.03 $\bigstar$},79.1$\pm$1.19
"grace,enc:gcn bgrl,pred:mlp,sbm fix+random",66.9$\pm$1.99,61.73$\pm$1.6,89.76$\pm$2.15,80.27$\pm$1.28 X,46.89$\pm$3.87,70.85$\pm$2.79,60.7$\pm$3.24,36.02$\pm$1.79,27.15$\pm$1.01,77.07$\pm$1.42
"grace,enc:gcn bgrl,pred:mlp,sbm fast+random",66.99$\pm$1.35,62.02$\pm$1.1 X,89.98$\pm$1.95,80.69$\pm$1.5,\color{violet}{47.8$\pm$2.55 $\bigstar$},71.7$\pm$2.73,63.45$\pm$3.41,\color{violet}{36.21$\pm$1.22},26.95$\pm$1.22,78.55$\pm$1.03
"grace,enc:gcn bgrl,pred:mlp,sbm fast bug+random",75.44$\pm$1.0,\color{red}{74.46$\pm$1.35 $\bigstar$},90.26$\pm$2.44,\color{blue}{90.77$\pm$1.15 $\bigstar$},\color{blue}{47.94$\pm$2.88 $\bigstar$},\color{violet}{79.69$\pm$1.14},69.42$\pm$4.2,\color{blue}{52.06$\pm$3.03 $\bigstar$},\color{red}{50.3$\pm$2.2 $\bigstar$},78.19$\pm$1.69
"bgrl,enc:gcn bgrl,pred:mlp,sbm+random",68.9$\pm$2.54,68.98$\pm$1.52,88.71$\pm$2.61,\color{violet}{88.5$\pm$1.03},45.69$\pm$2.24,75.66$\pm$2.58,67.37$\pm$3.64,20.84$\pm$1.56 X,35.17$\pm$2.14,77.73$\pm$1.84
"bgrl,enc:gcn bgrl,pred:mlp,sbm fix+random",67.58$\pm$2.08,68.07$\pm$1.21,90.05$\pm$1.85,80.6$\pm$1.07 X,42.22$\pm$2.96,75.23$\pm$2.41,58.67$\pm$4.53,23.2$\pm$1.13,25.66$\pm$0.69,77.8$\pm$1.0
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast+random",67.53$\pm$1.65,68.03$\pm$1.08,90.75$\pm$1.99,80.78$\pm$1.07,43.58$\pm$2.98,75.06$\pm$2.04,62.54$\pm$4.28,23.07$\pm$0.99,25.69$\pm$0.79,77.67$\pm$1.67
"bgrl,enc:gcn bgrl,pred:mlp,sbm fast bug+random",70.05$\pm$1.44,68.59$\pm$2.03,89.95$\pm$1.47,82.96$\pm$1.02,45.95$\pm$3.18,77.14$\pm$1.61,69.79$\pm$3.92,19.28$\pm$1.03 X,37.35$\pm$1.58,77.81$\pm$1.38
"lgrace,enc:gcn bgrl,pred:mlp,sbm+random",73.7$\pm$2.81,68.06$\pm$1.18,91.18$\pm$1.74,86.35$\pm$1.46,46.41$\pm$4.53,\color{blue}{81.81$\pm$1.07 $\bigstar$},\color{red}{72.17$\pm$3.01 $\bigstar$},27.12$\pm$2.15,32.29$\pm$2.92,\color{red}{80.78$\pm$1.28 $\bigstar$}
"lgrace,enc:gcn bgrl,pred:mlp,sbm fix+random",\color{violet}{77.55$\pm$1.81 $\bigstar$},\color{violet}{72.46$\pm$1.1},\color{violet}{91.22$\pm$1.79 $\bigstar$},81.11$\pm$1.3,46.03$\pm$2.85,78.06$\pm$2.4,68.81$\pm$3.9,29.63$\pm$1.33,27.83$\pm$1.46,80.19$\pm$0.78
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast+random",\color{blue}{79.14$\pm$2.69 $\bigstar$},\color{blue}{73.11$\pm$1.28 $\bigstar$},\color{blue}{91.44$\pm$2.31 $\bigstar$},80.78$\pm$1.0,45.86$\pm$2.33,78.93$\pm$1.75,\color{violet}{70.63$\pm$4.22 $\bigstar$},30.69$\pm$2.27,27.17$\pm$2.12,\color{violet}{80.46$\pm$0.73 $\bigstar$}
"lgrace,enc:gcn bgrl,pred:mlp,sbm fast bug+random",\color{red}{79.18$\pm$2.14 $\bigstar$},69.89$\pm$2.23,\color{red}{91.51$\pm$1.68 $\bigstar$},82.63$\pm$1.18,47.16$\pm$3.41,\color{red}{82.27$\pm$1.13 $\bigstar$},\color{blue}{71.45$\pm$2.45 $\bigstar$},23.81$\pm$1.28,31.09$\pm$3.42,\color{blue}{80.65$\pm$0.88 $\bigstar$}
"lbgrl,enc:gcn bgrl,pred:mlp,sbm+random",67.37$\pm$2.02,65.55$\pm$1.53,89.34$\pm$2.3,84.78$\pm$1.83,45.34$\pm$3.1,76.93$\pm$2.23,66.41$\pm$3.73,23.25$\pm$1.73,38.81$\pm$1.16,79.44$\pm$0.85
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fix+random",72.24$\pm$1.75,68.6$\pm$2.07,90.78$\pm$2.09,80.53$\pm$1.54 X,44.59$\pm$2.96,73.55$\pm$2.36,63.59$\pm$3.24,30.52$\pm$1.24,29.74$\pm$1.5,76.93$\pm$1.04
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fast+random",73.3$\pm$1.95,69.9$\pm$2.09,90.92$\pm$2.04,80.31$\pm$1.15 X,43.96$\pm$3.38,73.9$\pm$2.05,65.87$\pm$5.56,30.95$\pm$1.04,29.92$\pm$0.97,77.33$\pm$1.03
"lbgrl,enc:gcn bgrl,pred:mlp,sbm fast bug+random",73.41$\pm$2.62,66.35$\pm$2.69,91.22$\pm$1.44 $\bigstar$,82.39$\pm$0.9,45.57$\pm$2.6,78.67$\pm$1.28,70.35$\pm$3.37 $\bigstar$,24.76$\pm$3.16,\color{violet}{39.35$\pm$2.19},79.05$\pm$0.97