In [1]:
import utils as ut

In [2]:
names = [
    'HP/USAir_res.csv',
    'HP/NS_res.csv',
    'HP/PB_res.csv',
    'HP/Yeast_res.csv',
    'HP/Celegans_res.csv',
    'HP/Power_res.csv',
    'HP/Router_res.csv',
    'HP/Ecoli_res.csv'
]
data, res = ut.mix_dataset(names, 'Hits@50')
data = ut.tex_table(data,res)
data.T

\resizebox{\textwidth}{!}{
\begin{tabular}{lllllllll}
\toprule
 & HP/USAir_res.csv & HP/NS_res.csv & HP/PB_res.csv & HP/Yeast_res.csv & HP/Celegans_res.csv & HP/Power_res.csv & HP/Router_res.csv & HP/Ecoli_res.csv \\
\midrule
baseline,enc:gcn ncn,pred:mlp & 88.64$\pm$2.61 & 80.93$\pm$0.91 & \color{blue}{51.57$\pm$3.08 $\bigstar$} & 84.1$\pm$0.8 & 51.56$\pm$28.47 & 21.96$\pm$3.65 & 52.67$\pm$2.86 & \color{red}{86.01$\pm$0.88 $\bigstar$} \\
grace,enc:gcn ncn,pred:mlp,random & 88.12$\pm$2.32 & \color{red}{84.27$\pm$2.12 $\bigstar$} & 46.47$\pm$2.74 & 82.41$\pm$0.84 & 70.23$\pm$3.41 & 33.73$\pm$1.71 & 46.57$\pm$3.84 & 83.26$\pm$0.98 \\
grace,enc:gcn ncn,pred:mlp,deg & 78.33$\pm$3.61 & 82.28$\pm$1.79 & 48.08$\pm$3.39 & 75.24$\pm$4.48 & 67.18$\pm$3.85 & 35.28$\pm$1.28 & 50.59$\pm$3.62 & 77.78$\pm$1.14 \\
grace,enc:gcn ncn,pred:mlp,evc & 89.84$\pm$2.1 & 77.99$\pm$1.67 & \color{red}{53.61$\pm$3.11 $\bigstar$} & 83.5$\pm$0.77 & 69.39$\pm$3.75 & \color{red}{36.71$\pm$1.96 $\bigstar$} & 31.67$\pm$12.82 & 82.92$\pm$1.09 \\
grace,enc:gcn ncn,pred:mlp,pr & 89.2$\pm$2.7 & \color{violet}{83.07$\pm$2.3} & 43.38$\pm$15.35 & 82.29$\pm$1.0 & 70.3$\pm$3.68 & 26.89$\pm$9.25 & 52.87$\pm$3.67 & 81.86$\pm$0.98 \\
infomap prob pred & 47.15$\pm$10.78 X & 81.02$\pm$0.93 & 5.23$\pm$1.06 X & 71.83$\pm$1.52 & 35.06$\pm$4.98 X & NaN & 22.81$\pm$1.1 X & 42.82$\pm$1.33 X \\
grace,enc:gcn ncn,pred:mlp,sbm fast2 & 88.73$\pm$2.51 & 79.67$\pm$1.64 & 44.8$\pm$2.25 & 74.12$\pm$3.15 & 60.98$\pm$2.74 & \color{blue}{36.28$\pm$1.53 $\bigstar$} & 41.17$\pm$7.99 & 80.0$\pm$1.35 \\
bgrl,enc:gcn ncn,pred:mlp,random & 70.28$\pm$23.37 & 77.79$\pm$1.92 & 44.07$\pm$6.41 & 83.3$\pm$0.8 & 60.84$\pm$1.84 & 24.77$\pm$1.66 & 51.56$\pm$4.1 & 81.79$\pm$0.92 \\
bgrl,enc:gcn ncn,pred:mlp,deg & 85.44$\pm$3.46 & \color{blue}{83.28$\pm$1.62 $\bigstar$} & 44.52$\pm$2.9 & 76.67$\pm$7.02 & 64.29$\pm$6.21 & 25.03$\pm$5.68 & 52.37$\pm$3.66 & 80.32$\pm$3.81 \\
bgrl,enc:gcn ncn,pred:mlp,evc & 88.31$\pm$2.51 & 81.35$\pm$1.43 & 45.88$\pm$3.45 & 82.33$\pm$0.81 & 65.69$\pm$4.82 & 26.3$\pm$0.94 & 32.6$\pm$26.78 & 76.02$\pm$1.26 \\
bgrl,enc:gcn ncn,pred:mlp,pr & 89.2$\pm$2.77 & 21.09$\pm$33.58 X & 49.89$\pm$2.8 & \color{violet}{84.55$\pm$0.58 $\bigstar$} & 63.99$\pm$4.38 & 25.99$\pm$1.67 & 51.1$\pm$4.59 & 81.94$\pm$1.09 \\
leiden prob pred & 47.15$\pm$10.78 X & NaN & 5.23$\pm$1.06 X & NaN & NaN & 33.85$\pm$1.48 & 22.81$\pm$1.1 X & NaN \\
bgrl,enc:gcn ncn,pred:mlp,sbm fast2 & 81.79$\pm$3.91 & 81.41$\pm$1.13 & 45.52$\pm$2.53 & 80.43$\pm$1.58 & 57.86$\pm$4.03 & \color{violet}{36.18$\pm$1.37 $\bigstar$} & \color{blue}{53.74$\pm$3.17 $\bigstar$} & 73.44$\pm$6.0 \\
lbgrl,enc:gcn ncn,pred:mlp,random & 88.71$\pm$2.09 & 76.51$\pm$6.89 & 45.97$\pm$3.22 & 77.71$\pm$1.46 & 68.67$\pm$3.72 & 28.56$\pm$1.46 & 52.03$\pm$3.22 & 80.56$\pm$0.74 \\
lbgrl,enc:gcn ncn,pred:mlp,deg & 64.87$\pm$4.44 & 79.12$\pm$1.37 & 44.28$\pm$3.4 & 74.47$\pm$7.02 & 57.02$\pm$4.1 & 27.7$\pm$2.28 & 42.03$\pm$8.95 & 79.45$\pm$1.32 \\
lbgrl,enc:gcn ncn,pred:mlp,evc & 80.38$\pm$4.55 & 70.97$\pm$17.73 & 44.79$\pm$2.76 & 68.34$\pm$2.69 X & 57.32$\pm$6.35 & 24.51$\pm$1.7 & 52.78$\pm$3.45 & 78.82$\pm$1.45 \\
lbgrl,enc:gcn ncn,pred:mlp,pr & 88.73$\pm$6.4 & 69.56$\pm$24.24 & 41.11$\pm$8.38 & 80.47$\pm$0.85 & 57.3$\pm$5.85 & 25.3$\pm$1.02 & \color{red}{53.96$\pm$3.53 $\bigstar$} & 78.25$\pm$1.08 \\
louvain prob pred & 47.15$\pm$10.78 X & 81.02$\pm$0.93 & 5.23$\pm$1.06 X & 71.83$\pm$1.52 & 35.06$\pm$4.98 X & 33.85$\pm$1.48 & 22.81$\pm$1.1 X & NaN \\
lbgrl,enc:gcn ncn,pred:mlp,sbm fast2 & 87.95$\pm$2.12 & 80.49$\pm$1.28 & 45.81$\pm$2.4 & 62.96$\pm$1.99 X & 60.42$\pm$3.57 & 3.0$\pm$8.24 X & 52.54$\pm$3.9 & 76.88$\pm$3.42 \\
lgrace,enc:gcn ncn,pred:mlp,random & 89.95$\pm$2.13 & 53.67$\pm$32.47 X & 44.58$\pm$8.37 & 76.88$\pm$25.63 $\bigstar$ & 68.21$\pm$7.37 & 32.58$\pm$1.96 & 29.14$\pm$18.37 & 83.88$\pm$1.11 \\
lgrace,enc:gcn ncn,pred:mlp,deg & \color{blue}{91.36$\pm$1.78 $\bigstar$} & 82.65$\pm$1.13 & 47.91$\pm$1.96 & 75.76$\pm$10.01 & \color{blue}{71.4$\pm$2.93 $\bigstar$} & 33.17$\pm$2.36 & 50.64$\pm$4.15 & 82.98$\pm$0.94 \\
lgrace,enc:gcn ncn,pred:mlp,evc & \color{violet}{90.21$\pm$4.01} & 64.95$\pm$32.54 & \color{violet}{50.0$\pm$3.68} & \color{red}{84.95$\pm$0.54 $\bigstar$} & \color{violet}{70.79$\pm$2.56} & 32.71$\pm$2.49 & 51.21$\pm$3.19 & \color{violet}{84.3$\pm$0.96} \\
lgrace,enc:gcn ncn,pred:mlp,pr & \color{red}{92.0$\pm$2.13 $\bigstar$} & 78.34$\pm$1.48 & 46.83$\pm$3.04 & \color{blue}{84.61$\pm$0.57 $\bigstar$} & \color{red}{73.03$\pm$3.04 $\bigstar$} & 25.39$\pm$1.98 & 42.9$\pm$14.39 & \color{blue}{85.96$\pm$0.71 $\bigstar$} \\
lgrace,enc:gcn ncn,pred:mlp,sbm fast2 & 88.75$\pm$2.62 & 73.49$\pm$10.8 & 43.92$\pm$2.78 & 80.35$\pm$1.77 & 60.72$\pm$4.46 & 30.34$\pm$10.28 & \color{violet}{53.16$\pm$2.81} & 82.61$\pm$0.82 \\
\bottomrule
\end{tabular}

}

,HP/USAir_res.csv,HP/NS_res.csv,HP/PB_res.csv,HP/Yeast_res.csv,HP/Celegans_res.csv,HP/Power_res.csv,HP/Router_res.csv,HP/Ecoli_res.csv
"baseline,enc:gcn ncn,pred:mlp",88.64$\pm$2.61,80.93$\pm$0.91,\color{blue}{51.57$\pm$3.08 $\bigstar$},84.1$\pm$0.8,51.56$\pm$28.47,21.96$\pm$3.65,52.67$\pm$2.86,\color{red}{86.01$\pm$0.88 $\bigstar$}
"grace,enc:gcn ncn,pred:mlp,random",88.12$\pm$2.32,\color{red}{84.27$\pm$2.12 $\bigstar$},46.47$\pm$2.74,82.41$\pm$0.84,70.23$\pm$3.41,33.73$\pm$1.71,46.57$\pm$3.84,83.26$\pm$0.98
"grace,enc:gcn ncn,pred:mlp,deg",78.33$\pm$3.61,82.28$\pm$1.79,48.08$\pm$3.39,75.24$\pm$4.48,67.18$\pm$3.85,35.28$\pm$1.28,50.59$\pm$3.62,77.78$\pm$1.14
"grace,enc:gcn ncn,pred:mlp,evc",89.84$\pm$2.1,77.99$\pm$1.67,\color{red}{53.61$\pm$3.11 $\bigstar$},83.5$\pm$0.77,69.39$\pm$3.75,\color{red}{36.71$\pm$1.96 $\bigstar$},31.67$\pm$12.82,82.92$\pm$1.09
"grace,enc:gcn ncn,pred:mlp,pr",89.2$\pm$2.7,\color{violet}{83.07$\pm$2.3},43.38$\pm$15.35,82.29$\pm$1.0,70.3$\pm$3.68,26.89$\pm$9.25,52.87$\pm$3.67,81.86$\pm$0.98
infomap prob pred,47.15$\pm$10.78 X,81.02$\pm$0.93,5.23$\pm$1.06 X,71.83$\pm$1.52,35.06$\pm$4.98 X,NaN,22.81$\pm$1.1 X,42.82$\pm$1.33 X
"grace,enc:gcn ncn,pred:mlp,sbm fast2",88.73$\pm$2.51,79.67$\pm$1.64,44.8$\pm$2.25,74.12$\pm$3.15,60.98$\pm$2.74,\color{blue}{36.28$\pm$1.53 $\bigstar$},41.17$\pm$7.99,80.0$\pm$1.35
"bgrl,enc:gcn ncn,pred:mlp,random",70.28$\pm$23.37,77.79$\pm$1.92,44.07$\pm$6.41,83.3$\pm$0.8,60.84$\pm$1.84,24.77$\pm$1.66,51.56$\pm$4.1,81.79$\pm$0.92
"bgrl,enc:gcn ncn,pred:mlp,deg",85.44$\pm$3.46,\color{blue}{83.28$\pm$1.62 $\bigstar$},44.52$\pm$2.9,76.67$\pm$7.02,64.29$\pm$6.21,25.03$\pm$5.68,52.37$\pm$3.66,80.32$\pm$3.81
"bgrl,enc:gcn ncn,pred:mlp,evc",88.31$\pm$2.51,81.35$\pm$1.43,45.88$\pm$3.45,82.33$\pm$0.81,65.69$\pm$4.82,26.3$\pm$0.94,32.6$\pm$26.78,76.02$\pm$1.26
"bgrl,enc:gcn ncn,pred:mlp,pr",89.2$\pm$2.77,21.09$\pm$33.58 X,49.89$\pm$2.8,\color{violet}{84.55$\pm$0.58 $\bigstar$},63.99$\pm$4.38,25.99$\pm$1.67,51.1$\pm$4.59,81.94$\pm$1.09
leiden prob pred,47.15$\pm$10.78 X,NaN,5.23$\pm$1.06 X,NaN,NaN,33.85$\pm$1.48,22.81$\pm$1.1 X,NaN
"bgrl,enc:gcn ncn,pred:mlp,sbm fast2",81.79$\pm$3.91,81.41$\pm$1.13,45.52$\pm$2.53,80.43$\pm$1.58,57.86$\pm$4.03,\color{violet}{36.18$\pm$1.37 $\bigstar$},\color{blue}{53.74$\pm$3.17 $\bigstar$},73.44$\pm$6.0
"lbgrl,enc:gcn ncn,pred:mlp,random",88.71$\pm$2.09,76.51$\pm$6.89,45.97$\pm$3.22,77.71$\pm$1.46,68.67$\pm$3.72,28.56$\pm$1.46,52.03$\pm$3.22,80.56$\pm$0.74
"lbgrl,enc:gcn ncn,pred:mlp,deg",64.87$\pm$4.44,79.12$\pm$1.37,44.28$\pm$3.4,74.47$\pm$7.02,57.02$\pm$4.1,27.7$\pm$2.28,42.03$\pm$8.95,79.45$\pm$1.32
"lbgrl,enc:gcn ncn,pred:mlp,evc",80.38$\pm$4.55,70.97$\pm$17.73,44.79$\pm$2.76,68.34$\pm$2.69 X,57.32$\pm$6.35,24.51$\pm$1.7,52.78$\pm$3.45,78.82$\pm$1.45
"lbgrl,enc:gcn ncn,pred:mlp,pr",88.73$\pm$6.4,69.56$\pm$24.24,41.11$\pm$8.38,80.47$\pm$0.85,57.3$\pm$5.85,25.3$\pm$1.02,\color{red}{53.96$\pm$3.53 $\bigstar$},78.25$\pm$1.08
louvain prob pred,47.15$\pm$10.78 X,81.02$\pm$0.93,5.23$\pm$1.06 X,71.83$\pm$1.52,35.06$\pm$4.98 X,33.85$\pm$1.48,22.81$\pm$1.1 X,NaN
"lbgrl,enc:gcn ncn,pred:mlp,sbm fast2",87.95$\pm$2.12,80.49$\pm$1.28,45.81$\pm$2.4,62.96$\pm$1.99 X,60.42$\pm$3.57,3.0$\pm$8.24 X,52.54$\pm$3.9,76.88$\pm$3.42
"lgrace,enc:gcn ncn,pred:mlp,random",89.95$\pm$2.13,53.67$\pm$32.47 X,44.58$\pm$8.37,76.88$\pm$25.63 $\bigstar$,68.21$\pm$7.37,32.58$\pm$1.96,29.14$\pm$18.37,83.88$\pm$1.11
"lgrace,enc:gcn ncn,pred:mlp,deg",\color{blue}{91.36$\pm$1.78 $\bigstar$},82.65$\pm$1.13,47.91$\pm$1.96,75.76$\pm$10.01,\color{blue}{71.4$\pm$2.93 $\bigstar$},33.17$\pm$2.36,50.64$\pm$4.15,82.98$\pm$0.94
"lgrace,enc:gcn ncn,pred:mlp,evc",\color{violet}{90.21$\pm$4.01},64.95$\pm$32.54,\color{violet}{50.0$\pm$3.68},\color{red}{84.95$\pm$0.54 $\bigstar$},\color{violet}{70.79$\pm$2.56},32.71$\pm$2.49,51.21$\pm$3.19,\color{violet}{84.3$\pm$0.96}
"lgrace,enc:gcn ncn,pred:mlp,pr",\color{red}{92.0$\pm$2.13 $\bigstar$},78.34$\pm$1.48,46.83$\pm$3.04,\color{blue}{84.61$\pm$0.57 $\bigstar$},\color{red}{73.03$\pm$3.04 $\bigstar$},25.39$\pm$1.98,42.9$\pm$14.39,\color{blue}{85.96$\pm$0.71 $\bigstar$}
"lgrace,enc:gcn ncn,pred:mlp,sbm fast2",88.75$\pm$2.62,73.49$\pm$10.8,43.92$\pm$2.78,80.35$\pm$1.77,60.72$\pm$4.46,30.34$\pm$10.28,\color{violet}{53.16$\pm$2.81},82.61$\pm$0.82

In [15]:
data1 = ut.res_load('HP/L_pubmed.csv')
data2 = ut.res_load('HP/pubmed_res.csv')
data2 = data2.T.join(data1.T)
data2.to_csv('HP/pubmed_res.csv', sep=';')

In [16]:
names = [
    'HP/cora_res.csv',
    'HP/citeseer_res.csv',
    'HP/pubmed_res.csv'
]
data, res = ut.mix_dataset(names, 'Hits@100')
data = ut.tex_table(data,res)
display(data.T)

\resizebox{\textwidth}{!}{
\begin{tabular}{llll}
\toprule
 & HP/cora_res.csv & HP/citeseer_res.csv & HP/pubmed_res.csv \\
\midrule
baseline,enc:gcn ncn,pred:mlp & \color{violet}{85.74$\pm$0.95} & 85.66$\pm$2.07 & \color{red}{81.38$\pm$1.66 $\bigstar$} \\
grace,enc:gcn ncn,pred:mlp,random & 84.04$\pm$0.76 & 89.56$\pm$1.55 & 75.06$\pm$1.22 \\
grace,enc:gcn ncn,pred:mlp,deg & 84.31$\pm$2.6 & 90.22$\pm$0.98 & 75.36$\pm$1.67 \\
grace,enc:gcn ncn,pred:mlp,evc & \color{red}{87.1$\pm$1.76 $\bigstar$} & \color{red}{92.66$\pm$1.28 $\bigstar$} & 75.85$\pm$2.05 \\
grace,enc:gcn ncn,pred:mlp,pr & 84.63$\pm$1.54 & \color{blue}{90.3$\pm$1.03} & \color{violet}{79.88$\pm$1.66} \\
bgrl,enc:gcn ncn,pred:mlp,random & 84.33$\pm$1.29 & 87.99$\pm$2.26 & 72.81$\pm$2.49 \\
bgrl,enc:gcn ncn,pred:mlp,deg & 76.12$\pm$1.52 X & 85.66$\pm$17.82 & 75.35$\pm$1.69 \\
bgrl,enc:gcn ncn,pred:mlp,evc & 84.69$\pm$1.0 & 88.69$\pm$1.59 & 78.04$\pm$1.06 \\
bgrl,enc:gcn ncn,pred:mlp,pr & 84.5$\pm$0.94 & 78.52$\pm$21.32 & 69.59$\pm$1.96 X \\
lbgrl,enc:gcn ncn,pred:mlp,random & 83.29$\pm$1.55 & 64.02$\pm$9.23 X & 75.71$\pm$1.44 \\
lbgrl,enc:gcn ncn,pred:mlp,deg & 83.19$\pm$3.41 & 82.62$\pm$3.37 & \color{blue}{80.32$\pm$1.25 $\bigstar$} \\
lbgrl,enc:gcn ncn,pred:mlp,evc & 81.7$\pm$1.8 & 82.05$\pm$2.38 & 73.77$\pm$1.08 \\
lbgrl,enc:gcn ncn,pred:mlp,pr & 76.57$\pm$7.23 X & 81.8$\pm$10.84 & 78.83$\pm$1.83 \\
lgrace,enc:gcn ncn,pred:mlp,random & 83.07$\pm$1.32 & 82.41$\pm$15.21 & NaN \\
lgrace,enc:gcn ncn,pred:mlp,deg & 79.36$\pm$7.14 & 78.0$\pm$7.32 & NaN \\
lgrace,enc:gcn ncn,pred:mlp,evc & 84.8$\pm$1.96 & \color{violet}{90.26$\pm$1.52} & NaN \\
lgrace,enc:gcn ncn,pred:mlp,pr & \color{blue}{86.93$\pm$1.34 $\bigstar$} & 87.66$\pm$11.02 & NaN \\
\bottomrule
\end{tabular}

}

,HP/cora_res.csv,HP/citeseer_res.csv,HP/pubmed_res.csv
"baseline,enc:gcn ncn,pred:mlp",\color{violet}{85.74$\pm$0.95},85.66$\pm$2.07,\color{red}{81.38$\pm$1.66 $\bigstar$}
"grace,enc:gcn ncn,pred:mlp,random",84.04$\pm$0.76,89.56$\pm$1.55,75.06$\pm$1.22
"grace,enc:gcn ncn,pred:mlp,deg",84.31$\pm$2.6,90.22$\pm$0.98,75.36$\pm$1.67
"grace,enc:gcn ncn,pred:mlp,evc",\color{red}{87.1$\pm$1.76 $\bigstar$},\color{red}{92.66$\pm$1.28 $\bigstar$},75.85$\pm$2.05
"grace,enc:gcn ncn,pred:mlp,pr",84.63$\pm$1.54,\color{blue}{90.3$\pm$1.03},\color{violet}{79.88$\pm$1.66}
"bgrl,enc:gcn ncn,pred:mlp,random",84.33$\pm$1.29,87.99$\pm$2.26,72.81$\pm$2.49
"bgrl,enc:gcn ncn,pred:mlp,deg",76.12$\pm$1.52 X,85.66$\pm$17.82,75.35$\pm$1.69
"bgrl,enc:gcn ncn,pred:mlp,evc",84.69$\pm$1.0,88.69$\pm$1.59,78.04$\pm$1.06
"bgrl,enc:gcn ncn,pred:mlp,pr",84.5$\pm$0.94,78.52$\pm$21.32,69.59$\pm$1.96 X
"lbgrl,enc:gcn ncn,pred:mlp,random",83.29$\pm$1.55,64.02$\pm$9.23 X,75.71$\pm$1.44
"lbgrl,enc:gcn ncn,pred:mlp,deg",83.19$\pm$3.41,82.62$\pm$3.37,\color{blue}{80.32$\pm$1.25 $\bigstar$}
"lbgrl,enc:gcn ncn,pred:mlp,evc",81.7$\pm$1.8,82.05$\pm$2.38,73.77$\pm$1.08
"lbgrl,enc:gcn ncn,pred:mlp,pr",76.57$\pm$7.23 X,81.8$\pm$10.84,78.83$\pm$1.83
"lgrace,enc:gcn ncn,pred:mlp,random",83.07$\pm$1.32,82.41$\pm$15.21,NaN
"lgrace,enc:gcn ncn,pred:mlp,deg",79.36$\pm$7.14,78.0$\pm$7.32,NaN
"lgrace,enc:gcn ncn,pred:mlp,evc",84.8$\pm$1.96,\color{violet}{90.26$\pm$1.52},NaN
"lgrace,enc:gcn ncn,pred:mlp,pr",\color{blue}{86.93$\pm$1.34 $\bigstar$},87.66$\pm$11.02,NaN

In [4]:
names = [
    'HP_SBM/_Celegans.csv',
    'HP_SBM/_USAir.csv'
]
data, res = ut.mix_dataset(names, 'Hits@50')
data = ut.tex_table(data,res)
display(data.T)

\resizebox{\textwidth}{!}{
\begin{tabular}{lll}
\toprule
 & HP_SBM/_Celegans.csv & HP_SBM/_USAir.csv \\
\midrule
louvain prob pred & 32.28$\pm$3.88 X & 47.18$\pm$5.16 X \\
grace,enc:gcn ncn,pred:mlp,sbm & 64.78$\pm$4.89 & 90.02$\pm$2.26 \\
grace,enc:gcn ncn,pred:mlp,sbm+random & 67.74$\pm$2.38 $\bigstar$ & 86.16$\pm$3.96 \\
grace,enc:gcn ncn,pred:mlp,sbm+deg & 65.94$\pm$4.76 & \color{red}{92.33$\pm$1.62 $\bigstar$} \\
grace,enc:gcn ncn,pred:mlp,sbm+evc & \color{red}{70.51$\pm$2.72 $\bigstar$} & 87.27$\pm$2.53 \\
grace,enc:gcn ncn,pred:mlp,sbm+pr & \color{blue}{68.23$\pm$3.54 $\bigstar$} & \color{violet}{90.75$\pm$2.05 $\bigstar$} \\
bgrl,enc:gcn ncn,pred:mlp,sbm & 57.48$\pm$3.33 & 80.47$\pm$3.32 \\
bgrl,enc:gcn ncn,pred:mlp,sbm+random & 54.57$\pm$6.23 & 88.19$\pm$2.18 \\
bgrl,enc:gcn ncn,pred:mlp,sbm+deg & 57.39$\pm$4.86 & \color{blue}{91.93$\pm$2.26 $\bigstar$} \\
bgrl,enc:gcn ncn,pred:mlp,sbm+evc & 63.8$\pm$4.16 & 76.59$\pm$4.02 \\
bgrl,enc:gcn ncn,pred:mlp,sbm+pr & \color{violet}{67.79$\pm$5.1 $\bigstar$} & 75.6$\pm$3.63 \\
lbgrl,enc:gcn ncn,pred:mlp,sbm & 42.19$\pm$3.06 X & 77.67$\pm$4.3 \\
lbgrl,enc:gcn ncn,pred:mlp,sbm+random & 54.48$\pm$4.32 & 83.51$\pm$2.62 \\
lbgrl,enc:gcn ncn,pred:mlp,sbm+deg & 55.59$\pm$3.45 & 77.79$\pm$3.6 \\
lbgrl,enc:gcn ncn,pred:mlp,sbm+evc & 46.83$\pm$3.25 & 85.84$\pm$3.1 \\
lbgrl,enc:gcn ncn,pred:mlp,sbm+pr & 56.57$\pm$6.14 & 82.96$\pm$3.4 \\
\bottomrule
\end{tabular}

}

,HP_SBM/_Celegans.csv,HP_SBM/_USAir.csv
louvain prob pred,32.28$\pm$3.88 X,47.18$\pm$5.16 X
"grace,enc:gcn ncn,pred:mlp,sbm",64.78$\pm$4.89,90.02$\pm$2.26
"grace,enc:gcn ncn,pred:mlp,sbm+random",67.74$\pm$2.38 $\bigstar$,86.16$\pm$3.96
"grace,enc:gcn ncn,pred:mlp,sbm+deg",65.94$\pm$4.76,\color{red}{92.33$\pm$1.62 $\bigstar$}
"grace,enc:gcn ncn,pred:mlp,sbm+evc",\color{red}{70.51$\pm$2.72 $\bigstar$},87.27$\pm$2.53
"grace,enc:gcn ncn,pred:mlp,sbm+pr",\color{blue}{68.23$\pm$3.54 $\bigstar$},\color{violet}{90.75$\pm$2.05 $\bigstar$}
"bgrl,enc:gcn ncn,pred:mlp,sbm",57.48$\pm$3.33,80.47$\pm$3.32
"bgrl,enc:gcn ncn,pred:mlp,sbm+random",54.57$\pm$6.23,88.19$\pm$2.18
"bgrl,enc:gcn ncn,pred:mlp,sbm+deg",57.39$\pm$4.86,\color{blue}{91.93$\pm$2.26 $\bigstar$}
"bgrl,enc:gcn ncn,pred:mlp,sbm+evc",63.8$\pm$4.16,76.59$\pm$4.02
"bgrl,enc:gcn ncn,pred:mlp,sbm+pr",\color{violet}{67.79$\pm$5.1 $\bigstar$},75.6$\pm$3.63
"lbgrl,enc:gcn ncn,pred:mlp,sbm",42.19$\pm$3.06 X,77.67$\pm$4.3
"lbgrl,enc:gcn ncn,pred:mlp,sbm+random",54.48$\pm$4.32,83.51$\pm$2.62
"lbgrl,enc:gcn ncn,pred:mlp,sbm+deg",55.59$\pm$3.45,77.79$\pm$3.6
"lbgrl,enc:gcn ncn,pred:mlp,sbm+evc",46.83$\pm$3.25,85.84$\pm$3.1
"lbgrl,enc:gcn ncn,pred:mlp,sbm+pr",56.57$\pm$6.14,82.96$\pm$3.4