In [1]:
import utils as ut

In [13]:
names = ['Enc_cora_res.csv', 'Enc_citeseer_res.csv', 'Enc_NS_res.csv', 'Enc_Power_res.csv']
means, res = ut.mix_dataset(names, 'Hits@50')
display(ut.average_methods(means).sort_values())
big_tab = ut.tex_table(means, res).T
big_tab

lbgrl_enc:gcn_grace_pred:mlp_random_mean    33.8675
grace_enc:gcn_grace_pred:mlp_random_mean    40.4400
lbgrl_enc:gcn_bgrl_pred:mlp_random_mean     46.1800
grace_enc:gcn_ncn_pred:mlp_random_mean      48.6500
lbgrl_enc:gcn_ncn_pred:mlp_random_mean      58.2900
grace_enc:gcn_bgrl_pred:mlp_random_mean     58.5600
bgrl_enc:gcn_grace_pred:mlp_random_mean     58.8050
bgrl_enc:gcn_ncn_pred:mlp_random_mean       63.0600
bgrl_enc:gcn_bgrl_pred:mlp_random_mean      64.9525
dtype: float64

\resizebox{\textwidth}{!}{
\begin{tabular}{lllll}
\toprule
 & Enc_cora_res.csv & Enc_citeseer_res.csv & Enc_NS_res.csv & Enc_Power_res.csv \\
\midrule
grace enc:gcn grace pred:mlp random & \color{red}{72.11$\pm$2.71 $\bigstar$} & 2.24$\pm$2.76 X & \color{blue}{87.41$\pm$1.09 $\bigstar$} & 0.0$\pm$0.0 X \\
grace enc:gcn bgrl pred:mlp random & \color{blue}{69.42$\pm$1.92 $\bigstar$} & \color{violet}{75.87$\pm$1.85} & 63.91$\pm$3.55 X & 25.04$\pm$5.04 \\
grace enc:gcn ncn pred:mlp random & 52.99$\pm$26.62 & \color{blue}{83.1$\pm$1.25 $\bigstar$} & 33.21$\pm$40.7 X & 25.3$\pm$1.41 \\
bgrl enc:gcn grace pred:mlp random & \color{violet}{68.09$\pm$3.48} & 74.9$\pm$3.2 & 66.86$\pm$28.63 & 25.37$\pm$12.75 \\
bgrl enc:gcn bgrl pred:mlp random & 67.32$\pm$1.06 & 63.76$\pm$17.25 & \color{red}{88.14$\pm$1.87 $\bigstar$} & \color{red}{40.59$\pm$2.65 $\bigstar$} \\
bgrl enc:gcn ncn pred:mlp random & 62.94$\pm$1.98 & \color{red}{85.43$\pm$2.22 $\bigstar$} & \color{violet}{83.69$\pm$1.6} & 20.18$\pm$12.04 \\
lbgrl enc:gcn grace pred:mlp random & 57.71$\pm$2.47 X & 1.91$\pm$1.5 X & 49.42$\pm$28.77 X & \color{violet}{26.43$\pm$1.4} \\
lbgrl enc:gcn bgrl pred:mlp random & 62.64$\pm$4.42 & 56.35$\pm$11.81 & 47.99$\pm$22.05 X & 17.74$\pm$10.32 \\
lbgrl enc:gcn ncn pred:mlp random & 64.72$\pm$2.12 & 62.46$\pm$10.32 & 79.38$\pm$1.57 & \color{blue}{26.6$\pm$1.09} \\
\bottomrule
\end{tabular}

}

,Enc_cora_res.csv,Enc_citeseer_res.csv,Enc_NS_res.csv,Enc_Power_res.csv
grace enc:gcn grace pred:mlp random,\color{red}{72.11$\pm$2.71 $\bigstar$},2.24$\pm$2.76 X,\color{blue}{87.41$\pm$1.09 $\bigstar$},0.0$\pm$0.0 X
grace enc:gcn bgrl pred:mlp random,\color{blue}{69.42$\pm$1.92 $\bigstar$},\color{violet}{75.87$\pm$1.85},63.91$\pm$3.55 X,25.04$\pm$5.04
grace enc:gcn ncn pred:mlp random,52.99$\pm$26.62,\color{blue}{83.1$\pm$1.25 $\bigstar$},33.21$\pm$40.7 X,25.3$\pm$1.41
bgrl enc:gcn grace pred:mlp random,\color{violet}{68.09$\pm$3.48},74.9$\pm$3.2,66.86$\pm$28.63,25.37$\pm$12.75
bgrl enc:gcn bgrl pred:mlp random,67.32$\pm$1.06,63.76$\pm$17.25,\color{red}{88.14$\pm$1.87 $\bigstar$},\color{red}{40.59$\pm$2.65 $\bigstar$}
bgrl enc:gcn ncn pred:mlp random,62.94$\pm$1.98,\color{red}{85.43$\pm$2.22 $\bigstar$},\color{violet}{83.69$\pm$1.6},20.18$\pm$12.04
lbgrl enc:gcn grace pred:mlp random,57.71$\pm$2.47 X,1.91$\pm$1.5 X,49.42$\pm$28.77 X,\color{violet}{26.43$\pm$1.4}
lbgrl enc:gcn bgrl pred:mlp random,62.64$\pm$4.42,56.35$\pm$11.81,47.99$\pm$22.05 X,17.74$\pm$10.32
lbgrl enc:gcn ncn pred:mlp random,64.72$\pm$2.12,62.46$\pm$10.32,79.38$\pm$1.57,\color{blue}{26.6$\pm$1.09}

In [4]:
names = ['Enc_cora_res.csv', 'Enc_citeseer_res.csv', 'Enc_NS_res.csv', 'Enc_Power_res.csv']
means, res = ut.mix_dataset(names, 'Hits@100')
big_tab = ut.tex_table(means, res).T
big_tab

\resizebox{\textwidth}{!}{
\begin{tabular}{lllll}
\toprule
 & Enc_cora_res.csv & Enc_citeseer_res.csv & Enc_NS_res.csv & Enc_Power_res.csv \\
\midrule
grace enc:gcn grace pred:mlp random & \color{blue}{78.46$\pm$1.93 $\bigstar$} & 17.43$\pm$31.5 X & \color{blue}{89.93$\pm$0.93 $\bigstar$} & 4.13$\pm$8.25 X \\
grace enc:gcn bgrl pred:mlp random & \color{violet}{77.95$\pm$1.47 $\bigstar$} & 83.25$\pm$1.78 & 73.61$\pm$1.97 X & \color{violet}{31.73$\pm$2.54} \\
grace enc:gcn ncn pred:mlp random & 64.28$\pm$32.24 $\bigstar$ & \color{blue}{90.55$\pm$0.37 $\bigstar$} & 86.5$\pm$3.49 & 29.56$\pm$1.8 \\
bgrl enc:gcn grace pred:mlp random & 72.76$\pm$2.92 & \color{violet}{84.46$\pm$1.97} & 68.69$\pm$29.52 & 29.3$\pm$14.72 \\
bgrl enc:gcn bgrl pred:mlp random & 74.35$\pm$1.56 & 73.03$\pm$15.66 & \color{red}{91.64$\pm$1.58 $\bigstar$} & \color{red}{46.07$\pm$3.17 $\bigstar$} \\
bgrl enc:gcn ncn pred:mlp random & 77.08$\pm$0.67 $\bigstar$ & \color{red}{90.57$\pm$1.37 $\bigstar$} & \color{violet}{87.77$\pm$3.45} & 25.07$\pm$14.26 \\
lbgrl enc:gcn grace pred:mlp random & 66.07$\pm$2.24 X & 1.91$\pm$1.5 X & 55.44$\pm$33.22 X & \color{blue}{31.85$\pm$1.29} \\
lbgrl enc:gcn bgrl pred:mlp random & 72.25$\pm$4.4 & 67.43$\pm$10.63 & 57.52$\pm$15.04 X & 22.66$\pm$12.53 \\
lbgrl enc:gcn ncn pred:mlp random & \color{red}{78.79$\pm$1.79 $\bigstar$} & 79.1$\pm$2.68 & 80.29$\pm$2.38 & 31.53$\pm$0.8 \\
\bottomrule
\end{tabular}

}

,Enc_cora_res.csv,Enc_citeseer_res.csv,Enc_NS_res.csv,Enc_Power_res.csv
grace enc:gcn grace pred:mlp random,\color{blue}{78.46$\pm$1.93 $\bigstar$},17.43$\pm$31.5 X,\color{blue}{89.93$\pm$0.93 $\bigstar$},4.13$\pm$8.25 X
grace enc:gcn bgrl pred:mlp random,\color{violet}{77.95$\pm$1.47 $\bigstar$},83.25$\pm$1.78,73.61$\pm$1.97 X,\color{violet}{31.73$\pm$2.54}
grace enc:gcn ncn pred:mlp random,64.28$\pm$32.24 $\bigstar$,\color{blue}{90.55$\pm$0.37 $\bigstar$},86.5$\pm$3.49,29.56$\pm$1.8
bgrl enc:gcn grace pred:mlp random,72.76$\pm$2.92,\color{violet}{84.46$\pm$1.97},68.69$\pm$29.52,29.3$\pm$14.72
bgrl enc:gcn bgrl pred:mlp random,74.35$\pm$1.56,73.03$\pm$15.66,\color{red}{91.64$\pm$1.58 $\bigstar$},\color{red}{46.07$\pm$3.17 $\bigstar$}
bgrl enc:gcn ncn pred:mlp random,77.08$\pm$0.67 $\bigstar$,\color{red}{90.57$\pm$1.37 $\bigstar$},\color{violet}{87.77$\pm$3.45},25.07$\pm$14.26
lbgrl enc:gcn grace pred:mlp random,66.07$\pm$2.24 X,1.91$\pm$1.5 X,55.44$\pm$33.22 X,\color{blue}{31.85$\pm$1.29}
lbgrl enc:gcn bgrl pred:mlp random,72.25$\pm$4.4,67.43$\pm$10.63,57.52$\pm$15.04 X,22.66$\pm$12.53
lbgrl enc:gcn ncn pred:mlp random,\color{red}{78.79$\pm$1.79 $\bigstar$},79.1$\pm$2.68,80.29$\pm$2.38,31.53$\pm$0.8